### ISSUE TITLE
fmt unicode support

### ISSUE THREAD

**Issue by whutlee** [Microsoft/vscode-go#206] opened 2016-02-25 02:37 UTC
when debug with dlv   
fmt.Println("Hello, 世界") show nothing in the debug console

**Comment by danielalves** [comment] 2016-03-08 05:13
I have a somewhat related problem. When I try to print a unicode character by its UTF-8 Hex representation, Code aborts the debugging session with the message: `Error: Unexpected end of input. Stopping the debug adapter.`. When running the program normally through the terminal, the unicode character is printed correctly.

* Delve version
```
Delve Debugger
Version: 0.11.0-alpha
Build: 758f76ffee71a511ff41d5c423a03c1bf1f9fbf4
```
* Go version
```
go version go1.6 darwin/amd64
```
* OS
```
OSX Yosimite 10.10.5
```
* How to reproduce

```go
func main() {
    fmt.Fprintln("\xF0\x9F\x92\xA5") 
}
```
* What I expected to see?

The :boom: unicode character printed to the debug console, as it happens when using delve directly:
```
=>  56:		fmt.Println("\xF0\x9F\x92\xA5")
    57:     fmt.Println("After boom")
(dlv) n
💥
> main.main() ./main.go:57 (PC: 0x27f5)
    56:		fmt.Println("\xF0\x9F\x92\xA5")
=>  57:     fmt.Println("After boom")
```

* What did I see instead?

The message `Error: Unexpected end of input. Stopping the debug adapter.`

**Comment by lukehoban** [comment] 2016-03-09 20:08
I believe this is fixed with https://github.com/Microsoft/vscode-go/commit/3583c0f68bc6f8ed01be8986e9db9780bc02a65c and in release `0.6.23`.  See also #233.

**Comment by lukehoban** [comment] 2016-03-09 20:49
Unfortunately, it looks like this is not fixed yet.  The issue that @danielalves mentioned is the same as #233, and that is fixed.  But the original issue from @whutlee appears to still be there.

@weinand for help with this.

The issue only happens when there are unicode characters in the message being communicated back to the VS Code debugger.  It appears that these must be causing some character length computations to be off, which truncated the last few characters of the JSON before passing it to JSON.parse inside the VS Code debugger.

Here's what I see from the VS Code side:
![screen shot 2016-03-09 at 12 42 43 pm](https://cloud.githubusercontent.com/assets/223467/13649813/6d761158-e5f4-11e5-8de3-d8698c590a50.png)

Note how the string is truncated, and also has two leading newlines.  (the variable names are off here - `e` is actually the minified name assigned to `body`).

What's weird though is that if I'm debugging my debugAdapter (`"debugServer": 4711`), then I don't see this failure (or at least, it's very rare).  Here's what it looks like on that stdout event when I'm debugging my debugAdapter:

![screen shot 2016-03-09 at 12 46 54 pm](https://cloud.githubusercontent.com/assets/223467/13649965/388c9b8c-e5f5-11e5-95fb-70456b8e31bf.png)

**Comment by weinand** [comment] 2016-03-09 21:16
@lukehoban I'm trying to reproduce this...

**Comment by weinand** [comment] 2016-03-09 22:00
@lukehoban I tried to reproduce the problem with an equivalent JavaScript program:

```js
console.log("世界");
console.log("💥");
```

But this just works fine in VS Code 0.10.10 (that is non-server mode of the debug adapter).
This means that VS Code and the debugAdapter implementation (from the node module) are able to send these unicode characters as OutputEvents correctly.

The corresponding code in node-debug is:
```ts
		process.stdout.on('data', (data: string) => {
			this.sendEvent(new OutputEvent(data.toString(), 'stdout'));
		});
```

and in go-debug:
```ts
		this.delve.onstdout = (str: string) => {
			this.sendEvent(new OutputEvent(str, 'stdout'));
		};
```

When debugging node-debug I see 'data' containing raw bytes and 'data.toString()' converts this into a correct string (the expected characters plus a newline).

Since I don't (yet) have the go tooling installed, I haven't debugged the go-debug code, but could you verify that the 'str' argument shows the string correctly too?

**Comment by lukehoban** [comment] 2016-03-09 22:40
Yeah - everything looks good up to that point.

In ` ProtocolServer.prototype._send` I see:
* `json`: `"{"seq":8,"type":"event","event":"output","body":{"category":"stdout","output":"世界\n"}}"`
* `data`: `"Content-Length: 90\r\n\r\n{"seq":8,"type":"event","event":"output","body":{"category":"stdout","output":"世界\n"}}"`

These values appear to be correct all the way to the socket `Socket.prototype._write` when debugging the debugAdapter server.  I'm not sure how to test this in the non-server scenario though.

**Comment by weinand** [comment] 2016-03-09 22:52
In your package.json you can add a "--debug-brk" runtime arg:

```json
				"program": "./out/src/debugAdapter/goDebug.js",
				"runtimeArgs": [
					"--debug-brk"
				],
				"runtime": "node",
```

Then you can attach to your debug-adapter on port 5858.

**Comment by lukehoban** [comment] 2016-03-09 23:38
Okay - this is now fixed with https://github.com/Microsoft/vscode-go/commit/28fd411d9320e3254ee69bebb83802e8bf7c2b56.

It seems that `console.warn` calls from the Go debugAdapter are still showing up in the `rawData` in https://github.com/Microsoft/vscode/blob/33697437626f87331ed5ae950647b4a92a0375e3/src/vs/workbench/parts/debug/node/v8Protocol.ts#L125.  And then the code there is using `idx` as a byte offset even though it was computed as a string index.  So when the `console.warn` content has unicode chars, things get confused.

I confirmed that the `console.warn` content is being sent to stderr when I do ` node goDebug.js --server=4711 2> out.txt`.  So I'm not sure why it's still showing up here.

Sounds like it's safest to avoid any console logging at all in the debugAdpater by default.  But I'm still not sure what the real root problem is here.

**Closed by lukehoban** 2016-03-09 23:38 UTC

**Comment by lukehoban** [comment] 2016-03-09 23:49
@weinand Okay - looks like both `stderr` and `stdout` are being piped through to `stdout` when the debugAdapter is implemented in node by this: https://github.com/Microsoft/vscode/blob/a4f8a1657f57dc4a91242e0d294c29e97c8e2054/src/vs/workbench/parts/debug/node/rawDebugSession.ts#L235 and this: https://github.com/Microsoft/vscode/blob/d46c0646f239f04cefc3649bc998cb0c15993f4e/src/vs/base/node/stdForkStart.js#L50.  

So at least for now, it's not safe for a debugAdapter implemented in Node to write to `stderr` either.

**Comment by weinand** [comment] 2016-03-09 23:53
@lukehoban thanks for your investigation and findings. I will create bugs for this on our side.

**Comment by danielalves** [comment] 2016-03-10 04:54
Wow! In just a day! Thank you guys for the fix, @lukehoban @weinand
