### ISSUE TITLE
Format removes imports of vendored packages in use

### ISSUE THREAD

**Issue by sindrepm** [Microsoft/vscode-go#613] opened 2016-11-11 08:40 UTC
I just upgraded to the latest version and discovered a bug. When I have imports like the following:

```go
import (
   "github.com/xanzy/go-gitlab"
   "github.com/emicklei/go-restful"
)
```

Whenever I save the file, those import lines are removed even if they are referenced in the code. This has worked fine up until the last upgrade so not sure what has happened. From what I have found, it only applies to packages which contains a hyphen as shown above (e.g. "go-gitlab" and "go-restful").

I have been able to reference these packages just by the "gitlab" or "restful" names before, but now it seems that the goimports tool doesn't like that? If I alias the imports with "gitlab" or "restful" it works and the lines are not removed.

It is quite an annoying bug so hopefully this can be fixed.

**Comment by AlekSi** [comment] 2016-11-11 16:37
> it only applies to packages which contains a hyphen as shown above

For me it's `gopkg.in/Shopify/sarama.v1`. I think this is due to package name is different from import path's last element.

It's really annoying.

**Comment by AlekSi** [comment] 2016-11-11 16:51
It works with `"go.formatTool": "gofmt"`. So my guess it is something between `goreturns`, `GOPATH` and `vendor/`.

**Comment by ramya-rao-a** [comment] 2016-11-11 19:32
Can you run `goreturns` and/or `goimports` from the command line independent of VS Code and see if you still have the issue? This is to determine if the problem is with the formatting tool or with how VS Code uses the formatting too.

**Comment by sindrepm** [comment] 2016-11-12 09:39
I have tried running `goreturns`, `goimports` and `gofmt` directly on the .go file, and it works fine. The import lines are not removed. However, saving from the editor it immediately removes those imports.

**Comment by ramya-rao-a** [comment] 2016-11-12 17:18
Can you share your settings?

**Comment by ramya-rao-a** [comment] 2016-11-12 21:27
I tried the below code and I get build errors(`syntax error: unexpected -, expecting expression`), but no imports get removed on save
```
package main

import (
	"fmt"
	"github.com/emicklei/go-restful"
)

func main() {

	fmt.Println("Hello")
	go-restful.BodyParameter("hello", "bye")
}
```

**Comment by AlekSi** [comment] 2016-11-13 08:24
My settings don't have anything Go-related except `"go.gopath"` with a single path.

Most, if not all, tools for Go (including `gofmt`, `goimports` and `goreturns`) work by parsing code into AST, modifying AST and printing it back. If Go code has syntax errors, it can't be parsed, and the tool just exits with an error message. That's why import is not removed by tool – tool did nothing.

Go differentiates between [the last element of import path and package name](https://golang.org/ref/spec#Import_declarations). For `github.com/xanzy/go-gitlab`, `github.com/emicklei/go-restful` and `gopkg.in/Shopify/sarama.v1` package names are [`gitlab`](https://github.com/xanzy/go-gitlab/blob/master/builds.go#L17), [`restful`](https://github.com/emicklei/go-restful/blob/master/compress.go#L1) and [`sarama`](https://github.com/Shopify/sarama/blob/v1.10.1/broker.go#L1). I _suspect_ some part of vscode-go assumes that last part of import path equals package name. It's often, but not always, true.

**Comment by AlekSi** [comment] 2016-11-13 09:00
I created a small example: https://github.com/AlekSi/vscode-bug

**Comment by ramya-rao-a** [comment] 2016-11-14 00:35
@AlekSi 

Previously, the formatting tool (`gofmt`, `goreturns`, `goimports`) ran on the file on disk, which meant we had to save the file before running the format even if the user didn't want to.

As a means to fix that I had made the change to use `stdin` as input to the formatting tool instead of passing filename
This broke your scenario of vendor imports, because the formatting tool was unable to find the vendor packages.

Until the next update, as a workaround can you use `gofmt` as your choice of formatting tool?

@sindrepm 
This need not be the same case as yours. Can you share a sample code where you are seeing the imports getting removed?

**Comment by sindrepm** [comment] 2016-11-14 21:07
@ramya-rao-a 

Thanks for the update. I am pretty sure my issue is the same as @AlekSi mentions. It can very easily be reproduce with this simplified code:

```go
package main

import "github.com/xanzy/go-gitlab"

func main() {
	c := gitlab.Client{}
}
```
Try saving this file and the import line is removed. I do have `github.com/xanzy/go-gitlab` in my vendor folder.

Your workaround by changing `go.formatTool` to `gofmt` worked! With `goreturns` it fails.

**Comment by ramya-rao-a** [comment] 2016-11-14 23:13
@sindrepm Great, the pkg is a vendor pkg for you too. The next update (mostly end of this week), should have the fix

**Comment by ramya-rao-a** [comment] 2016-11-21 04:17
The latest update of the Go extension (0.6.50) has the fix for this.

**Comment by AlekSi** [comment] 2016-11-24 12:56
Unfortunately, it doesn't work. Please try with https://github.com/AlekSi/vscode-bug.

**Comment by AlekSi** [comment] 2016-11-24 13:01
Sorry, nevermind, that one is another issue (#623).

**Comment by sirianni** [comment] 2017-12-21 21:11
I am seeing this behavior again.  This worked for me a few days ago.

![output](https://user-images.githubusercontent.com/381302/34275064-a00c03c6-e669-11e7-82ed-6ca9aecf3d03.gif)

**Comment by ramya-rao-a** [comment] 2017-12-22 03:25
@sirianni can you try setting "go.formatTool" to "goimports"?

**Comment by ehzhang** [comment] 2017-12-22 03:41
I'm also seeing this behavior, just noticed today:
![dec-21-2017 19-38-52](https://user-images.githubusercontent.com/3484848/34284437-b6cdd176-e686-11e7-8d34-7a801c8317ce.gif)

This is fixed if i set `"go.formatTool": "gofmt"`. The import is removed when set to `"goreturns"`. I don't have `goimports` installed.

**Comment by sirianni** [comment] 2017-12-22 14:59
>can you try setting "go.formatTool" to "goimports"?

Setting `go.formatTool` to `goimports` fixes the issue.  Guess this is a bug in `goreturns` then?

**Comment by AlekSi** [comment] 2017-12-22 15:01
Same here.

**Comment by ramya-rao-a** [comment] 2017-12-22 18:11
Yes, we moved to passing the file contents to the formatting tool instead of having the tool work on the file on disk.

When doing so gofmt and goimports work well, but goreturns has issues with vendor pkgs and global variables that conflict with methods from other pkgs

The same issue existed in goimports before, but is now fixed. I have logged an issue for goreturns to use the same fix. https://github.com/sqs/goreturns/issues/40

Until that issue is fixed, use goimports

**Comment by xyi** [comment] 2017-12-25 00:45
I have the same issue which guide me to here. I think it should be reopened until the issue solved.

**Comment by ramya-rao-a** [comment] 2017-12-26 04:54
@xyi We won't be re-opening the issue as the fix needs to be done upstream in the `goreturns` tool. Am sure the author of the tool will welcome a PR if anybody here wants to give it a try. It should be a pretty simple fix.
- Add new flag `-srcdir` just like the one taken by `goimports`
- Pass the value to `goimports`

**Comment by ramya-rao-a** [comment] 2017-12-26 04:56
Re-opening this issue, so that as soon as we have the upstream issue fixed, the Go extension should be updated to pass the `-srcdir` flag to `goreturns`

**Closed** 2018-01-05 18:56 UTC
Labels: bug

**Comment by ramya-rao-a** [comment] 2018-01-05 19:43
This fix is now out in the latest update to the Go extension (0.6.71)

**Comment by quetool** [comment] 2018-01-11 20:02
I have installed 0.6.73 and still happening

**Comment by ramya-rao-a** [comment] 2018-01-11 22:08
@quetool Uninstalled what? Can you run `Go: Install/Update Tools` to ensure all the packages are up to date and try again?

**Comment by quetool** [comment] 2018-01-12 12:05
@ramya-rao-a uninstalled the Go extension. I do not have `Go: Install/Update Tools`.
![captura de pantalla 2018-01-12 a la s 09 02 27](https://user-images.githubusercontent.com/14978705/34874427-a539ce18-f777-11e7-8ed9-a9610e792e74.png)

these is my bug (it's my twitter account) https://twitter.com/quetool/status/951539146056749057

**Comment by ramya-rao-a** [comment] 2018-01-12 14:40
@quetool Is the package that is getting deleted used elsewhere in the code? Formatting removes unused imports.

**Comment by quetool** [comment] 2018-01-12 14:45
@ramya-rao-a  Yes, is used in some functions to send messages to slack. This is what you are asking?

![captura de pantalla 2018-01-12 a la s 11 43 55](https://user-images.githubusercontent.com/14978705/34880051-f55a0a46-f78d-11e7-8f19-34ab5c9018ac.png)

**Comment by ramya-rao-a** [comment] 2018-01-12 17:30
Can you update all the dependent Go tools and try again? You can run the command `Go: Install/Update Tools`  from the command pallet. Its not available in the menu

**Comment by yaoweizhen** [comment] 2018-01-13 02:21
> Formatting removes unused imports.
That makes no sense to remove unused imports quietly, instead, if it could be a warning.

**Comment by yaoweizhen** [comment] 2018-01-13 02:26
> Go: Install/Update Tools

Missing ">" , the command should be ">Go: Install/Update Tools"

**Comment by Newt0n** [comment] 2018-02-06 03:26
This issue still happening on 1.19.3(macOS), it's really really annoying for daily work, "goimports"/"goreturns" both don't work for me, any new fix?

**Comment by ramya-rao-a** [comment] 2018-02-06 22:09
@Newt0n Did you try updating the tools as suggested in https://github.com/Microsoft/vscode-go/issues/613#issuecomment-357302856?

**Comment by viettd** [comment] 2018-02-07 03:32
VSCode Version 1.19.3
Go Extension: 0.6.73
Tried to `>Go: Install/Update Tools` => the same
Updated `go.formatTool` to `gofmt` => solved

**Comment by Newt0n** [comment] 2018-02-07 05:05
@ramya-rao-a Yes, I've tried `Go: Install/Update Tools` but has no magic, only update `go.formatTool ` to `gofmt` works, just like @viettd .

**Comment by halfcrazy** [comment] 2018-02-07 14:07
@Newt0n The toolset to update is based on your config. (https://github.com/Microsoft/vscode-go/blob/d0c5309dd7f32689410e6f946245856c469ccc81/src/goInstallTools.ts#L90-L93)

**Comment by ramya-rao-a** [comment] 2018-02-07 17:36
@Newt0n, @viettd
- Add the setting `"go.formatTools": "goreturns"`
- Delete `goreturns` binary from your GOPATH. @Newt0n for you it would be `/Users/Newton/go/bin`
- Try manually formatting your Go file, you will be prompted that `goreturns` is missing and an option to install it. Choose "Install"
