### ISSUE TITLE
Formatting of hover tooltip changes with language server enabled

### ISSUE THREAD

**Issue by zmb3** [Microsoft/vscode-go#852] opened 2017-03-09 14:57 UTC
With language server enabled, the hover tooltips use the same monospace font everywhere:

![ls-type](https://cloud.githubusercontent.com/assets/7527103/23755503/cf90df1c-049d-11e7-9e63-353f0832bdfd.png)

When language server is disabled, the doc portion of the tooltip is rendered using the UI font and not the editor font.

![ggd-type](https://cloud.githubusercontent.com/assets/7527103/23755538/f04610b0-049d-11e7-9de6-564dfbf08a35.png)

Obviously not a dealbreaker, but I think it looked nicer with separate fonts.

**Comment by ramya-rao-a** [comment] 2017-03-09 19:31
Totally agree, I have been meaning to file this for a while, but have been swamped lately.
Thanks for reporting @zmb3!

I have narrowed the root cause to the languge server sending hover docs in markdown vs simple text.
There are 2 things to investigate here

1. Can the language server return simple text instead of markdown content? @sqs @keegancsmith
2. Why does VS Code render markdown content in the weird monospace font? @jrieken

**Comment by jrieken** [comment] 2017-03-10 08:07
The `MarkedString` is two types: `string` and `{language:string; value:string}` When you use the former you can just use markdown syntax to write text with links, bold, italics etc. The latter is a code and get translated to \```language\nvalue\n\```. It actually is contained in the former type and there for historic reasons. Rendering-wise only code is rendered in the editor-font, all the rest in the UI font

**Comment by keegancsmith** [comment] 2017-03-10 10:31
@jrieken for the docs string, we set the language as `markdown` in the `MarkedString` https://sourcegraph.com/github.com/sourcegraph/go-langserver@4193810334683f87b8ed5d896aa4753f0dfcdf20/-/blob/langserver/hover.go#L150:1-154:1

If I understand what you are saying correctly, our doc strings should be rendered in the UI font. This issue is saying it is rendered in the editor font. Should this be regarded as a bug in vscode, or am I misunderstanding you?

**Comment by jrieken** [comment] 2017-03-10 12:39
What you do this basically this

```markdown
This is **not** bold?
```

and not this

This is **not** bold?

**Comment by ramya-rao-a** [comment] 2017-03-23 18:30
@keegancsmith I took another look at this.

When we return a hover content of type `{language: string, value: string}`, it is treated as "code" and is rendered with editor font and syntax highlighting is applied as per the "language" provided. That is how you see the colors in the signature:

![image](https://cloud.githubusercontent.com/assets/16890566/24263796/7cbd619c-0fbb-11e7-9489-5adbb2be00c2.png)

The docs/comments are returned by the language server in the same form `{language: string, value: string}` with language as "markdown". This again gets treated as "code" and gets the editor font.

When language server is disabled, the Go extension returns the signature in the form `{language: string, value: string}` (See https://github.com/Microsoft/vscode-go/blob/29a5a495ca635584cd08c5fa25616a142ef9b2a3/src/goExtraInfo.ts#L27), but returns the docs/comments as just a string (See https://github.com/Microsoft/vscode-go/blob/29a5a495ca635584cd08c5fa25616a142ef9b2a3/src/goExtraInfo.ts#L29)

Thats how the comments get UI font.

Now to get the same from the language server, we should make [MarkedString](https://sourcegraph.com/github.com/sourcegraph/go-langserver@4193810334683f87b8ed5d896aa4753f0dfcdf20/-/blob/pkg/lsp/service.go#L203:1-204:1) a union type and update https://sourcegraph.com/github.com/sourcegraph/go-langserver@4193810334683f87b8ed5d896aa4753f0dfcdf20/-/blob/langserver/hover.go#L150:1-151:1 to return just a string

Is that doable?

**Comment by ramya-rao-a** [comment] 2017-06-05 17:29
This has been fixed in the language server.
Please get the latest by `go get -u github.com/sourcegraph/go-langserver`, restart VS Code and you should be able to see the fix.

**Closed by ramya-rao-a** 2017-06-05 17:29 UTC
