### ISSUE TITLE
Hovering over method shows documentation for same-named package-level function

### ISSUE THREAD

**Issue by Xjs** [microsoft/vscode-go#2632] opened 2019-07-05 11:07 UTC
When hovering the mouse over a method of a type that has the same name as a package-level function in the same package, the documentation of the package-level function is displayed.

(This seems to only occur in the mouseover hover window. The IntelliSense completion annotation seems ok)

Steps to Reproduce:

1. Create a Go file with e. g. the following content:
```
package main

import (
	"fmt"

	"github.com/golang/protobuf/proto"
)

var buf *proto.Buffer

func main() {
	var msg proto.Message

	if err := buf.Unmarshal(msg); err != nil {
		fmt.Println(err)
	}
}
```
2. Hover over `buf.Unmarshal` in line 13. 

Expected behaviour:

The bubble should contain the text »Unmarshal parses the protocol buffer representation in the Buffer and places the decoded result in pb.  If the struct underlying pb does not match the data in the buffer, the results can be unpredictable. Unlike proto.Unmarshal, this does not reset pb before starting to unmarshal.« (docstring of proto.Buffer.Unmarshal, cf. https://godoc.org/github.com/golang/protobuf/proto#Buffer.Unmarshal)

Observed behaviour:

The bubble contains the text »Unmarshal parses the protocol buffer representation in buf and places the decoded result in pb. If the struct underlying pb does not match the data in buf, the results can be unpredictable. Unmarshal resets pb before starting to unmarshal, so any existing data in pb is always removed. Use UnmarshalMerge to preserve and append to existing data.« (docstring of proto.Unmarshal, cf. https://godoc.org/github.com/golang/protobuf/proto#Unmarshal)

**Comment by ramya-rao-a** [comment] 2019-07-06 07:10
I believe the root cause for this is similar to that of #2107

The extension runs `go doc github.com/golang/protobuf/proto Unmarshal` to get the documentation on the word over which you hover. This gives docs on the function

To get docs on the method on the struct/type, the extension should be running `go doc package-import-path Buffer.Unmarshal`.

But, at this point the extension is not aware that it should be using the `Buffer.` prefix on the symbol.

Have you tried the [language server](https://github.com/microsoft/vscode-go#go-language-server)? Since it maintains more context on the file, its ast etc, it might be giving more accurate information

**Comment by Xjs** [comment] 2019-07-08 09:01
Thanks for your reply! The language server does give more accurate information; however, only the first sentence of the documentation is displayed. (That first sentence is correct, though.)

I haven't found anything in the docs, can the language server (gopls in this case) be persuaded to output more than the first sentence? Is that a bug I should report to gopls? I'm not sure how this all plays together.

**Comment by Xjs** [comment] 2019-07-08 09:24
Found it myself, for the record, including

```
"gopls": { "hoverKind": "FullDocumentation" }
```

in settings.json does what I want.

**Comment by ramya-rao-a** [comment] 2019-07-10 02:16
Oh wow, I was not aware of that setting :)

Glad that you found it out.

Closing this issue in favor of #2107

Happy Coding!

**Closed by ramya-rao-a** 2019-07-10 02:16 UTC
