### ISSUE TITLE
Perfomance downgrade when using "go module" mode

### ISSUE THREAD

**Issue by sashker** [Microsoft/vscode-go#2251] opened 2019-01-15 04:53 UTC
Hello.

I saw similar tickets and they were closed (probably #2217) but I can state that difference in performance with modules and without is dramatic.

Having go.mod and go.sum within a project directory, I might wait for auto complete and other functions up to 3 seconds. Simply removing go.sum and go.mod makes VS works as usual pretty quickly.

Testing project is quite small (around 1000 strings) though use many dependencies.

Go version: 1.11.4
Platform: darwin

**Comment by eknkc** [comment] 2019-01-15 15:39
This is also what I see. Due to the unusable performance I use go mod vendor to vendor in any dependencies and use vscode in non-module way. Go cli still uses the modules.

The exact same project with modules enabled is significantly slower (to the point that it's unusable) in code completion / reference lookups etc.

**Comment by hnlq715** [comment] 2019-01-16 03:09
+1

**Comment by abdullahsaleem93** [comment] 2019-01-16 10:16
+1 becomes almost unusable

**Comment by eknkc** [comment] 2019-01-16 13:02
BTW, just checked the language server stuff. [bingo](https://github.com/saibing/bingo) seems to be working fine with decent performance. However saibing/bingo#54 is kind of a deal breaker for me. I guess the language servers are the way to go in future development?

**Comment by sashker** [comment] 2019-01-16 13:08
I tried recommended language server by Sourcegraph but it doesn't eliminate the problem. I believe that we have to wait until the upcoming server from Google.
Anyway, I'd love to understand what causes such a problem.

**Comment by OneOfOne** [comment] 2019-01-16 18:15
@sashker sourcegraph lsp is mostly dead / maintained, I recommend using `bingo`.

```
	"go.useLanguageServer": true,
	"go.languageServerFlags": ["-format-style=goimports"],
	"go.languageServerExperimentalFeatures": {
		"format": true,
		"autoComplete": true,
		"rename": true,
		"goToDefinition": true,
		"hover": true,
		"signatureHelp": true,
		"goToTypeDefinition": true,
		"goToImplementation": true,
		"documentSymbols": true,
		"workspaceSymbols": true,
		"findReferences": true
	},
```

@eknkc a simple workaround would be typing the package name and saving (while `"go.languageServerFlags": ["-format-style=goimports"]` is set to get it imported, I know it's inconvenient but it's still way better than the alternative.

**Comment by OneOfOne** [comment] 2019-01-16 18:41
I forgot to paste that part, not fully awake yet :)

**Comment by ramya-rao-a** [comment] 2019-01-20 21:20
A few notes:
- Yes, language server is the way for future delvelopment, and we are hoping that the one from Google would cater to both module and GOPATHs
- The Go language server by Sourcegraph does not support modules and has stopped adding new features
- If you want to use bingo as your language server, install it and then follow the settings in https://github.com/Microsoft/vscode-go/issues/2251#issuecomment-454883375
- If you are not using the language server and are seeing slowness in auto-completion, please log an issue at https://github.com/stamblerre/gocode

**Comment by segevfiner** [comment] 2019-01-23 15:45
I wonder if this is related https://github.com/golang/go/issues/29427.

**Comment by CMGS** [comment] 2019-03-26 06:42
+1

**Comment by lucashtc** [comment] 2019-04-02 02:31
+1 becomes almost unusable

**Comment by ramya-rao-a** [comment] 2019-04-03 06:13
Hello everyone,
Thanks for your patience.

Please install the [latest beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.7) of this extension.
I'll be releasing the same in the next update to the extension early next week. https://github.com/Microsoft/vscode-go/issues/2410 is the test plan for the next update if anyone is interested.

The beta version will prompt you to use `gopls`, the language server from Google if it detects that you are using Go modules. Please install and use the language server. It performs much better especially for auto-completions.

This was the long term plan for module support. Therefore, closing this issue.

If you find any other performance issue while using `gopls`, please log new issues.

Thanks again and Happy Coding!

**Closed by ramya-rao-a** 2019-04-03 06:13 UTC
Labels: go-modules

**Comment by hnlq715** [comment] 2019-04-03 08:07
nice job

**Comment by Helcaraxan** [comment] 2019-04-03 08:10
Having switched to using `bingo` a few days ago I can confirm that the language servers are _really_ fast, even if they are still in their infancy and will require quite a lot of polishing.

Autocomplete is back at its usual speed. And renaming symbols is actually 100x faster (as in _instantaneous_). You can also now rename symbols on non-compiling files which we couldn't before.

Next pet-pieve (but which is not this extension's issue): loading times of my very large project with the language server which is now ~8 minutes.

**Comment by wooque** [comment] 2019-04-03 11:05
`bingo` is currenlty better than `gopls`
It uses less memory and has more features (supports renaming symbols for example)

**Comment by glerchundi** [comment] 2019-04-03 11:11
As stated on the `bingo`s readme:
```
Note
I am very sorry that I have planned not continue to maintain this project.

According to the issue #13 collaborating on golsp, I hope that we will eventually have a unified language server: gopls.

It is Google's upcoming Go language server. It is in the best interests of the community to only have a single language server.

I have ported some features such as references, rename, workspace symbol, implementation of bingo to gopls.

If you want to use the enhanced version of gopls, try https://github.com/saibing/tools.
```

**Comment by treeder** [comment] 2019-04-03 14:08
@ramya-rao-a there's no vsix file here to install: https://github.com/Microsoft/vscode-go/releases/tag/latest

**Comment by ramya-rao-a** [comment] 2019-04-03 16:52
@treeder Thanks for letting me know, I must have clicked the "Publish Release" button before the upload was complete. The release is updated now.

All, please read the section on language servers at https://github.com/Microsoft/vscode-go/blob/8ea6e4708dfd141ab65b4c7eb4f71e55d098a222/README.md#go-language-server-experimental as well.

**Comment by treeder** [comment] 2019-04-03 17:03
😮  wow, this is like night and day, sooooooo much better. It's basically instant now whereas it was taking like 5 seconds to click through references before. Nice work!

**Comment by sevein** [comment] 2019-04-06 23:04
Wow, using `useLanguageServer` and `gopls`.
So fast! My old laptop and I thank you very much.

**Comment by kyleferguson** [comment] 2019-04-11 21:55
Mine was also super slow and using the beta version mentioned by @ramya-rao-a  and the gopls language server (which auto requests to be installed when you edit a go file after adding the beta version) fixed the issues for me. Thanks!!
