### ISSUE TITLE
0.6.71 rejects all changes, until goreturns is updated

### ISSUE THREAD

**Issue by ryantriangles** [Microsoft/vscode-go#1447] opened 2018-01-08 17:56 UTC
The update to 0.6.71 has introduced a strange bug for me, which persists even despite uninstalling and re-installing the plugin: the formatting process rejects any and all changes, with the sole exception of defining the package name. 

![vscode-go_problem_a](https://user-images.githubusercontent.com/6828359/34684178-5ae835d8-f4f8-11e7-8b3a-c84beef58a8b.gif)

Any lines I add to a file will be erased the moment I save. Any lines I delete from a file will be restored the moment I hit save. It doesn't remove legitimate lines that were already there – if I write some code in vim, then open the file in VS Code and edit it, saving only removes the lines VS Code added. (It does still remove illegitimate lines, like an unused import.)

![vscode-go_problem_b](https://user-images.githubusercontent.com/6828359/34684297-cadfeeb2-f4f8-11e7-9c6f-b85855001ff4.gif)

I don't have auto-save on, and I haven't customised any of VSCode-Go's settings.

**Comment by ramya-rao-a** [comment] 2018-01-08 20:31
Until the issue is resolved, add the below in your settings
```
"[go]": {
      "editor.formatOnSave": false
}
```

Do you see any errors in the console? Help -> Toggle Developer Tools -> Console

**Comment by ramya-rao-a** [comment] 2018-01-08 20:33
Does manual formatting remove the changes as well?

**Comment by ramya-rao-a** [comment] 2018-01-08 23:23
Can you repro it if you added the setting `"go.formatTool": "goimports"` or `"go.formatTool": "gofmt"`?

**Comment by harunrzl** [comment] 2018-01-09 04:16
I've got similar error. Somehow it solved after I install this package:
`go get -u -v sourcegraph.com/sqs/goreturns`

**Comment by ramya-rao-a** [comment] 2018-01-09 05:21
Thanks @harunrzl. `goreturns` is the default tool used for formatting. 

@ryantriangles Does that help you as well?

**Comment by Deleplace** [comment] 2018-01-09 10:34
Same problem.
A top-popin said "Works better with latest version of goreturns, install it?", I clicked OK and now it is fixed.
If you don't get the popin, try the `go get` command given by @harunrzl

**Comment by ryantriangles** [comment] 2018-01-09 13:25
Setting `"go.formatTool"` to `"goimports"` or `"gofmt"` eliminates the problem, so it does seem to be something with goreturns. 

Invoking goreturns manually works fine, and doesn't remove the lines that it removes in vscode-go.

Despite installing goreturns manually (with `go get -u -v sourcegraph.com/sqs/goreturns`), the first launch of VS Code in a Go folder always triggers the prompt "The Go extension is better with the latest version of 'goreturns', Update/Cancel." Clicking Update successfully triggers another install of goreturns, but doesn't solve the problem (neither within the session nor after re-launching).

**Comment by ramya-rao-a** [comment] 2018-01-09 19:50
@ryantriangles Looks like the `goreturns` that is getting updated and the one that is getting used by the Go extension are different in your case. Can you search your machine for the file `goreturns` (`goreturns.exe` in case of Windows) and see if you have more than 1?

I am able to repro the issue by installing an older version of `goreturns`. The newer version supports the flag `srcdir` which the latest version of the Go extension needs. If user still has the older version, the Go extension re-tries formatting by calling `goreturns` again, but this time without the srcdir flag. Looks like there was a race condition causing the current issue in this case.

I have pushed a fix which you can try as well.
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix`
- Reload VS Code window and try editing and saving your files.

**Comment by ramya-rao-a** [comment] 2018-01-09 23:38
I've published a release that should fix this issue.

Sorry for the trouble everyone.

**Closed by ramya-rao-a** 2018-01-09 23:38 UTC

**Comment by zengming00** [comment] 2018-01-10 06:42
Now, code formatting never work☹

**Comment by wangjieyanda** [comment] 2018-01-10 07:07
me too,the vscode formatting never work,I cannnot write code with the ide

**Comment by ramya-rao-a** [comment] 2018-01-10 18:05
@zengming00 @wangjieyanda Which platform are you on? Windows? Mac? Linux?

**Comment by ramya-rao-a** [comment] 2018-01-10 18:08
Looks like the original issue was a Windows only issue which was solved by my fix. But my fix in turn caused issues in Mac :(

**Comment by wangjieyanda** [comment] 2018-01-12 10:10
it was solved in 0.6.72 version,thanks @ramya-rao-a

**Comment by WenhaiLin** [comment] 2018-01-13 06:51
@ramya-rao-a The binary program of `goreturns` is not updated automatically when go-extension has been updated on Mac.

@zengming00 @wangjieyanda You can build the binary program of `goreturns` manually and then replaces it with the new on.

**Comment by ramya-rao-a** [comment] 2018-01-13 23:06
@WenhaiLin Do you get the pop up asking you to update `goreturns`?

**Comment by WenhaiLin** [comment] 2018-01-15 08:23
@ramya-rao-a Yes, it happen time and time again. So I build the binary program of `goreturns` manually. 

**Comment by ramya-rao-a** [comment] 2018-01-15 16:09
@WenhaiLin Then `go get -u` must be failing to update the tool. I found myself in a weird setup where `go get -u` would update the source code of the Go tool I am updating but would not update the binary.

Try running it manually
`go get -u -v sourcegraph.com/sqs/goreturns`. If you have set `go.toolsGopath` then set `export GOPATH=<value of the the go.toolsGopath>` before running `go get` and then set it back to the older GOPATH

**Comment by byrain** [comment] 2018-01-18 10:37
@ramya-rao-a @WenhaiLin 
thank you so much! Build `goreturns` manually solved my problem.
OS: MAC.  Vscode version:1.19.2
