### ISSUE TITLE
Docs for all functions of the same name in the package are combined in hover and auto-completion feature

### ISSUE THREAD

**Issue by SmallRoomLabs** [Microsoft/vscode-go#2404] opened 2019-03-31 10:54 UTC
On VCS 1.26.1 with go plugin 0.9.2 on go1.12.1 darwin/amd64 I get the text in the quick info-popup repeated three times as shown in this screenshot-photo (I couldn't figure out how to make a screenshot without the popup closing).

The same thing happens also for longer doc-texts so it's not caused because it's a single liner.
![InfoTimes3](https://user-images.githubusercontent.com/325326/55288162-b6a48f00-53b3-11e9-88a0-5e65b6fcea82.jpg)

**Comment by ramya-rao-a** [comment] 2019-04-01 04:44
Thanks for reporting @SmallRoomLabs 

- Are you using any of the language servers? If yes, which one?
- Are you using Go modules?
- Does this consistently happen or randomly?

**Comment by SmallRoomLabs** [comment] 2019-04-01 07:27
No language servers, not what I know of anyways.  I've disabled all plugins except the go. I've removed all user/workspace/folder settings.

Yes, go modules are enabled for this project

It happens consistently over reloads and restarts of vcs.

But I think I've possibly found the root cause here. Looking (in the terminal) at the godoc for testing.Errorf it shows the docs for both the Test, Benchmark and Main variants of Errorf.  Docs for all three are identical which in the popup looks as it's just repeated three times.

<img width="401" alt="Screen Shot 2019-04-01 at 9 16 11 AM" src="https://user-images.githubusercontent.com/325326/55309688-d5139480-545e-11e9-8196-0ae01a368ce5.png">

The same thing happens with the longer descriptions like for the testing.Run

<img width="574" alt="Screen Shot 2019-04-01 at 9 18 20 AM" src="https://user-images.githubusercontent.com/325326/55309944-7c90c700-545f-11e9-8788-8dff38330d86.png">

The popup displays all three sections of this text, but removes the non-indented "headers"

<img width="546" alt="Screen Shot 2019-04-01 at 9 24 56 AM" src="https://user-images.githubusercontent.com/325326/55310153-10fb2980-5460-11e9-98fb-afce9f26f8c1.png">

So the bug here is not that the description is repeated, but rather that the popup removes the headers for the three different functions/methods from the godoc.  I guess the title of this issue should be renamed to something more appropriate.

**Comment by ramya-rao-a** [comment] 2019-04-01 16:41
Thanks for all the details @SmallRoomLabs, that is very helpful.

The issue is that while fetching docs, we only have access to package name and the symbol name (in this case the function name). If the same function name is used across multiple receivers, we don't know which receiver should we be using. This is being tracked in #2107

The last we checked this, the wrong function's docs were shown. @segevfiner, Do you recall that the docs for all the variations got combined?

**Comment by segevfiner** [comment] 2019-04-01 16:44
Yeah it often combines the docs of several functions of the same name into one.

We fixed this for auto complete, and we are still waiting on the `godef` PR that I made, so that we can reenable the commented out code that fixes this for hovers on our side.

**Comment by ramya-rao-a** [comment] 2019-04-03 06:14
Thanks @segevfiner 

@SmallRoomLabs I'll close this issue in favor of #2107

**Closed by ramya-rao-a** 2019-04-03 06:14 UTC
Labels: needs more info
