### ISSUE TITLE
formatting doesn't work 90% of the time when language server is enabled

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#1667] opened 2018-05-07 20:51 UTC
Like the title, there are no errors in any of the panels.

Sometimes it'll work, most of the time it doesn't.

Here's my current code settings: https://github.com/OneOfOne/dotfiles/blob/master/.config/Code/User/settings.json#L105

**Comment by ramya-rao-a** [comment] 2018-05-07 21:36
Even after disabling format on type and paste?
Any errors in the console? Help -> Toggle Developer Tools -> Console?
Is this a recent thing you noticed after an update to either VS Code or the Go extension itself?

**Comment by OneOfOne** [comment] 2018-05-07 21:51
Disabling all formatOnXXX doesn't 

No errors in Dev Console

Only things printed in Go's output panel:

```
....path...>Finished running tool: /home/oneofone/bin/go build -i -o /tmp/go-code-check ...pkg-path...

....path...>Finished running tool: /home/oneofone/bin/go vet ./...

....path...>Finished running tool: /home/oneofone/code/go/bin/megacheck
```

Running `goimports -w .` from the terminal works as expected.

https://github.com/OneOfOne/dotfiles/commit/9c24638e99cdd45519c9c49c9abe9245b81c8418

**Comment by OneOfOne** [comment] 2018-05-07 22:26
I will when I get a chance, I've been very busy lately, maybe next weekend unless someone else figures it out.

**Comment by OneOfOne** [comment] 2018-05-08 18:31
So https://github.com/Microsoft/vscode-go/issues/1662#issuecomment-387495548 seems to have fixed this problem as well, I don't understand how it's related (I didn't dig into the code yet).

I won't close this issue yet in case it's just randomly working.

**Comment by ramya-rao-a** [comment] 2018-05-09 04:15
@OneOfOne I'll close this issue nevertheless. If you see this happening again, you can re-open this issue. In case the issue is locked (which it does in 10 days or so), feel free to open a new issue

**Comment by OneOfOne** [comment] 2018-05-10 21:33
So this is back, it's related to turning off `go-langserver` (the bug where it randomly stops is back).

**Comment by ramya-rao-a** [comment] 2018-05-11 00:36
So you are seeing this even after using the fix from #1662 correct?

**Comment by ramya-rao-a** [comment] 2018-05-11 00:52
I randomly come across this as well, but no reliable repro steps.
One thing I've noticed is that there is a formatting error from the language server.
Looks like the language server now supports formatting and requests going there sometimes fail.

Can you keep the Output pane open, choose the "go-langserver" channel there and the next time you see formatting stop, check if the output pane has any formatting related error

**Comment by OneOfOne** [comment] 2018-05-15 02:05
```
langserver-go: reading on stdin, writing on stdout
Passing an initialize rootPath URI ("file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts") is deprecated. Use rootUri instead.
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'µ' '\x00'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x00'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x01'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x02'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x03'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x04'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x05'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x06'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\a'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\b'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\t'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\n'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\v'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\f'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\r'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x0e'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x0f'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x10'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x11'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¶' '\x12'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x01'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x02'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x03'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x04'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x05'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x06'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\a'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\b'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\t'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\n'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\v'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\f'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\r'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x0e'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x0f'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x10'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x12'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x13'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x14'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x15'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x16'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x17'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'·' '\x18'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'¸' '\x01'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go": file only has 182 lines
[Error - 5:00:50 AM] Request textDocument/hover failed.
  Message: invalid position: /home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go:183:25 (file only has 182 lines)
  Code: 0 
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for out of range position &{{'\x00' '\x00'} {'Ñ' '\x00'}} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/struct.go"
[Error - 5:01:31 AM] Request textDocument/formatting failed.
  Message: /home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/struct.go:161:7: expected ';', found "new "
  Code: 0 
[Error - 5:01:35 AM] Request textDocument/formatting failed.
  Message: /home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/struct.go:161:8: expected ';', found "new "
  Code: 0 
[Error - 5:01:37 AM] Request textDocument/formatting failed.
  Message: /home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/struct.go:161:8: expected ';', found "new "
  Code: 0 
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for out of range position &{{'\x00' '\x00'} {'¶' '\x00'}} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go"
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for out of range position &{{'\x00' '\x00'} {'¶' '\x00'}} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go"
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for out of range position &{{'µ' '\x01'} {'¶' '\x00'}} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go"
[Error - 5:03:51 AM] Request textDocument/formatting failed.
  Message: /home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/s2ts.go:1:1: expected 'package', found ackage
  Code: 0 
[Error - 5:04:17 AM] Request textDocument/formatting failed.
  Message: /home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/struct.go:162:8: expected ';', found "new "
  Code: 0 
[Error - 5:04:34 AM] Request textDocument/formatting failed.
  Message: /home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/struct.go:161:8: expected ';', found "new "
  Code: 0 
jsonrpc2 handler: notification "$/setTraceNotification" handling error: jsonrpc2: code -32601 message: method not supported: $/setTraceNotification
[Error - 5:04:47 AM] Request textDocument/formatting failed.
  Message: /home/oneofone/code/go/src/github.com/OneOfOne/struct2ts/struct.go:161:8: expected ';', found "new "
  Code: 0 
```

**Comment by ramya-rao-a** [comment] 2018-05-15 05:54
That looks similar to what I logged in https://github.com/sourcegraph/go-langserver/issues/277

**Closed** 2018-05-16 01:35 UTC
Labels: upstream

**Comment by ramya-rao-a** [comment] 2018-05-16 01:37
@OneOfOne I've added a setting to opt in to the not yet stable features from the language server. Try the below and your formatting issues should be solved even when `go.useLanguageServer` is `true`


- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

And when you want to try the formatting feature from the language server, add the below setting
```
 "go.languageServerExperimentalFeatures": {
      "format": true
    }
```

**Comment by OneOfOne** [comment] 2018-05-16 02:15
You rock, thanks.

I'll try it once I get home tomorrow morning.
