### ISSUE TITLE
gocode method autocompletion lookup does not seem to be working properly with go 1.11

### ISSUE THREAD

**Issue by phenixrizen** [Microsoft/vscode-go#1891] opened 2018-08-29 01:50 UTC
Steps to Reproduce:

1. Install go 1.11
2. Update go tools from within vscode
3. Try to autocomplete a method

**Comment by ramya-rao-a** [comment] 2018-08-29 07:14
@phenixrizen When updating go tools, did you get the message that all tools were updated?
After every change in Go version, we need the tools to be re-compiled for them to work.

Also, are you using `go.mod`?

**Comment by cryptix** [comment] 2018-08-29 14:18
I had multiple strange behaviors when opening a `go.mod` project outside of a gopath setup.

* when using _Go to Definition (F12)_, even on types in the same project, not a module. The loading bar just doesn't finish.
* on one instance `go vet` somehow populated with all the go tools dependencies into my projects `go.mod` (a seperate tidy cleaned it up) even though I was using separate `go.toolsdir` settings.

I haven't been able to reproduce this one yet but vscode-go generally feels sluggish in _go module mode_ so I haven't tested that much further.

**Comment by phenixrizen** [comment] 2018-08-29 15:48
@ramya-rao-a  I'm not using module-aware mode

**Comment by phenixrizen** [comment] 2018-08-29 16:34
@ramya-rao-a for reference I've opened a issue on the gocode repo: https://github.com/mdempsky/gocode/issues/48

**Comment by ramya-rao-a** [comment] 2018-08-29 17:36
Thanks @phenixrizen 

since you are getting zero candidates when running `gocode -s -debug`, its definitely an issue with `gocode` itself.

I'll close this issue in favor of the upstream issue you have already created

**Closed by ramya-rao-a** 2018-08-29 17:36 UTC
Labels: needs more info
