### ISSUE TITLE
Automatic reformatting of source code makes editing very difficult

### ISSUE THREAD

**Issue by DogFather** [Microsoft/vscode-go#1193] opened 2017-09-05 07:06 UTC
Whenever I am editing a .go file in VS Code (go v1.9, latest version vscode-go, delve debugger) the document is continuously reformatted whilst typing. The cursor often moves to new location causing input to be entered in the wrong place. Also parts of the text are automatically selected causing the next bit of typing to overwrite the selection.

**Example:** 
I want to enter, say, fmt.Println("Hello World!"). Starting on a blank line at left margin I start typing. If I then hit 'f' and pause temporarily, the formatter inserts a Tab, repositions the 'f' after the Tab and highlights it (along with any matching 'f' in the code). If I then hit 'm', the 'f' is overwritten.

The behaviour occurs so frequently, and extremely irritatingly, I am having to use another editor to enter my code.

I have tried overriding the go.formatTool setting with "gofmt" instead of "goreturns" but this has no effect.

**Comment by ramya-rao-a** [comment] 2017-09-05 19:46
You seem to have Auto Save enabled.
Format on Save is enabled by default.

This is a duplicate of #899 and is fixed in the latest update to the Go extension (0.6.64) that I released a few minutes ago.

Can you reload your VS Code window and the extension will get updated (unless you have configured it otherwise) and try again?

**Closed by ramya-rao-a** 2017-09-05 19:46 UTC
