### ISSUE TITLE
Cannot read property 'currentGoroutine' 

### ISSUE THREAD

**Issue by yinanrong** [Microsoft/vscode-go#675] opened 2016-12-02 09:21 UTC
it throws when i debug my program with input a parameter  from vscode command line .
the parameter i read just like 	 this.
`  var port int `
` fmt.Scanln(&port)`
everything is ok if i use  go command line to compile .
## the whole  excption:

> TypeError: Cannot read property 'currentGoroutine' of null\n    at GoDebugSession.evaluateRequest (C:\Users\eval\.vscode\extensions\lukehoban.Go-0.6.51\out\src\debugAdapter\goDebug.js:595:45)\n    at GoDebugSession.DebugSession.dispatchRequest (C:\Users\eval\.vscode\extensions\lukehoban.Go-0.6.51\node_modules\vscode-debugadapter\lib\debugSession.js:424:22)\n    at GoDebugSession.ProtocolServer._handleData (C:\Users\eval\.vscode\extensions\lukehoban.Go-0.6.51\node_modules\vscode-debugadapter\lib\protocol.js:104:38)\n    at Socket.<anonymous> (C:\Users\eval\.vscode\extensions\lukehoban.Go-0.6.51\node_modules\vscode-debugadapter\lib\protocol.js:24:60)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at Pipe.onread (net.js:543:20)

**Comment by ramya-rao-a** [comment] 2016-12-16 02:37
Can you share a sample code project that we can use to repro this?

**Comment by svanas** [comment] 2016-12-16 16:25
#473

**Comment by ramya-rao-a** [comment] 2017-01-11 22:28
@yinanrong I am assuming that when you say "vscode command line" you mean the debug console.
And so closing as duplicate of #473

**Closed by ramya-rao-a** 2017-01-11 22:28 UTC
Labels: debug
