### ISSUE TITLE
Start Without Debugging doesn't work with filepath

### ISSUE THREAD

**Issue by turbosheep44** [microsoft/vscode-go#3126] opened 2020-03-25 14:39 UTC
### What version of Go, VS Code & VS Code Go extension are you using?

`go version`
	- go version go1.13.6 linux/amd64
`code -v`
	- 1.43.2
VS Code Go extension version
	- 0.13.1
`go env GOOS GOARCH`
	- linux amd64

### Describe the bug

Even when the `launch.json` configuration points to a file path, 'Run without debugging' still hits breakpoints.

### Steps to reproduce

Use the `helloweb` snippet to generate a basic project.

Use the following `launch.json`:

```
{
    "version": "0.2.0",
    "configurations": [{
        "name": "Launch Server",
        "type": "go",
        "request": "launch",
        "program": "${workspaceFolder}/main.go",
    }]
}
```

Using `Run -> Start Debugging` works normally (hits breakpoints etc.), however using `Run -> Run Without Debugging` still hits breakpoints and stall execution.

**Comment by stamblerre** [comment] 2020-03-25 14:58
Duplicate of https://github.com/microsoft/vscode-go/issues/3121

**Comment by stamblerre** [comment] 2020-03-25 15:00
This will be fixed in the next version of the extension (you can install the [current beta](https://github.com/microsoft/vscode-go/releases/tag/latest) by following the instructions [here](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) if you want to try it earlier).

**Closed by stamblerre** 2020-03-25 15:00 UTC
