### ISSUE TITLE
Issue with multiple paths in GOPATH

### ISSUE THREAD

**Issue by margenton-dbg** [Microsoft/vscode-go#2001] opened 2018-10-12 20:26 UTC
Issue Type: <b>Bug</b>

- Setup a GOPATH with multiple paths
- Install some go tooling (not sure how to trigger that)
- The error messages suggest that the module didn't detect the multiple paths in the GOPATH

Extension version: 0.6.91
VS Code version: Code - Insiders 1.28.0-insider (caaa5369cb4d22b7481e6ff97252cf92937709eb, 2018-09-28T05:18:20.266Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (13.32GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jrwren** [comment] 2018-10-12 22:18
This is a duplicate of #1966

**Comment by ramya-rao-a** [comment] 2018-10-15 21:57
Thanks @jrwren!

@margenton-dbg #1966 is tracking this issue and @jrwren's fix is available as described in 
https://github.com/Microsoft/vscode-go/issues/1966#issuecomment-430028529

**Closed by ramya-rao-a** 2018-10-15 21:57 UTC
