### ISSUE TITLE
`TypeError: Cannot read property 'stopOnEntry' of undefined` when attaching to remote debugger with breakpoints

### ISSUE THREAD

**Issue by jeffcharles** [Microsoft/vscode-go#1008] opened 2017-05-24 19:59 UTC
VSCode version: 1.12.2
Go extension version: 0.6.61

I have my launch configurations defined as:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch test package",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "program": "${workspaceRoot}"
        },
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "remotePath": "${workspaceRoot}",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/consumer",
            "env": {},
            "args": [],
            "showLog": true,
            "stopOnEntry": true
        }
    ]
}
```

When I run _Launch_ after setting some breakpoints, I get `TypeError: Cannot read property 'stopOnEntry' of undefined`. Whenever I restart the same debugger I get the same error. The debugger panes are all empty except for the breakpoint panes after this error comes up. Disabling the breakpoints and restarting the debugger makes the error go away but pressing the play button doesn't cause the program to run at all.

The remote output looks like: 

```
2017/05/24 19:35:10 server.go:73: Using API v1
2017/05/24 19:35:10 debugger.go:97: launching process with args: [/vidyard/go/src/github.com/vidyard/Calculon/consumer/debug]
API server listening at: [::]:2345
2017/05/24 19:35:23 debugger.go:350: created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0xa0bb48, File:"/vidyard/go/src/github.com/vidyard/Calculon/consumer/<scrubbed>.go", Line:87, FunctionName:"main.<scrubbed>", Cond:"", Tracepoint:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(nil), LoadLocals:(*api.LoadConfig)(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2017/05/24 19:35:23 debugger.go:350: created breakpoint: &api.Breakpoint{ID:2, Name:"", Addr:0xa109a7, File:"/vidyard/go/src/github.com/vidyard/Calculon/consumer/<scrubbed>.go", Line:17, FunctionName:"main.<scrubbed>", Cond:"", Tracepoint:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(nil), LoadLocals:(*api.LoadConfig)(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2017/05/24 19:35:23 debugger.go:505: continuing
2017/05/24 19:36:15 debugger.go:496: halting
```

**Comment by ramya-rao-a** [comment] 2017-05-31 05:35
Thanks for reporting @jeffcharles.

Does debugging work for you when `stopOnEntry` is set to `false`?

@roblourens `stopOnEntry` is set to `true` here, would this be a duplicate of what you logged in #763 ?

**Comment by roblourens** [comment] 2017-05-31 06:30
Yeah, possibly.

**Comment by jeffcharles** [comment] 2017-06-01 01:16
Setting it to `false` raises the same error

**Comment by ramya-rao-a** [comment] 2017-06-01 04:09
@jeffcharles Can you share the callstack for the error "TypeError: Cannot read property 'stopOnEntry' of undefined" ?

**Comment by shayzu** [comment] 2017-07-09 12:37
Hi,

Forgive me if I am "complaining" on the wrong thread - and if I am wrong please forward me to the right one.

I am also having hard  time with the extension:
From /Users/shayzukerman/go/src/oracle_db, I have set a breakpoint in the first and second lines in function main(), and when connecting to the remote server, the program runs until in terminates.
My setup:

Relevant block in launch.json:

            "name": "Remote on Centos 7 VM",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "remotePath": "${workspaceRoot}",
            "port": 2345,
            "host": "192.168.56.101",
            "program": "${workspaceRoot}/src/oracle_db",
            "env": {},
            "args": [],
            "showLog": true,
            "stopOnEntry": true
        }
Remote server command:
oracle@Cent64Ora12 oracle_db]$ dlv debug --headless  --listen=192.168.56.101:2345
API server listening at: 192.168.56.101:2345

When connecting to the Remote server from a terminal:
Shays-MacBook:oracle_db shayzukerman$ dlv connect 192.168.56.101:2345
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x4de95b for main.main() /home/oracle/go/src/oracle_db/oracle_db.go:38
(dlv) c
> main.main() /home/oracle/go/src/oracle_db/oracle_db.go:38 (hits goroutine(1):1 total:1) (PC: 0x4de95b)
(dlv)

Delve's version on the client and the server:
Delve Debugger
Version: 1.0.0-rc.1
Build:

Version of "Go" Extension for VSCODE: 0.6.62 - 9th June, 2017.

What have I done wrong?

**Comment by ramya-rao-a** [comment] 2017-07-10 00:43
@shayzu If you are not getting the error "TypeError: Cannot read property 'stopOnEntry' of undefined" then this is the wrong thread. You can open a new issue.

From your description, I understand that you are trying remote debugging and that you have also tried delve from the command line. What I don't understand is what the problem is.

**Comment by shayzu** [comment] 2017-07-10 14:46
Hi,

When conducting a remote debugging from VSCODE's Go debugger - the remote debugger does not stop in the breakpoints. which were set in the editor.
On the other hand, it does stop when the Remote Delve server is controlled from a local Delve client.

No, I don't receive the 'stopOnEntry' of undefined" error.
So, I will open a new issue.

Thanks
 
Shay

**Comment by ramya-rao-a** [comment] 2018-01-09 03:03
@jeffcharles Closing this issue as we havent heard back from you.

If you still see problems with debugging, please log a new issue

**Closed by ramya-rao-a** 2018-01-09 03:03 UTC
Labels: debug
