### ISSUE TITLE
automatic import adder should not separate first import from its comment

### ISSUE THREAD

**Issue by mbenkmann** [microsoft/vscode-go#1701] opened 2018-05-31 09:33 UTC
0. Relevant Settings:

       "go.autocompleteUnimportedPackages": true

1. Type the following program

```
package main

//#include <stdlib.h>
import "C"

func main() {
    fmt
}
```

2. Place cursor behind "fmt"
3. Type "."  The Intellisense window should pop up with suggestions.
4. Accept any suggestion (e.g. "Errorf")
5. The import statement will be rewritten to

```
//#include <stdlib.h>
import (
	"fmt"
	"C"
)
```

However this breaks the magic of import "C" which uses the preceding comment.

When converting import lines to a parenthesized import block, vscode-go should insert the "import (" before the comment lines immediately preceding (i.e. with no empty lines in between) the first import (if there are any).

**Comment by ramya-rao-a** [comment] 2018-05-31 15:04
Can you share what happens when you just type out `fmt.Println("hello")` and then format the file? The formatter adds missing imports as well. I am curious to see how that is handled.

**Comment by mbenkmann** [comment] 2018-05-31 15:27
If vscode-go is supposed to add imports on "Format Document", then it doesn't seem to be working. Only if I set the formatTool to "goimports" does "Format Document" add imports. As for goimports' behaviour, it simply adds another import line without switching to the parentheses form, so it does not break the code.

**Comment by mbenkmann** [comment] 2018-05-31 15:30
I am not aware of any other magic packages aside from "C".

**Comment by mbenkmann** [comment] 2018-05-31 16:15
Having a brief a look at the code. The culprit seems to be src/goImport.ts:getTextEditForAddImport. As the code is currently written it simply inserts "import (" before the first import and then replaces "import" with "\t". In a case like this

```
import "foo"

//...
import "C"

import "bar"
```

that process works fine. It's only when the "C" is the first import that this breaks because it inserts the "import (" between the "C" and the comment. That's the actual issue. If the first package is preceded by a comment line, then the "import (" must be inserted before the comment. I don't even see this as a special case for "C". If someone writes code like this
```
// Use package "foo" instead of "newfoo" because the latter is still too buggy
import "foo"
```

converting it to

```
// Use package "foo" instead of "newfoo" because the latter is still too buggy

import (
  "foo"
  "fmt"
)
```

also breaks the association between the package and the comment.

So the solution would look something like this:

Current code:
```
edits.push(vscode.TextEdit.insert(new vscode.Position(imports[0].start, 0), 'import (\n\t"' + arg + '"\n'));
```

Fixed code (pseudo-code as I don't know vscode-go well enough):

```
insertBeforeLine = imports[0].start;
while (insertBeforeLine > 0) && textOfLine(insertBeforeLine-1).matches(/^\s*\/\//) {
  insertBeforeLine = insertBeforeLine - 1 ;
}
edits.push(vscode.TextEdit.insert(new vscode.Position(insertBeforeLine, 0), 'import (\n\t"' + arg + '"\n'));
```

This only handles // comments but I think that's fine. All of the examples in the documentation of cgo use these comments, so I'm sure 99% of programmers do that, too.

**Comment by stamblerre** [comment] 2020-02-12 18:13
This is a feature request for `goimports` - VS Code Go should not modify the output produced by `goimports`.

@heschik: Would you support a change like this or is this working as intended?

**Comment by heschik** [comment] 2020-02-12 18:19
Seems someone got to it in the intervening 2 years.

```
$ cat foo.go
package main

//#include <stdlib.h>
import "C"

func main() {
    fmt.Print()
}
$ goimports foo.go
package main

//#include <stdlib.h>
import "C"
import "fmt"

func main() {
	fmt.Print()
}
```

**Comment by stamblerre** [comment] 2020-02-12 18:35
Great! Closing this issue since it is now fixed.

**Comment by stamblerre** [comment] 2020-02-12 18:41
Ah, my mistake - I didn't realize that VS Code had extra code for handling `goimports`, so while this is fixed in `goimports`, it's not in VS Code Go. As an alternative, @mbenkmann, you can try using the [language server](https://github.com/golang/tools/blob/master/gopls/doc/vscode.md), which does not have this problem.

**Closed** 2020-04-27 23:48 UTC
Labels: help wanted, needs-decision

**Comment by ramya-rao-a** [comment] 2020-05-13 07:09
The latest update 0.14.2 has the fix for this, Thanks @hyangah 
And thanks for reporting @mbenkmann
