### ISSUE TITLE
Yacc generated file crashes gopls server

### ISSUE THREAD

**Issue by ddyok** [microsoft/vscode-go#2847] opened 2019-10-21 09:37 UTC
The attached file crashes gopls server.
[yacc.go.txt](https://github.com/microsoft/vscode-go/files/3749986/yacc.go.txt)
Open attached file (yacc.go.txt) in vscode (and change the .txt extension back to .go, of course, as github upload required an extension change).

**VSCode settings**
{
    "workbench.startupEditor": "newUntitledFile",
    "workbench.statusBar.feedback.visible": false,
    "workbench.colorTheme": "One Dark Pro Bold",
    "workbench.iconTheme": "vscode-icons",
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "editor.formatOnSave": true,
    "eslint.packageManager": "yarn",
    "javascript.validate.enable": false,
    "eslint.quiet": true,
    "workbench.colorCustomizations": {
        "editorWarning.foreground": "#ff0",
        "editorInfo.foreground": "#00f",
        "editorError.foreground": "#111111"
        // "editorError.border": "#111111"
    },
    "prettier.jsxSingleQuote": true,
    "prettier.singleQuote": true,
    "prettier.trailingComma": "es5",
    "prettier.useTabs": true,
    "prettier.arrowParens": "always",
    "prettier.tabWidth": 4,
    "editor.fontSize": 13,
    "editor.tabSize": 2,
    "editor.copyWithSyntaxHighlighting": false,
    "editor.cursorWidth": 2,
    "editor.minimap.showSlider": "always",
    "bracketPairColorizer.highlightActiveScope": true,
    "editor.matchBrackets": false,
    "bracket-pair-colorizer-2.highlightActiveScope": true,
    "breadcrumbs.enabled": false,
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "gitlens.blame.avatars": false,
    "editor.formatOnPaste": true,
    "editor.formatOnType": false,
    "vsicons.dontShowNewVersionMessage": true,
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true,
        "diagnostics": true,
        "documentLink": true
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        }
    },
    "gopls": {
        "usePlaceholders": true, // add parameter placeholders when completing a function
        // Experimental settings
        "completeUnimported": true, // autocomplete unimported packages
        // "watchChangedFiles": true, // watch file changes outside of the editor
        "deepCompletion": true, // enable deep completion
    },
    "files.eol": "\n", // formatting only supports LF line endings
}

**To Reproduce**
Open attached file (yacc.go.txt) in vscode (and change the .txt extension back to .go, of course, as github upload required an extension change).
[yacc.go.txt](https://github.com/microsoft/vscode-go/files/3749986/yacc.go.txt)

.

**Expected behavior**
Not to crash.

**Screenshots**

**System information:**
 -go version go1.13 darwin/amd64
 - 0.11.7
 - 1.39.2

**Additional context**

**Comment by stamblerre** [comment] 2019-10-21 16:47
I believe that this is a duplicate of https://github.com/golang/go/issues/34433. The crash should be fixed on master, but the underlying issue is not yet.

**Comment by stamblerre** [comment] 2019-10-21 16:47
Duplicate of https://github.com/golang/go/issues/34433

**Comment by ramya-rao-a** [comment] 2019-11-04 05:56
Thanks for reporting @ddyok!

Closing in favor of the upstream issue

**Closed by ramya-rao-a** 2019-11-04 05:56 UTC
