### ISSUE TITLE
Full call stack missing while debugging

### ISSUE THREAD

**Issue by allanbomsft** [Microsoft/vscode-go#2297] opened 2019-01-31 18:52 UTC
Steps to Reproduce:
1. Set a break point in a function
2. Start the debugger

Expected: Call Stack pane shows the full call stack
Actual: Call Stack pane only shows the current function, not the full call stack.

Issue happens with vscode-go version 0.8.
Issue does not happen with vscode-go version 0.7.
Used VS Code 1.30.2 on Windows 10 in both cases.

Version 0.8 (call stack is missing):
![2](https://user-images.githubusercontent.com/21695978/52077565-2af2bb80-2546-11e9-8f61-848d9096aebc.png)

Version 0.7 (call stack is visible as expected):
![1](https://user-images.githubusercontent.com/21695978/52077540-17475500-2546-11e9-8205-71fc11d01f7d.png)

**Comment by ramya-rao-a** [comment] 2019-02-01 03:10
This is a duplicate of #2187

We have the fix for this in our latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension. Please try that out or wait until we release an update next week.

**Closed by ramya-rao-a** 2019-02-01 03:10 UTC

**Comment by allanbomsft** [comment] 2019-02-01 23:14
Sorry for the dupe. I missed it because I had only searched in currently open issues.

**Comment by ramya-rao-a** [comment] 2019-02-02 00:56
No problem at all, Happy Coding!
