### ISSUE TITLE
Go modules projects makes intellisense and many other functionality is very slow

### ISSUE THREAD

**Issue by ahmetb** [Microsoft/vscode-go#2366] opened 2019-03-04 22:34 UTC
I'm working on a clean module cache and vscode extension at 0.9.2 with all the tools it uses cleanly installed.

Everything is slow when I use it with a project using Go modules (vgo).

For example:
- I hit ctrl+space for intellisense: takes 10 seconds or more, eventually fails most of the time.
- Go to Definition: Rarely works, takes at least 15 seconds (or feels like it)
- Save: as the extension compiles on save by default, I get the compilation errors in about 10-15 seconds later.

So the extension is **unbearably slow** right now for me. Often I see tons of `go` tool processes in the background eating up my CPU, and they all eventually finish around the same time and go away.

![image 1](https://user-images.githubusercontent.com/159209/53767368-78867f00-3e8a-11e9-89b7-d8ea72336b39.png)

I am suspecting that vscode-go directly/indirectly calling the `go` tool but it's not canceling execs when the intellisense or whatever else is cancelled (i.e. a new build comes but it's still trying to compile the old build).

## Repro

Just clone https://github.com/grpc-ecosystem/grpc-health-probe/ which has only 1 external module dependency (grpc-go) and try intellisense on `grpc.*` calls and see how it doesn't work.

**Comment by tj** [comment] 2019-03-04 22:36
possibly related to this node_modules stuff if you have any client-side projects in your GOPATH, sounds really similar — see https://github.com/golang/go/issues/30058 and #2276

**Comment by bketelsen** [comment] 2019-03-04 22:45
did you try deleting your $GOPATH/pkg directory?  Sometimes on upgrades, that's necessary for me.  I built it into my upgrade-go bash script.  It's a stretch...

**Comment by ahmetb** [comment] 2019-03-04 22:48
Yeah there's no $GOPATH set and I did `go clean -modcache`.

**Comment by ramya-rao-a** [comment] 2019-03-05 22:52
@ahmetb 

- Anyway you can check what arguments are those `go` process are running with?
- Can you share all your Go related settings that you have edited?

**Comment by ahmetb** [comment] 2019-03-06 08:32
@ramya-rao-a The only go.* setting I customize is `"go.toolsGopath": "~/gotools"` and it looks like many folks are experiencing similar stuff so it's probably not the settings.

I've tried to watch ps output as I refactor code, some stuff I see:

- on save
  - /Users/ahmetb/.homebrew/bin/go test -c -o /var/folders/h7/n46zg3md4l57vzsgxcs355hw00dl55/T/vscode-goSZbkWu/go-code-check .
  - /Users/ahmetb/.homebrew/bin/go vet ./...
- on intellisense
  - /Users/ahmetb/gotools/bin/gocode-gomod -s -sock unix -addr 127.0.0.1:37373
  - /Users/ahmetb/gotools/bin/gocode-gomod -f=json -builtin -ignore-case autocomplete /private/var/folders/h7/n46zg3md4l57vzsgxcs355hw00dl55/T/tmp.B1MZsZFnGe/internal/probe/tls_test.go

**Comment by ramya-rao-a** [comment] 2019-03-06 08:56
@ahmetb 

The reason I asked about the settings was to figure out if you are using the language server as well as  which of godef/gogetdoc tools are being used for code navigation.

The on save things you are seeing are build and vet being triggered. Try playing with `go.buildOnSave`, `go.vetOnSave` and `go.lintOnSave` settings to see if either of those are the reason for slowness

For intellisense/code-completion, we use `gocode` in general. For modules we use a fork of `gocode` and this is named `gocode-gomod` to ensure we have both the original and the fork, just in case you switch back and forth between modules and non-modules project. 

What you are seeing is one instance running in server mode (-s -sock) and the other in client mode for every completion request fired by VS Code.

- Run `gocode-gomod exit` to close the current server instance just in case it is trying to hold on to stale cache. 
- Try disabling the docs feature in completion by adding the below setting 
```
"go.gocodeFlags": [
	"-builtin",
	"-ignore-case",
	"-unimported-packages",
	"-exclude-docs"
]
```

If you still see completions being slow, then please log an issue at https://github.com/stamblerre/gocode

**Comment by mhr3** [comment] 2019-03-13 19:03
+1 mostly about the "Go to definition" being *incredibly* slow recently, any tricks to make that better?

Our project (gvt-based, no go mod) is pretty big and sometimes it used to take ~5seconds to find the definition, but now it sometimes works, other times it just spins for over a minute... (by which time I usually just quit vscode)

**Comment by ahmetb** [comment] 2019-03-13 20:31
@ramya-rao-a I think I probably shouldn't be disabling anything. I strongly recommend you reset all settings and follow the repro I provided in the original post.

It's not reasonable to expect an user rolling with the default settings to know so much detail about the tools used by the vscode-go extension. I personally have no desire to learn more about them, they should just work. :)

**Comment by ahmetb** [comment] 2019-03-14 22:00
Here's very small repro. This project has nothing but an empty go.mod and "os" import. Getting the method list for `os.*` intellisense took 3.5 seconds.

![image](https://user-images.githubusercontent.com/159209/54394296-b729ef80-4669-11e9-99dd-ffe5c2facc1a.png)

**Comment by ramya-rao-a** [comment] 2019-03-18 01:40
@ahmetb My suggestion to disable certain settings was not made as a solution to the problem, but only as a way to investigate and troubleshoot which feature is the root cause of the perf problems. 

Of course, I don't expect users to be aware of the inner workings of the extension and all its settings. On the other hand, I do hope that users who take the time to report an issue in an open source project are also kind enough to work with me in troubleshooting the problem.

I am concerned about the fact that the on save operations are very slow for you. Playing with the `buildOnSave`, `lintOnSave` and `vetOnSave` settings can give us an idea on which features are causing the perf issues. 

Regarding both code navigation and code completion, we are completely reliant on the tools that power these features. So unfortunately, there isn't much we can fix from the extension's side.

I have updated our wiki regarding [slowness with auto completion and code navigation when using modules](https://github.com/Microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code#why-is-code-navigation-and-code-completion-slow-when-using-go-modules). It has pointers on how to use the language server from Google. We will be updating our extension to use this language server by default in a few weeks. Please give it a read.

**Comment by ramya-rao-a** [comment] 2019-04-05 04:16
Hello everyone,
Thanks for your patience.

Please install the [latest beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.7) of this extension.
I'll be releasing the same in the next update to the extension early next week. https://github.com/Microsoft/vscode-go/issues/2410 is the test plan for the next update if anyone is interested.

The beta version will prompt you to use `gopls`, the language server from Google if it detects that you are using Go modules. Please install and use the language server. It performs much better especially for auto-completions.

This was the long term plan for module support. Therefore, closing this issue.

If you find any other performance issue while using `gopls`, please log new issues.

Thanks again and Happy Coding!

**Closed by ramya-rao-a** 2019-04-05 04:16 UTC

**Comment by tj** [comment] 2019-04-05 18:41
wow it seems muuuuch faster, thanks!

**Comment by tj** [comment] 2019-04-05 18:52
ah silly me, that's because you can't just write statements at the package level, that's invalid Go :D haha, interesting that it behaves this way though, seems like a problem with gopls I'll report there

**Comment by didil** [comment] 2019-04-06 09:05
it's much faster indeed but unimported packages auto-complete seems to be broken with gopls

**Comment by tusharsingh** [comment] 2019-04-06 12:33
@didil did auto-indenting/formatting also break?

**Comment by didil** [comment] 2019-04-06 14:43
@tusharsingh sometimes after an error it would break and I'd have to reload vscode. But I reverted to not using go modules for now

**Comment by stamblerre** [comment] 2019-04-07 00:03
gopls doesn't support auto-completing imported packages yet. And gofmt/goimports should continue to work, as long as you have these settings:

```
"editor.formatOnSave": true,
"editor.codeActionsOnSave": {
    "source.organizeImports": true
},
```

**Comment by stamblerre** [comment] 2019-04-07 00:12
Also, https://github.com/Microsoft/vscode-go/issues/2419#issuecomment-480531811 is likely relevant for the autocompletion of unimported packages.

**Comment by ramya-rao-a** [comment] 2019-04-07 00:56
@tj and @didil Please add a comment in #2419 with the cases where completion of unimported packages aren't working as expected. Also, mention if you are using Go modules or not

**Comment by tj** [comment] 2019-04-07 10:45
@stamblerre hmm no luck for me, I have to run "Go: Add Import" and add them that way, I've been using `"go.formatTool": "goreturns"`

**Comment by NickDubelman** [comment] 2019-04-11 23:02
When I have buildOnSave = package and vetOnSave = package, it's taking about 3 seconds to detect some trivial syntax error in main.go. But when I turn off vetOnSave, it goes down to about a second.

This is consistent in the mainline version and the current beta version (Go-0.9.3-beta.7).

**Comment by ramya-rao-a** [comment] 2019-04-12 01:21
@NickDubelman the buildOnSave and vetOnSave features don't use the language server by default and therefore will no change.  You can opt in to use them from the language server by setting `diagnostics` to `true` in the `go.languageServerExperimentalFeatures` setting
