### ISSUE TITLE
golang.org/x/tools/gopls version need to update

### ISSUE THREAD

**Issue by AlphaWong** [microsoft/vscode-go#2886] opened 2019-11-05 10:45 UTC
The golang package version has been updated

```console
/home/alpha/works/pkg/mod/golang.org/x/tools/gopls@v0.1.7/main.go:20:41: not enough arguments in call to cmd.New
	have (string, string, nil)
	want (string, string, []string, func(*source.Options))
```

# original (v0.1.7)
```go
// https://github.com/golang/tools/blob/gopls/v0.1.7/gopls/main.go#L20
tool.Main(context.Background(), cmd.New("gopls", "", nil), os.Args[1:])
```

# latest
```go
// https://github.com/golang/tools/blob/master/gopls/main.go#L22
tool.Main(ctx, cmd.New("gopls", "", nil, hooks.Options), os.Args[1:])
```

# Library
## original (v0.1.7)
```go
https://github.com/golang/tools/blob/gopls/v0.1.7/internal/lsp/cmd/cmd.go#L71
func New(name, wd string, env []string) *Application {
	if wd == "" {
		wd, _ = os.Getwd()
	}
	app := &Application{
		cache:   cache.New(),
		name:    name,
		wd:      wd,
		env:     env,
		OCAgent: "off", //TODO: Remove this line to default the exporter to on
	}
	return app
}
```

## latest
```go
// https://github.com/golang/tools/blob/master/internal/lsp/cmd/cmd.go#L75
// latest
func New(name, wd string, env []string, options func(*source.Options)) *Application {
	if wd == "" {
		wd, _ = os.Getwd()
	}
	app := &Application{
		cache:   cache.New(options),
		name:    name,
		wd:      wd,
		env:     env,
		OCAgent: "off", //TODO: Remove this line to default the exporter to on
	}
	return app
}
```

**Comment by AlphaWong** [comment] 2019-11-05 10:57
this line should have a problem as the `0.1.7` and latest branch have breaking change
```ts
// https://github.com/microsoft/vscode-go/blob/e936903d648caa40f4bbc7a6d0e28aeb59aedd43/src/goLanguageServer.ts#L402
const defaultLatestVersion = semver.coerce('0.1.7');
const defaultLatestVersionTime = moment('2019-09-18', 'YYYY-MM-DD');
async function shouldUpdateLanguageServer(tool: Tool, path: string, makeProxyCall: boolean): Promise<boolean> {
	// Only support updating gopls for now.
	if (tool.name !== 'gopls') {
		return false;
	}

	// First, run the "gopls version" command and parse its results.
	// If "gopls" is so old that it doesn't have the "gopls version" command,
	// or its version doesn't match our expectations, prompt the user to download.
	const usersVersion = await goplsVersion(path);
	if (!usersVersion) {
		return true;
	}

	// We might have a developer version. Don't make the user update.
	if (usersVersion === '(devel)') {
		return false;
	}

	// Get the latest gopls version.
	let latestVersion = makeProxyCall ? await latestGopls(tool) : defaultLatestVersion;
```
```

**Comment by AlphaWong** [comment] 2019-11-05 11:09
# workaround 
```console
# install gopls separately
go get golang.org/x/tools/gopls@v0.1.7
```

**Comment by stamblerre** [comment] 2019-11-05 17:27
@ramya-rao-a: I believe that https://github.com/microsoft/vscode-go/pull/2877 will fix this issue. The problem is that if multiple packages installed depend on different versions of x/tools, the temporary `go.mod` file that is used to support Go 1.11 may cause conflicts. This shouldn't be much of a problem since `gopls` will be auto-updated, but it will be an issue for people installing multiple tools at once. Sorry I didn't notice this earlier, I thought the PR had already been merged.

**Comment by ramya-rao-a** [comment] 2019-11-06 01:49
0.11.9 has been published with the fix by @stamblerre in #2877

**Comment by ramya-rao-a** [comment] 2019-11-06 01:50
@AlphaWong Can you share if the fix in the latest version helps?

**Comment by AlphaWong** [comment] 2019-11-06 03:01
I check my vscode and find that my current version is 0.11.8
let me upgrade it and check it again

**Comment by AlphaWong** [comment] 2019-11-06 03:05
@ramya-rao-a it works. Thx community!

**Closed** 2019-11-06 03:05 UTC
