### ISSUE TITLE
Stop debugging never lets go of ports

### ISSUE THREAD

**Issue by carc1n0gen** [Microsoft/vscode-go#511] opened 2016-10-05 14:50 UTC
Hello, I was trying this extension for debugging a simple web app that uses the Iris web framework.  For some reason when I stop debugging the process never lets of of the ports I bound the server to.

However if I run the binary myself and Ctr+c to kill it, the ports are let go correctly

**Comment by ramya-rao-a** [comment] 2016-10-28 23:24
Is there any sample repo where we can try to repro this?

**Comment by roblourens** [comment] 2016-10-31 17:07
I think this is the same as https://github.com/Microsoft/vscode-go/issues/438

**Comment by ramya-rao-a** [comment] 2017-01-27 19:19
Closing as duplicate of #438

**Closed by ramya-rao-a** 2017-01-27 19:19 UTC
Labels: debug
