### ISSUE TITLE
auto completion and type hint for build-in package not working 

### ISSUE THREAD

**Issue by gh0o0st** [Microsoft/vscode-go#1489] opened 2018-01-30 13:32 UTC
vscode version 1.19.3
host mac 10.13.3

auto completion and type hint for build-in package not working, downloaded package auto completion and type hint seems works fine.

I do not how this happened, it works fine a couple weeks ago, it just stopped working recently.

I try to reinstall vscode or the extension, this keeps getting back.

code auto complete for other language seems work fine. definitely of issue related the this extension 

Does someone know this issue? Or what else should I provide?

sorry for my english, I hope I explained myself.

**Comment by gh0o0st** [comment] 2018-01-30 13:36
go env output
```
GOARCH="amd64"
GOBIN="/Users/simonding/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/simonding/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qt/hb0yfwvj5gd52hzhcg4mj3j80000gn/T/go-build692757637=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by ramya-rao-a** [comment] 2018-02-01 03:09
Are you referring to the information shown on hover when you say "type hint"?

For completion try the below
- In a terminal, run ` gocode close` and then `gocode -s -debug`. This will run the gocode server in debug mode
- Now try completion in vscode
- For every new word you type, you should be able to see the result from gocode in the terminal. If you dont see completions from std lib here, then log an issue in the `gocode` repo

**Comment by alexwall** [comment] 2018-02-04 18:14
Same here, 

Hover and jump to definition stopped to work. But dependency resolution and syntax check seems to work. 
This happened several times in the past. 
I can't reproduce it right now, because after running `go:install and update` it works again. 

My guess is the that the experimental `Go Language Server` stop working for some reasons.

**Comment by ramya-rao-a** [comment] 2018-02-05 03:05
Thanks @alexwall 
@gh0o0st Were you using the language server as well?

**Comment by gh0o0st** [comment] 2018-02-05 04:59
no. just regular use.

2018-02-05 11:05 GMT+08:00 Ramya Rao <notifications@github.com>:

**Comment by gh0o0st** [comment] 2018-02-05 05:01
I have solved this problem, by updating all the third party package. now everything works fine.

**Comment by alexwall** [comment] 2018-02-05 05:31
@Gh0o0st What do you mean with `all third party packages`?

Update command?

**Comment by gh0o0st** [comment] 2018-02-05 05:44
go get -u all

all the downloaded package, gocode, godoc, etc

2018-02-05 13:31 GMT+08:00 alexwall <notifications@github.com>:

**Comment by ymm1x** [comment] 2018-02-08 17:50
I had the same problem.
In my case, It was caused by the environment variable GOROOT being invisible from the extension.
Try add `export GOROOT=/usr/local/Cellar/go/1.9.3/libexec` to your shell's bootstrap file (~/.bashrc or etc)

**Comment by ramya-rao-a** [comment] 2018-02-09 01:03
Looks like everyone here has figured out the problem to be either an environment issue or a tool needing update. Closing.

**Closed by ramya-rao-a** 2018-02-09 01:03 UTC
Labels: needs more info
