### ISSUE TITLE
Add settings to expose configuration for CodeLens with go modules

### ISSUE THREAD

**Issue by timfallmk** [microsoft/vscode-go#3089] opened 2020-03-05 03:30 UTC
**Is your feature request related to a problem? Please describe.**
When opening a `go.mod` file, CodeLens will add lines above "outdated" dependencies. Clicking on _one_ line will upgrade all dependencies, changing `go.mod` and `go.sum`.
![image](https://user-images.githubusercontent.com/5316117/75945099-276aeb80-5e4e-11ea-9892-34bc410089c9.png)

**Describe the solution you'd like**
Add a settings option to access the flags exposed for this function. Flags were added here https://github.com/golang/tools/commit/98b3097d01357396050840fabde3c2842d04d966

**Describe alternatives you've considered**
Not opening `go.mod`, for fear of it changing unexpectedly

**Additional context**
This seems similar to the bug where running `go build` in the background would update `go.mod` without a user's knowledge. It would be nice to be able to turn this behavior on/off.

**Comment by hyangah** [comment] 2020-03-05 15:39
cc @ridersofrohan

**Comment by stamblerre** [comment] 2020-03-05 18:05
What version of Go are you using? This is a bug - upgrading one of the dependencies shouldn't upgrade all of them.

**Comment by timfallmk** [comment] 2020-03-05 18:44
Version info:
```1.43.0-insider
3943d614597f9f7c384846613d417e97ea6d5ab4
x66
```

My assumption was a build-related command was being run (or `go get` without a specific package)

**Comment by stamblerre** [comment] 2020-03-05 18:52
And to confirm, this is with `gopls/v0.3.3` (`gopls version`)? Depending on your VS Code settings, this might be possible, but the upgrade button itself should only upgrade one dependency. If you could share your `gopls` logs when this happens, that would be very helpful. Details on how to capture them [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).

**Comment by timfallmk** [comment] 2020-03-05 18:57
Correct
```
golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=
```
I didn't see anything pop out at me from `gopls` the last time I saw it, but I will see if I can repro. The thrust of the request was also about exposing knobs and options too, but it's good to see that behavior is a bug.

**Comment by stamblerre** [comment] 2020-03-05 19:09
What configuration specifically could we expose here? I'm not sure that there any configurable knobs here. Please do attach logs the next time you see this issue and we'll take a look. I was suspicious that https://go-review.googlesource.com/c/tools/+/221108 made it into `gopls/v0.3.3`, but it seems it did not, so this is a genuine bug.

**Comment by ridersofrohan** [comment] 2020-03-05 20:35
I was not able to reproduce this in `go 1.14` or `go 1.13` using gopls `v0.3.3` or on `master`. When I click on a single `Upgrade dependency`, it only updates that single dependency, `go get -u <module>` might add some more indirect dependencies but it does not upgrade all the dependencies. Please let me know if you can reproduce this.

Also, you mentioned as an alternative: "Not opening go.mod, for fear of it changing unexpectedly", has your go.mod file been changing unexpectedly or only when you clicked on the upgrade dependency?

**Comment by timfallmk** [comment] 2020-03-05 20:55
I'm not able to reproduce this exact behavior with a similar config locally. I'll try once more on the WSL remote I where I first encountered it, but it may have been a transient ghost.

If so, sorry for wasting everyone's time 😕.

It would still be a nice to have to be able to toggle this little bit of codelens helpfulness on and off.

**Comment by stamblerre** [comment] 2020-03-05 21:50
No worries! Thanks for reporting the issue. I'll close this for the time being, but please reopen if you're able to reproduce it. We may consider allowing users to toggle this if people find problems with it, but I'd prefer not to do that right away.

**Closed by stamblerre** 2020-03-05 21:50 UTC
Labels: needs more info, upstream-gopls
