### ISSUE TITLE
Breakpoints being deleted/moved on file save

### ISSUE THREAD

**Issue by kkotowick** [microsoft/vscode-go#3180] opened 2020-04-15 19:27 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go

> go1.14 windows/amd64

- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders

> 1.44.0
> 2aae1f26c72891c399f860409176fe435a154b13
> x64

- Check your installed extensions to get the version of the VS Code Go extension 

> 0.13.1

- Run `go env GOOS GOARCH` to get the operating system and processor architecture details

> windows
> amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

```
{
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "diagnostics": true,
        "documentLink": true
    },
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
        // Optional: Disable snippets, as they conflict with completion ranking.
        "editor.snippetSuggestions": "none",
    },
    "[go.mod]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
    }
}
```

### Describe the bug
When saving a .go file, all breakpoints are removed from the file.

### Steps to reproduce the behavior:
1. Edit a .go file
2. Set breakpoints on any two lines other than the first line
3. Save the file
4. Notice that the breakpoints you set have disappeared, and there is now a single breakpoint on the first line.

### Screenshots or recordings

![Breakpoint](https://user-images.githubusercontent.com/5480106/79379877-964b6200-7f2d-11ea-9f40-6ad47682dcc8.gif)

**Comment by kkotowick** [comment] 2020-04-15 19:33
After some further testing, I've found that if I set:
```
"[go]": {
        "editor.formatOnSave": false,
}
```
Instead of `true`, this issue does not occur.

**Comment by hyangah** [comment] 2020-04-15 20:51
Strangely I couldn't reproduce the problem. I copied the settings. Checked vscode/extension/go versions. The only difference I see is I am using mac, not windows. Puzzled.

![dbg](https://user-images.githubusercontent.com/4999471/79387176-33f85e80-7f39-11ea-9008-1a1cca725a0f.gif)

**Comment by hyangah** [comment] 2020-04-16 01:17
@kkotowick can you also share the list of active extensions?

**Comment by lggomezml** [comment] 2020-04-19 23:28
I´m now sure this is related to the debug feature, as it seems to be something related to the workbench events and actions rather than anything from the debug adapter side (AFAIK we can't even control that state programatically from that process, only via responses once a debug session is active)

**Comment by hyangah** [comment] 2020-04-20 22:04
@lggomezml That sounds like this is an issue to be reported to upstream (microsoft/vscode).

@kkotowick I cannot even reproduce this on my mac to file an issue myself. It may be possible that this is isolated to the windows UI. Can you please file an issue in the upstream repo? Thanks.

**Comment by dtsao** [comment] 2020-05-17 18:38
Same issue here. 
$ go version
go version go1.13.7 windows/amd64
$ code -v
1.45.0
d69a79b73808559a91206d73d7717ff5f798f23c
x64
go extension: 0.14.2
$ go env GOOS GOARCH
windows
amd64

@kkotowick's work around works for me https://github.com/microsoft/vscode-go/issues/3180#issuecomment-614238283

**Comment by stamblerre** [comment] 2020-06-04 21:03
I've just tried to reproduce this on my Windows machine, and I wasn't able to, even when the file has to be formatted and changed. It does sound like an upstream VS Code issue, so I'm going to go ahead and close this and suggest filing an issue in https://github.com/microsoft/vscode. Some other things to check might be the `gopls` version (`gopls version`) to confirm that it is at the latest (`gopls/v0.4.1`), because there were some formatting bugs with `gopls` in earlier versions.

**Closed by stamblerre** 2020-06-04 21:03 UTC
Labels: debug, upstream
