### ISSUE TITLE
Small IntelliSense delay when using Go modules

### ISSUE THREAD

**Issue by mxxcx** [Microsoft/vscode-go#2217] opened 2018-12-27 22:12 UTC
I'm noticing a very small delay between typing and auto complete, of course not a big deal but I do find it a little annoying, I did a test between a ts file and go file

here is the go file  https://gyazo.com/f2658d3c4c2e57514b554cb05bed4a41
here is the tsx file  https://gyazo.com/7299d9e89040a6a308aedadcf1d30130

Maybe is just me, but I'm seeing a small milliseconds delay. I'm using go modules. 

Thanks

**Comment by ramya-rao-a** [comment] 2018-12-29 06:00
Thanks for reporting this @mxxcx 
Since you are using Go modules, I am moving this issue to https://github.com/stamblerre/gocode
@stamblerre can help figuring out what is going on.

**Comment by ramya-rao-a** [comment] 2018-12-29 06:01
Also, just to be sure that you are using the latest `gocode` for Go modules, please run the command `Go: Install/Update Tools`, select `gocode-gomod`, press `Ok` to update it and try again

**Comment by mxxcx** [comment] 2018-12-29 10:52
@ramya-rao-a I just updated, although I do update the tools regularly, and the delay is still there. Thanks

https://gyazo.com/c74cb48d0aaa0af2c8dd4fa11b30ecab

**Comment by ramya-rao-a** [comment] 2018-12-31 01:11
@mxxcx The auto-completion in module mode is known to be slower than in the non-module mode. @stamblerre and her team are working on improving performance in this area.

@stamblerre Is there anything @mxxcx can share to see if the slowness being seen is what we are already aware about or if it is being caused by something else?

**Comment by stamblerre** [comment] 2019-01-02 18:53
@mxxcx: is your Go project very large?

**Comment by mxxcx** [comment] 2019-01-02 19:02
@stamblerre decently large, over 14k lines of code.

**Comment by stamblerre** [comment] 2019-01-02 19:04
I expect the delay you are seeing is a result of the speed of `go/packages` on large codebases. This is something we're working on, but unfortunately it's not a specific result of gocode. Hopefully, we will have a fix for this soon, and I apologize for the latency issues.

**Closed** 2019-01-03 10:47 UTC
Labels: go-modules, upstream
