### ISSUE TITLE
Constant taskkill.exe prompts when coding

### ISSUE THREAD

**Issue by raymondjolly** [microsoft/vscode-go#2407] opened 2019-04-02 12:49 UTC
With the latest version of vscode-go, there are constant taskkill.exe prompts while trying to write go code. This behavior specifically occurs while typing and when intellisense is working. The only way for me to use Go with VS Code is for me to install an older version of vscode-go such as 0.6.90 which is 6 months old. Please note that I do not experience this issue with any other language or lint package. I have tried capturing an image of the taskkill.exe prompt but it disappears when trying to do so.

Here are my current settings:

`{
    "explorer.confirmDelete": false,
    "window.zoomLevel": 0,
    "explorer.confirmDragAndDrop": false,
    "git.enabled": true,
    "workbench.colorTheme": "Solarized Dark",
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "todo-tree.defaultHighlight": {
        "foreground": "green",
        "type": "none"
    },
    "todo-tree.customHighlight": {
        "TODO": {},
        "FIXME": {}
    },
    "team.showWelcomeMessage": false
}`

**Comment by ramya-rao-a** [comment] 2019-04-03 05:30
Thanks for reporting @raymondjolly, that's unfortunate indeed.

I haven't seen any such prompts and the extension doesn't have any code that would explicitly  show any such prompt.

- Is this prompt coming from VS Code or externally?
- Is there a specific task you are asked to kill?
- Can you disable all other extensions, and see if that makes any difference?
- A screenshot would really help. Next time this happens, press the `PrtSc` button, then open Mspaint and press Ctrl+V to paste the image.

**Comment by raymondjolly** [comment] 2019-04-04 14:09
Hi, Ramya,
Thank you for the quick response.  I believe that the taskkill.exe prompts are coming from outside of VS Code but the vscode-go addon is indeed the cause.  I was able to capture some of the prompts by clicking on a window while type in sample functions like fmt.Println the images are as follows:

![goError1](https://user-images.githubusercontent.com/15862473/55562123-59655200-56c1-11e9-811f-ec6b9f2b50f5.png)
![goError2](https://user-images.githubusercontent.com/15862473/55562144-6124f680-56c1-11e9-8f87-804761612b0c.png)
![goError3](https://user-images.githubusercontent.com/15862473/55562164-67b36e00-56c1-11e9-8f1e-bcae61efa708.png)
![goError4](https://user-images.githubusercontent.com/15862473/55562174-6d10b880-56c1-11e9-8372-13ae27313118.png)

The PID codes are very random but all come from C:\Windows\System32\taskkill.exe

As I said before, if I roll back to an earlier version of this extension, I do not have this problem.

**Comment by raymondjolly** [comment] 2019-05-30 12:22
I provided additional information to this issue more than a month ago. Has there been any progress?

**Comment by ramya-rao-a** [comment] 2019-05-30 16:50
My apologies @raymondjolly, I have been pressed for time and didnt get a chance to dig deeper here. This is especially difficult because I cant replicate the problem on my Windows machine.

Most of the features of this extension are backed by external Go tools. The extensions spawns a child process to run each such tool. My guess is that the problem you are seeing is related to such processes being spawned.

The only way forward that I can think of is for you to have a local developer environment of the vscode-go extension set up and for me to guide you in narrowing down on what the root cause might be. 

If you are up for this, then please follow the below steps

- [Set up local dev env for vscode-go](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- In `goMain.ts` file, the `activate` function is the one where all the features get registered. You can disable them one by one, or disable all and then enable them one by one to see which feature might be causing the problem
- All registrations start at https://github.com/microsoft/vscode-go/blob/0.10.2/src/goMain.ts#L284. From that line onwards any time you see `ctx.subscriptions.push()`, a new feature is getting registered

**Comment by ramya-rao-a** [comment] 2019-07-07 00:22
Hello @raymondjolly,

I finally got some time to look deeper into this issue and have found what exactly causes calls to taskkill.exe. This extension relies on a lot of external Go tools to provide various language features. We spawn child processes to run each such tool, collect the results and give it back to VS Code. When VS Code cancels such ongoing requests, we call a function called [killTree](https://github.com/microsoft/vscode-go/blob/0.11.2/src/util.ts#L809) in order to kill the child process and all its children.

With your statement about the 0.6.90 version working fine and the hint about auto-completion, I was able to narrow down the exact child process that is getting killed by this approach. It is the new feature of having documentation show up in the auto-completion window/box.

Now, I am still not sure why it would result in taskkill.exe showing up as prompts, it should just silently run in the background, so I can't confirm this hypothesis. But, you can help :)

To confirm that this is really the case, can you please try the below?
- Use the latest version of the Go extension (0.11.2)
- Add the below to your settings. The first 3 are the flags that are set by default. For your case, we add the 4th `-exclude-docs` to disable the new feature I described above
```
"go.gocodeFlags": [
    "-builtin",
    "-ignore-case",
    "-unimported-packages",
    "-exclude-docs"
  ]
```
- Write go code as usual. Auto-completion should work and you should no longer see the taskkill.exe prompts
- Now to confirm that the above was indeed the fix, remove the setting shared above, reload VS Code and start typing again. The prompts should re-appear

**Comment by raymondjolly** [comment] 2019-07-08 18:06
Hi, Ramya

Thank you for following up on this issue.  I have spent the last hour testing the solution and I do see a dramatic reduction in the number of taskkill.exe prompts.  It doesn't eliminate them completely but it does make it possible to develop using Go with VS Code on Windows.  I have also at your request changed the JSON object back to the default settings and this confirms that the flag settings to indeed help.  Thanks again.

**Comment by stamblerre** [comment] 2020-02-18 21:55
@raymondjolly: Thanks for following up. Can this issue be closed?

**Comment by raymondjolly** [comment] 2020-04-20 20:44
I wanted to provide an update to the team on this issue.  Since the new release of the vscode-go add on which uses the gopls library, I am no longer experiencing this issue to taskkill hell.  In fact, I am actually seeing new highlighting features which I could not see before.  I actually can say that Go with VS Code is actually usable again.

**Comment by raymondjolly** [comment] 2020-04-20 20:47
By the way, Rebecca I saw your gopls presentation on YouTube which led me to try VS Code again.  Thanks for providing the background on the challenge of having different editors on the market.  I think that you and your team are doing great work.

**Comment by stamblerre** [comment] 2020-04-20 21:17
Glad to hear VS Code is working well for you now, @raymondjolly! Thank you for the kind words 😊 

Looks like we're having new issues related to taskkill, which are being discussed on https://github.com/microsoft/vscode-go/issues/3178, so I'll close this issue now.

**Closed by stamblerre** 2020-04-20 21:17 UTC

**Comment by ramya-rao-a** [comment] 2020-04-25 05:54
@raymondjolly Thanks for the follow up!

In the latest release of the extension we moved away from using taskkill.exe directly to using the [tree-kill](https://www.npmjs.com/package/tree-kill) package in order to kill older processes. That explains why you don't see the taskkill.exe prompts anymore.
