### ISSUE TITLE
ms-vscode.go extension causing high CPU

### ISSUE THREAD

**Issue by kiyapedia** [microsoft/vscode-go#2956] opened 2019-12-22 15:01 UTC
Please direct general questions to:
- [Gitter](https://gitter.im/Microsoft/vscode-go)
- [Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [Wiki](https://github.com/microsoft/vscode-go/wiki) before filing an issue.
Helpful pages include:
- [GOPATH](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)
- [Module Support](https://github.com/microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code)
- [Debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code)
	- Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- <go version go1.13.4 darwin/amd64>
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- <1.41.0>
- Check your installed extensions to get the version of the VS Code Go extension 
	- <0.11.9>
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- <darwin/amd64>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
1. Go to vscode and enable ms-vscode.go extension
2. start typing go code
3. CPU maxes 100%. Can view via Activity Monitor.
4. This is on a MAC

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by kiyapedia** [comment] 2019-12-28 13:26
My machine becomes impossible to use with this extension. Here is a screenshot of Activity Monitor.

<img width="798" alt="Screen Shot 2019-12-28 at 7 24 53 AM" src="https://user-images.githubusercontent.com/19699368/71544301-3e1f2e80-2943-11ea-9b37-384bb1a3453c.png">

**Comment by ramya-rao-a** [comment] 2020-01-28 06:23
Please share any Go related settings you might have added or edited. You can get these by running the command `Preferences: Open Settings (JSON)`

Also run the command `Developer: Open Process Explorer` which can shed some light on which process is using high cpu

**Comment by estebanborai** [comment] 2020-01-30 20:33
Im using the extension and while writting an struct like this:
![image](https://user-images.githubusercontent.com/34756077/73487474-d74bc580-4385-11ea-9164-46c50f5e41a3.png)

The following processes are created and never ends:
![image](https://user-images.githubusercontent.com/34756077/73487542-fea29280-4385-11ea-8cfd-b7a7fda385c7.png)

If I keep on writting more processes for `doc` are created even with the same argument "Square" (for this case)

![Screen Shot 2020-01-30 at 17 31 23](https://user-images.githubusercontent.com/34756077/73487864-986a3f80-4386-11ea-9783-0430bcdb80ee.png)

The current state of the file is:
![image](https://user-images.githubusercontent.com/34756077/73487913-ae780000-4386-11ea-952c-b05b255fdad0.png)

**Comment by stamblerre** [comment] 2020-01-30 22:29
@estebanborai: Can you also share your VS Code settings as requested above?

**Comment by estebanborai** [comment] 2020-01-30 22:36
Hey @stamblerre, sorry I didn't shared my VSCode settings and thanks for your help!

```json
{
  "workbench.iconTheme": "material-icon-theme",
  "editor.tabSize": 2,
  "editor.fontLigatures": true,
  "editor.fontSize": 13,
  "editor.renderWhitespace": "all",
  "editor.fontWeight": "300",
  "editor.fontFamily": "'Courier New', monospace",
  "editor.tokenColorCustomizations": {
        "textMateRules": [{
          "scope": [
            "comment",
          //   "punctuation.definition.comment",
          //   "comment.block",
          //   "comment.line",
          //   "comment.block.documentation",
          //   "comment.line.double-slash",
          //   "entity.other.attribute-name",
          //   "entity.other.attribute-name.html",
          //   "markup.italic",
          //   "entity.other.attribute-name.id",
          //   "entity.other.attribute-name.class.css",
          //   "entity.other.attribute-name.tag.jade",
          //   "entity.other.attribute-name.class.jade",
          //   "entity.other.attribute-name.id.jade",
          //   "keyword.control",
          //   "storage",
          //   "emphasis",
          //   "variable.language"
          ],
          "settings": {
            "fontStyle": "italic"
          }
      }]
  },
  "debug.console.fontFamily": "'Courier New', monospace",
  "breadcrumbs.enabled": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
}
```

**Comment by stamblerre** [comment] 2020-01-30 22:38
Thanks for sharing! Looks like many `go doc` processes are being started and not exiting.
@ramya-rao-a: I recall seeing an issue related to process timeouts - seems like this is relevant here?

**Comment by stamblerre** [comment] 2020-02-14 05:46
Thanks for this report - I think that the root cause here is probably the same as a number of issues - too many subprocesses are getting started concurrently. I've filed https://github.com/microsoft/vscode-go/issues/3044 to track work on improving this behavior, so you can follow along with progress on that issue.

**Comment by stamblerre** [comment] 2020-02-14 05:46
Duplicate of #3044

**Comment by estebanborai** [comment] 2020-02-14 10:12
Nice!

Thanks for your help!

**Comment by ramya-rao-a** [comment] 2020-03-16 05:32
@estebanborai The `go doc` process is either trigged from the completion feature or the hover feature. Can you add `-exclude-docs` to the `go.gocodeFlags` settings to disable calling this from completion and then let us know if this solves the problem? This will help us narrow down which among the 2 features are resulting in this issue for you

```
"go.gocodeFlags": [
    "-builtin",
    "-ignore-case",
    "-unimported-packages",
    "-exclude-docs"
  ]
```

Re-opening to allow for the above discussion

**Closed** 2020-03-23 05:36 UTC
Labels: needs more info
