### ISSUE TITLE
High CPU report while working with go code

### ISSUE THREAD

**Issue by jjaimon** [microsoft/vscode-go#2687] opened 2019-08-07 10:21 UTC
Issue Type: <b>Bug</b>

I started seeing multiple godef process running while working with go code.  go version `go1.12.7 darwin/amd64`.  Its easily reproducible by just scrolling the code in the editor.  For eg.
```
ps -ef |grep godef|wc                                                                                                       
      93
```
Given below is part of process list 
```
xxx 98366 90870   0  3:41PM ??         0:00.06 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 1153
  xxx 98367 90870   0  3:41PM ??         0:00.08 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 1178
  xxx 98368 90870   0  3:41PM ??         0:00.06 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 1194
  xxx 98369 90870   0  3:41PM ??         0:00.09 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 1277
  xxx 98370 90870   0  3:41PM ??         0:00.06 (godef)
  xxx 98371 90870   0  3:41PM ??         0:00.05 (godef)
  xxx 98372 90870   0  3:41PM ??         0:00.06 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 1377
  xxx 98373 90870   0  3:41PM ??         0:00.10 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 1440
  xxx 98374 90870   0  3:41PM ??         0:00.04 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 1524
  xxx 98375 90870   0  3:41PM ??         0:00.08 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 1608
  xxx 98378 90870   0  3:41PM ??         0:00.07 (godef)
  xxx 98379 90870   0  3:41PM ??         0:00.07 (godef)
  xxx 98380 90870   0  3:41PM ??         0:00.04 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 2012
  xxx 98381 90870   0  3:41PM ??         0:00.11 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 2037
  xxx 98382 90870   0  3:41PM ??         0:00.07 (godef)
  xxx 98383 90870   0  3:41PM ??         0:00.06 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 2127
  xxx 98384 90870   0  3:41PM ??         0:00.04 /Users/someuser/go/bin/godef -t -i -f /Users/someuser/prov/myfile.go -o 2151
  xxx 98385 90870   0  3:41PM ??         0:00.02 (godef)
```
Extension version: 0.11.4
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 5|
|Memory (System)|16.00GB (0.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aykevl** [comment] 2019-08-11 10:55
I also had a case of very high CPU usage by VS Code. I haven't reproduced it yet, but can share this screenshot which shows something is going horribly wrong (perhaps others have a clue):

![Screenshot at 2019-08-11 12-47-44](https://user-images.githubusercontent.com/729697/62832943-fff4cd00-bc36-11e9-833f-939c99ac30af.png)

This continued for a minute or so at which point it seems to have finished processing.

**Comment by aykevl** [comment] 2019-08-12 18:34
Something very similar happened again, twice.

The first time I managed to get a screenshot of htop:

![Screenshot at 2019-08-12 19-39-03](https://user-images.githubusercontent.com/729697/62888415-7ed52d00-bd3f-11e9-8473-b6c957d4f2f0.png)

Interestingly there are lots of `go list` processes for the same package, so most of those are redundant. I'm not sure why this extension invokes `go list` so often.

The second time I saw lots of `compile` processes (from the Go toolchain). There were over 20 of those.

---

If there is any way I can help (by giving more information, for example), I'd like to, because this issue is the main reason why I might switch back to vim.

**Comment by aykevl** [comment] 2019-08-16 17:45
So far, switching to `gopls` appears to solve these issues. I will report back if it doesn't.

**Comment by jjaimon** [comment] 2019-08-16 18:01
Thanks for the suggestion.  I'll try this and report back.

**Comment by jjaimon** [comment] 2019-08-18 18:05
Switching to `gopls`  appears to solve the issue for me too.

**Comment by maxannear** [comment] 2019-09-02 21:50
Experiencing the exact same issue. Switching to `gopls` did not fix it for me unfortunately. Its making my computer unusable when I have VS code open to a Go project. 

I've given up and downloaded the trial of GoLand 😢

**Comment by stamblerre** [comment] 2019-09-03 00:13
@maxannear: Can you confirm that `gopls` was actually running by opening "View: Debug Console" -> Output -> Tasks and then checking that `gopls` is one of the tasks listed? If you are still having CPU issues with `gopls`, please file an issue on the [Go issue tracker](https://github.com/golang/go/issues/new), and I'd be happy to debug with you.

**Comment by maxannear** [comment] 2019-09-03 02:27
Hi @stamblerre thanks for following up.

I can confirm that `gopls` is running as a task in "View: Debug Console" -> Output -> Tasks.

My VS Code process explorer looks as follows. Sorry I'm not too familiar with exactly how all these tools work together so am unsure what exactly is causing the issue. Is it a problem in the `vscode-go`, `gopls` or `go list`?. The excessive CPU used by `go list` was happening when I wasn't using `gopls`. Often the CPU can be that high when I'm not typing in VS Code
![Screen Shot 2019-09-03 at 12 55 08 PM](https://user-images.githubusercontent.com/3599054/64139822-56c87d80-ce56-11e9-8f63-89b36952917a.png)

**Comment by stamblerre** [comment] 2019-09-03 20:36
From what I can tell, those particular calls to `go list` do not look like the ones that `gopls` makes, and if that's the case, then I would imagine they are being made directly by the extension. @ramya-rao-a: Is there a feature of the extension that uses `go list`?

**Comment by ramya-rao-a** [comment] 2019-09-25 02:59
@maxannear My apologies, this issue got lost in my sea of notifications

The screenshot shows both `gopls` and `go list` calls. So, this is when the language server is enabled.

Though the extension does call `go list` for a couple of different features, none of the calls follow the pattern of `go list -json packagename`.

The only time the extension runs `go list -json` is when the `Go to Implementation` or the `Peek Implementation` commands are run. In this case it actually runs `go list -e -json` and no import path is passed. 
@stamblerre, does `go list` without package path passed internally run `go list` on the individual packages? That can explain the above, but only if @maxannear has been running the `Implementation` related commands

@maxannear, 
- Can you get on to the latest version of the extension, follow prompts if any regarding updating `gopls` and try again?
- Also share if you have any other Go related extension installed
- If there are any Go related settings you have added/updated, please share that as well. You can get them by running the command `Preferences: Open Settings (JSON)`

**Comment by ermissa** [comment] 2019-10-01 23:08
I am facing same issue with @maxannear. Because of the gomodule incompatibility of other tools I switched to `gopls` but it is causing high CPU. It's even hard to type most of times. My go settings,

{
    "go.formatTool": "goimports",
    "go.useLanguageServer": true
}

**Comment by stamblerre** [comment] 2019-10-03 22:12
@ermissa: Do you mind filing a separate issue on the [Go issue tracker](https://github.com/golang/go/issues/new)? Please include the information found in the [troubleshooting guide](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md).

**Comment by bxcodec** [comment] 2019-10-15 08:30
I don't know where to report. But this happens to me, and it shows the gopls that causing the high CPU 

<img width="1440" alt="Screen Shot 2019-10-15 at 15 27 43" src="https://user-images.githubusercontent.com/11002383/66814306-95c31600-ef60-11e9-82e7-fb97cb219cce.png">

And this happens always when I open the VS Code

**Comment by stamblerre** [comment] 2019-10-15 15:32
@bxcodec: What version of `gopls` are you using (`gopls` version`)?

**Comment by stamblerre** [comment] 2020-02-12 17:39
Looks like this issue hasn't had much activity for a few months. I'm going to close it, but please open a new issue if you encounter these problems again.

**Closed by stamblerre** 2020-02-12 17:39 UTC
Labels: needs more info
