### ISSUE TITLE
non-sensical errors shown on Go file

### ISSUE THREAD

**Issue by aybabtme** [microsoft/vscode-go#3212] opened 2020-04-29 03:51 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.14.2 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
```
1.44.2
ff915844119ce9485abfe8aa9076ec76b5300ddd
x64
```
- Check your installed extensions to get the version of the VS Code Go extension 
	- `0.14.1`
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- `darwin
amd64`

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

```
{
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "[go]": {},
}
```

### Describe the bug

When editing the following Go file:
```go
package feature

import (
	"context"
	"testing"

	"github.com/hashicorp/consul/sdk/testutil"
	"github.com/stretchr/testify/require"
)

func TestKV(t *testing.T) {
	ctx := context.Background()

	kv := &KV{
		name: "test",
		Cfg:  &RunCfg{},
	}
	vars := &RunVars{}

	sconsul, err := testutil.NewTestServerT(t)
	require.NoError(t, err)
	require.NotNil(t, sconsul)
	err = kv.Run(ctx, vars)
	require.NoError(t, err)
}
```

A red line underscores the `testutil` string with error `expected identifier on left side of :=`. Package `testutil` is something that I just `go get` and added to my vendored modules.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/1189716/80559007-20191780-8991-11ea-9502-7937aa9f40a2.png">
This file is valid and no error is emitted when providing it to Go via the CLI.

At the same time, another error in another file seems to be working against an old signature of this method:

```
errc <- load.Run(ctx, runVars)
```

Where it complains that `runVars` is of the wrong type (type `*feature.RunVars` but expects `*feature.RunCfg`). This method _used_ to take a `*feature.RunCfg` as 2nd argument, but I refactored it away. It seems that something in the tooling isn't aware of this.

<img width="716" alt="image" src="https://user-images.githubusercontent.com/1189716/80559141-7be3a080-8991-11ea-95f1-561f117d2d78.png">

However, when hovering over the signature of `load.Run`, it says that the argument should indeed be of type `*feature.RunVars`.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/1189716/80559125-70907500-8991-11ea-9436-7ec169f3f2f3.png">

### Steps to reproduce the behavior:
I have no idea how to reproduce this, but I've been seeing this kind of behavior randomly show up while I'm working, ever since Go modules became a thing.

**Comment by stamblerre** [comment] 2020-04-29 04:01
Thanks for the report and detailed images! Can you confirm that your `gopls` version is `v0.4.0` (`gopls version`)? Can you try to capture your `gopls` logs when you see this happen next? (See details [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs). Finally, are you seeing this happen in a public repository or a private one? If it's public, can you point me to it so I can try reproducing myself?

**Comment by aybabtme** [comment] 2020-04-29 04:18
Hi @stamblerre, it's a private repository.

```bash
$ gopls version
golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=
```

I'll try to get logs next time this happens. For now, I restarted `gopls` and the issue went away.

**Comment by stamblerre** [comment] 2020-05-14 02:02
I'm going to close this issue since it's not currently actionable. @aybabtme, please file a new issue on the golang/go repository if you encounter this again: https://github.com/golang/go/issues/new. Thanks!

**Closed by stamblerre** 2020-05-14 02:02 UTC
Labels: needs more info, upstream-gopls
