### ISSUE TITLE
"Failed to eval expression" when unmarshalling nested struct with json tags

### ISSUE THREAD

**Issue by Kezzo** [microsoft/vscode-go#2968] opened 2020-01-04 12:08 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.5 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- Version: 1.41.1 Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Check your installed extensions to get the version of the VS Code Go extension 
	- Version: 0.12.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- darwin amd64

### Describe the bug

1. Unmarshalling a nested struct like the following:
```
type GithubResponse struct {
	Data struct {
		RateLimit struct {
			Cost      int `json:"cost"`
			Limit     int `json:"limit"`
			Remaining int `json:"remaining"`
		} `json:"rateLimit"`
	} `json:"data"`
}
```

2. Use this json as input:
`{"data":{"rateLimit":{"cost":1,"limit":5000,"remaining":4997}}}`

3. Observe that the following error message is shown and the struct data can't be inspected in the debug variables window:
```
Failed to eval expression:  {
 "Expr": "*(*\"struct { Cost int \"json:\\\"cost\\\"\"; Limit int \"json:\\\"limit\\\"\"; Remaining int \"json:\\\"remaining\\\"\" }\")(824635023936)",
 "Scope": {
  "goroutineID": -1,
  "frame": 0
 },
 "Cfg": {
  "followPointers": true,
  "maxVariableRecurse": 1,
  "maxStringLen": 64,
  "maxArrayValues": 64,
  "maxStructFields": -1
 }
} 

Eval error: 1:24: expected ')', found json (and 1 more errors)
```

The json data is correctly unmarshalled from go though. This can be tested by logging the created struct. The result will look like this:
`{{{1 5000 4997}}}`

**Comment by ramya-rao-a** [comment] 2020-01-15 07:22
Thanks for reporting @Kezzo 

@jhendrixMSFT Can you take a look at this?

**Comment by jhendrixMSFT** [comment] 2020-01-17 22:48
This is an issue in dlv, see https://github.com/go-delve/delve/issues/1768.  From the details I believe we can work around it by adding some escape characters.

**Comment by hairyhenderson** [comment] 2020-02-18 00:50
@jhendrixMSFT https://github.com/go-delve/delve/issues/1528 implies that this a `vscode-go` bug, not a `delve` bug.

And in https://github.com/go-delve/delve/issues/1768#issuecomment-570916476 the implication seems to be that `vscode-go` is the only tool where the issue is seen (`dlv --headless` and `goland` both work correctly).

Is it possible to take another look at this?

**Comment by Aisuko** [comment] 2020-04-13 09:38
Hi, guys. I hit the same issue(similar). There my situation use use `helm client-go api` install charts. Always work with `type xxx map[string]interafce{}`. And I always get the issue `Failed to eval expression`

```
➜  cattle git:(dev) go version
go version go1.14.1 darwin/amd64
➜  cattle git:(dev) code -v
1.44.0
2aae1f26c72891c399f860409176fe435a154b13
x64
➜  cattle git:(dev) code-insiders -v
zsh: command not found: code-insiders
➜  cattle git:(dev) go env GOOS GOARCH
darwin
amd64
➜  cattle git:(dev) 
```



![Screen Shot 2020-04-13 at 5 34 53 PM](https://user-images.githubusercontent.com/8053949/79110485-18604d00-7dad-11ea-86ef-10a1f36fef20.png)

**Comment by lggomez** [comment] 2020-04-20 23:46
I can`t reproduce the first issue:

<img width="1151" alt="Screen Shot 2020-04-20 at 20 25 30" src="https://user-images.githubusercontent.com/6326271/79808811-49a8c200-8345-11ea-99d4-605939b05782.png">

The second is a separate issue on our side, we're not sending the correct expression to delve:

<img width="1097" alt="Screen Shot 2020-04-20 at 20 43 16" src="https://user-images.githubusercontent.com/6326271/79809709-94c3d480-8347-11ea-8ed0-c2820a1919ca.png">

The watch and variables pane expect a tree object which we create from the delve response in order to show the key and value properties of the map, and on traversal from the pane we're not converting back this object to go syntax, thus being `b.data.data["issuer"]` instead of `b["issuer"]` and `b["issuer"]["foo"]`

I will create another issue with this

**Comment by lggomez** [comment] 2020-04-21 00:04
As explained, I created #3198 with @Aisuko`s bug

**Comment by stamblerre** [comment] 2020-06-03 02:06
#3198 has now been migrated to https://github.com/golang/vscode-go/issues/135 (see https://github.com/microsoft/vscode-go/issues/3247).

Is anyone able to reproduce the first issue mentioned in https://github.com/microsoft/vscode-go/issues/2968#issue-545277630?

**Comment by ramya-rao-a** [comment] 2020-06-03 05:03
@stamblerre, Given that no-one has responded to @lggomez's comment from April 20 on not able to reproduce the first issue, we can close this.

If anyone sees the same problem, please log an issue at https://github.com/golang/vscode-go/issues/ as [we are moving](https://github.com/microsoft/vscode-go#we-are-moving---).

**Closed by ramya-rao-a** 2020-06-03 05:03 UTC
Labels: debug, needs-investigation
