### ISSUE TITLE
Tell where goreturns is

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#106] opened 2015-11-26 13:07 UTC
When I run "Format Code" I get:

> The 'goreturns' command is not available. Please check your go.formatCommand user setting and ensure it is installed.

![image](https://cloud.githubusercontent.com/assets/159209/11423705/92383c0a-93fb-11e5-942c-045a6097f111.png)

I had to google to find out where goreturns is.

**Comment by lukehoban** [comment] 2015-11-26 19:02
_Meta comment_:  You should be seeing a green "Analysis Tools Missing" in the bottom right of your screen.  Clicking that will offer to install all the necessary tools for you.  I'll see if I can make this clearer in the README (it's there already near the bottom, but could be more prominent).

Beyond that, I'm going to treat this as a dupe of #102.  If we offer'd to install tools on a one off basis here (maybe even with an "Install" and "Install All" option), that is probably the best way to address this.

**Closed by lukehoban** 2015-11-26 19:02 UTC
