### ISSUE TITLE
go-langserver using an insane amount of cpu

### ISSUE THREAD

**Issue by primalmotion** [microsoft/vscode-go#1994] opened 2018-10-12 03:49 UTC
Since the last upgrade of vscode/vscode-go go-langserver is using an insane amount of cpu after a few minutes of use (from 400% to 700%) 

my config did not change, and I run update tools command

Here's the relevant part of it

```json
{
    "go.autocompleteUnimportedPackages": true,
    "go.coverOnSingleTest": true,
    "go.coverageDecorator": {
        "type": "highlight"
    },
    "go.coverageOptions": "showUncoveredCodeOnly",
    "go.docsTool": "gogetdoc",
    "go.enableCodeLens": {
        "references": false,
        "runtest": true,
    },
    "go.formatTool": "goreturns",
    "go.languageServerExperimentalFeatures": {
        "autoComplete": false,
        "format": false
    },
    "go.buildOnSave": "package",
    "go.lintFlags": [
        "--disable-all",
        "--exclude-use-default=false",
        "--enable=errcheck",
        "--enable=goimports",
        "--enable=ineffassign",
        "--enable=golint",
        "--enable=prealloc"
    ],
    "go.lintOnSave": "package",
    "go.lintTool": "golangci-lint",
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": false,
    "go.useLanguageServer": true,
    "go.vetOnSave": "off",
    "go.vetFlags": [
        "-shadow",
    ],
    "go.liveErrors": {
        "enabled": true,
        "delay": 500
    },
    "go.gotoSymbol.includeGoroot": true
}
```

```console
go-langserver -version
v3-dev
```

**Comment by ramya-rao-a** [comment] 2018-10-16 01:33
To first decide if this is a issue with VS Code, the Go extension or the language server, can you try with an older version of VS Code and the Go extension and check the performance?

Older version of VS Code can be found in https://code.visualstudio.com/updates

Older version of the Go extension can be found in https://github.com/Microsoft/vscode-go/releases 
Just download the vsix file and run `code --install-extension Go-x.y.z.vsix`

**Comment by primalmotion** [comment] 2018-10-16 18:06
first thing I did was to go back to VScode version from August (using same version of language server and vscode-go). Didn't need to push the investigation further, all is working well now for 30min. So it seems the regression is from VScode. I'll continue to work with this version for a while and report if things are going crazy again.

**Comment by primalmotion** [comment] 2018-10-16 22:58
I confirm it works perfectly with vscode `1.27.2`

**Comment by ramya-rao-a** [comment] 2018-10-17 02:10
@primalmotion, @gow You opened and worked on the same project in both new and old versions of VS Code? 

@dbaeumer Any idea why the latest VS Code would cause such an issue? The version of language client used in the Go extension is 4.3.0

**Comment by primalmotion** [comment] 2018-10-17 02:57
@ramya-rao-a yes. I worked all day on the same set of workspace as usual.

**Comment by dbaeumer** [comment] 2018-10-17 09:29
@ramya-rao-a something might have changed in VS Code which as a result pokes the server more often. One way to find this out is to enable tracing in both setups and see if there are more requests send to the server and if so which once.

**Comment by ankur-anand** [comment] 2018-10-17 15:02
@ramya-rao-a I've updated the go-tool today `0.6.91` and after that, it uses a huge chunk of CPU all the time, 

average load
```command
 ankur ▶ ~/Desktop/…/twoSum ▶ $ ▶ uptime
 20:20:31 up 30 min,  1 user,  load average: 14.81, 14.53, 11.34
```
process info
```command
 ankur ▶ ~/Desktop/…/twoSum ▶ $ ▶ ps -eo pcpu,pid,user,args | sort -k1 -r -n | head -10
52.6  5406 ankur    /usr/bin/go build -o /tmp/vscode-goKgQCYU/go-code-check .
51.6  5415 ankur    /usr/bin/go vet ./...
51.4  5600 ankur    /usr/bin/go build -o /tmp/vscode-goKgQCYU/go-code-check .
51.2  5596 ankur    /usr/bin/go vet ./...
41.9  7757 ankur    go list -e -json -compiled -test=true -export=true -deps=true -tags= -- .
41.8  7644 ankur    /usr/bin/go build -o /tmp/vscode-gosPJvQE/go-code-check .
41.7  7784 ankur    /usr/bin/go vet ./...
41.5  7640 ankur    /usr/bin/go vet ./...
41.3  7791 ankur    /usr/bin/go build -o /tmp/vscode-gosPJvQE/go-code-check .
 3.7 13848 ankur    /usr/lib/chromium-browser/chromium-browser --type=renderer --field-trial-handle=16958379901938881904,8968544606741407184,131072 --service-pipe-token=7304318142105071701 --lang=en-US --enable-offline-auto-reload --enable-offline-auto-reload-visible-only --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=7304318142105071701 --renderer-client-id=45 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
````
go version
`go version go1.11 linux/amd64`

CPU Consuming most time in the User Space
```command
 ankur ▶ ~/Desktop/…/twoSum ▶ $ ▶  mpstat
Linux 4.15.0-36-generic (thinkpad-e470) 	10/17/2018 	_x86_64_	(4 CPU)

08:17:21 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
08:17:21 PM  all   78.19    0.06    3.00    0.26    0.00    0.22    0.00    0.00    0.00   18.27
```

**Comment by gow** [comment] 2018-10-17 17:05
I confirmed that VS Code `1.27.2` doesn't have this issue with same Go extension `0.6.91`

**Comment by ramya-rao-a** [comment] 2018-10-17 21:41
@ankur-anand This issue is tracking the problem of the Go language server consuming a lot of CPU where as your issue is independent of the Go language server, therefore can you please log a separate issue and we can take it from there?

**Comment by primalmotion** [comment] 2018-10-30 04:44
there is a related issue there sourcegraph/go-langserver#209

**Comment by huttarichard** [comment] 2018-11-03 14:30
having same issue, for me os crashed sourcegraph/go-langserver#336

**Comment by ramya-rao-a** [comment] 2018-11-06 06:15
@huttarichard Do you also not see the problem in 1.27.2? You can get the older version from https://code.visualstudio.com/updates/v1_27

**Comment by huttarichard** [comment] 2018-11-07 11:15
@ramya-rao-a I can confirm, so far did not happen

**Comment by pmalekn** [comment] 2018-11-08 10:58
I am only using vs code with Go for a couple of weeks and using langserver was always causing huge CPU spikes and memory consumption. VS code version `1.28.2`, go plugin `0.7.0`, `go-langserver` SHA `0ed1299806f7c16c0fd25d9ac31ef20e48cd4ce0`.

Attaching cpu and heap profiles if that might help anyone. (while creating the heap profile langserver was using around 14 gigs of memory - at least that's what Activity Monitor said)

[pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/Microsoft/vscode-go/files/2561389/pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)
[pprof.samples.cpu.001.pb.gz](https://github.com/Microsoft/vscode-go/files/2561390/pprof.samples.cpu.001.pb.gz)

**Comment by ramya-rao-a** [comment] 2018-11-09 02:36
@pmalekn Can you also check if you see the same when using VS Code 1.27?

**Comment by pmalekn** [comment] 2018-11-09 13:32
@ramya-rao-a 1.27.2 seems better after using it for a while but I wouldn't like to bet on it. I've left `go-langserver` version as described in my previous post and now I don't see those memory and CPU spikes

**Comment by primalmotion** [comment] 2018-11-12 23:01
still miserable with vscode `1.29.0`

**Comment by sandipb** [comment] 2018-11-15 23:00
@ramya-rao-a I have been closely looking at this because it has been significantly hampering my development. I looked closely, for example at the traces of the langserver.

One odd thing stood out - currently, when I am typing in the code editor, it seems that vscode sends a `notif: textDocument/didChange` message, and then a `request #n: textDocument/documentSymbol`  request **on every character being entered in the editor**. This causes an insane amount of unnecessary chatter for a line of text being input.

Is this by the protocol design?

Can this be, in some ways _debounced_ and so the messages only sent after a minimum x millis?

Can this be configurable? Like, if I want to only care about getting popup help after I pause typing for 500ms?

I am just guessing out there, that a possible edge case is being triggered in the lang server because two many requests are being sent for the same document, and we can reduce this a bit by asking langserver less frequently by cutting down on obvious unnecessary calls.

**Comment by dbaeumer** [comment] 2018-11-19 10:37
@jrieken could this be caused by the outline view?

**Comment by ramya-rao-a** [comment] 2018-11-20 07:14
@sandipb Thats a good observation. Disable both the outline view in the explorer viewlet and the breadcrumbs feature and see if that makes any difference.

Outline view: 
- Open the File explorer
- Right-click on the section header "OUTLINE" to disable it

Breadcrumbs:
- View -> Toggle Breadcrumbs to disable it

**Comment by sandipb** [comment] 2018-11-21 00:02
Lol. I didn't even know that Breadcrumbs was a feature. Didn't have it on.

Just now had an editing session with the outline disabled. Still had the issue with langserver.

Is there a way to force the outline view to use the default outline cli (`go-outline`) regardless of whether langserver is enabled?

**Comment by primalmotion** [comment] 2018-11-21 21:52
I tried to disable breadcrumb and outline view, doesn't improves anything for me

**Comment by lybest** [comment] 2018-12-14 09:11
I have the same issue, did someone fix this problem?

**Comment by ColtonProvias** [comment] 2018-12-18 18:11
It looks like everybody is just waiting for the official Go langserver to be released, which could be a while. Even over on Sourcegraph's repository, they are advocating just waiting for the official server to ship.

Still, it's not helpful in the interim for us suffering from this bug.

**Comment by tj** [comment] 2019-01-10 20:37
not sure if this is related, it seems fine usually, but any time I try vscode for more than ~30 minutes it spawns a ton of these processes and crashes my machine

<img width="1179" alt="screen shot 2019-01-01 at 4 49 34 pm" src="https://user-images.githubusercontent.com/25254/50995630-87e6ed00-1517-11e9-9d10-2b369ece5ebe.png">

**Comment by primalmotion** [comment] 2019-02-05 18:53
we're getting closer https://github.com/sourcegraph/go-langserver/issues/209#issuecomment-460540748

**Comment by ramya-rao-a** [comment] 2019-08-26 03:23
Closing this issue as we have now moved to suggesting `gopls` as the language server of choice than `go-langserver`

For more on language server integration with this extension, please see [Go language server](https://github.com/microsoft/vscode-go#go-language-server)

To go a feature request for gopls, use the [Go issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E)

**Closed by ramya-rao-a** 2019-08-26 03:23 UTC
Labels: needs more info
