### ISSUE TITLE
Build and lint fails when running at workspace level and using modules

### ISSUE THREAD

**Issue by jbrodriguez** [microsoft/vscode-go#2317] opened 2019-02-09 21:36 UTC
These are my vscode-go settings

```
	"go.lintTool": "golangci-lint",
	// "go.lintFlags": ["--fast"],
	"go.gotoSymbol.ignoreFolders": ["vendor"],
	"go.liveErrors": {
		"enabled": true,
		"delay": 250
	},
	"go.lintOnSave": "workspace",
	"go.buildOnSave": "workspace",
```

I have two projects that use Go modules.

One of them has this general structure

```
.
├── Makefile
├── README.md
├── go.mod
├── go.sum
├── ....
└── teemon.go
```

The editor flashes some lint squiggly lines, but after it's done, everything is ok.

I can build an executable without problems.

```
Volumes/Home/code/teemon>Finished running tool: /usr/local/bin/go vet ./...

/Volumes/Home/code/teemon>Finished running tool: /usr/local/bin/go build teemon teemon/app teemon/constant teemon/dto teemon/env teemon/lib teemon/model teemon/power teemon/services

/Volumes/Home/code/teemon>Finished running tool: /Volumes/Home/go/bin/golangci-lint run --print-issued-lines=false ./...
```

Another project has this structure

```
.
├── README.md
├── client
│   ├── dist
│   ├── http.js
│   ├── https.js
│   ├── index.html
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── src
│   └── tests
├── ...
└── server
    ├── Makefile
    ├── ...
    ├── go.mod
    ├── go.sum
    ├── unbalance.go
    └── unbalance_test.go
```

This throws up lint errors (and red squiggly lines)

```
/Volumes/Home/code/unbalance/server>Finished running tool: /usr/local/bin/go vet ./...

/Volumes/Home/code/unbalance>Finished running tool: /usr/local/bin/go build _/Volumes/Home/code/unbalance/server _/Volumes/Home/code/unbalance/server/algorithm _/Volumes/Home/code/unbalance/server/app _/Volumes/Home/code/unbalance/server/common _/Volumes/Home/code/unbalance/server/domain _/Volumes/Home/code/unbalance/server/dto _/Volumes/Home/code/unbalance/server/lib _/Volumes/Home/code/unbalance/server/ntk _/Volumes/Home/code/unbalance/server/services
can't load package: package _/Volumes/Home/code/unbalance/server: cannot find package "_/Volumes/Home/code/unbalance/server" in any of:
	/usr/local/Cellar/go/1.11.5/libexec/src/_/Volumes/Home/code/unbalance/server (from $GOROOT)
	/Volumes/Home/go/src/_/Volumes/Home/code/unbalance/server (from $GOPATH)
...
Error while running tool: /Volumes/Home/go/bin/golangci-lint run --print-issued-lines=false ./...
level=error msg="Running error: context loading failed: failed to load program with go/packages: go [list -e -json -compiled -test=true -export=false -deps=true -- ./...]: exit status 1: go build unbalance/app: no Go files in \ngo build unbalance/domain: no Go files in \ngo build github.com/jbrodriguez/mlog: no Go files in \ngo build unbalance/lib: no Go files in \ngo build unbalance/services: no Go files in \ngo build github.com/jbrodriguez/pubsub: no Go files in \ngo build unbalance/dto: no Go files in \ngo build github.com/jbrodriguez/actor: no Go files in \ngo build github.com/labstack/echo: no Go files in \ngo build github.com/labstack/echo/middleware: no Go files in \ngo build github.com/teris-io/shortid: no Go files in \ngo build github.com/mcuadros/go-version: no Go files in \ngo build github.com/vaughan0/go-ini: no Go files in \ngo build unbalance/algorithm: no Go files in \ngo build unbalance/common: no Go files in \ngo build unbalance/ntk: no Go files in \n"
```

I can still build an executable, but I can't get rid of the  'warnings' and golangci-lint is failing.

I believe it has to do with the fact that go.mod isn't at the root of the workspace.

Any suggestions ?

**Comment by ramya-rao-a** [comment] 2019-02-17 09:01
Do you see the same issue if you change the `go.lintOnSave` and `go.buildOnSave` settings to `package`?

**Comment by jbrodriguez** [comment] 2019-02-17 13:11
Wow !

It works if both are set to 'package'

```
/Volumes/Home/code/unbalance/server>Finished running tool: /usr/local/bin/go build -o /var/folders/w9/7tlszcbs3msddknxvpp64gwc0000gn/T/vscode-golXxdzq/go-code-check .

/Volumes/Home/code/unbalance/server>Finished running tool: /usr/local/bin/go vet ./...

/Volumes/Home/code/unbalance/server>Finished running tool: /Volumes/Home/go/bin/golangci-lint run --print-issued-lines=false
```

I also tried it on another project with the same subfolder for go structure and it seems to run golangci-lint on the whole go project, which is fine by me.

Why the difference between package/workspace in these scenarios?

Should I always use package then ?

**Comment by ramya-rao-a** [comment] 2019-02-24 02:44
@jhendrixMSFT Can you try to set `buildOnSave` and `lintOnSave` settings to `workspace` and check the behavior on a project with sub modules?

> I also tried it on another project with the same subfolder for go structure and it seems to run golangci-lint on the whole go project, which is fine by me.

Did this other project use modules as well?

**Comment by jbrodriguez** [comment] 2019-02-27 19:35
> Did this other project use modules as well?

Yes it uses projects as well

**Comment by dtzar** [comment] 2019-04-02 17:26
I am also experiencing this problem even while setting the `buildOnSave` and `lintOnSave` settings to `workspace`.  The issue is when you do a `go get -m <module>` or `go mod download` golang installs the dependencies into the `GOPATH\pkg\mod\...` dir and vscode doesn't search this path.  It only checks the `GOROOT\modules` or `GOPATH\modules` directories.

**Comment by ramya-rao-a** [comment] 2019-04-03 06:08
When trying to build the entire workspace, this extension tries to figure out the import paths of all the packages under the workspace, and pass them all to `go build` command.

This clearly is not working as expected when using modules.

Anyone knows what is the best way to get compile time errors for all packages under a given folder?
Will `go build .` suffice?

**Comment by bragagia** [comment] 2019-05-10 10:24
I just ran into the same issue using `gopls`, everything works just fine when working at package level but while using workspaces, autoimports stops working (everything else still seems to works fine).

I tried to set both `go.lintOnSave` and `go.buildOnSave` to `"package"` but it didn't change anything.

My go-related settings: 
```
"go.useLanguageServer": true,
"[go]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
},
```

**Comment by stamblerre** [comment] 2019-05-10 22:01
`gopls` has a different set of configurations, so it won't respect changes to `go.lintOnSave` and `go.buildOnSave`. To get diagnostics from the language server, you will need to set:

```json5
"go.languageServerExperimentalFeatures": {
        "diagnostics": true
},
```

**Comment by ramya-rao-a** [comment] 2019-05-12 01:16
@stamblerre That still wouldn't help here as the workspace option is most likely used when there are multiple modules/packages in the workspace and `gopls` doesn't support multiple modules in the same VS Code workspace at the moment

**Comment by stamblerre** [comment] 2019-08-12 17:42
@bragagia: Are you still encountering issues with `gopls`? If so, please file an issue on the [Go issue tracker](https://github.com/golang/go/issues/new) and I can help you troubleshoot.

@ramya-rao-a: https://github.com/golang/go/issues/33544 is tracking the consolidation of `gopls` configurations across editors.

**Comment by ramya-rao-a** [comment] 2019-12-12 03:40
Closing this issue in favor of the upstream issue

**Closed by ramya-rao-a** 2019-12-12 03:40 UTC
Labels: bug, go-modules, under-discussion
