### ISSUE TITLE
VSCode removes the character right after auto complete point when language server enabled.

### ISSUE THREAD

**Issue by smy20011** [microsoft/vscode-go#2525] opened 2019-05-19 22:53 UTC
If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
- any Go related settings you might have added/changed

Steps to Reproduce:

1. Enable go language server
2. Trigger autocomplete at `os.` for code
```go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Printf(os.)
}
```
3. Choose GetEnv
4. You will get following code
```go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Printf(os.Getenv()
}
```
The second parentheses is missing.

Video: https://streamable.com/00ea0

**Comment by SteelPhase** [comment] 2019-05-20 14:44
I can confirm similar behavior, not sure if it's also related, but I have times where autocomplete doesn't actually insert any text at all after pressing tab.

**Comment by stamblerre** [comment] 2019-05-20 20:06
/cc @muirrn

Looks like this is a result of https://go-review.googlesource.com/c/tools/+/177757. Maybe we should be checking for an enclosing function call before determining the postfix?

**Comment by muirrn** [comment] 2019-05-20 21:58
Should be fixed now on master. Sorry about that!

**Comment by SteelPhase** [comment] 2019-05-21 14:36
I'll keep an eye on this behavior, but the fix does appear to solve the issue.

**Comment by ramya-rao-a** [comment] 2019-05-22 07:11
Thanks everyone, closing this issue as the latest `gopls` has the fix

**Closed by ramya-rao-a** 2019-05-22 07:11 UTC
