### ISSUE TITLE
Format on save doesn't work anymore

### ISSUE THREAD

**Issue by tapir** [Microsoft/vscode-go#1419] opened 2017-12-19 20:28 UTC
I've just noticed that go doesn't automatically format anymore.
I've also noticed that now go.formatOnSave is deprecated hence I'vee switched to editor.formatOnSave: true yet it still doesn't work.

**Comment by ramya-rao-a** [comment] 2017-12-19 22:00
Can you try
```
"[go]": {
   "editor.formatOnSave": true
}
```

Remember that Workspace Settings will override Global/User Settings.

Can you also try on a smaller package separately?
If the formatter takes more than 750ms then it is skipped as slow processes like that can end up adding edits to file after manual edits from user

**Comment by tapir** [comment] 2017-12-20 10:44
Hi,

tried above setting on 2 different computer (one windows another one linux) with multiple size projects including very small ones. Still no luck.

**Comment by tapir** [comment] 2017-12-20 10:55
Actually, now I notice, other facilities such as automatically arranging imports, go to definition etc don't work either. Here is my global settings file (there is no workspace specific setting) 

```json
// Place your settings in this file to overwrite the default settings
{
    "go.lintTool": "gometalinter",
    "git.confirmSync": false,
    "extensions.ignoreRecommendations": true,
    "workbench.startupEditor": "newUntitledFile",
    "git.autofetch": true,
    "[go]": {
        "editor.formatOnSave": true
     }
}
```

**Comment by gangachris** [comment] 2017-12-20 13:04
Release notes say `go.formatOnSave` is deprecated. Tried the above setting by @ramya-rao-a but still no luck. 
Also tried adding `"go.formatFlags": ["-w"],` since its using goreturns, but no luck.

**Comment by ramya-rao-a** [comment] 2017-12-20 14:55
Does manual formatting work?

**Comment by tapir** [comment] 2017-12-20 15:03
It does, yes.

**Comment by esinek** [comment] 2017-12-20 16:07
Same here. Running `gofmt` from the cmd line works. Save on format or Option-Shift-F (the default format file in MacOS, which, I believe should use gofmt) doesn't format file either.
When I select some lines and do Cmd-K, Cmd-F, I get the following message:
`Sorry, but there is no formatter for 'go'-files installed.`
this is with the following:
```
    "editor.formatOnSave": false,
    "[go]": {
        "editor.formatOnSave": true
    }
```

**Comment by ramya-rao-a** [comment] 2017-12-20 17:15
Ok, then it's the case of formatter taking more time than 750ms.

I am currently on vacation. A few things you can do
- stay on the current version, run manual formatting when needed. When I get back, I can look at bringing back the old behavior as a fall back, but it will bring back the 5 issues that the new model is fixing
- or you can revert to the previous version. Get the vsix file from the previous release https://github.com/Microsoft/vscode-go/releases/tag/0.6.69 and run "code --install-extension Go-0.6.69.vsix" and then disable aauto update of extensions

**Comment by tapir** [comment] 2017-12-20 17:17
Ok thanks. 

I'm not convinced it's the 750ms issue though because even a very simple hello world can't be formatted on my computer.

Have a nice vacation.

**Comment by philipithomas** [comment] 2017-12-20 18:10
I'm also having this issue all of a sudden. No formatting or goimports being run.

**Comment by gangachris** [comment] 2017-12-20 19:05
@philipithomas had to revert to 0.6.69 like @ramya-rao-a suggested.

**Comment by ramya-rao-a** [comment] 2017-12-21 04:24
@esinek manual formatting shldnt be affected. I don't recall the keyboard shortcut in Mac for formatting. Can you try the formatting cmd from the cmd pallet or right click on editor and choose "format document"

@tapir That does sound suspicious. Can you drop a few console.log() statements in the file "$HOME/.vscode/extensions/lukehoban.go-0.6.70/out/src/goFormat.js" and see if formatting provider is being called? There is code there tracking time taken for formatting. console.log() that time as well

**Comment by egorovli** [comment] 2017-12-21 09:48
Also missing go.formatOnSave which was fine until I had a variable name collision with some package which gets automatically imported :(

![out2](https://user-images.githubusercontent.com/5165202/34250132-f3df1366-e64c-11e7-8dcc-17dd8904456b.gif)

`config` is defined in `main.go`, trying to save `routes.go` which uses this `config` variable, but instead package `github.com/prometheus/common/config` gets imported.

**Comment by lunny** [comment] 2017-12-21 10:06
here only `gofmt` work, but `goimports` and `goreturns` didn't work.

**Comment by andrevoget** [comment] 2017-12-22 05:21
I have the same problem. Neither

"go.formatTool": "gofmt"
"go.formatTool": "goimports"
"go.formatTool": "goreturns"

work all of a sudden.

**Comment by nathj07** [comment] 2017-12-24 07:48
This is the same behaviour I am seeing:
OS: MacOS Sierra
VS-Code: 1.19.1
Extension: 0.6.70
goimports works from the command line, and on save it will add/remove imports from the standard library but nothing from the project, the  GOPATH, or the vendored directory.

I too am on vacation so no real rush, just thought a little more info may help. Enjoy the holidays.

**Comment by iwaseyusuke** [comment] 2017-12-25 07:15
On my environment, formatting on save does not work when problems of linter are too much (exceed the max num of the problems (>100?)).

Can I increase the max num of problems like `"python.linting.maxNumberOfProblems"`?
Or force to run format tool even if problems are too much?

**Comment by tapir** [comment] 2017-12-25 07:21
Strangely started working on my Linux computer. Did nothing or maybe I've updated the whole VSCode package (that I'm not sure as I did not pay attention to what's in the update)

Windows computer is still not working with the latest version of VSCode

**Comment by ramya-rao-a** [comment] 2017-12-26 05:08
@egorovli The reason for what you are seeing is explained in https://github.com/Microsoft/vscode-go/issues/613#issuecomment-353649374

@iwaseyusuke The formatting tool does not depend on what the linter does. The format on save feature however is aborted when formatting takes more than 750ms.

@tapir Did you use the same codebase on Linux and Windows for comparison? It could be that the formatting tool is slower in Windows when compared to Linux? Also, did you get a chance to follow the steps in https://github.com/Microsoft/vscode-go/issues/1419#issuecomment-353255121 and get some logging on the time taken by formatting?

@nathj07 Adding/removing of imports just from std lib and not from GOPATH seems unrelated to this issue. Does the same happen when you are on the 0.6.69 version of the Go extension? See https://github.com/Microsoft/vscode-go/issues/1419#issuecomment-353125217 for instructions on reverting to 0.6.69.

**Comment by iwaseyusuke** [comment] 2017-12-26 05:12
@ramya-rao-a Thanks! Indeed the file failed to format have too many lines. Can we increase the value of timeout (750ms)?

**Comment by nathj07** [comment] 2017-12-26 07:35
@ramya-rao-a I have rolled back the extension, that was a simple process thanks for that. It has indeed worked. Thanks for your help.

**Comment by ramya-rao-a** [comment] 2017-12-26 07:37
@nathj07 Can you log a separate issue for the adding/removing of imports working only for std lib in the latest version with a sample code that I can use to repro?

**Comment by nathj07** [comment] 2017-12-26 07:56
@ramya-rao-a  done - #1427  the code I added reproduces what I've been seeing. Thanks for the help.

**Comment by tapir** [comment] 2017-12-27 06:26
Here is the requested change and it's result after a save in Go workspace: https://imgur.com/a/2YnhP

I've also noticed other errors related to Go extension in the console. Will that cause any issues?

**Comment by ramya-rao-a** [comment] 2017-12-27 21:56
@tapir Add a `console.log(timeTaken);` just before the `return resolve(textEdits);` Ensure that you have reloaded VS Code after making changes to the `goFormat.js` file. If you still get the `Activating extension "lukehoban.Go" failed` message with the missing module, then your current version of the extension seems to be corrupted. Uninstall and Install the extension and try again.

Others on 0.6.70 version and not getting the format on save feature,
Do you see any error messages in the Console when saving the file? Help -> Toggle Developer Tools -> Console

**Comment by tapir** [comment] 2017-12-28 06:39
Re-instelled the extension and everything works again. Don't know why I didn't try that before...
So the actual bug is corruption on extension update then? Does anybody have similar error?

**Comment by kaixianghu** [comment] 2017-12-28 23:29
I am experiencing the same issue of auto format not being run. I have auto save turned on.
Added debug message as suggested in comment#1419,  my experiment shows that format function was simply not called, i see no prints of any log when i perform a random edit, and wait for editor to auto save.

if I manually trigger a format, i see time taken to format printed.

I have tried re-installing go plugin, trying goformt, goimports as formatter, nothing seem to work

**Comment by ramya-rao-a** [comment] 2017-12-29 18:19
@kaixianghu Thanks for the extra information about auto-save. Now I can repro!! Can you try disabling the auto-save feature and then seeing if the formatter is being called on manual file save?

**Comment by kaixianghu** [comment] 2017-12-29 19:45
@ramya-rao-a , disabled auto-save feature, manually saving the file does trigger auto-format.

**Comment by lunny** [comment] 2017-12-30 04:30
@ramya-rao-a I haven't enable auto-save and reinstall Go extension resolved my problem.

**Comment by iwaseyusuke** [comment] 2017-12-30 14:03
@ramya-rao-a Sorry for the delay.

Yes, I could reproduce this issue consistently with the large file (over 8000 lines in a single file):

```
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] stdout maxBuffer exceeded
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Check the console in dev tools to find errors when formatting.
```

With the file which has about 4000 lines:

```
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host]% 1925
```

Also, when succeeded to format:

```
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host]% 47
```

Hmmm... it might be better to refactor and split my codes first...

**Comment by ramya-rao-a** [comment] 2017-12-30 19:40
@iwaseyusuke I can fix the issue of the formatting tool erroring with the max buffer issue. Are the numbers 1925 and 47 the time taken?

**Comment by iwaseyusuke** [comment] 2018-01-05 06:46
@ramya-rao-a Yes, I just followed [your comments](https://github.com/Microsoft/vscode-go/issues/1419#issuecomment-353255121) and got the outputs of console.

**Comment by ramya-rao-a** [comment] 2018-01-05 20:17
Ok, so far there are 4 categories I see forming
1. Issue with the Go installation where uninstalling and installing the extension again works.
     - These are the cases where in the console you see error messages about extension activation failure
     - Or error about no formatter for go installed 
2. Auto-Save is enabled and set to `afterDelay`
     - We moved from our own special implementation of format-on save feature to that supported by VS Code. And by design the latter is disabled when auto-save is on. This is to keep cursor and selections stable as you type. 
3. Formatter takes more than 750ms
     - Slow formatters are aborted by the format on save feature of VS Code as they can delay the save operation and cause perf issues.
     - With the latest Go extension (0.6.71), we start logging a message in the console (Help -> Toggle Developer Tools -> Console) if the formatter is taking too long.
4. Packages being wrongly imported when there are global variables matching the pkg name. 
     - With the latest Go extension (0.6.71), you will be prompted to update your `goreturns` tool after which you shouldn't see this issue.

Anybody seeing anything other than the above 4?

**Comment by STiAT** [comment] 2018-01-24 12:10
I had the issue of goreturns taking too long to update, which worked perfectly well before I updated this week. "go.formatTool": "gofmt" works though.

**Comment by mlitvin** [comment] 2018-01-28 08:54
I have an issue where autosave doesn't format but issuing the "format document" command manually works.

I have  files.autoSave, as off, it doesn't look like the 750ms issue (the files are short, and doing it manually is very responsive).

It is linting, building and vetting on save, just not formatting.

I'm running vscode 1.19.3, and go extention  0.6.73

**Comment by bofabcd** [comment] 2018-01-28 22:44
[Extension Host] Formatting took too long(1406ms). Format On Save feature could be aborted.

**Comment by ramya-rao-a** [comment] 2018-01-29 06:47
@mlitvin Do you see similar error like @bofabcd in https://github.com/Microsoft/vscode-go/issues/1419#issuecomment-361103284 when the formatting on save doesn't work? You will have to open the console via Help -> Toggle Developer Tools -> Console

@bofabcd Unfortunately, that is the expected outcome of slow formatters currently

**Comment by mlitvin** [comment] 2018-01-29 07:05
OK looking at the console  I do get the error that it take too long. Sorry.

**Comment by ramya-rao-a** [comment] 2018-01-29 18:16
Anybody reaching this issue please see https://github.com/Microsoft/vscode-go/issues/1419#issuecomment-355654879

Closing this issue now, as most of the formatting issues have been addressed.

**Closed by ramya-rao-a** 2018-01-29 18:16 UTC
