### ISSUE TITLE
high-cpu go processes when saving in Live Share session

### ISSUE THREAD

**Issue by henrahmagix** [microsoft/vscode-go#2526] opened 2019-05-20 11:45 UTC
This extension is trying to list all files at `/` when I save code in a Live Share session (that I joined). I guess the working directory isn't being shared correctly?

Should we always turn off auto tests/coverage on save when in a Live Share session, i.e. the code is hosted on a different computer?

Required extension settings:
- run tests on save
- run coverage on save

Steps to Reproduce:

1. Join someone's Live Share session
2. Make a change to a file and save
3. Your process list `ps ax | grep go` should include the following:
  ```
  /usr/local/bin/go list -f ImportPath: {{.ImportPath}} FolderPath: {{.Dir}} ./...
  ```
  and it will take a lot of CPU.
4. Confirm the process' working directory is `/`:
  ```bash
  lsof -p 1234
  ```
  where `1234` is the process id from above

**Comment by a-h** [comment] 2019-09-25 13:07
I can reproduce this issue on my Mac. It makes Live Share sessions break down as my computer ends up running lots of Go processes which are using up the CPU.

I end up using `killall go` to stop the rogue processes. This bug also stops tests from running and therefore also stops code coverage from working.

**Comment by a-h** [comment] 2019-09-25 13:52
I see:

```
33814 ??         4:33.64 /usr/local/go/bin/go vet ./...
33841 ??         2:28.23 /usr/local/go/bin/go vet ./...
33847 ??         2:23.97 /usr/local/go/bin/go vet ./...
33858 ??         0:54.82 /usr/local/go/bin/go vet ./...
33865 ??         0:51.31 /usr/local/go/bin/go vet ./...
33880 ??         0:01.62 /usr/local/go/bin/go vet ./...
```

Then, when I look at which files are open:

```
$ lsof -p 33880
COMMAND   PID   USER   FD     TYPE            DEVICE SIZE/OFF       NODE NAME
go      33880 adrian  cwd      DIR               1,4     1024          2 /
go      33880 adrian  txt      REG               1,4 14470036 8624964552 /usr/local/go/bin/go
go      33880 adrian  txt      REG               1,4   973824 8624820655 /usr/lib/dyld
go      33880 adrian    0u    unix 0xe59aa3b5f05f035      0t0            ->0xe59aa3b5f05fcb5
go      33880 adrian    1u    unix 0xe59aa3b5f05dbe5      0t0            ->0xe59aa3b5f05d02d
go      33880 adrian    2u    unix 0xe59aa3b5f05d4dd      0t0            ->0xe59aa3b5f05ce9d
go      33880 adrian    4u  KQUEUE                                       count=0, state=0xa
go      33880 adrian   46r     REG               1,4 24519407 8626567451 /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar
```

**Comment by stamblerre** [comment] 2020-02-12 16:01
This sounds quite similar to https://github.com/microsoft/vscode-go/issues/2421, since the number of processes started can affect all VS Code instances, not just live share ones. Let's continue the conversation on that issue. I'll close this one as a duplicate.

**Comment by stamblerre** [comment] 2020-02-12 16:01
Duplicate of https://github.com/microsoft/vscode-go/issues/2421

**Closed by stamblerre** 2020-02-12 16:01 UTC
