### ISSUE TITLE
Not all formatting verbs are highlighted

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [microsoft/vscode-go#3000] opened 2020-01-25 02:58 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.5 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64

- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.12.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- linux/amd64

### Share the Go related settings you have added/edited
```json
    "go.useLanguageServer": true,
    "gopls": {
        "deepCompletion": true,
        "staticcheck": true,
        "completeUnimported": true,
    },
    "go.autocompleteUnimportedPackages": true,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.delveConfig": {
        "dlvLoadConfig": {
            "followPointers": true,
        },
    },
```
Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

### Describe the bug
VSCode normally highlights "normal" formatting verbs like `%s` or `%d`, however, `%w` remains unhighlighted in calls to `fmt.Errorf`

### Steps to reproduce the behavior:
1. open a go file
1. copy the following code: 
```go
package main

import "fmt"

func main() {
    fmt.Errorf("vscode example %s: %w", "test", errors.New("test"))
}
```
3. Note the highlighted `%s`, but normal `%w`

### Screenshots or recordings
![Screenshot](https://user-images.githubusercontent.com/21071450/73115496-31382f80-3f2f-11ea-9ad6-3365e14fe5d9.png)

**Comment by stamblerre** [comment] 2020-01-25 17:45
I would guess that this is because `%w` is new, as of Go 1.13. As of @ramya-rao-a's comment in May 2019 (https://github.com/microsoft/vscode-go/issues/2510#issuecomment-492515712), it seems that VS Code uses https://github.com/atom/language-go/blob/master/grammars/go.cson for syntax highlighting, so perhaps it makes sense to move this issue to the https://github.com/atom/language-go repository?

**Comment by ramya-rao-a** [comment] 2020-01-27 04:47
This issue is a duplicate of #2819

The discussion there leads to an upstream issue in VS Code https://github.com/microsoft/vscode/issues/82549. Please subscribe to this issue for updates.

**Closed by ramya-rao-a** 2020-01-27 04:47 UTC
