### ISSUE TITLE
Debugging and symbolic links from GOPATH src to other location

### ISSUE THREAD

**Issue by truewt** [microsoft/vscode-go#1938] opened 2018-09-23 09:18 UTC
Hi,

I have already seen some issues reporting problems with symbolic links, but they were marked as solved. However, in my case symbolic links still present an issue which I'd like to resolve, because otherwise I have some additional work with my cloud sync software (basically I need to copy changes from classic directory over to the actual directory of project which is being sync'd and I also lose all intermediate changes to file until I copy it). Maybe I overlooked that this feature won't work because of debugger, but since delve itself can debug symbolic links, I don't see a problem why vscode wouldn't support this as well (maybe because of the nature of problem - providing function's name instead of file path requires a bit of logic to provide correct name to debugger). I can't really provide some example code at the moment, but I will try to describe how to reproduce the problem. I'm using Manjaro Linux, vscode 1.27.2 and vscode-go 0.6.89.

For the beginning let's suppose we have a project folder called `prodir`, which is located at `/home/user/projects/prodir`. Symbolic link which points to it is located at `/home/user/go/src/github.com/user/prodir`. The project is being opened in vscode (doesn't matter if via original path or via symbolic link, the behavior of debugger is same at the end). It contains file `main.go` and directory called `subdir`. `subdir` then contains another file called `child.go`. Along project files there is also `.vscode` directory which contains `launch.json`. This results in a tree structure:

```
prodir
| - main.go
| - subdir
    | - child.go
| - .vscode
    | - launch.json
```

The contents of `launch.json`:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch",
      "type": "go",
      "request": "launch",
      "mode": "debug",
      "remotePath": "",
      "port": 2345,
      "host": "127.0.0.1",
      "program": "${workspaceRoot}",
      "env": {},
      "args": [],
      "trace": "verbose",
    }
  ]
}
```

The important thing to note is that `main.go` use structs from `child.go` (contained in `subdir`), so it imports it the following string: "github.com/user/prodir/subdir". Let's try to debug our program and set breakpoint at line 14 in file `child.go`. Now start our debug configuration called "Launch". We get the following (from trace) into the debug console:

```
Verbose logs are written to:
/tmp/vscode-go-debug.txt
10:42:19 AM, 9/23/2018
InitializeRequest
InitializeResponse
Using GOPATH: /home/user/go
Running: /home/user/go/bin/dlv debug --headless=true --listen=127.0.0.1:2345 --
InitializeEvent
SetBreakPointsRequest
Creating on: /home/user/project/prodir/subdir/child.go:14
Error on CreateBreakpoint: could not find /home/user/project/prodir/subdir/child.go:14
All set:[null]
SetBreakPointsResponse
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
```

Which means that we have unverified breakpoint which won't be hit. In case that we would set the breakpoint somewhere inside `main.go` everything would work as expected. So the problem is with breakpoints in imports/code in subdirectories.

How to fix this issue with symbolic links? Simply copy over prodir to `/home/user/go/src/github.com/user` (for now) with a different name `workdir` (located at `/home/user/go/src/github.com/user/workdir` then). Let's start from beginning, open up project in vscode. Great, the only thing which remains to the working debugging is to replace imports "github.com/user/prodir/..." with "github.com/user/workdir/...". Let's try to debug our program and set breakpoint at line 14 in file `child.go`. Now start our debug configuration called "Launch". We get the following (from trace) into the debug console:

```
Verbose logs are written to:
/tmp/vscode-go-debug.txt
11:09:11 AM, 9/23/2018
InitializeRequest
InitializeResponse
Using GOPATH: /home/user/go
Running: /home/user/go/bin/dlv debug github.com/user/workdir --headless=true --listen=127.0.0.1:2345 --
InitializeEvent
SetBreakPointsRequest
InitializeEvent
SetBreakPointsRequest
All cleared
Creating on: /home/user/go/src/github.com/user/workdir/subdir/child.go:14
All set:[{"id":1,"name":"","addr":9876916,"file":"/home/user/go/src/github.com/user/workdir/subdir/child.go","line":14,"functionName":"github.com/user/workdir/subdir.TheThingWeCalledFromMainGo","Cond":"","continue":false,"goroutine":false,"stacktrace":0,"LoadArgs":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":64,"MaxArrayValues":64,"MaxStructFields":-1},"LoadLocals":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":64,"MaxArrayValues":64,"MaxStructFields":-1},"hitCount":{},"totalHitCount":0}]
SetBreakPointsResponse
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
```

Hooray, debugging works as expected! Now we can continue our work on the project and be happy with the features of the great vscode.

Aside of the written story I tracked down this problem with looking to the source from both vscode-go, where CreateBreakpoint is called, to the delve's breakpoints and file path to address resolver. I didn't set up debugging environment to trace down what's the actual problem for this behavior. It could be the problem of vscode-go or delve, I'm not sure, but I think that I'm not alone with such a problem. If there is any interest to fix this, I'm open to help in any possible way - maybe via (voice) chat to provide additional resources or with some guidance to setup up debugging for both vscode-go and delve (if possible) to fix the problem by myself.

Thanks for any feedback in advance!

**Comment by ramya-rao-a** [comment] 2018-12-30 04:08
Hey @truewt,

Thanks for reporting with such details and I apologize for not replying sooner.

> If there is any interest to fix this, I'm open to help in any possible way

The problem indeed is with symlinks. I have had other users report similar issues, but I never got to replicate the problem and therefore no solution yet :(

> provide additional resources or with some guidance to setup up debugging for both vscode-go and delve (if possible) to fix the problem by myself.

I would gladly help you in figuring out where the problem is. Please follow the below links for setting up a local environment of the Go extension:

- [Build and Debug the Go extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- You are already aware of the `trace` attribute in the debug config that shows logs from the debug adapter. Add `"showLog": true` to see the logs from delve. Add `"logOutput": "rpc"` to see the logs that show the rpc communications between the debug adapter and delve. 
- [Debugging the debugger](https://github.com/Microsoft/vscode-go/tree/master/src/debugAdapter) to add breakpoints in the code related to debugging.

**Comment by excenter** [comment] 2019-04-01 19:54
https://github.com/Microsoft/vscode-go/issues/2111#issuecomment-478721111
so, as it stands there's no way to debug code that follows a symlink?

**Comment by sryze** [comment] 2019-05-26 02:13
I think I have the same problem: https://github.com/microsoft/vscode-go/issues/2539

**Comment by ramya-rao-a** [comment] 2020-05-28 23:13
Hello all,

We are closing this issue as we havent been able to replicate the problem. [We are also moving](https://github.com/microsoft/vscode-go#we-are-moving---)! Please log a new issue in https://github.com/microsoft/vscode-go if you continue to have problems when debugging with symlinks

Thanks for all the support & Happy Coding!

**Closed by ramya-rao-a** 2020-05-28 23:13 UTC
Labels: debug, needs-investigation, symlink
