### ISSUE TITLE
Go plugin makes cgo spam the system

### ISSUE THREAD

**Issue by abergmeier** [microsoft/vscode-go#3052] opened 2020-02-14 21:06 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.13.4 linux/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.42.0
ae08d5460b5a45169385ff3fd44208f431992451
x64`
- Check your installed extensions to get the version of the VS Code Go extension 
	- latest
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- `linux
amd64`

When I use a `main.go` like:
```
import (
	"github.com/gotk3/gotk3/gtk"
)

func main() {
	// Initialize GTK without parsing any command line arguments.
	gtk.Init(nil)
}
```

the Go plugin starts spamming my systems with CGO compilation.
This eats up >50% CPU time easy. Even after closing VSCode, they still persist.
Only way to get rid of them is `killall cgo`. 

I have no problem with starting CGO, but IMO there needs to be a clear indication why and how
long this should take.

**Comment by stamblerre** [comment] 2020-02-15 02:29
Are you using the language server? What is the contents of your VS Code `settings.json` file?

**Comment by abergmeier** [comment] 2020-02-16 09:34
> Are you using the language server?

Is there any reason not to?

> What is the contents of your VS Code settings.json file?
```
{
    "mesonbuild.configureOnOpen": true,
    "workbench.colorTheme": "Monokai",
    "window.menuBarVisibility": "compact",
    "window.zoomLevel": 1,
    "workbench.activityBar.visible": false,
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "files.autoSave": "off"
}
```

**Comment by stamblerre** [comment] 2020-02-18 17:29
> Is there any reason not to?

No, the language server should work with cgo.

/cc @heschik for cgo expertise

**Comment by heschik** [comment] 2020-02-19 18:44
This isn't totally shocking behavior, but I wasn't able to reproduce it. Could you [gather a gopls log](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#vs-code) and attach it? I'm particularly interested in `packages.Load` calls.

**Comment by stamblerre** [comment] 2020-03-25 21:29
I'm going to close this issue since it hasn't had any activity for the last month. @abergmeier: please reopen if you're still encountering this problem.

**Closed by stamblerre** 2020-03-25 21:29 UTC
Labels: needs more info
