### ISSUE TITLE
Turn off code completion in comments

### ISSUE THREAD

**Issue by mholt** [Microsoft/vscode-go#203] opened 2016-02-23 00:32 UTC
When typing comments, I don't want the 'return' key to use the first suggestion, I want to go to the next line. How can I disable code completion in comments?

**Comment by ironcladlou** [comment] 2016-02-24 15:07
Dupe of https://github.com/Microsoft/vscode-go/issues/103

**Comment by mholt** [comment] 2016-02-24 16:41
I'd like to suggest making it the default setting then :+1:

**Comment by lukehoban** [comment] 2016-02-29 22:10
There is unfortunately nothing `vscode-go` can do about this.  It is a limitation of `vscode` itself.  

Fixing this (or enable extensions to fix it themselves) is being looked at in https://github.com/Microsoft/vscode/issues/1657 and is being tracked as part of the March iteration plan https://github.com/Microsoft/vscode/issues/3555.

**Closed by lukehoban** 2016-02-29 22:10 UTC
