### ISSUE TITLE
Stepping fails with 'next while nexting' error

### ISSUE THREAD

**Issue by aarzilli** [microsoft/vscode-go#2563] opened 2019-06-04 10:49 UTC
1. Debug https://github.com/aarzilli/delve_client_testing/blob/master/05nextbp/main.go
2. set a breakpoint on main.go:23
3. continue once
4. set a breakpoint on main.go:12
5. repeatedly hit next

pretty soon you will encounter the 'next while nexting' error.

**Comment by lggomez** [comment] 2019-07-09 04:13
@aarzilli under which conditions is this error triggered from delve? I see that delve returns it on internal breakpoints but I'm not familiar with its internals. Some additional context on this error may be helpful to catch the cause on our side

There are no parameters involved in this apicall so the problem lies somewhere else in our workflow. Is it a requirement for Next() calls to be blocking in coroutines? our code seems to be doing it that way


Some additional info on the debug adapter side:
This is the next handler: https://github.com/microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L1358-L1371. We keep track internally of the the goroutines, using a common reentry handler: https://github.com/microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L1291-L1320

**The current implementation does an extra ListGoroutines call per action**, updates the internal goroutine list and then sets up the current goroutine id if the current `debugState.currentGoroutine == 0`: https://github.com/microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L1304-L1307. I think this step may be ommited for actions that already return a debugger state with all of the active goroutines like these commands, and use that state instead

I know that this is a separate optimization, but can you confirm if the debug state goroutines can be reused instead of making that extra call to ListGoroutines for this scenario?

**Comment by aarzilli** [comment] 2019-07-09 07:02
When a call to 'next' is interrupted by a breakpoint on a goroutine other than the goroutine where the 'next' command was invoked delve will stop and return a state that has the NextInProgress field set (this also applies to 'step' and 'stepout', by the way). When this happens the frontend needs to do one of two things:

1. cancel the 'next' (or 'step' or 'stepout') command by calling the CancelNext API endpoint and notify the user that the 'next' command was interrupted
2. resume the 'next' (or 'step' or 'stepout') command by issuing a 'continue' command and notify the user of the breakpoint stops that have been skipped

Before you ask: due to the nature of go's runtime it's currently impossible to resume just one goroutine (and the desirability of doing that would be questionable anyway).

**Comment by aarzilli** [comment] 2019-07-09 07:19
Regarding the currentGoroutine thing. It is possible for a debugger state to not have a currentGoroutine set to anything, however doing what that code does seems wrong, if the currentGoroutine is not set it's not valid to simply attribute the current stop to whatever the first goroutine happens to be.

> but can you confirm if the debug state goroutines can be reused instead of making that extra call to ListGoroutines for this scenario?

the DebuggerState object does not contain a list of goroutines at all, in fact sending the whole list of goroutines can be very slow and the ListGoroutines endpoint has parameters specifically to avoid this (which due to a design mistake didn't exist when this extension was written). Issue #2562 is partly about this.

**Comment by lggomez** [comment] 2019-07-09 19:43
[05nextbp.log](https://github.com/microsoft/vscode-go/files/3374562/05nextbp.log)

> When a call to 'next' is interrupted by a breakpoint on a goroutine other than the goroutine where the 'next' command was invoked delve will stop and return a state that has the NextInProgress field set

I attach this log starting from the first breakpoint hit and next call on line 12 and it looks that it is indeed what is happening

The first 3 successful calls are on threadId 15 (the adapter uses the threadId fuekd for goroutine ids, bringing up some confusion)
```log
From client: next({"threadId":15})
NextRequest
To client: {"seq":0,"type":"response","request_seq":19,"command":"next","success":true}
NextResponse
```

Followed by the failing call on threadId 9
```log
From client: next({"threadId":9})
NextRequest
To client: {"seq":0,"type":"response","request_seq":38,"command":"next","success":true}
NextResponse
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2019-07-09T16:18:40-03:00 debug layer=debugger nexting\n"}}
2019-07-09T16:18:40-03:00 debug layer=debugger nexting
```

> 1. cancel the 'next' (or 'step' or 'stepout') command by calling the CancelNext API endpoint and notify the user that the 'next' command was interrupted
> 2. resume the 'next' (or 'step' or 'stepout') command by issuing a 'continue' command and notify the user of the breakpoint stops that have been skipped

So we end up having to go with one of these two routes right? @ramya-rao-a I don't think we can track the skipped breakpoints from the adapter so unless we send a generic notification we would have to just interrupt the next command like in 1.

**Comment by lggomez** [comment] 2019-07-09 19:48
PS: As the logs show, on top of ListGoroutine (ThreadRequest) calls we make additional calls to Stacktrace , ListLocalVars and Eval

**Comment by jdowning100** [comment] 2019-11-20 17:28
Any update on this? This is an incredibly frustrating bug as it randomly kills my debug sessions (and it doesn't help that "failed to next: next while nexting" is basically error message gore)

**Comment by Basez** [comment] 2019-12-12 09:54
This is happening for me right now as well.. it does not actually kill the debug session, but I need to press F-5 to resume the session. Even though no "current line" is highlighted in VScode...

**Comment by ramya-rao-a** [comment] 2019-12-19 19:18
cc @quoctruong and @jhendrixMSFT for any additional insights

**Comment by ventsislav-georgiev** [comment] 2020-01-15 09:39
Still happening and as @Basez it does not kill the debug session.
OS: macOS Catalina 10.15.2
VSCode: 1.41.1
VSCode-Go: 0.12.0
Go: 1.12.14

**Comment by ramya-rao-a** [comment] 2020-05-28 21:57
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Closing this issue in favor of https://github.com/golang/vscode-go/issues/119. Please subscribe to it for further updates.

Thanks for all the support & Happy Coding!

**Closed by ramya-rao-a** 2020-05-28 21:57 UTC
Labels: debug, help wanted
