### ISSUE TITLE
Issues using w/ delve 1.0.0-rc.1: connection refused

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode-go#1012] opened 2017-05-28 22:44 UTC
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 15.6.0
- Go   lukehoban  0.6.61

When I attempt to use vscode go extension with delve 1.0.0-rc.1, I get this error:

> could not launch process: dial tcp :53100: getsockopt: connection refused
> Process exiting with code: 1

This did not happen with delve 0.12.2.

**Comment by ramya-rao-a** [comment] 2017-05-31 05:25
Related to #986

@josh-tepper Are you able to debug using the command line without any issues?

@derekparker Would you say delve 1.0.0-rc.1 is stable enough for editors to use? If not, then I can add a note in the README that we don't support delve 1.0.0-rc.1 yet. Any idea as to why delve fails to launch process in this scenario.

cc @roblourens

**Comment by ramya-rao-a** [comment] 2017-06-05 13:05
Closing as duplicate of #986 

@josh-tepper Please follow the workaround here: https://github.com/Microsoft/vscode-go/issues/986#issuecomment-304347853

**Closed by ramya-rao-a** 2017-06-05 13:05 UTC
Labels: debug, help wanted
