### ISSUE TITLE
setting "go.useLanguageServer": true results in goto definition saying "no definition found"

### ISSUE THREAD

**Issue by gideondsouza** [Microsoft/vscode-go#996] opened 2017-05-14 09:04 UTC
These are my details:

OS: Fedora 25. 
VSCODE:
Version 1.12.1
Commit f6868fce3eeb16663840eb82123369dec6077a9b
Date 2017-05-04T21:40:39.245Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

Go : 1.8
vscode-go : 0.6.61

-------
So I set `go.useLanguageServer": true` in my config. It prompted me to install source graph. Now when I hit F12 (goto definition) on say `fmt.Println(..)` it shows a tooltip saying "no definition for Println found" Additionally, the output from go-langserver  says :

```
[Error - 2:30:06 PM] Request textDocument/definition failed.
  Message: import "/home/gideon/Coding/golang/Project-Euler-Go/05": cannot import absolute path
  Code: 0 

```
The output from the JSON Language Server just says : _enable_

When I set "go.useLanguageServer" back to false, F12 on fmt.Println(..) goes to the right definition.

Expected behaviour is that goto definition should go to the definition, as for what extra hints the language server should give me, I haven't seen it yet.

**Comment by ramya-rao-a** [comment] 2017-05-15 00:27
cc @keegancsmith

**Comment by keegancsmith** [comment] 2017-05-18 14:33
This is a duplicate of https://github.com/sourcegraph/go-langserver/issues/185

**Comment by ramya-rao-a** [comment] 2017-06-01 05:51
Closing this issue as we have an upstream issue for tracking the problem

**Closed by ramya-rao-a** 2017-06-01 05:51 UTC
