### ISSUE TITLE
PROBLEMS panel symlink error

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1568] opened 2018-03-09 02:18 UTC
_From @bukshee on March 8, 2018 15:56_

- VSCode Version: 1.21.0
- OS Version: Linux, Debian 

Steps to Reproduce:

1. I'm doing Go development with the latest version of VSCode. Upon saving the file the PROBLEMS panel pops up with an error. I double click on the file and got:
> Unable to open 'main.go': File not found
> (file:///home/golang/golib/src/github.com/golib/src/github.com/bukshee/json/main.go).

Cause of error most probably is that symlinks not resolved properly. Linux prompt:
```sh
json » pwd
/home/golang/work/json
json » file main.go 
main.go: C source, ASCII text
json » pwd -P
/home/golang/golib/src/github.com/bukshee/json
json » ls -ld ~/work
lrwxrwxrwx 1 golang golang 28 Feb  3 15:26 /home/golang/work -> golib/src/github.com/bukshee

```
![screenshot_2018-03-08_16-53-11](https://user-images.githubusercontent.com/23742579/37160768-4219c978-22f1-11e8-8a7e-0ff24d646bb5.png)

Does this issue occur when all extensions are disabled?: No

_Copied from original issue: Microsoft/vscode#45310_

**Comment by ramya-rao-a** [comment] 2018-03-09 02:19
Can you share whats in the output pane? That will have the arguments passed to `go build` that resulted in the error in the Problems view

**Comment by bukshee** [comment] 2018-03-09 07:16
The two are same dirs, see my linux prompt comment above. The output pane is empty, all I do is start vscode, open up main.go, make an error like

funct main()

then save. The Problems pane gets populated by the error message you see and when I double click on it this is the message I get.
I have Go 0.6.77 extension installed from lukehoban.

**Comment by ramya-rao-a** [comment] 2018-03-10 00:23
> The two are same dirs, see my linux prompt comment above.

I understand that you have one of the dirs symlinked to the other. My question was which of the 2 is opened in VS Code (I know they are the undelying files are the same). For example, when you right-click on any of the file sin the File Explorer and select "Copy Path" and then paste it somewhere to view it, is the file path under `/home/golang/work/json` or `/home/golang/golib/src/github.com/bukshee/json`?

> The output pane is empty

When you open the output pane, select "Go" from the drop down that is on the top right corner of the output pane. You will see logs from `go build` command there.

**Comment by bukshee** [comment] 2018-03-11 14:18
Dear Ramya,

The symlinked version was opened in VSCode, obviously. Otherwise I could not report a symlink error. So once again:

```sh
json » cd    
~ » cd work/json 
json » pwd
/home/golang/work/json
json » pwd -P
/home/golang/golib/src/github.com/bukshee/json
~ » ls -ld work
lrwxrwxrwx 1 golang golang 28 Feb  3 15:26 work -> golib/src/github.com/bukshee
json » code .
```

At this point Copy path returns the proper path (no symlink):
/home/golang/golib/src/github.com/bukshee/json/main.go

but in the Problems panel double clicking on the error I get:

Unable to open 'main.go': File not found (file:///home/golang/golib/src/github.com/golib/src/github.com/bukshee/json/main.go).

Cheers.

**Comment by sandipb** [comment] 2018-03-16 00:32
This bit me too today, and I think I have found the reason.

`runTool` in [util.ts](https://github.com/Microsoft/vscode-go/blob/master/src/util.ts) uses `path.resolve` to join the paths returned by `go build` and the package directory.

the behavior of path.resolve doesn't match how paths are actually resolved on the filesystem. 

On the filesystem, a `..` will always resolve to the actual absolute path of the directory rather than its position in the path with symlink.

Here is a reproduction of the bug:

```console
$ tree -I node_modules
.
├── a
│   ├── b
│   └── e
│       └── c
│           ├── d
│           │   └── b -> /Users/snbhatta/mynpm/a/b
│           └── something.txt
├── package-lock.json
├── package.json
└── test.js

6 directories, 4 files

$ node test.js
Using shell: 'ls a/e/c/d/b/../../something.txt' =  ls: a/e/c/d/b/../../something.txt: No such file or directory

Using path.resolve(a/e/c/d/b, ../../something.txt) =  /Users/snbhatta/mynpm/a/e/c/something.txt
```

The JS source:
```javascript
let exec = require('child_process').exec;
let path = require('path');

exec("ls a/e/c/d/b/../../something.txt", (error, stdout, stderr) => {
    console.log("Using shell: 'ls a/e/c/d/b/../../something.txt' = ", stdout+stderr);
    console.log("Using path.resolve(a/e/c/d/b, ../../something.txt) = ", path.resolve("a/e/c/d/b", "../../something.txt"));

});
```

**Comment by sandipb** [comment] 2018-03-16 01:45
Other than the path resolving issue I mentioned above, there is an additional issue I think is happening.

`go build` is being run with `PWD` set to `/`, at least on my system. 

For some infuriating reason, `go build` uses the PWD variable to determine the file paths.

Just making sure that the PWD variable in the build environment matches what we are trying to build, fixes this bug for me. (i hot patched the vscode-go plugin to test the fix)

```diff
diff --git a/src/goBuild.ts b/src/goBuild.ts
index 73880b6..9685144 100644
--- a/src/goBuild.ts
+++ b/src/goBuild.ts
@@ -56,6 +56,10 @@ export function goBuild(fileUri: vscode.Uri, goConfig: vscode.WorkspaceConfigura
        }

        const buildEnv = Object.assign({}, getToolsEnvVars());
+    if (buildEnv.hasOwnProperty("PWD")) {
+        buildEnv.PWD = cwd;
+    }
+
        const tmpPath = path.normalize(path.join(os.tmpdir(), 'go-code-check'));
        const isTestFile = fileUri && fileUri.fsPath.endsWith('_test.go');

```

**Comment by ramya-rao-a** [comment] 2018-03-16 03:36
@bukshee Thanks for the details and sorry for not getting back sooner
The output of `go build` is printed out in the output pane and then used to show errors in the Problems pane. Can you please share the logs printed in the output pane? Click on the "Output" tab next to the "Problems" tab and then select "Go" from the drop down that appears on the top right corner of the Output pane. Make a change in the file and save. You should see the results of `go build` in the output pane

**Comment by bukshee** [comment] 2018-03-16 12:49
go build output on my linux:

```sh
json » go build main.go
# command-line-arguments
./main.go:54:1: syntax error: non-declaration statement outside function body
./main.go:56:2: syntax error: non-declaration statement outside function body
json » pwd
/home/golang/work/json
```

so inside the symlinked dir.

**Comment by sandipb** [comment] 2018-03-16 15:44
@bukshee 
vscode actually builds your code a bit differently. It builds the object in a temp directory and then discards it. 

![screen shot 2018-03-16 at 8 29 28 am](https://user-images.githubusercontent.com/105359/37529914-9674e23c-28f5-11e8-8031-078c0a3c89ae.png)

I wish it showed a bit more information though - like cwd and environment of the tools, especially because the behavior of the tool changes based on them.

**Comment by ramya-rao-a** [comment] 2018-03-16 17:57
@bukshee I was not referring to the output of `go build` when you manually run it on a terminal. I was referring to the output of the `go build` command run by the Go extension which gets printed to the Output pane as shown in the screenshot that @sandipb has shared above.

@sandipb That's a good idea, we can definitely print the `cwd`, but printing all env var of the tool would be excessive

**Comment by sandipb** [comment] 2018-03-16 18:01
@ramya-rao-a perhaps only the relevant ones? `GOPATH` and `GOROOT`

**Comment by ramya-rao-a** [comment] 2018-03-16 18:25
@sandipb Yes, that can easily be done as well. PRs are welcome. Pointer: https://github.com/Microsoft/vscode-go/blob/0.6.77/src/util.ts#L589

**Closed** 2018-03-23 18:48 UTC
Labels: needs more info
