### ISSUE TITLE
Debugging process does not exit.

### ISSUE THREAD

**Issue by term1nal** [Microsoft/vscode-go#239] opened 2016-03-10 20:04 UTC
Attempting to debug my application, but finding that the socket bindings stay open after stopping the debug as well as closing VSCode all together. I have to `netstat -tulpn` to find the process listening on the port and kill it manually. Something I'm doing wrong? Bug?

For the sake of the post, it shows up in netstat like: `tcp6       0      0 :::8000                 :::*                    LISTEN      14391/debug`

**Comment by DasJott** [comment] 2016-04-08 10:55
I wanted to debug a small web project in go with delve installed.
Maybe the launch file was wrong, whatever, the result was as well, that the port was and stayed blocked. It didn't even show up in netstat or anywhere else.
Had to reboot.

**Comment by Julusian** [comment] 2016-04-16 14:15
I am having this issue too. The process called 'debug' spawned by dlv is left running even after dlv exits. 
Makes vscode really painful to use for a http server

**Comment by aca02djr** [comment] 2016-08-24 16:14
Having this issue too, only seems to be on Linux though as the process exits fine on OS X.

**Comment by jaylittle** [comment] 2016-09-08 13:23
I'd love to see a fix for this.  Just recently started working with go in Visual Studio on Linux and this behavior is driving me bonkers

**Comment by josefcs** [comment] 2016-09-13 09:46
Also stumbled upon this isse. It makes the debugger unusable for me.

**Comment by ramya-rao-a** [comment] 2016-10-31 18:51
@roblourens This would be same as #438 as well ?

**Comment by roblourens** [comment] 2016-10-31 18:59
I think so

**Comment by mattetti** [comment] 2017-01-16 03:27
@ramya-rao-a can we mark this as a duplicate of #438 and close this issue?

**Closed** 2017-01-16 06:31 UTC
Labels: debug, duplicate

**Comment by term1nal** [comment] 2017-01-17 01:07
Well... excuse me. This issue was filed 4 months in advanced of #438. If anything, **that** issue is a duplicate of **this** one. But whatever.

**Comment by DasJott** [comment] 2017-01-18 11:24
No one looks on the dates anymore...
