### ISSUE TITLE
Debugging goes into proc.go at every step

### ISSUE THREAD

**Issue by mxxcx** [Microsoft/vscode-go#2133] opened 2018-11-19 17:23 UTC
I'm using go modules, and every debug step into or step over goes into a proc.go file `gopark` function and then goes back. You can see it in this gif. https://gyazo.com/adb4a54cc467ce372a4b5595b72d150f

Steps to Reproduce:

Have some test and try to debug them. 

launch.json

`{
      "name": "Test",
      "type": "go",
      "mode": "test",
      "request": "launch",
      "remotePath": "",
      "port": 2346,
      "host": "127.0.0.1",
      "program": "${workspaceRoot}/test",
      "env": {
        "GOPATH": "/Users/user/golang"
      },
      "args": ["-test.short"],
      "showLog": false
    }`

**Comment by ramya-rao-a** [comment] 2018-11-21 02:48
Can you try running dlv from the command line, debug the same test and see if the step into/over in that case does something similar?

**Comment by stffabi** [comment] 2018-11-21 06:57
We are seeing the same behaviour on different machines in our company. I'll try to test dlv from the command line later this day.

**Comment by virtuald** [comment] 2018-11-21 20:53
I'm seeing the same issue, on `go version go1.10.4 darwin/amd64`

```
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
```

**Comment by virtuald** [comment] 2018-11-21 20:56
Is there a way to easily obtain the commandline that vscode is providing to dlv? That seems like it would be useful.

**Comment by ramya-rao-a** [comment] 2018-11-22 02:37
@virtuald Of course. I just added a note on it at https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#try-using-dlv-from-the-terminalcommand-line

**Comment by stffabi** [comment] 2018-11-22 10:11
@ramya-rao-a I've tried running dlv from the command line. An attach from vscode to the running dlv leads to the same behaviour. Stepping into/out goes into proc.go `gopark`. Furthermore I've now even seen some assembler files popup during the debugging.

**Comment by ramya-rao-a** [comment] 2018-11-29 06:37
@stffabi I didn't mean attaching vscode to a running dlv instance. I meant using the dlv client directly. Run `dlv debug` on the folder that has your file. That will open an interactive session where you can add break points, step into/over code using [commands](https://github.com/derekparker/delve/tree/master/Documentation/cli)

**Comment by anphung** [comment] 2018-12-03 15:08
Same here, and it's very slow for it to Step into/over, or showing Variables in the debug tab.
I try with using `dlv debug`, and use interactive session `b`, `c`, `n`, it's quite fast there.
```
$ go version
go version go1.11 darwin/amd64
$ dlv version
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c
$ code --version
1.29.1
bc24f98b5f70467bc689abf41cc5550ca637088e
x64
```

**Comment by anphung** [comment] 2018-12-03 16:15
Inspecting the `vscode-go-debug.txt` from the debug, `global vars` request is huge for me, I guess thats the reason. Is there anyway to disable global vars?

**Comment by anphung** [comment] 2018-12-03 18:41
It's both. Actually, it jumps into proc.go for around several seconds (the time varies). If just wait for several seconds then it'll jump back to the next line that it supposed to jump in the first place.
I guess it jumps like that because of the slowness, and the slowness is because of loading all global vars.

**Comment by ramya-rao-a** [comment] 2018-12-03 19:11
> Inspecting the vscode-go-debug.txt from the debug, global vars request is huge for me, I guess thats the reason. Is there anyway to disable global vars?

Thats an interesting find. There is no official way to disable global vars, but can you try the below

- Open the file `~/.vscode/extensions/ms-vscode.go-0.7.0/out/src/debugAdapter/goDebug.js`. If you are using Insiders then use `.vscode-insiders`. If you are not on the latest version of VS Code (0.7.0), then use the appropriate version
- Find the function `getPackageInfo`, and add `return Promise.resolve(null);` to the first line inside the function. This will return null for package and consequently the `global vars` call will not be made.

Check if this solves the problem of slowness

**Comment by anphung** [comment] 2018-12-03 19:46
That's faster. It still jumps into proc.go sometime, but jumps out immediately (not several seconds anymore).

**Comment by anphung** [comment] 2018-12-04 09:08
Digging a little deeper, most responses from delve are too much for vscode-go, such as `ListGoroutines`, `StackTraceRequest`, it takes lots of bandwidth, hence the slowness.

**Comment by ramya-rao-a** [comment] 2018-12-05 18:11
Is this only with certain code bases or even a simple hello world program? If you can provide a sample code that I can try this on, I can look deeper into what is causing the slowness as well as the jump to proc.go

> I try with using dlv debug, and use interactive session b, c, n, it's quite fast there.

@anphung When you used `dlv debug`, did you see the jump to proc.go there as well?

**Comment by anphung** [comment] 2018-12-05 18:56
With `dlv debug`, the speed is just like "native", no proc.go jump, pretty fast.
With vscode, in normal code base, sometime it stops in `proc.go` for long, some time several seconds, it's up to whether I'm running some other heavy programs in my machine.

Delve RPCs give out much information, in exchange vscode only uses part of it. For example, [ListGoroutines](https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L777-L782), vscode only extract id, function name from `goroutines`.

I guess vscode can't do much here, unless people build a more lightweight RPCs in `delve` project.

Here is a sample: Set breakpoint at line 17, if you can't see the slowness, try increase `n`.
https://play.golang.org/p/Vyc1IkvlRHF

**Comment by ramya-rao-a** [comment] 2018-12-06 05:46
Thanks @mxxcx and @anphung 

@derekparker, @aarzilli Any thoughts on this?

**Comment by aarzilli** [comment] 2018-12-06 10:10
A while ago we added two parameters to ListGoroutines that allow retrieving goroutines in smaller chunks (there is however a bug, see related PR).
Same PR will also improve the speed of Eval, ListLocalVars and ListFunctionArgs.
I think calling ListPackageVars at every step is probably a bad idea. If I were you I'd nix the globals view entirely (evaluating expressions is more useful anyway). An alternative is only showing variables for the current package, by calling `ListPackageVars(Filter="^[curpkg]")` (however vendored packages will be a pain).
I don't know why it's showing proc.go at every step, that looks more like a problem on your side.

**Comment by leesjensen** [comment] 2018-12-06 23:09
For me the debug performance is fine, but the constant flipping to proc.go is really annoying.

**Comment by ori-saporta83** [comment] 2018-12-12 12:45
I experience the exact same behavior with the debugger jumping to the function "gopark" in proc.go every step I make. 
Is there any estimation for a fix?

**Comment by mhr3** [comment] 2018-12-13 10:53
I can confirm the same jumping into `gopark`, in a codebase _not_ using go modules. Also the jump is super fast... but also super distracting.

**Comment by tcagan** [comment] 2018-12-13 13:43
I am experiencing the same behavior. 
The jump is sometimes very quick and sometimes slower. Quite a bad experience debugging now...

My setup:
Mac (High Sierra)
go version go1.10.2 darwin/amd64
VS Code Version 1.29.1 (1.29.1) bc24f98b5f70467bc689abf41cc5550ca637088e

If there's something I can do to help - let me know. It is really annoying :-|

**Comment by ramya-rao-a** [comment] 2018-12-13 17:41
I tried with older versions of the Go extension and I can still see the issue which tells me that this is not due to any recent changes in the extension.

If somebody here can try with older versions of dlv, then we can at least narrow down or eliminate recent changes to dlv as the reason.

**Comment by ramya-rao-a** [comment] 2018-12-18 21:47
cc @Microsoft/vscode-gophers

@mikecowgill The only side-effect is that you won't see any global variables when debugging which I believe is not that big of an issue. That may fix the slowness, but it doesn't fix the jump to proc.go issue for most people here

**Comment by stffabi** [comment] 2018-12-19 08:51
I've seen the problem on latest Go 1.11.x and latest dlv on MacOS X Mojave.

I've tried downgrading Go and/or dlv:
- Using Go1.11 and downgrading dlv to the first version which supports Go1.11 didn't solve the problem.
- Downgrading Go to 1.10.x didn't solve the problem.
- Using Go1.10 and an old dlv version of February this year (https://github.com/derekparker/delve/commit/279a8a792e2748ba07be9ca15688d1871c0f1a5f) didn't solve the problem.

The next thing I've tried was downgrading the vscode-go extension, unfortunately my experience wasn't the same as yours @ramya-rao-a . All results with Go1.11.4 and dlv master:
- 0.6.75: Fast debugging experience, no jumps to gopark
- 0.6.87: Fast debugging experience, no jumps to gopark
- 0.6.88: Fast debugging experience, no jumps to gopark
- 0.6.89: Slow debug experience, jumps to gopark
- 0.6.90: Slow debug experience, jumps to gopark

@ramya-rao-a your workaround of adding `return Promise.resolve(null);` to `getPackageInfo` seems to fix the problem of slow debugging and the jumps to gopark at least for me.

**Comment by seanstrickland-wf** [comment] 2018-12-21 21:32
I've also been having this issue for a month or so and @ramya-rao-a's workaround addressed the slowness and jumping issues for me.

**Comment by segevfiner** [comment] 2018-12-24 00:05
This is happening for me on both Windows 10, and macOS 10.14. All it takes for me is to debug the following code, breaking on the `Println` line, and than constantly running "step over":
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	for {
		fmt.Println("Hello, World!")
		time.Sleep(2 * time.Second)
	}
}
```

The trigger for this seems to be new Goroutines opening, and VS Code deciding to open them expanded in the call stack view. But I think the issue is triggered by simply having more than one call stack expanded in call stack view.

I  think this is happening due to a bug in the debug adapter implementation, from the [Debug Adapter Protocol Specification](https://microsoft.github.io/debug-adapter-protocol/specification#Types_StackFrame):
```ts
interface StackFrame {
  /**
   * An identifier for the stack frame. It must be unique across all threads. This id can be used to retrieve the scopes of the frame with the 'scopesRequest' or to restart the execution of a stackframe.
   */
  id: number;

  // <snip>
}
```

But the code does this: https://github.com/Microsoft/vscode-go/blob/0ee759fd87cd0a44287e7a3a4dd081dde111cfb3/src/debugAdapter/goDebug.ts#L804-L813

The stack frame ID is merely the 0-based index of the frame in the thread, and not unique across all threads, as required by the protocol. This probably messes up VS Code manifesting as this bug.

@ramya-rao-a

**Comment by segevfiner** [comment] 2018-12-24 09:10
I wrote a possible fix for the `gopark` jumping: #2207. Feel free to test the fix and comment if it works for you.

**Comment by davidxu2018** [comment] 2018-12-24 12:14
@segevfiner i think you fixed this bug, it's ok. thanks

**Comment by egorse** [comment] 2018-12-30 21:19
@segevfiner seems works better than before. but during couple of runs at least once it still hit gopark.

**Comment by ramya-rao-a** [comment] 2018-12-31 05:43
@stffabi Using 
https://play.golang.org/p/nYkRp-yG1aK and 0.6.88 version of the extension, I still see the jump.

**Comment by segevfiner** [comment] 2018-12-31 06:52
It seems that the extension is responsible for providing a log of the adapter protocol (VS Code doesn't supply a mechanism to log on its side)

Maybe we should integrate [LoggingDebugSession](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/adapter/src/loggingDebugSession.ts) from the adapter module so that we can produce such a log which might help reveal the cause, if it's in the debug adapter that is.

**Comment by segevfiner** [comment] 2018-12-31 21:32
@ramya-rao-a It got auto closed by GitHub. This should be reopened.

**Comment by ramya-rao-a** [comment] 2018-12-31 22:00
@segevfiner The master branch now uses the LoggingDebugSession.

**Comment by segevfiner** [comment] 2019-01-01 13:43
With the more verbose logging, it seems that the trigger for this is a `scopes` request on the currently debugged thread taking a long time, and while it's still not finished (The response is sent) a `next` (or `step`, etc.) request and response goes through. Immediately after that VS Code shifts it's focus to the next thread (You see a `stacktrace` request for it), and the next time you do `next`/`step`/`etc.` the focus will jump to that thread. I wonder if this is a bug in VS Code itself...

(The `scopes` request is the one that does the large local/global variables query that is slow)

**Comment by segevfiner** [comment] 2019-01-01 18:58
Debugging VS Code a bit, it seems to me we are hitting this line in VS Code: [vscode/src/vs/workbench/parts/debug/electron-browser/debugService.ts:496](https://github.com/Microsoft/vscode/blob/77eb4b7ad1a2a694d2402742f3deb0022b52b611/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L496) and that call to `focusStackFrame` is selecting to focus some other thread than the one currently being debugged, and that thread is, more often than not, stopped on `gopark`.

We really shouldn't be reaching a code path where VS Code selects some arbitrary thread to focus, that seems like a bug in VS Code.

The code there is a bit weird too, like [vscode/src/vs/workbench/parts/debug/electron-browser/debugService.ts:773](https://github.com/Microsoft/vscode/blob/77eb4b7ad1a2a694d2402742f3deb0022b52b611/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L773) with that `shift`... selecting the *second* stopped thread...? 😕

**Comment by ramya-rao-a** [comment] 2019-01-02 07:49
All,

I have added a new property `showGlobalVariables` to the debug configuration which will control the showing of the global variables. It is `false` by default. Try the latest [beta version](
https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension to get the fix. This reverts the feature introduced in 0.6.89.

@aarzilli We already pass the current package as filter when calling `ListPackageVars`

@segevfiner Great insights!
Can you log an issue in the VS Code repo for your findings? Mention me there and I can rope in the right people who can help us. Log the issue with enough details so that we don't have to point folks back to this issue.

**Comment by joegilley** [comment] 2019-01-27 03:18
before @ramya-rao-a 's beta (v0.8.0), I experienced this issue (slow-down and proc jumping between steps).  I also noticed that while experiencing the slowdown, the `dlv` process was churning through system memory, at one point asking for 11GB at 100% CPU util.  I was able to **mitigate** the problem by changing the dlv configuration to ask for very small inspection limits:
```
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 2,   // <--
            "maxStringLen": 64,
            "maxArrayValues": 64,
            "maxStructFields": 2       // <--
        }
```
but that made the inspection useless 😞 

then I reverted to API version 1:
```
"go.delveConfig": {
  "apiVersion": 1,
  ...
}
```
which fixed it entirely, but was less than ideal.

The beta fixed the issue *entirely* for me.  I've reverted to the default `go.delveConfig` settings and it still flies.  <3 <3 @ramya-rao-a

**Comment by ramya-rao-a** [comment] 2019-01-31 18:17
Hello again!

Turns out we didnt really turn the `showGlobalVariables` feature back on in the beta version 0.8.1-beta.10 :(

So folks (@joegilley, @anphung, @tcagan, @mikecowgill, @stffabi, @seanstrickland-wf, @egorse ), who saw the slowness and then saw the slowness go away (either with the beta version, or by using the workaround I mentioned in https://github.com/Microsoft/vscode-go/issues/2133#issuecomment-443832073), can you please update to the [latest beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (the version should be 0.8.1-beta.11) and let me know if you still see the slowness?

I really need this feedback before releasing the next update, so thanks a ton in advance!

**Comment by stffabi** [comment] 2019-02-04 12:19
@ramya-rao-a I've just tried 0.8.1-beta.12 with vscode insiders. The jumps to proc.go have gone 🎉 , that's awesome...

Regarding the slowness, I think it has gotten faster, but it's still slower than before `0.6.89`. Disabling the global variables with `showGlobalVariables` works like a charm and the debugging is fast as with older versions.

**Comment by ramya-rao-a** [comment] 2019-02-04 16:37
> Regarding the slowness, I think it has gotten faster, but it's still slower than before 0.6.89. Disabling the global variables with showGlobalVariables works like a charm and the debugging is fast as with older versions.

Thanks for that feedback @stffabi!
If any of the others (@joegilley, @anphung, @tcagan, @mikecowgill, @seanstrickland-wf, @egorse ) can confirm the same, then I will go ahead disable the `showGlobalVariables` feature by default

**Comment by jhendrixMSFT** [comment] 2019-02-04 16:43
If there's a repro available that demonstrates the slowness it would help, maybe there's a better way we can implement this feature.

**Comment by mxxcx** [comment] 2019-02-07 14:38
@ramya-rao-a I just got the new update, and yes it is slower with global variables ON, I had it off, using the workaround you posted with return null, you can see bellow, it can take up to 1 second to step over, and those are simple if statements in a big codebase albeit. 

https://gyazo.com/b24bebc3b90c48b2ffd1f8e70fd501cf

**Comment by ramya-rao-a** [comment] 2019-02-07 18:23
@mxxcx 
Did you get the update for both VS Code (1.31) and the Go extension (0.9.1)?
If you are on the latest Go extension, then instead of the workaround that changes the code, you can add `"showGlobalVariables": false` in your debug configuration.

**Comment by mxxcx** [comment] 2019-02-07 18:35
@ramya-rao-a yes, got the update for both, hence it overwrite the workaround I did when you initially posted it, thanks for the config tip. No proc.go btw, so I guess this can be closed.

**Comment by ramya-rao-a** [comment] 2019-02-07 19:43
Thanks @mxxcx!

Conclusion:
- The jump to `proc.go` is fixed in VS Code. Get the latest version of 1.31
- The slowness is fixed in the latest version of the Go extension (0.9.1). If you still see slowness, then add `"showGlobalVariables": "false"` in your debug configuration

**Closed by ramya-rao-a** 2019-02-07 19:43 UTC
Labels: debug, under-discussion
