### ISSUE TITLE
[Feature Request] Shortcut to run current file

### ISSUE THREAD

**Issue by kokizzu** [Microsoft/vscode-go#244] opened 2016-03-15 00:47 UTC
There's a need to `go run` current file.

**Comment by lukehoban** [comment] 2016-03-24 00:09
Agreed.  I'm hoping we can do that as part of https://github.com/Microsoft/vscode-go/pull/134 or building upon that.  We need all of `build`, `install`, `run` and `generate`.

**Comment by ironcladlou** [comment] 2016-04-09 21:34
Dupe of https://github.com/Microsoft/vscode-go/issues/73

**Comment by ironcladlou** [comment] 2016-04-09 21:34
Close enough to a dupe, at least.

**Closed** 2016-04-09 21:48 UTC

**Comment by ramya-rao-a** [comment] 2017-01-11 20:44
@kokizzu As mentioned in https://github.com/Microsoft/vscode-go/issues/73#issuecomment-270196488 you can use the debugging feature to launch current package. As long as the `program` property in the launch.config points to your package, using `F5` will run your package.
