### ISSUE TITLE
Autocomplete does not provide completions for function parameters

### ISSUE THREAD

**Issue by dppascual** [microsoft/vscode-go#3037] opened 2020-02-10 21:30 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.13.6 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.42.0`
- Check your installed extensions to get the version of the VS Code Go extension 
	- `0.13.0`
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- `darwin amd64`

### Share the Go related settings you have added/edited

```
// Golang Settings
    "go.lintTool": "golint",
    "go.goroot": "/usr/local/go",
    "go.gopath": "/Users/${HOME}/go",
 
    "go.useLanguageServer": true,
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "gopls": {
        "usePlaceholders": false,    // add parameter placeholders when completing a function
        "completeUnimported": true, // autocomplete unimported packages
        "deepCompletion": true,     // enable deep completion
    },
    "go.languageServerFlags": [
        "-rpc.trace", // for more detailed debug logging
    ],
```

### Describe the bug

Not sure if it is a bug or a wrong configuration but I couldn't find any similar problem on the net to solve it. When I start typing a function parameter, visual code does not show any suggestion as can be shown in the following image.

<img width="646" alt="Screenshot 2020-02-10 at 21 54 05" src="https://user-images.githubusercontent.com/10468373/74191627-41048300-4c54-11ea-9499-276f3dfd4853.png">

It can be solved introducing manually the keyword shortcut `Ctrl + Space`, but it is a bit irritating to must to introduce this shortcut each time a function param is typed.

<img width="853" alt="Screenshot 2020-02-10 at 21 54 17" src="https://user-images.githubusercontent.com/10468373/74191635-4530a080-4c54-11ea-97b8-4e0ad0c6ead8.png">

How can I enable autocomplete in this situation? Or is it a expected behaviour?

**Comment by stamblerre** [comment] 2020-02-10 21:34
This sounds like a duplicate of https://github.com/microsoft/vscode-go/issues/3007. I'll send out a PR for this.

**Comment by stamblerre** [comment] 2020-02-11 02:15
Mailed https://github.com/microsoft/vscode-go/pull/3038. Going to close this issue as a duplicate.

**Comment by stamblerre** [comment] 2020-02-11 02:15
Duplicate of #3007

**Closed by stamblerre** 2020-02-11 02:15 UTC

**Comment by dppascual** [comment] 2020-02-13 12:00
Thanks for creating a PR 😊
