### ISSUE TITLE
Initial open of a file doesn't trigger a build.

### ISSUE THREAD

**Issue by newhook** [microsoft/vscode-go#118] opened 2015-11-28 14:38 UTC
It should.

**Comment by lukehoban** [comment] 2015-11-28 18:57
I almost made a change to do this, but then decided not to for now.

There's three things that could make sense:

1. Build when a new file is opened
2. Build when the active document in the editor changes
3. Build when Code initially opens with a `.go` file showing

I did make a change to do (3).  

For the first two, the one downside is that the previous set of errors gets cleared out when a new build is triggered.  Currently, that doesn't cause many issues, because it's only when an edit is actually made and a save triggered that build results update, which is infrequently enough and based on when there are changes that may necessitate a new error check.

If builds get triggered on opening a file, that means that something like go to defintion into library code will clear out the currently reported errors.  And if it's only on opening a new file, errors won't come back when you navigate back (until you edit/save).

The alternative would be to re-build whenever the active editor changes.  The build errors would change quite a lot, but at least the results would always (up to some slight delay) be up to date with the current file open in the editor.

Thoughts?

**Comment by newhook** [comment] 2015-11-28 18:59
It seems the issue here is really that we clear out all errors. Perhaps only the errors/warnings related to the current package should be cleared?

**Comment by lukehoban** [comment] 2015-11-28 19:04
That's an interesting idea. The challenge is making sure that errors are eventually removed. But j think if they get associated with the package and removed whenever that packages errors are updated that could well work. 

I'll look into that option.

**Comment by lukehoban** [comment] 2015-11-29 01:37
Here's one problem.

1. Make a change in `a.go` which causes an error in `b.go` (change the name of a declared function).
2. The error is reported against `b.go`.
3. Now undo the change in `a.go`.

The user wants the error to go away.  As far as I can tell, there is no way to ensure that happens without clearing out all the errors reported by the Go extension before computing and displaying the new errors, since there is no way to know which ones were caused by this file's compile.

**Comment by newhook** [comment] 2015-11-29 01:41
If its inside the same package I don't think there is a problem since you should clear the errors for the current package. However, I guess the real problem could be errors outside of the current package.

a/a.go
func Foo() { // Rename to foo.
}

b/b.go
...
a.Foo()

**Comment by lukehoban** [comment] 2015-11-29 01:51
That's a good point. 

And the way that we currently compute errors when saving a file is to do a build in it's package, so we don't produce errors for consumers in other packages anyway.

So maybe we can still do better than we do today on this.

**Comment by newhook** [comment] 2015-11-29 02:51
Unless the idea of a build scope is introduced I don't think there is much better that could be done.

**Comment by ironcladlou** [comment] 2016-02-20 21:57
The concept of a build scope that I believe supports what's being asked for comes implicitly with the introduction of `go install` (#134). One outstanding question I had in that PR was whether it makes sense to tie the `install` support into the diagnostics engine. I need to get back into the plugin code to understand more about how that could/should work. For example, does it make sense to use `install` *instead of* `build` if user has packages defined? Could they supplement one another?

My workflow to account for this is usually to use the package-scoped builds for my first pass and then use `go install` to check for inter-package breakages. It would be nice to unify the experience.

**Comment by yhuang0** [comment] 2017-09-02 16:11
It's been two years and we don't have any attempt to address this?

It seems go doesn't report all errors in a package so navigating to another file within the same package and running build doesn't give you much. But when navigating to a file in a different package you want to run build again because you want to see errors of the latter package, not the former one. In the case of tabbing through different files you may want to add a delay to not prematurely call build. So basically what this looks like:

OnNavigateToGoFile, reset timer -> set timer for 1 sec if new package -> call build on package

The config would look something like this:
go.buildOnOpen {
  scope: package,
  active: true,
  delay: 1sec
}

That should be doable for a first version, the next version you could probably add caching of errors by package. When you navigate to a different package you see the cached version of the errors but again after a certain delay you call build again so errors are updated.

**Comment by ramya-rao-a** [comment] 2019-07-06 20:28
When using the [language server](https://github.com/microsoft/vscode-go#go-language-server), build is run on each file that is opened.

Since adding this feature to the extension itself is not trivial, closing this issue in favor of the language server.

**Closed by ramya-rao-a** 2019-07-06 20:28 UTC
