### ISSUE TITLE
【Error: Error: Illegal value for `line`】 after "save all"

### ISSUE THREAD

**Issue by c633** [Microsoft/vscode-go#452] opened 2016-08-24 08:11 UTC
From @cjqpker:
- VSCode Version: Code 1.4.0
- OS Version: Darwin x64

Steps to Reproduce:
golang extention installed
1. Open a Golang project
2. Edit -> replace in Files ----> replace sth in more than one files
3. File -> save all ----> get a tip on top:【Error: Error: Illegal value for `line`】

Copied from the original issue (with more details): https://github.com/Microsoft/vscode/issues/10869

**Comment by ramya-rao-a** [comment] 2016-08-29 23:54
Seem to be connected to linting. When I set `go.lintOnSave` to false in User Settings, I don't see this anymore. @cjqpker @c633 : Can you confirm?

**Comment by Narven** [comment] 2016-08-31 13:44
I'm also having this issue, together with massive flickering of code... and the current line automatic trying to select one character at the time.

@ramya-rao-a the `go.lintOnSave: false` did not work.

**Comment by c633** [comment] 2016-09-01 03:40
@ramya-rao-a:
>  the go.lintOnSave: false did not work.

Same from me.

**Comment by ramya-rao-a** [comment] 2017-01-13 02:10
Sorry for the late response.

@Narven We now know that the behaviour you are seeing is usually caused by one of the other extensions interfering with the save process. If you are still seeing this issue, then can you try disabling other extensions that you may have and see if this still persists?

@c633 Can you try the same? i.e disable other extensions and see if you still see the issue?

**Comment by sebrandon1** [comment] 2017-01-24 17:19
I was hitting that error `【Error: Error: Illegal value for line】` until I updated my Go plugin in VSCode to 0.6.52.  Just throwing in my 2 cents.

**Comment by ramya-rao-a** [comment] 2017-01-24 18:14
@sebrandon1 I meant disable **other** extensions (not the Go extension) to eliminate the case of other extension interfering with the Go extension's save process :)

**Comment by ramya-rao-a** [comment] 2018-08-16 19:10
Closing this issue as it hasnt seen any recent activity

**Closed by ramya-rao-a** 2018-08-16 19:10 UTC
