### ISSUE TITLE
After Go code reformatter runs, the cursor jumps to the end of the file

### ISSUE THREAD

**Issue by sponeil** [Microsoft/vscode-go#2436] opened 2019-04-10 20:09 UTC
Issue Type: <b>Bug</b>

This was working great until I applied the VS Code 1.33 update, so I would like to report it on the VS Code side of the fence, but as I may not be able to reproduce it without the extension, it may be ignored if I do.

Anyway, it's amazing how frustrating this one is because I lose my place in the code almost every time I save (which I do often). I may hunt down a VS Code downgrade to apply.

Extension version: 0.9.2
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (4.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|70%|

</details>

**Comment by mkraft** [comment] 2019-04-10 21:26
I'm having this issue with almost every save. I've been using VSCode for many years and this is the first time I've considered changing editors. It's infuriatingly annoying.

Extension: 0.9.2
VSCode: Version 1.33.0 (1.33.0) 0dd516dd412d42323fc3464531b1c715d51c4c1a
OS: macOS 10.14.4 (18E226)

**Comment by mkraft** [comment] 2019-04-10 23:49
Duplicate report of https://github.com/Microsoft/vscode-go/issues/2426

**Comment by ramya-rao-a** [comment] 2019-04-11 15:32
Thanks @mkraft!

@sponeil This indeed is a duplicate of #2426 and is an upstream issue. Please see https://github.com/Microsoft/vscode-go/issues/2426#issuecomment-481922142 for the fix

**Closed by ramya-rao-a** 2019-04-11 15:32 UTC

**Comment by sponeil** [comment] 2019-04-11 16:59
Thanks, the quick replies are very much appreciated.
