### ISSUE TITLE
Error squigglies don't update after selecting item in completions list

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#560] opened 2016-10-26 20:00 UTC
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

Type the following, receive squigglies
![image](https://cloud.githubusercontent.com/assets/762848/19742863/bbf5a068-9b7b-11e6-92be-a908f4efe5e8.png)

With your cursor at the end of `println`, press ctrl+space, select Println
![image](https://cloud.githubusercontent.com/assets/762848/19742888/d3aa1388-9b7b-11e6-83e5-44da2c5bf66d.png)

Error squigglies don't update until the user saves
![image](https://cloud.githubusercontent.com/assets/762848/19742947/15ef5dfc-9b7c-11e6-851f-f563803a7f13.png)

**Comment by ramya-rao-a** [comment] 2016-10-28 21:43
Build is run on save. For save on type, you can set `files.autoSave` appropriately.

**Comment by ramya-rao-a** [comment] 2016-10-28 21:46
But what I feel you are alluding to is that there is an error, the tool suggests a way to correct it, user chooses the given option, tool should stop complaining.
I can see that happening in typescript

**Comment by ramya-rao-a** [comment] 2017-01-20 07:00
What is being suggested is from the auto-complete list. If this was a code-action, then the error squiggles should be expected to go away. In this case, one has to save to trigger build, to remove the errors. Closing as by design

**Closed by ramya-rao-a** 2017-01-20 07:00 UTC
Labels: enhancement
