### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Danceofdeath** [Microsoft/vscode-go#2463] opened 2019-04-24 03:42 UTC
- Issue Type: `Performance`
- Extension Name: `Go`
- Extension Version: `0.10.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Demmon\ms-vscode.Go-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ramya-rao-a** [comment] 2019-04-24 07:17
- Are you using Go modules?
- Can you share any Go related settings you may have?

If using Go modules and the language server, then can you try the steps at https://github.com/Microsoft/vscode-go/issues/2461#issuecomment-486097632 and see if that helps?

**Comment by Danceofdeath** [comment] 2019-04-24 08:24
{
    "go.formatTool": "goreturns",
    "editor.formatOnSave": true,
    "workbench.statusBar.feedback.visible": true,
    "[go]": {},
    "team.showWelcomeMessage": false,
    "go.gocodeAutoBuild": true,
    "breadcrumbs.enabled": true,
    "workbench.colorTheme": "Monokai",
    "go.lintFlags": [],
    "files.autoSave": "off",
    "go.useLanguageServer": true
}

**Comment by ramya-rao-a** [comment] 2019-04-24 21:17
Thanks @Danceofdeath 
Does https://github.com/Microsoft/vscode-go/issues/2461#issuecomment-486097632 help at all?

**Comment by Danceofdeath** [comment] 2019-04-25 01:57
No,i tried many ways, the plugins of go didn't work at all



------------------ Original ------------------

**Comment by Danceofdeath** [comment] 2019-04-25 02:00
By the way,it happens after i install a plugin called  gopel.




------------------ Original ------------------
From:  "太阳      "<1035153625@qq.com>;
Date:  Thu, Apr 25, 2019 09:57 AM
To:  "Microsoft/vscode-go"<reply@reply.github.com>;"Microsoft/vscode-go"<vscode-go@noreply.github.com>;
Cc:  "Mention"<mention@noreply.github.com>; 
Subject:  Re: [Microsoft/vscode-go] Extension causes high cpu load (#2463)



 



------------------ Original ------------------

**Comment by ramya-rao-a** [comment] 2019-04-25 03:37
You can disable the language server by setting `go.useLanguageServer` to `false` in your settings and reloading VS Code.
Does that help?

**Comment by ramya-rao-a** [comment] 2019-04-25 05:15
We have figured out the root cause for the high cpu usage and a fix has been made.
A new release (0.10.1) has just been published and it will have the fix to the issue.

Thanks a lot for reporting and your patience!

**Closed by ramya-rao-a** 2019-04-25 05:15 UTC
Labels: needs more info
