### ISSUE TITLE
"Error Prompt" doesn't work

### ISSUE THREAD

**Issue by normal-cock** [microsoft/vscode-go#3017] opened 2020-01-30 15:20 UTC
"Error Prompt" doesn't work. For example in the following code there isn't red underline under the 8's line where there is syntax error.

![image](https://user-images.githubusercontent.com/2618306/73462501-ded79280-43b6-11ea-9b60-3b110177264f.png)

* VSCode Version:1.41.1
* OS Version: Mac OS 10.15.2
* golang plugin: go 0.12.0

My `Settings(JSON)` is:
```python
{
    "window.zoomLevel": 0,
    "python.pythonPath": "/Users/dae/venv-python3/bin/python",
    "workbench.sideBar.location": "left",
    "files.eol": "\n",
    "workbench.tree.indent": 16,
    "workbench.colorTheme": "Monokai",
    "editor.fontSize": 14,
    "editor.scrollBeyondLastLine": false,
    "window.title": "${activeEditorFull}${separator}${rootName}",
    "editor.formatOnPaste": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.snippetSuggestions": "top",
    "explorer.confirmDragAndDrop": false,
    "go.formatTool": "goimports",
    "go.gocodeAutoBuild": false,
    "go.goroot": "/usr/local/go",
    "go.gopath": "/Users/dae/go",
    "powermode.enabled": true,
    "[markdown]": {
        "editor.defaultFormatter": "fcrespo82.markdown-table-formatter"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "files.exclude": {
        "**/.classpath": true,
        "**/.factorypath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/Frameworks/**": true,
        "**/node_modules": true,
        "/Applications/XCode.app": true
    },
    "java.errors.incompleteClasspath.severity": "ignore",
    "vsintellicode.python.completionsEnabled": false,
    "vsintellicode.typescript.completionsEnabled": false,
    "vsintellicode.java.completionsEnabled": false,
    "python.autoUpdateLanguageServer": false,
    "markdown-toc.depthTo": 3,
    "extensions.ignoreRecommendations": false,
    "search.followSymlinks": false,
    "markdown-table-formatter.markdownGrammarScopes": [
        "markdown",
        "diagram"
    ],
    "editor.copyWithSyntaxHighlighting": false,
    "C_Cpp.loggingLevel": "Debug",
    "C_Cpp.workspaceParsingPriority": "low",
    "search.exclude": {
        "**/Frameworks": true
    },
    "C_Cpp.exclusionPolicy": "checkFilesAndFolders",
    "gitlens.advanced.messages": {
        "suppressFileNotUnderSourceControlWarning": true
    },
    "go.useLanguageServer": true,
    "go.gotoSymbol.includeGoroot": true
}
```

**Comment by stamblerre** [comment] 2020-01-30 17:56
Can you share your `gopls` logs for this? Specifically, can you run `gopls -rpc.trace -v check path/to/file.go`?

**Comment by normal-cock** [comment] 2020-01-31 03:01
```
2020/01/31 11:00:48 Info:2020/01/31 11:00:48 Build info
----------
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.1.8-0.20200130002326-2f3ba24bd6e7 h1:xgunrWcYH8cy9t1I7Phk8YsN3aALl4mOjNK2Q4SOu9U=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200130002326-2f3ba24bd6e7 h1:EBZoQjiKKPaLbPrbpssUfuHtwM6KV/vb4U85g/cigFY=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=

Go info
-------
go version go1.13.5 darwin/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dae/Library/Caches/go-build"
GOENV="/Users/dae/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dae/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/dae/test_dir/test_go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r1/pc07ms_94wn1_b0smcnrfttw0000gn/T/go-build110219898=/tmp/go-build -gno-record-gcc-switches -fno-common"
2020/01/31 11:00:50 initial workspace load failed: internal error: go list gives conflicting information for package github.com/kardianos/govendor/internal/pathos
2020/01/31 11:00:50 Error:2020/01/31 11:00:50 initial workspace load failed: internal error: go list gives conflicting information for package github.com/kardianos/govendor/internal/pathos
2020/01/31 11:00:50 Info:2020/01/31 11:00:50 go/packages.Load
	snapshot = 0
	query = [./... builtin]
	packages = 0
2020/01/31 11:00:51 Info:2020/01/31 11:00:51 go/packages.Load
	snapshot = 1
	query = [file=/Users/dae/test_dir/test_go/main.go]
	packages = 1
2020/01/31 11:00:51 Info:2020/01/31 11:00:51 go/packages.Load
	snapshot = 1
	package = test_go
	files = [/Users/dae/test_dir/test_go/main.go]
/Users/dae/test_dir/test_go/main.go:8:6-7: c declared but not used
```

**Comment by stamblerre** [comment] 2020-01-31 05:33
Looks like this command does output the error, though it's possible something is going on with VS Code that it's not showing it. Please note the error message here though:

`go list gives conflicting information for package github.com/kardianos/govendor/internal/pathos`

Does this code compile?

**Comment by normal-cock** [comment] 2020-01-31 07:50
Yes, it does. It's just a single golang file.

The workspace directory structure is:
![image](https://user-images.githubusercontent.com/2618306/73521282-95338a00-4440-11ea-8e4c-19bc69e4e6b8.png)

And I've found out that when I open `test` directory in my workspace directly, "Error Prompt" works normally as the following image shows:
![image](https://user-images.githubusercontent.com/2618306/73521558-40dcda00-4441-11ea-90d3-c77fe0982992.png)

**Comment by hyangah** [comment] 2020-01-31 12:22
Indeed. I could reproduce the case with `v0.3.0-pre3` when the workspace directory doesn't contain any package.
```
$ tree
.
└── test
    └── main.go
$ code .
```
Here is the gopls log with more debug info.
[goplslog.txt](https://github.com/microsoft/vscode-go/files/4139211/goplslog.txt)

After I added a file in the top directory, the problem went away.

I don't understand the above load failure error (`github.com/kardianos/govendor/internal/pathos`) which may be other bugs (stale data cached somewhere?)

**Comment by stamblerre** [comment] 2020-01-31 21:26
Ah, yes that would happen if you have no `go.mod` file and are outside of `GOPATH` because we don't try to `go list` subdirectories (in case it ends up being too expensive). We should be able to "reclaim" the file though. I filed golang/go#36951.

**Comment by ramya-rao-a** [comment] 2020-02-01 06:50
Closing in favor of the upstream issue

@normal-cock Thanks for reporting! Please subscribe to https://github.com/golang/go/issues/36951 to follow the progress on gopls for this issue

**Closed by ramya-rao-a** 2020-02-01 06:50 UTC
Labels: upstream-gopls

**Comment by Wisgon** [comment] 2020-02-01 14:54
I got the same error, I found that if I set "go.languageServerExperimentalFeatures" {"diagnostics": false}，and ctrl+s to save, then the error shows again!

**Comment by stamblerre** [comment] 2020-02-02 02:30
That is because VS Code falls back to running `go build` on save if you disable diagnostics from the language server. This should only be an issue in this one specific case, and it can be easily worked around by opening the subdirectory. `gopls` should show diagnostics for other Go files outside of GOPATH or outside of a module, so if that's not working, please open a new issue [here](https://github.com/golang/go/issues/new).

**Comment by warent** [comment] 2020-02-16 10:01
I've encountered the same problem, working on a normal project outside of my GOPATH. It doesn't work even with a go.mod initialized. Setting
```
"go.languageServerExperimentalFeatures": {"diagnostics": false}
```
fixed it for me as well.

**Comment by warent** [comment] 2020-02-16 10:13
I encountered this issue in addition to a problem with modules not loading any autocomplete data and showing `invalid type`, even with go.mo defined. For anyone confused like me, @stamblerre means the problem is because your VS Code is open on a directory in which your go code is a subdirectory. The fix is to open the subdirectory that has your Go code so that it's the root directory.
