### ISSUE TITLE
Auto-complete fails if basename of import path doesn't match package name

### ISSUE THREAD

**Issue by kemitche** [Microsoft/vscode-go#378] opened 2016-07-08 16:03 UTC
For example, the package at github.com/fernet/fernet-go is imported (by default) as `fernet`. However, autocompletion doesn't find anything:

```
package main

import "github.com/fernet/fernet-go"

func main() {
	fernet.D // no auto-complete suggestions found
}
```

Manually naming the package `fernet` on import works:

```
package main

import fernet "github.com/fernet/fernet-go"

func main() {
	fernet.D // will begin to auto-complete
}
```

**Comment by lukehoban** [comment] 2016-07-23 23:16
I can't reproduce this for autocomplete - but I can reproduce it on hover over `DecodeKeys' for example (I don't see anything in the first case above, but do in the second).

`vscode-go` used `gocode` for autocomplete and `godef` for hover.  It looks like at least `godef` doesn't handle this kind of import correctly.  It's possible that `gocode` doesn't either in some cases, though I can't reproduce that with the latest `gocode`.

Unfortunately, there is nothing that `vscode-go` can do to fix this - it would need to be addressed in those other projects.

https://github.com/rogpeppe/godef
https://github.com/nsf/gocode

**Closed by lukehoban** 2016-07-23 23:16 UTC

**Comment by eosrei** [comment] 2016-07-24 20:07
Ah. Here is the problem: https://github.com/rogpeppe/godef/issues/40
