### ISSUE TITLE
There is no document formatter for 'go'-files installed

### ISSUE THREAD

**Issue by pmalekn** [Microsoft/vscode-go#2249] opened 2019-01-14 15:08 UTC
After launching vs code today I cannot get `go-langserver` to work correctly, meaning it is running but doesn't respond (?)/requests are not being sent. Formatting also doesn't work (like mentioned in the title), I get the following when I manually trigger `Format Document`:

```
There is no document formatter for 'go'-files installed.
```

`Log(Extension Host)` shows the following when I launch vs code: 

```
[2019-01-14 16:03:36.600] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.Go {"startup":false,"activationEvent":"onLanguage:go"}
[2019-01-14 16:03:36.600] [exthost] [info] ExtensionService#loadCommonJSModule /Users/pmalek/.vscode/extensions/ms-vscode.go-0.8.0/out/src/goMain
```

Whereas Developer Tools gives me this:

```
[ms-vscode.Go]Header must provide a Content-Length property.
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:42
t._doInvokeHandler @ rpcProtocol.ts:461
t._invokeHandler @ rpcProtocol.ts:446
t._receiveRequest @ rpcProtocol.ts:366
t._receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:171
e.fire @ event.ts:228
a @ ipc.net.ts:103
n._socketDataListener @ ipc.net.ts:132
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594

Error: Header must provide a Content-Length property.
	at StreamMessageReader.onData (/Users/pmalek/.vscode/extensions/ms-vscode.go-0.8.0/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
	at Socket.<anonymous> (/Users/pmalek/.vscode/extensions/ms-vscode.go-0.8.0/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

Originally posted here https://github.com/Microsoft/vscode/issues/66479

**Comment by jschank** [comment] 2019-01-15 19:06
I have this problem also. Just started today

**Comment by ramya-rao-a** [comment] 2019-01-20 21:07
Thanks for reporting.

This is a duplicate of #2252 and is due to an upstream bug in the language server from Sourcegraph. See https://github.com/sourcegraph/go-langserver/issues/356

For workaround, please see https://github.com/Microsoft/vscode-go/issues/2252#issuecomment-455902293

**Closed by ramya-rao-a** 2019-01-20 21:07 UTC

**Comment by chrismwendt** [comment] 2019-01-22 17:42
My apologies, I accidentally introduced this bug in https://github.com/sourcegraph/go-langserver/commit/8c25906a7dbc904acc96b5435ec42fa5da8b232c

This has been fixed in https://github.com/sourcegraph/go-langserver/commit/267fa34a98ba30e53d228500831b6db37883c199
