### ISSUE TITLE
When hitting Stop during Debug, it does not kill debug process

### ISSUE THREAD

**Issue by kisPocok** [Microsoft/vscode-go#834] opened 2017-03-03 15:45 UTC
"debug" process is not being killed after Stop button is pressed. I have to kill it manually.

vscode 1.10.1
go extension 0.6.54
macOS 10.12.3

Reference https://github.com/Microsoft/vscode-go/issues/438

**Comment by fasa123** [comment] 2017-03-03 17:15
Same problem here (on Linux).  
I assume it stems from having multiple goroutines being executed (a server running) and as thus a simple SIGTERM is not enough. 

Just force close the process by sending a SIGKILL. 

If you are debugging your application and are clicking on the Close button the expected behaviour should be a SIGKILL (-9) and not a SIGTERM (-15).

**Comment by fasa123** [comment] 2017-03-03 18:55
So turns out bash/sh cannot parse the file because of Windows line endings (it uses CRLF). Just change the line endings to LF and it works perfectly again on Linux (and should as well on Mac obviously). 

One thing I'd love to know is why a Linux specific file has Windows specific formatting.

**Comment by ramya-rao-a** [comment] 2017-03-04 00:04
This should be fixed with the latest version 0.6.55

**Closed by ramya-rao-a** 2017-03-04 00:04 UTC
Labels: debug

**Comment by kisPocok** [comment] 2017-03-04 00:15
"Eureka, it works" :)
