### ISSUE TITLE
Plugin regularly loses autocompletion

### ISSUE THREAD

**Issue by peterbourgon** [Microsoft/vscode-go#344] opened 2016-05-28 15:03 UTC
In the last few weeks, when I'm in long coding sessions, I find that I lose all autocompletion, beyond the (what I assume is automatic) lexicographical autocomplete based on current file content. Restarting VSCode always fixes it — for awhile.

I realize this isn't much to go on. Perhaps you can recommend something I can do when it happens again to get more information?

**Comment by lukehoban** [comment] 2016-05-28 15:20
Could you try running `Developer: Toggle Developer Tools` and then looking at the Console tab to see if there are any errors being reported?

**Comment by peterbourgon** [comment] 2016-05-28 15:47
The only error that pops up is 

```
params[i].trim is not a function: TypeError: params[i].trim is not a function
    at /Users/peter/.vscode/extensions/lukehoban.Go-0.6.39/out/src/goSuggest.js:91:63
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
 ```

but it happens when I'm still typing the letters, rather than when I hit the dot and expect the dropdown.

[Here's a video](https://dl.dropboxusercontent.com/u/1061416/behavior.mov), if it helps.

**Comment by peterbourgon** [comment] 2016-05-28 15:52
And [here's a video of me restarting and getting it working again](https://dl.dropboxusercontent.com/u/1061416/working.mov). (It crashed when I quit, that isn't normal, maybe has to do with developer tools being opened?) You can see after I restart that error doesn't pop up anymore, so maybe it is related!

**Comment by lukehoban** [comment] 2016-05-29 22:35
Okay - that helps.

For now, you could try turning off `useCodeSnippetsOnFunctionSuggest`.  The problem is ultimately happening in handing that feature.  I'm still not sure the root cause here, but we can at least add some more safeguards to that feature.

The next time you see completion lists go away, it would be really interesting to know what what API you were trying to get completion on if you can catch it.

**Comment by peterbourgon** [comment] 2016-05-30 19:11
This is pretty thin evidence, because it's possible it was broken before — but I _just_ had it happen when I imported a new package and gave it an alias, e.g.

```
import (
    "fmt"
    httptransport "github.com/go-kit/kit/transport/http" // <-- typed this line
)

func foo() {
    httptransport. // failed
}
```

**Comment by eosrei** [comment] 2016-07-23 07:30
@peterbourgon Same here. Package aliases break autocomplete consistently.

**Comment by eosrei** [comment] 2016-07-24 20:10
Relevant: https://github.com/nsf/gocode/issues/233

**Comment by ramya-rao-a** [comment] 2016-10-31 19:01
autocomplete works for me on packages with alias. 
@peterbourgon @eosrei Do you still see issues?

**Comment by eosrei** [comment] 2016-10-31 21:28
@ramya-rao-a Yes. I'll see about making a test case.

**Comment by ramya-rao-a** [comment] 2017-01-13 00:37
@peterbourgon @eosrei Any updates?

**Comment by peterbourgon** [comment] 2017-01-13 12:59
I haven't noticed this in the past few months. I've just tried exactly the steps I gave above and failed to reproduce. So I guess something got fixed in the interim. Thanks for the followup! I'll let you close the issue if you think it's OK.

**Comment by ramya-rao-a** [comment] 2017-01-13 18:34
Thanks @peterbourgon I'll close this issue.
@eosrei If this still occurs, please drop a note.

**Closed by ramya-rao-a** 2017-01-13 18:34 UTC
