### ISSUE TITLE
New code disappears on save in Go after debugging when using the language server

### ISSUE THREAD

**Issue by freekot** [microsoft/vscode-go#2787] opened 2019-09-24 17:19 UTC
Issue Type: <b>Bug</b>

After the last update ...
In Go

After debug mode was used. If any code is changed, the changes disappear on  Save. At the bottom of the file the last few lines are duplicated. The workaround is to quit and restart. Then editing and saving is Ok. Disabling format on save has no effect.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
go-coverage-viewer|def|1.0.3
vscode-todo-plus|fab|4.14.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.9.34911
cpptools|ms-|0.25.1
Go|ms-|0.11.6
java|red|0.49.0
vscode-yaml|red|0.5.3
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.19.0
vscode-spring-initializr|vsc|0.4.6
vscode-todo-highlight|way|1.0.4
linecount|yyc|0.1.7

</details>

**Comment by lemorian** [comment] 2019-09-26 20:12
I have been having the same issue as well, did downgrading the plugin to a older version help?
I didn't help me.

**Comment by freekot** [comment] 2019-09-27 01:17
I tried downgrading, reinstalled VS Code, reinstalled Go. Downgraded. Reinstalled. Changed settings on formatting. Turned off language server. turn it on. Did something else in random order. Today it seems to behave well. Yesterday I left completely unable to save any new modifications to my code.
One other symptom ...
On Save the new lines that I create just disappear. The same number of lines at the bottom of the file get duplicated.

**Comment by stamblerre** [comment] 2019-10-03 22:36
Can you share your VSCode settings? Are you using the language server?

**Comment by ramya-rao-a** [comment] 2019-10-04 06:09
Please share the Go related settings you might have added/edited so that we can determine if you are using the language server or not. You can get them by running the command Preferences: Open Settings(JSON)

**Comment by rzauls** [comment] 2019-10-04 07:09
I'm having the same issue, adding code and saving, causes the new code to disappear, also some weird artifacts appear at the end of the line. The language server is enabled.

About VS Code:
```
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```
settings json (only the relevant/semi-relevant)
```
{
    "git.confirmSync": false,
    "editor.formatOnSave": true,
    "go.autocompleteUnimportedPackages": true,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "extensions.ignoreRecommendations": false,
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
}
```

**Comment by digdiver** [comment] 2019-10-04 07:25
The problem is same: "On Save the new lines that I create just disappear. The same number of lines at the bottom of the file get duplicated."
```
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.3.9600
```
settings json
```
{
    "diffEditor.renderSideBySide": true,
    "git.enableSmartCommit": true,
    "go.formatTool": "gofmt",
    "go.useLanguageServer": true,
    "[go]": {
        
    }
}
```

Extensions:
```
Name: GitHub Pull Requests
Id: github.vscode-pull-request-github
Description: Pull Request Provider for GitHub
Version: 0.11.2
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
```

```
Name: Go
Id: ms-vscode.go
Description: Rich Go language support for Visual Studio Code
Version: 0.11.7
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go
```

**Comment by jpvillaseca** [comment] 2019-10-08 17:05
It also happened to me, the only solution is to restart vscode.
It happened with and without the language server. This is my current config
`	"go.inferGopath": true,
	"go.useLanguageServer": true,
	"go.formatTool": "gofmt",
	"go.languageServerExperimentalFeatures": {
		"format": false,
		"autoComplete": true,
		"rename": true,
		"goToDefinition": true,
		"hover": true,
		"signatureHelp": true,
		"goToTypeDefinition": true,
		"goToImplementation": true,
		"documentSymbols": true,
		"workspaceSymbols": true,
		"findReferences": true,
		"diagnostics": true,
		"documentLink": true
	},`

**Comment by stamblerre** [comment] 2019-10-17 16:19
Enough people have reported this issue that I have started a thread in the Go issue tracker. Please follow the suggestions here: https://github.com/golang/go/issues/34955. Hopefully we'll be able to track this down. Thank you!

**Comment by ramya-rao-a** [comment] 2019-10-17 16:27
@jpvillaseca You mention that you see this even without the language server. Can you confirm this by
- disabling language server `"go.useLanguageServer": false`
- reload vs code window
- try again

**Comment by ramya-rao-a** [comment] 2019-10-17 16:27
Closing this issue in favor of the upstream issue for gopls https://github.com/golang/go/issues/34955
If anyone sees this even when not using the language server, please log a new issue

**Closed** 2019-10-24 16:30 UTC
Labels: needs more info, upstream-gopls
