### ISSUE TITLE
no definitions for builtin.go functions

### ISSUE THREAD

**Issue by yaronsumel** [Microsoft/vscode-go#674] opened 2016-12-02 09:05 UTC
go to definition/peek (F12/ALT F12) not working on any builtin (src/builtin/builtin.go) functions ie. make/new/cap/len/append..

**Comment by ramya-rao-a** [comment] 2016-12-02 16:19
Can you try adding this setting? `"go.docsTool": "gogetdoc"` 
And then reload the VS Code window.

**Comment by yaronsumel** [comment] 2016-12-03 08:26
@ramya-rao-a with ` "go.docsTool": "gogetdoc" ` I'm not getting any definition.

**Comment by ramya-rao-a** [comment] 2016-12-04 01:14
@zmb3 Below is the output of `gogetdoc` on the built-in function `append`. Note that the `pos` is missing. Is this a known issue in `gogetdoc` ?

```
{
"name":"append",
"import":"builtin",
"decl":"func append(slice []Type, elems ...Type) []Type",
"doc":"The append built-in function appends elements to the end of a slice. If\nit has sufficient capacity, the destination is resliced to accommodate the\nnew elements. If it does not, a new underlying array will be allocated.\nAppend returns the updated slice. It is therefore necessary to store the\nresult of append, often in the variable holding the slice itself:\n\tslice = append(slice, elem1, elem2)\n\tslice = append(slice, anotherSlice...)\nAs a special case, it is legal to append a string to a byte slice, like this:\n\tslice = append([]byte(\"hello \"), \"world\"...)\n",
"pos":""
}
```

**Comment by zmb3** [comment] 2016-12-04 01:30
@ramya-rao-a it is known, but I wouldn't call it in issue.  This has been reported before: https://github.com/zmb3/gogetdoc/issues/19

Builtins are special - they are implemented in the compiler/runtime and are not ordinary Go functions.  There is no definition to go - they might even be implemented by multiple functions.

This isn't unique to `gogetdoc` - try `godef`:

```
$ godef -f main.go -o 3087 -a -json
{}
```

**Comment by ramya-rao-a** [comment] 2016-12-04 08:18
Thanks a lot for the clarification @zmb3
@yaronsumel, closing this as by design

**Closed by ramya-rao-a** 2016-12-04 08:18 UTC
Labels: upstream

**Comment by yaronsumel** [comment] 2016-12-05 04:03
hey @ramya-rao-a @zmb3 . actually in [go-lang-idea-plugin](https://github.com/go-lang-plugin-org/go-lang-idea-plugin) they sending the user to this file. anyway i cant even see the completion for builtin functions.

**Comment by ramya-rao-a** [comment] 2016-12-05 09:19
Do you see anything on hover for the builtin functions? I am able to get info on hover as well as completion. Does completion work otherwise for rest of your code?

**Comment by yaronsumel** [comment] 2016-12-05 09:55
@ramya-rao-a  nothing on hover for builtin (godoc and gogetdoc). completion works fine.

**Comment by ramya-rao-a** [comment] 2016-12-06 02:25
Do you see any errors in the console? Run `Developer: Toggle Developer Tools` to see the console.
