### ISSUE TITLE
"Restart language server" fails with "Cannot read property 'clear' of undefined"

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode-go#2928] opened 2019-12-05 17:45 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.13.4 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.40.2`
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.11.9
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- `darwin amd64`

### Share the Go related settings you have added/edited

```
  "go.autocompleteUnimportedPackages": true,
  "go.enableCodeLens": {
    "references": false,
    "runtest": false
  },
  "go.lintTool": "golangci-lint",
  "go.lintFlags": [
    "--disable=megacheck",
    "--disable=goimports",
    "--disable=typecheck",
    "--disable=maligned",
    "--disable=depguard",
    "--disable=lll",
    "--disable=nakedret",
    "--exclude=\\.nolint\\.go",
    "--tests"
  ],
  "go.vetOnSave": "off",
  "go.useCodeSnippetsOnFunctionSuggest": true,
  "go.goroot": "/usr/local/opt/go/libexec",
  "go.testFlags": [
    "-v"
  ],
  "go.gopath": "/Users/alex/.go",
  "go.coverOnTestPackage": false,
  "go.gotoSymbol.includeGoroot": true,
  "go.gotoSymbol.includeImports": true,
  "go.formatTool": "goimports",
  "[go]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    },
    "editor.codeActionsOnSaveTimeout": 5000,
    "editor.defaultFormatter": "ms-vscode.Go"
  },
  "go.useLanguageServer": true,
  "go.languageServerExperimentalFeatures": {
    "format": true
  },
  "go.languageServerFlags": [
    "-rpc.trace"
  ],
```

### Describe the bug

I've been having trouble with some `gopls` versions crashing (e.g. `e140590b`). I downgraded to `73c7173a` and killed `gopls`. But `gopls` did not start again on its own. So I ran `Go: Restart language server`, which failed with `Cannot read property 'clear' of undefined"`:

![Screen Shot 2019-12-05 at 12 37 36](https://user-images.githubusercontent.com/50314/70259641-95731a00-175c-11ea-8477-806052092de8.jpg)

Nothing appears in any log.

### Steps to reproduce the behavior:

Not sure if easily reproducible.

**Comment by stamblerre** [comment] 2019-12-05 20:33
I think this probably caused by [goLanguageServer.ts:248](https://github.com/microsoft/vscode-go/blob/4060ab19ee93156a6706ae5a11b1be12feddcd6b/src/goLanguageServer.ts#L248). Will add a fix when I get a chance. Thanks for the report!

**Comment by ramya-rao-a** [comment] 2019-12-10 05:57
I have pushed a [fix](https://github.com/microsoft/vscode-go/commit/05d741b9076d6ad1530625a6857bd54a27563ed3) for this that should be available in the[ latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension

@stamblerre Is https://github.com/microsoft/vscode-go/commit/05d741b9076d6ad1530625a6857bd54a27563ed3 what you had in mind?

**Comment by stamblerre** [comment] 2019-12-10 17:43
Yes - thank you for doing that @ramya-rao-a!

**Comment by oneslash** [comment] 2020-01-07 12:47
not reproducing anymore can we close the issue?

**Closed** 2020-02-19 00:19 UTC
Labels: bug
