### ISSUE TITLE
autocomplete pops up shell on forefront

### ISSUE THREAD

**Issue by karimelm** [Microsoft/vscode-go#262] opened 2016-03-23 11:17 UTC
When typing some letters, autocomplete kicks in and starts up go.exe in a command shell on the forefront, hindering typing in the editor for a fraction of a second, with every new word or after every space.
Sometimes, when typing fast multiple or even dozens of windows pop up. 
Vscode-go isn't really usable because of this. I'm not sure when this problem occurred but its present on multiple machines for me (windows 10). This is also the first time I've encountered this issue.

*In mac OS X everything works as expected

**Comment by lukehoban** [comment] 2016-03-23 22:26
I can't reproduce this on either of my Windows 10 machines.

Can you provide any details about your environment?  Versions of VS Code, gocode, vscode-go, etc.  Any non-standard shells installed (Cygwin, etc.)?

Closing for now but reopen with more details if you have them.

**Closed by lukehoban** 2016-03-23 22:27 UTC

**Comment by karimelm** [comment] 2016-03-23 22:58
Hey thanks for responding.

 

Vscode 0.10.11

Vscode-go 0.6.27, updated just now to .34 issue persists

Golang 1.6

No cygwin/other shells besides powershell/cmd

Reinstalled vscode, didn’t matter

 

Just tried: If I manually run gocode -s and then startup vscode, the command window doesn’t appear and autocomplete works as expected.

**Comment by lukehoban** [comment] 2016-03-24 00:06
Odd - I can't imagine why that would solve the problem.  I tried a few more things to reproduce based on that, but couldn't come up with anything.  Glad you found a workaround though.

**Comment by groseb** [comment] 2016-11-16 08:49
Hi,
I had the exact same issue and found this which solved it : 

> Windows users should consider doing this instead:
> 
> go get -u -ldflags -H=windowsgui github.com/nsf/gocode
> 
> That way on the Windows OS gocode will be built as a GUI application and doing so solves hanging window issues with some of the editors.

From https://github.com/nsf/gocode#setup

**Comment by ihrankouski** [comment] 2017-04-23 09:54
Same issue:
- Win 8.1
- VS Code 1.11.2
- go version go1.8.1 windows/amd64
- babun version 1.2.0

Tried `go get -u -ldflags -H=windowsgui github.com/nsf/gocode`, also tried `gocode -s` but still annoying console window appears :'(

**Comment by karimelm** [comment] 2017-04-23 10:05
Off the top of my head, this had something to do with gocode or one of those helper/formatting programs. Try deleting gocode from $GOHOME/bin and reinstalling with go get, solved the problem for me on another install.

**Comment by ihrankouski** [comment] 2017-04-23 10:08
Tried many times :)
I've just found a setting "go.gocodeAutoBuild" which if set to "false" somehow solves my issue...
