### ISSUE TITLE
golang os.Open fails in VSCode, but works from command line

### ISSUE THREAD

**Issue by npollitt** [microsoft/vscode-go#2939] opened 2019-12-10 23:30 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
go version go1.13.4 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
1.40.2
f359dd69833dd8800b54d458f6d37ab7c78df520
x64
- Check your installed extensions to get the version of the VS Code Go extension 
Name: Go
Id: ms-vscode.go
Description: Rich Go language support for Visual Studio Code
Version: 0.11.9
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
darwin
amd64

(macOS Catalina, 10.15.2)

### Share the Go related settings you have added/edited
{
    "go.goroot": "/usr/local/go",
    "go.gopath": "/Users/npollitt/source/go",
    "window.zoomLevel": 0,
    "editor.minimap.enabled": false,
    "breadcrumbs.enabled": true
}

### Describe the bug
os.Open(path) fails in debugger, but works on command line.

### Steps to reproduce the behavior:
1. I have an application that calls os.Open(path)
2. In VSCode, when I debug the application, os.Open() always fails with ENOENT - file not found.
3. When I compile and run the command from a terminal, the file is found and successfully opened.
4. I am using absolute path to eliminate issues with CWD (although CWD is correctly set for relative path).

**Comment by ramya-rao-a** [comment] 2019-12-11 05:57
- Does `os.Open()` work as expected when you debug your program using delve directly from the terminal? 
- Can you share the debug configuration you are using along with a small code snippet that we can use to replicate the problem?

**Comment by npollitt** [comment] 2019-12-11 18:31
When running with delve, the `os.Open()` call works as expected - file found, opened, no error.  `dlv debug package/path/to/vtr -- -f /absolute/path/to/file.json`

For debug info, you mean launch.json?
`
{
            "name": "Debug VTR",
            "mode": "debug",
            "program": "${workspaceFolder}/cmd/vtr",
            "cwd": "${workspaceFolder}",
            "showLog": true,
            "type": "go",
            "request": "launch",
            "env": {
                "ENV1": "value1",
                "ENV2": "value2",
            },
            "args" : [ 
                "-f /absolute/path/to/file.json"
            ]
        }
`

Code snippet, minus surrounding context:
`
	file, err := os.Open(path)
	if err != nil {
		log.Errorf("Error opening file: %s", err)
		file.Close()
		return err
	}
`

The `Open(path)` call successfully finds and opens the file when running on command line and when debugging with delve.  It only fails in the GUI.

FWIW: this is on macOS, so does this have something to do with new security measures?

**Comment by ramya-rao-a** [comment] 2019-12-12 00:25
Thanks for the details @npollitt 

@quoctruong Can you take a look at this?

**Comment by npollitt** [comment] 2020-01-08 22:24
Should this be assigned to someone?  Looks like nothing is happening.

**Comment by stamblerre** [comment] 2020-06-06 00:08
I am not able to reproduce this issue with the code sample/`launch.json` provided on Mac OS. Because we are migrating to a [new repository](https://github.com/golang/vscode-go) (https://github.com/microsoft/vscode-go/issues/3247), I am going to go ahead and close this issue.

@npollitt: If you are still encountering this problem, please create a public GitHub repository with your repro case and create a new issue in https://github.com/golang/vscode-go.

**Closed by stamblerre** 2020-06-06 00:08 UTC
Labels: debug
