### ISSUE TITLE
go 1.13 and testing

### ISSUE THREAD

**Issue by mwat56** [microsoft/vscode-go#2734] opened 2019-09-05 18:45 UTC
I upgraded from 1.12 to go 1.13 today. Now I can't properly test my project anymore. Regardless whether I test a single function, run file tests, or run package tests I get output like this:

    Running tool: /usr/local/bin/go test -timeout 30s github.com/mwat56/kaliber -coverprofile=/tmp/vscode-goJh8DXF/go-code-cover
    
    flag provided but not defined: -test.coverprofile
    
     Usage: /tmp/go-build388798247/b001/kaliber.test [OPTIONS]
    …

The last (`Usage …`) line comes from my program's flag handling. The `/tmp/…` is basically `os.Args[0]`.
So far I saw `-test.testlogfile`, `-test.timeout`, `-test.run`, `-coverprofile` mentioned in an error.
Trying to define those flags in my program only worked for the first two, while the latter two (quite illogically) resulted in another error:

    Running tool: /usr/local/bin/go test -timeout 30s github.com/mwat56/kaliber -coverprofile=/tmp/vscode-goJh8DXF/go-code-cover

    /tmp/go-build077616426/b001/kaliber.test flag redefined: test.coverprofile
    panic: /tmp/go-build077616426/b001/kaliber.test flag redefined: test.coverprofile

    goroutine 1 [running]:
    …

The same with `-test.run`. – In other words, not defining those flags causes an error and defining them causes an error as well.

I didn't do any code changes in my program since yesterday (when it compiled and tested w/o problems with go 1.12), so I am quite at a loss here.

Any ideas?

**Comment by mwat56** [comment] 2019-09-05 19:44
> I upgraded from 1.12 to go 1.13 today. Now I can't properly test my project anymore.
> …
> Any ideas?

I just found something interesting. In one of the project's files there's an `init()` function which calls the function that initialises the commandline flags:


    func init() {
    	initArguments()
    }

If I comment out `initArguments()` there are no testing errors as described above, and even the `debug test` option works as expected. What change in go 1.13 might be responsible? Everything worked fine with at least go 1.11 and 1.12.

**Comment by ramya-rao-a** [comment] 2019-09-08 01:27
@mwat56 Do you see the same errors when you try to run the test from a terminal using `go test -timeout 30s github.com/mwat56/kaliber -coverprofile=/tmp/vscode-goJh8DXF/go-code-cover`?

If so, then this would be a problem with Go itself and not the extension and I would suggest to log this issue in the Go issue tracker

**Comment by markphelps** [comment] 2019-09-08 18:19
I just ran across a similar issue and found this issue while Googling. I think the reason is that now go 1.13 has it's [own init function ](https://golang.org/pkg/testing/#Init) which register the common `test.X` flags. 

I think what is happening is that if you define your own `init` function then Go's `testing.Init` does not get called.

To verify this I added this line in my tests:

```
func init() {
	testing.Init() // add this line
	flag.BoolVar(&debug, "debug", false, "enable debug logging")
	flag.Parse()
}
```

And my tests passed under go 1.13. 

If I comment out that line then I get an error similar to yours:

```
flag provided but not defined: -test.v
Usage of /var/folders/2j/6kvcssmd1fv4rx5dm29t46f00000gn/T/go-build950179137/b290/storage.test:
```

I also found this in the [release notes](https://golang.org/doc/go1.13#testing): 

> Testing flags are now registered in the new Init function, which is invoked by the generated main function for the test. As a result, testing flags are now only registered when running a test binary, and packages that call flag.Parse during package initialization may cause tests to fail.

What's unfortunate is that this means that tests passing in 1.12 may not pass in 1.13 as you mentioned, and since `testing.Init` was added in 1.13, then it seems you may have to guard the call to `testing.Init` with build flags to get it to be backwards compatible.

**Comment by mwat56** [comment] 2019-09-08 18:41
> @mwat56 Do you see the same errors when you try to run the test from a terminal using `go test -timeout 30s github.com/mwat56/kaliber -coverprofile=/tmp/vscode-goJh8DXF/go-code-cover`?

@ramya-rao-a Thank you for that tip!

> If so, then this would be a problem with Go itself and not the extension and I would suggest to log this issue in the Go issue tracker

Indeed, the same problem. As @markphelps mentioned as well, this new behaviour seems to be a consequence of changes in Go itself. Thanks for looking into it!

**Comment by markphelps** [comment] 2019-09-08 18:43
Also just found this issue that seems to have a lot of discussion around this: https://github.com/golang/go/issues/31859

You may be able to just remove `flag.Parse` in your `init()` function as it seems that the generated test code that go generates may call it for you

**Comment by mwat56** [comment] 2019-09-08 19:42
@markphelps 
> You may be able to just remove `flag.Parse` in your `init()` function and instead call `flag.Parse` in a `TestMain`. This would prevent you from having to do the build tag dance I mentioned above.

Unfortunately that won't be possible: The file with the commandline flags needs to parse/validate them (and merge them with values from config files) and setup other parts of the program with those values. All that is supposed to be done _before_ `main()` is run.

For the time being I've added `testing.Init()` in my `init()` function before my own flag handling gets started. So far it seems to work: the problems mentioned in my initial post don't come up but real test failures are shown and after fixing them a `Success: Tests passed` is shown.

I just wish this (i.e. the workaround) would have been mentioned in the release notes, not just a

> "packages that call flag.Parse during package initialization may cause tests to fail" …

**Comment by ramya-rao-a** [comment] 2019-09-09 01:46
Thanks for sharing more context on this @markphelps!

I am closing this issue as it has been concluded that the problem is due to the changes in Go 1.13

**Closed by ramya-rao-a** 2019-09-09 01:46 UTC
Labels: needs more info

**Comment by mwat56** [comment] 2019-09-09 10:42
@markphelps 
> [...] you may have to guard the call to `testing.Init` with build tags to get it to be backwards compatible.

Can you give me an example how to do that?

**Comment by mwat56** [comment] 2019-09-09 10:48
@mwat56 
> For the time being I've added `testing.Init()` in my `init()` function before my own flag handling gets started.

As it turns out that is not a good idea after all: if the program gets called with `-help` all the testing flags are mixed into the program's own flags, which is rather confusing for the unsuspecting user.

Is there a way to figure out at runtime whether the program is running in a testing environment or "normally"?

**Comment by markphelps** [comment] 2019-09-09 13:22
> @markphelps
> 
> > [...] you may have to guard the call to `testing.Init` with build tags to get it to be backwards compatible.
> 
> Can you give me an example how to do that?

@mwat56 yeah, here's something I did in a personal project: https://github.com/markphelps/flipt/pull/129/commits/cd7fb4957955dd1763bcf6ca6dd4e60fba6bfc60#diff-77b87a2786da4b38e7dd9d4fd463953c

I created 2 files, one `storage/init_go113_test.go` that has the build tag:

```
// +build go1.13
```

This means it will be built with all versions of Go that support 1.13, basically 1.13+

Then I created another file `storage/init_test.go` that has the build tag:

```
// +build !go1.13
```

Which means it will be built for all versions of Go that don't support 1.13, so anything < 1.13

Hope that helps

**Comment by tevin-morake** [comment] 2019-10-23 08:34
> I just ran across a similar issue and found this issue while Googling. I think the reason is that now go 1.13 has it's [own init function ](https://golang.org/pkg/testing/#Init) which register the common `test.X` flags.
> 
> I think what is happening is that if you define your own `init` function then Go's `testing.Init` does not get called.
> 
> To verify this I added this line in my tests:
> 
> ```
> func init() {
> 	testing.Init() // add this line
> 	flag.BoolVar(&debug, "debug", false, "enable debug logging")
> 	flag.Parse()
> }
> ```
> 
> And my tests passed under go 1.13.
> 
> If I comment out that line then I get an error similar to yours:
> 
> ```
> flag provided but not defined: -test.v
> Usage of /var/folders/2j/6kvcssmd1fv4rx5dm29t46f00000gn/T/go-build950179137/b290/storage.test:
> ```
> 
> I also found this in the [release notes](https://golang.org/doc/go1.13#testing):
> 
> > Testing flags are now registered in the new Init function, which is invoked by the generated main function for the test. As a result, testing flags are now only registered when running a test binary, and packages that call flag.Parse during package initialization may cause tests to fail.
> 
> What's unfortunate is that this means that tests passing in 1.12 may not pass in 1.13 as you mentioned, and since `testing.Init` was added in 1.13, then it seems you may have to guard the call to `testing.Init` with build tags to get it to be backwards compatible.

Thank you. This has helped me greatly
