### ISSUE TITLE
Visual Studio Code freezes while browsing code.

### ISSUE THREAD

**Issue by abhishekkrm** [microsoft/vscode-go#3189] opened 2020-04-17 20:09 UTC
Issue Type: <b>Bug</b>

The system was fine, but last few days its freezing a lot while browsing and editing the file.
MAC OS : 
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76

VSCODE:
 1.44.2

VSCODE-GO:
0.14.1

Extension version: 0.14.1
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|64, 25, 10|
|Memory (System)|16.00GB (4.86GB free)|
|Process Argv|-psn_0_118813|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by hyangah** [comment] 2020-04-17 20:17
Can you please run `Preferences: Open Settings (JSON)` command to open your settings.json file and share all the settings with the `go.` or `["go"]` prefixes? 

And, did you experience the same issue when using the go extension 0.13.x ? (You can test and downgrade the extension version from the extension view -> click the gear button for the Go extension -> choose "Install Another Version.." )

**Comment by abhishekkrm** [comment] 2020-04-17 21:13
@hyangah  Thank for the information
I don't see any go specific settings.
<img width="637" alt="OpenSettings" src="https://user-images.githubusercontent.com/9190889/79614565-9fffd180-80b5-11ea-8e03-530d6b7319ea.png">

{
    "window.zoomLevel": -1,
}


I reverted it to 0.13.0 so far no issue will update here if observe hang/freeze again.

**Comment by stamblerre** [comment] 2020-04-19 17:18
This sounds like https://github.com/microsoft/vscode-go/issues/3178, so maybe you can try the temporary workaround that @hyangah suggested there - adding `"[go]": { "editor.codeLens": false }` to your settings.

**Comment by stamblerre** [comment] 2020-04-20 21:14
Duplicate of #3178

**Comment by stamblerre** [comment] 2020-04-20 21:14
Let's continue the discussion on #3178.

**Closed by stamblerre** 2020-04-20 21:14 UTC
Labels: needs-investigation
