### ISSUE TITLE
Infinite Saving 'get_ads_for_aparat.go': Getting code actions from ''Go', 'Go'' 

### ISSUE THREAD

**Issue by EmadHelmi** [microsoft/vscode-go#3162] opened 2020-04-08 08:11 UTC
- Run `go version` to get version of Go
	- go version go1.14.1 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.43.2
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- Linux
        - amd64

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
        - "go.formatTool": "gofmt",
        - "go.buildOnSave": "off",
        - "go.useLanguageServer": true

### Describe the bug
I have two projects in gopath dir (`/home/emadhelmi/go`).

1. One of them located in `/home/emadhelmi/go/src/xxx/yyy/zzz`
2. And the other one located in `/home/emadhelmi/go/src/xxx/yyy/ttt/www`
The first one is totally good, and when I save any file in that project it saves very fast. But in the second one when I save a file It takes long time to save the file and it freeze on the `Saving 'get_ads_for_aparat.go': Getting code actions from ''Go', 'Go'' ` message appeared in the bottom of the vscode
I check my both projects for local settings, but there is no such a file and all go settings are the one that I mentioned above.
Also I off the `build on save` feature but the bug still exists.

This is the image of the message in my vscode

https://imgur.com/9pnxs2W

**Comment by stamblerre** [comment] 2020-04-10 16:29
What other extensions do you have installed? Do you have the Go Group Imports extension installed by any chance?

If not, can you please share the output of `gopls -rpc.trace -v check path/to/file.go` for the file that's causing problems?

**Comment by stamblerre** [comment] 2020-04-10 16:31
Ah, I see that you've also filed #3161 for a similar issue. As @hyangah said, the two do sound like the same issue. I'll close this as a duplicate and we can continue discussion there.

**Comment by stamblerre** [comment] 2020-04-10 16:31
Duplicate of #3161

**Closed by stamblerre** 2020-04-10 16:31 UTC
Labels: needs more info
