### ISSUE TITLE
Possible to complete function parenthesis?

### ISSUE THREAD

**Issue by polds** [Microsoft/vscode-go#158] opened 2015-12-16 00:19 UTC
I'm wondering if I'm missing a setting somewhere, the code complete works great as I'm typing along something like `fmt.Printf` I can see the context menu telling me `Printf` takes an `format string, a...interface{}`, but when I hit tab Code only completes `fmt.Printf` and not `fmt.Printf()` or even better `fmt.Printf(format, ...)`

So question is: Is there a setting to either enable closing of parenthesis when you complete and/or give better insights as to what that function takes argument wise?

**Comment by lukehoban** [comment] 2015-12-16 04:02
I think this is a dupe of #128. Which we plan to address via #9.  I'm hoping we'll be able to get that feature in fairly soon.

Note that this is stylistically a little different than Sublime, but more inline with what Code does elsewhere.  My sense is that if we have #9 then it won't feel like there's a missing feature here.

If you think there's something beyond that that should be tracked though - feel free to reopen.

**Closed by lukehoban** 2015-12-16 04:02 UTC
