### ISSUE TITLE
Files stay in modified state after save when using modules and gopls

### ISSUE THREAD

**Issue by jose-sanchezm** [microsoft/vscode-go#2501] opened 2019-05-07 13:13 UTC
Environment:

Ubuntu 19.04 with Go 1.12

How to reproduce:

1. Set the GO111MODULE=on environment variable
2. Open a clean version of Visual Studio Code and install the Go extension.
3. Open a Go project in GOPATH that uses modules
4. Open a .go file in the project
5. The go extension will prompt you to install gopls. Install it.
6. Restart VS
7. Open the same file as in step 4.
8. Modify and save the file

Expected output
 
The file is formatted and saved and the modified status dissapears from the file name

Actual results

The file is saved but immediately it shows itself in the modified status again.

**Comment by hmalphettes** [comment] 2019-05-07 15:21
@jose-sanchezm I can reproduce the same behavior on the insiders build of the 5th of May and the vscode-go-0.10-beta2.

Once I moved my project out of the GOPATH things behaved as expected.

Here is a related report of what combination of GO111MODULE and GOPATH works and does not: https://github.com/microsoft/vscode-go/issues/2488#issuecomment-489556809

I hope this helps!

**Comment by jose-sanchezm** [comment] 2019-05-07 15:37
Thanks. After setting it off and moving it outside GOPATH now it behaves correctly. Nevertheless, it's still a bug since having the GO111MODULE set to on and a project in GOPATH should work as expected.

**Comment by hmalphettes** [comment] 2019-05-08 01:06
@jose-sanchezm I appreciate you filed it separately and clearly. I am definitely looking forward for a resolution too.

**Comment by jose-sanchezm** [comment] 2019-05-09 11:21
It seems that it happens sometimes (but quite less often) even in a project outside of GOPATH without the GO111MODULE variable set.

**Comment by stamblerre** [comment] 2019-05-10 22:43
By modified status, you mean the dot at the top of the file to indicate that it is unsaved? Can you share your VSCode settings?

**Comment by ChrisHines** [comment] 2019-05-11 15:09
I am also seeing this behavior on a project I have outside GOPATH.

gopls setting:
```
	// go
	"go.useLanguageServer": true,
	"go.languageServerExperimentalFeatures": {
		"diagnostics": true // for diagnostics as you type
	},
	"[go]": {
		"editor.snippetSuggestions": "none",
		"editor.formatOnSave": true,
		"editor.codeActionsOnSave": {
			"source.organizeImports": true
		},
	},
	"gopls": {
		"usePlaceholders": true, // add parameter placeholders when completing a function
		"enhancedHover": true, // experimental to improve quality of hover (will be on by default soon)
	},
```

Here is another clue. This happens for me on Windows. **If I switch the line endings on the file to only LF, the problem goes away. If I switch back to CRLF, it comes back.** (BTW, Gopls seems to be much less stable, much slower, and consumes much more memory than on the Mac I use it on for other projects.)

**Comment by stamblerre** [comment] 2019-05-13 15:01
Thanks for the information. We haven't been testing `gopls` on Windows much, so it's very helpful for us to get this feedback. I opened https://github.com/golang/go/issues/32001 to track investigations into problems on Windows.

**Comment by stamblerre** [comment] 2019-05-20 22:51
After some discussion on https://github.com/golang/go/issues/31937, we've suggested that `gopls` users used LF line endings (add the setting `"files.eol": "\n"` to your VSCode settings).

**Comment by Helcaraxan** [comment] 2019-06-12 23:10
I am currently stumbling on this issue, or something that looks extremely similar, as well and it's currently making my use of VSCode + `gopls` nearly impossible on Windows. Am also using it on OSX and Linux and no issues there (love the combo and have been cheering along as I see things improve week-by-week over the past few months ❤️ ).

For the record, my configuration:
```json
// Place your settings in this file to overwrite the default settings
{
    "files.eol": "\n",

    "go.toolsGopath": "<redacted>",

    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "diagnostics": true
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "gopls": {
        "usePlaceholders": true
    },

    "go.lintTool": "golangci-lint",
    "go.lintOnSave": "package",

    "go.vetOnSave": "off",
}
```

Please note that I am indeed setting the `"files.eol": "\n"` as suggested. This is with Go 1.12.5 in a project that is a Go module and which is not located on the `GOPATH`. The `GO111MODULE` variable is not set. Additionally, given that this was before linked to line-endings I'll also add that I am using Git Bash as my terminal and it is set to checkout-Windows-style / commit-Unix-style with respect to line-endings.

Last but not least I have been closely following `master` on golang/tools and am rebuilding a fresh `gopls` once or twice a week. I have observed the behaviour I relate below for the past ~2 weeks. My data does not go back before that as I had a hiatus in my Windows usage before that and only used Linux / OSX for a while.

My observations:
1. Making changes to a file, saving them, tend to work normally for a while.
2. After some time, or rather in the middle of a non-specific series of edits to my file that along the way pass through some dirty states (lots of type errors, syntax errors) the `gopls` server seems to give up from time-to-time: either crash-looping or it simply stops updating VSCode with annotations, etc.
3. When I then try to save the file I actually observe the file content reverting to the state of the file approximately (or quite likely, exactly) corresponding to the moment where `gopls` gave up. In other words it throws away all my edits since that previous point.
4. An `Undo` does (fortunately) get me my changes back but the file is obviously again in a modified state again. Trying to save again simply repeats the behaviour of point 3.
5. Usually reloading the VSCode window (which also reboots `gopls`), after presenting me again with the modified buffer but now a functional `gopls` server then allows me to successfully save the file with my modifications. I do however have now also observed (just today) cases where even a VSCode window reload does not allow the save to be successful as I still continue to loop through points 3. and 4. stated above.
6. In this final case the only thing that has managed to get me out of it is to temporarily set `"go.useLanguageServer": false` in my configs, reload the window again and then save.

I understand that is likely not enough data on this to diagnose the exact issue but I'd rather share it and then provide you with any elements you deem necessary. So just let me know what you need.

From my own analysis of the behaviour I see this might correspond to two separate issues:
- The fact that `gopls` just gives up at some point / dies / stalls. Given it's early / pre-stable state that's not a shocker, and I am not too fussed about it, but it's still worth noting that this seems to contribute to the observed behaviour. I am also seeing such regular `gopls` failures on OSX / Linux albeit without the same side-effect in VSCode.
- The fact that VSCode, once it loses `gopls`, no longer seems to want to record any subsequent changes when saving to disc but rather keeps writing the state of the file that was ACKed by `gopls`.

**Comment by linguohua** [comment] 2019-06-13 14:31
@Helcaraxan Hi, when you saving file, can you see that gopls uses high cpu and memory? If it is, maybe this is the reason of the problem. In my scenario, I found that the func 'shortestEditSequence' in diff.go cost so much cpu and memory, and I replace the 'Operations' function implement in diff.go with my simplest one, and now it cost less cpu and memory, gopls can response quickly to vscode. 
I know this is not the final solution, but maybe it can help to find out the problem.

```
// Operations returns the list of operations to convert a into b, consolidating
// operations for multiple lines and not including equal lines.
func Operations(a, b []string) []*Op {
	//trace, offset := shortestEditSequence(a, b)
	//snakes := backtrack(trace, len(a), len(b), offset)

	// M, N := len(a), len(b)
	M := len(a)
	var i int
	solution := make([]*Op, len(a)+len(b))

	aIdx := 0
	for bIdx, bcontent := range b {
		// if not the same, find out the same line of a
		if ( aIdx < M && bcontent != a[aIdx]) {
			prv := aIdx

			// find the same line from a
			for ; aIdx < M; aIdx++ {
				if bcontent == a[aIdx] {
					break
				}
			}

			// delete [prv:aIdx] from a
			op1 := &Op{}
			op1.Kind = Delete
			op1.I1 = prv
			op1.I2 = aIdx

			solution[i] = op1
			i++
		}

		if (aIdx >= M) {
			// insert all remain lines of b into a
			op2 := &Op{}
			op2.Kind = Insert
			op2.I1 = bIdx
			op2.I2 = bIdx
			op2.J1 = bIdx
			op2.Content = b[bIdx:]

			solution[i] = op2
			i++

			break
		}

		aIdx++
	}
	return solution[:i]
}
```

**Comment by stamblerre** [comment] 2019-06-13 14:38
@Helcaraxan: Thanks for the detailed report. I'm surprised to hear that VSCode has problems once `gopls` dies, though I think that's something @ramya-rao-a may know more about.
`gopls` has definitely been unstable, particularly earlier this week. Can you try updating to the most recent version and confirm that this is still happening for you? Things should have stabilized since Monday.

**Comment by Helcaraxan** [comment] 2019-06-13 16:31
Hello @stamblerre. With regards to `gopls` stability I had noticed the instability (cf. the above reported need to reload my VSCode window in order to save the file after getting stuck. That had actually prompted me to refetch master Tuesday or Wednesday evening (can't remember).

It's only once I had done that and rebuilt that I had the most severe issue (point 6 of my report) occurring for the first time. However I don't think it's possible to assert with authority that that rebuild was the trigger of those severe cases, I might just have been lucky before the upgrade and did not run into it them yet.

I'll need to check my Windows laptop tonight to get you the exact hash of golang/tools that I am currently using. Same with regards to the CPU usage question @linguohua. I'll post an update in a few hours once I get home.

**Comment by Helcaraxan** [comment] 2019-06-13 22:53
So I was able to check the various points that were raised:

- The `gopls` I am using was built from golang/tools@59534d075a876675ef41a20fd596536cfa103662.
- I was able to reproduce the issue in its most severe form at the very first try and I didn't even need to make any significant changes to my code before it was triggered, barely a few lines.
- From the CPU perspective there does seem to be something moderately interesting. After I hit save and the file is reverted to the unwanted earlier state - in this case the version of the file in which I opened it - the `gopls.exe` process has a noticeable spike in its CPU usage (5 - 10%) and it lasts for 10 to 15 seconds before it goes down to 0 again (left-most CPU spike on the screenshot below). If undo the revert and save again I can reproduce the spike (second CPU spike on the screenshot) as well as the problematic behaviour.

![image](https://user-images.githubusercontent.com/896592/59471668-a38e5080-8e33-11e9-87ad-3a18a8992b2d.png)

- After updating to the most recent golang/tools@ed0dc450797fdfbe6a9ee6bf3381a02099b897f9 I was still able to reproduce the issue.
- Before and after the update there was definitely something off in `gopls` as auto-completion was showing very strange behaviour. The screenshot below was taken after I closed VSCode entirely, restarted it and loaded a clean and syntactically correct file before making the edits on the line shown.
![image](https://user-images.githubusercontent.com/896592/59472301-d46f8500-8e35-11e9-87c3-4c752a42e672.png)

**Comment by linguohua** [comment] 2019-06-14 23:19
@Helcaraxan Hi, as I can see it from your post images, the line feet style you use is still '\r\n', you can see it in the right bottom status bar in vscode. Maybe you should change it to LF '\n' style. This is because 'goimports' format code with '\n' line feet, then the origin content will different with fomartted one, only because the line feet, and this is the worst case for ''shortestEditSequence who use MYERS algorithm.
Another thing is 'shortestEditSequence' has redundant memory allocate and copy operations,  see this unmerged yet pull  request here:https://github.com/golang/tools/pull/120/commits/13162aa1e88ff272738c6a6675010edd2140c8a4

**Comment by Helcaraxan** [comment] 2019-06-15 18:46
Good spot @linguohua. I had blindly trusted me setting
```json
{
  "files.eol": "\n",
}
```
in my configuration file but I apparently also had to wrangle my git settings to use
```ini
[core]
  eol = lf
  autocrlf = input
  safecrlf = true
```
After that a wipe of my repo and a new fresh clone VSCode now does detect the files with `LF` style.

----

**However** this does not appear to have solved the failure-to-save issues that I have been encountering. They are now occurring in a near deterministic fashion (which is good for debuggability but unfortunate if I want to do any productive work 😥 ).

I did have some time today so I dug into the `gopls` trace logs to find out what was exactly going on. I am attaching [the full log](https://github.com/microsoft/vscode-go/files/3293432/gopls_rpclog.txt).

It was generated while running `gopls` built from golang/tools@5aca471b1d59ca42d39ca6419e64061391b9a6ad. The entire session corresponds to the following actions starting with VSCode non running.
1. Opening VSCode on a previously opened project with a single file open containing no linting, formatting or other errors.
2. Removal of a `Less` method at the end of the file. This should result in the receiving type no longer being `sort.Sort()`able higher-up in the file. However no error gets highlighted at this point in my editor, despite clearly having introduced one.
3. Saving the file. This reverts the file to contain the removed function.

When looking at the RPC log file I can indeed clearly distinguish:
- The server being started and capabilities being negociated (*expected*).
- The file being opened and parsed by the server, followed by the expected responses with symbols, package links & co as well as an empty diagnostics array (*expected*).
- The file modification being received by the server but the response again contains an empty diagnostics array (**unexpected**).
- Import organisation is triggered (and some light formatting with it) which tells to reintroduce the now missing empty-line at the end of the file (*expected*).
- The file being saved with the expected content with no `Less` function (*expected*).
- A formatting response being returned by the server which tells to re-instate the removed function (**unexpected**)
- The server receiving a new "textDocument/hasChanged" RPC with the now modified state corresponding to the reverted state of the document (**unexpected**).

As highlighted above there are some unexpected responses from the server and it looks to me like those are sufficient by themselves to explain everything that I am observing. This would mean that this might be entirely contained within the `gopls` remit. If you agree with my assessment @stamblerre I'll create an issue in [golang/go](https://github.com/golang/go) with a digest of the information.

**Comment by stamblerre** [comment] 2019-06-28 18:16
@Helcaraxan: Can you try to repro on the latest version of `gopls` (`go get -u golang.org/x/tools/gopls@master`)? We have recently made a number of improvements that may have solved this issue.

**Comment by Helcaraxan** [comment] 2019-06-28 19:33
@stamblerre just tried it out and I have indeed been unable to reproduce the previously observed behaviour. 👍 Thank you very much for the heads-up, happy again to see the progress of `gopls` over time!

**Comment by stamblerre** [comment] 2019-06-28 20:17
Glad to hear it! Thanks for letting me know.

**Comment by ramya-rao-a** [comment] 2019-06-29 01:09
Thanks @Helcaraxan and @stamblerre for the detailed follow ups.
I will close this issue for now.

Workarounds:
- https://github.com/microsoft/vscode-go/issues/2501#issuecomment-494177715
- Update to the latest version of `gopls`

If the issue still persists, please log a bug in https://github.com/golang/go

**Closed by ramya-rao-a** 2019-06-29 01:09 UTC
Labels: go-modules, under-discussion, upstream-gopls
