### ISSUE TITLE
Extension host log errors when using gopls

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode-go#2919] opened 2019-11-27 18:15 UTC
I'm getting this in the extension log constantly:

```
[2019-11-27 11:30:52.705] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-11-27 11:30:52.705] [exthost] [error] Error: selectionRange must be contained in fullRange
	at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:365:679)
	at new w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:365:547)
	at new w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:354:169)
	at asDocumentSymbol (/Users/alex/.vscode/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/protocolConverter.js:396:22)
	at asDocumentSymbol (/Users/alex/.vscode/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/protocolConverter.js:400:31)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (/Users/alex/.vscode/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/protocolConverter.js:393:23)
	at /Users/alex/.vscode/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/client.js:1002:62
```

It's not connected to any problems I'm having, but I thought I should report it.

Latest VScode with extension version 0.11.9, gopls `c1736c0f`, [settings.json](https://gist.github.com/atombender/da8f3722b9504b0cd694e2065f0712d9).

**Comment by stamblerre** [comment] 2019-11-27 18:21
Looks like `gopls` is sending back some invalid responses for `textDocument/documentSymbol`. Could you share your `gopls` logs please?

**Comment by atombender** [comment] 2019-11-27 18:24
[Here](https://gist.github.com/atombender/396a84039f7a844f705bc7b54e9714ad).

Gopls has always been wonky for me, and I keep hoping the next upgrade will fix some issues. It tends to lose its mind whenever a file changes unrelated to direct editor edits (e.g. renaming, moving, deletion, `git checkout`, etc.).

**Comment by stamblerre** [comment] 2019-11-27 18:36
Could you please add the following to your `settings.json` and then upload a new log here? Sorry, forgot to mention that we would need more detail in this one.

```json
"go.languageServerFlags": [
    "-rpc.trace"
]
```

**Comment by atombender** [comment] 2019-11-27 18:40
Will do.

**Comment by ramya-rao-a** [comment] 2019-12-03 07:46
@atombender This issue was logged during the same time as your other issue #2920 for which a fix was pushed. Do you still see this issue after updating the version of gopls that contain that fix?

**Comment by atombender** [comment] 2019-12-03 20:36
@ramya-rao-a Yes, still getting the log messages.

**Comment by stamblerre** [comment] 2019-12-03 21:09
Yeah, this doesn't seem related to the other issue.
I'll be able to move forward on diagnosing this once we have some `gopls` logs that show the offending `textDocument/documentSymbols` responses.

**Comment by atombender** [comment] 2019-12-03 21:11
Here you go: [gopls.txt.zip](https://github.com/microsoft/vscode-go/files/3918719/gopls.txt.zip). I'm afraid I don't have anything correlating that log output with the extension host log errors. Perhaps I could clear the logs and see if I can catch only the newest few entries when it happens?

**Comment by stamblerre** [comment] 2019-12-03 21:23
Thank you! Yes, a shorter log would be ideal, if possible.

**Comment by atombender** [comment] 2019-12-04 05:20
Will try. Meanwhile, I'm getting this a lot:

```
[2019-12-03 19:35:48.498] [exthost] [warning] ms-vscode.Go - Code actions of kind 'source.organizeImports 'requested but returned code action is of kind 'quickfix'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.
```

and also this one started happening:

```
[2019-12-03 19:35:50.777] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-12-03 19:35:50.777] [exthost] [error] URIError: URI malformed
	at decodeURIComponent (<anonymous>)
	at Function.parse (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:124:53)
	at protocol2Code (/Users/alex/.vscode/extensions/ms-vscode.go-0.11.9/out/src/goLanguageServer.js:74:52)
	at asUri (/Users/alex/.vscode/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/protocolConverter.js:25:16)
	at asDocumentLink (/Users/alex/.vscode/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/protocolConverter.js:520:36)
	at Array.map (<anonymous>)
	at asDocumentLinks (/Users/alex/.vscode/extensions/ms-vscode.go-0.11.9/node_modules/vscode-languageclient/lib/protocolConverter.js:532:22)
```

**Comment by atombender** [comment] 2019-12-04 05:23
Here's a `gopls` log that I copied immdiately after I got a whole bunch of `selectionRange must be contained in fullRange` messages: [gopls.txt.zip](https://github.com/microsoft/vscode-go/files/3920163/gopls.txt.zip). I was writing the code:

```go
for _, opt := range opts {
		if err := opt(&copy) // <-- caret
}
```

**Comment by stamblerre** [comment] 2019-12-04 18:31
Thanks for the report! I was actually just able to reproduce this myself. I mailed [CL 209858](https://go-review.googlesource.com/c/tools/+/209858) to help us debug this issue.

**Comment by ramya-rao-a** [comment] 2019-12-05 06:19
Looks like the changes got merged, thanks @stamblerre 

@atombender Can you retry after getting the latest from master for gopls?

**Comment by atombender** [comment] 2019-12-05 14:51
Upgraded, but gopls now [crashes](https://gist.github.com/atombender/cca1344589e3299344767505e60e8273) on startup.

**Comment by stamblerre** [comment] 2019-12-05 22:03
Thanks for checking again. Looks like you're running into https://github.com/golang/go/issues/35994, which I'm looking into.

**Comment by stamblerre** [comment] 2019-12-06 20:35
The issue above is now fixed, if you'd be willing to try again.

**Comment by atombender** [comment] 2019-12-06 21:29
Thanks. Trying it out now.

**Comment by atombender** [comment] 2019-12-09 21:50
I think it's fixed.

**Comment by ramya-rao-a** [comment] 2019-12-11 06:18
Thanks @atombender!

**Closed by ramya-rao-a** 2019-12-11 06:18 UTC
Labels: under-discussion, upstream-gopls
