### ISSUE TITLE
tooling not installing fully, when clicking "Analysis Tools Missing"

### ISSUE THREAD

**Issue by joeblew99** [Microsoft/vscode-go#282] opened 2016-04-07 15:42 UTC
gets to the last line and hangs...
package golang.org/x/tools/go/types: no buildable Go source files in /Users/apple/workspace/go/src/golang.org/x/tools/go/types

my env:
````
x-MacBook-Pro:backend apple$ go env
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
x-MacBook-Pro:backend apple$ 
```



```
Fetching https://sourcegraph.com/sqs/goreturns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns?go-get=1 (status code 200)
get "sourcegraph.com/sqs/goreturns": found meta tag main.metaImport{Prefix:"sourcegraph.com/sqs/goreturns", VCS:"git", RepoRoot:"https://github.com/sqs/goreturns"} at https://sourcegraph.com/sqs/goreturns?go-get=1
sourcegraph.com/sqs/goreturns (download)
Fetching https://golang.org/x/tools/go/gcimporter?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcimporter?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcimporter": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcimporter?go-get=1
get "golang.org/x/tools/go/gcimporter": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
	/usr/local/go/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
	/Users/apple/workspace/go/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ast/astutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/ast/astutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ast/astutil?go-get=1
get "golang.org/x/tools/go/ast/astutil": verifying non-authoritative meta tag
Fetching https://sourcegraph.com/sqs/goreturns/returns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns/returns?go-get=1 (status code 200)
get "sourcegraph.com/sqs/goreturns/returns": found meta tag main.metaImport{Prefix:"sourcegraph.com/sqs/goreturns", VCS:"git", RepoRoot:"https://github.com/sqs/goreturns"} at https://sourcegraph.com/sqs/goreturns/returns?go-get=1
get "sourcegraph.com/sqs/goreturns/returns": verifying non-authoritative meta tag
Fetching https://sourcegraph.com/sqs/goreturns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns?go-get=1 (status code 200)
Fetching https://golang.org/x/tools/go/types?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/types?go-get=1 (status code 200)
get "golang.org/x/tools/go/types": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/types?go-get=1
get "golang.org/x/tools/go/types": verifying non-authoritative meta tag
package golang.org/x/tools/go/types: no buildable Go source files in /Users/apple/workspace/go/src/golang.org/x/tools/go/types
exec error: Error: Command failed: /bin/sh -c go get -u -v sourcegraph.com/sqs/goreturns
Fetching https://sourcegraph.com/sqs/goreturns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns?go-get=1 (status code 200)
get "sourcegraph.com/sqs/goreturns": found meta tag main.metaImport{Prefix:"sourcegraph.com/sqs/goreturns", VCS:"git", RepoRoot:"https://github.com/sqs/goreturns"} at https://sourcegraph.com/sqs/goreturns?go-get=1
sourcegraph.com/sqs/goreturns (download)
Fetching https://golang.org/x/tools/go/gcimporter?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcimporter?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcimporter": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcimporter?go-get=1
get "golang.org/x/tools/go/gcimporter": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
	/usr/local/go/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
	/Users/apple/workspace/go/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ast/astutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/ast/astutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ast/astutil?go-get=1
get "golang.org/x/tools/go/ast/astutil": verifying non-authoritative meta tag
Fetching https://sourcegraph.com/sqs/goreturns/returns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns/returns?go-get=1 (status code 200)
get "sourcegraph.com/sqs/goreturns/returns": found meta tag main.metaImport{Prefix:"sourcegraph.com/sqs/goreturns", VCS:"git", RepoRoot:"https://github.com/sqs/goreturns"} at https://sourcegraph.com/sqs/goreturns/returns?go-get=1
get "sourcegraph.com/sqs/goreturns/returns": verifying non-authoritative meta tag
Fetching https://sourcegraph.com/sqs/goreturns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns?go-get=1 (status code 200)
Fetching https://golang.org/x/tools/go/types?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/types?go-get=1 (status code 200)
get "golang.org/x/tools/go/types": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/types?go-get=1
get "golang.org/x/tools/go/types": verifying non-authoritative meta tag
package golang.org/x/tools/go/types: no buildable Go source files in /Users/apple/workspace/go/src/golang.org/x/tools/go/types

```

**Comment by joeblew99** [comment] 2016-04-07 15:47
https://github.com/golang/tools/tree/master/go/types

???

**Comment by joeblew99** [comment] 2016-04-07 16:06
I cleaned out bin, pkg and src

Got a bit further but hung later:

````

github.com/lukehoban/go-outline (download)
github.com/lukehoban/go-outline
Fetching https://sourcegraph.com/sqs/goreturns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns?go-get=1 (status code 200)
get "sourcegraph.com/sqs/goreturns": found meta tag main.metaImport{Prefix:"sourcegraph.com/sqs/goreturns", VCS:"git", RepoRoot:"https://github.com/sqs/goreturns"} at https://sourcegraph.com/sqs/goreturns?go-get=1
sourcegraph.com/sqs/goreturns (download)
Fetching https://golang.org/x/tools/go/gcimporter?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcimporter?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcimporter": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcimporter?go-get=1
get "golang.org/x/tools/go/gcimporter": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
	/usr/local/go/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
	/Users/apple/workspace/go/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ast/astutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/ast/astutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ast/astutil?go-get=1
get "golang.org/x/tools/go/ast/astutil": verifying non-authoritative meta tag
Fetching https://sourcegraph.com/sqs/goreturns/returns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns/returns?go-get=1 (status code 200)
get "sourcegraph.com/sqs/goreturns/returns": found meta tag main.metaImport{Prefix:"sourcegraph.com/sqs/goreturns", VCS:"git", RepoRoot:"https://github.com/sqs/goreturns"} at https://sourcegraph.com/sqs/goreturns/returns?go-get=1
get "sourcegraph.com/sqs/goreturns/returns": verifying non-authoritative meta tag
Fetching https://sourcegraph.com/sqs/goreturns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns?go-get=1 (status code 200)
Fetching https://golang.org/x/tools/go/types?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/types?go-get=1 (status code 200)
get "golang.org/x/tools/go/types": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/types?go-get=1
get "golang.org/x/tools/go/types": verifying non-authoritative meta tag
package golang.org/x/tools/go/types: no buildable Go source files in /Users/apple/workspace/go/src/golang.org/x/tools/go/types
exec error: Error: Command failed: /bin/sh -c go get -u -v sourcegraph.com/sqs/goreturns
Fetching https://sourcegraph.com/sqs/goreturns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns?go-get=1 (status code 200)
get "sourcegraph.com/sqs/goreturns": found meta tag main.metaImport{Prefix:"sourcegraph.com/sqs/goreturns", VCS:"git", RepoRoot:"https://github.com/sqs/goreturns"} at https://sourcegraph.com/sqs/goreturns?go-get=1
sourcegraph.com/sqs/goreturns (download)
Fetching https://golang.org/x/tools/go/gcimporter?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcimporter?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcimporter": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcimporter?go-get=1
get "golang.org/x/tools/go/gcimporter": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
	/usr/local/go/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
	/Users/apple/workspace/go/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ast/astutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/ast/astutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ast/astutil?go-get=1
get "golang.org/x/tools/go/ast/astutil": verifying non-authoritative meta tag
Fetching https://sourcegraph.com/sqs/goreturns/returns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns/returns?go-get=1 (status code 200)
get "sourcegraph.com/sqs/goreturns/returns": found meta tag main.metaImport{Prefix:"sourcegraph.com/sqs/goreturns", VCS:"git", RepoRoot:"https://github.com/sqs/goreturns"} at https://sourcegraph.com/sqs/goreturns/returns?go-get=1
get "sourcegraph.com/sqs/goreturns/returns": verifying non-authoritative meta tag
Fetching https://sourcegraph.com/sqs/goreturns?go-get=1
Parsing meta tags from https://sourcegraph.com/sqs/goreturns?go-get=1 (status code 200)
Fetching https://golang.org/x/tools/go/types?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/types?go-get=1 (status code 200)
get "golang.org/x/tools/go/types": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/types?go-get=1
get "golang.org/x/tools/go/types": verifying non-authoritative meta tag
package golang.org/x/tools/go/types: no buildable Go source files in /Users/apple/workspace/go/src/golang.org/x/tools/go/types
github.com/lukehoban/go-find-references (download)
github.com/lukehoban/ident (download)
github.com/rogpeppe/godef (download)
github.com/lukehoban/go-find-references
github.com/rogpeppe/godef (download)
Fetching https://9fans.net/go/acme?go-get=1
Parsing meta tags from https://9fans.net/go/acme?go-get=1 (status code 200)
get "9fans.net/go/acme": found meta tag main.metaImport{Prefix:"9fans.net/go", VCS:"git", RepoRoot:"https://github.com/9fans/go"} at https://9fans.net/go/acme?go-get=1
get "9fans.net/go/acme": verifying non-authoritative meta tag
Fetching https://9fans.net/go?go-get=1
Parsing meta tags from https://9fans.net/go?go-get=1 (status code 200)
9fans.net/go (download)
Fetching https://9fans.net/go/plan9?go-get=1
Parsing meta tags from https://9fans.net/go/plan9?go-get=1 (status code 200)
get "9fans.net/go/plan9": found meta tag main.metaImport{Prefix:"9fans.net/go", VCS:"git", RepoRoot:"https://github.com/9fans/go"} at https://9fans.net/go/plan9?go-get=1
get "9fans.net/go/plan9": verifying non-authoritative meta tag
Fetching https://9fans.net/go/plan9/client?go-get=1
Parsing meta tags from https://9fans.net/go/plan9/client?go-get=1 (status code 200)
get "9fans.net/go/plan9/client": found meta tag main.metaImport{Prefix:"9fans.net/go", VCS:"git", RepoRoot:"https://github.com/9fans/go"} at https://9fans.net/go/plan9/client?go-get=1
get "9fans.net/go/plan9/client": verifying non-authoritative meta tag
github.com/rogpeppe/godef
github.com/golang/lint (download)
Fetching https://golang.org/x/tools/go/gcimporter15?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/gcimporter15?go-get=1 (status code 200)
get "golang.org/x/tools/go/gcimporter15": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/gcimporter15?go-get=1
get "golang.org/x/tools/go/gcimporter15": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
golang.org/x/tools/go/gcimporter15
github.com/golang/lint
github.com/golang/lint/golint
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/gorename?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/gorename": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/gorename?go-get=1
get "golang.org/x/tools/cmd/gorename": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/buildutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/buildutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/buildutil?go-get=1
get "golang.org/x/tools/go/buildutil": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/refactor/rename?go-get=1
Parsing meta tags from https://golang.org/x/tools/refactor/rename?go-get=1 (status code 200)
get "golang.org/x/tools/refactor/rename": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/refactor/rename?go-get=1
get "golang.org/x/tools/refactor/rename": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ast/astutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/ast/astutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ast/astutil?go-get=1
get "golang.org/x/tools/go/ast/astutil": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/loader?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/loader?go-get=1 (status code 200)
get "golang.org/x/tools/go/loader": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/loader?go-get=1
get "golang.org/x/tools/go/loader": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/types/typeutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/types/typeutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/types/typeutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/types/typeutil?go-get=1
get "golang.org/x/tools/go/types/typeutil": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/refactor/importgraph?go-get=1
Parsing meta tags from https://golang.org/x/tools/refactor/importgraph?go-get=1 (status code 200)
get "golang.org/x/tools/refactor/importgraph": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/refactor/importgraph?go-get=1
get "golang.org/x/tools/refactor/importgraph": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/refactor/satisfy?go-get=1
Parsing meta tags from https://golang.org/x/tools/refactor/satisfy?go-get=1 (status code 200)
get "golang.org/x/tools/refactor/satisfy": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/refactor/satisfy?go-get=1
get "golang.org/x/tools/refactor/satisfy": verifying non-authoritative meta tag
golang.org/x/tools/go/buildutil
golang.org/x/tools/go/ast/astutil
golang.org/x/tools/go/types/typeutil
golang.org/x/tools/refactor/importgraph
golang.org/x/tools/refactor/satisfy
golang.org/x/tools/go/loader
golang.org/x/tools/refactor/rename
golang.org/x/tools/cmd/gorename
github.com/nsf/gocode (download)
github.com/nsf/gocode

```

**Comment by joeblew99** [comment] 2016-04-07 16:16
https://github.com/Microsoft/vscode-go#tools

I tried the manual install.

Did not help..

Basically whenever i try to format the code in vscode, the bar above comes up always asking to install 'goreturns'

**Comment by lukehoban** [comment] 2016-04-07 17:47
This is an issue with `goreturns` - I've opened a tracking issue here: https://github.com/sqs/goreturns/issues/19.

The root cause appears to be https://groups.google.com/forum/#!topic/golang-announce/qu_rAphYdxY.

For a workaround until `goreturns` gets fixed, you should be able to just change to: `"go.formatTool": "goimports"` and make sure you have done a `go get golang.org/x/tools/cmd/goimports`.

**Comment by joeblew99** [comment] 2016-04-07 19:48
Ok glad I am not crazy and thanks for the fast feedback.

Can you explain the work around in a bit more detail please ?
You want me to run the tool install from terminal right ?

**Comment by lukehoban** [comment] 2016-04-07 20:22
For the workaround:

1. In your settings (Preferences -> User Settings or Preferences -> Workspace Settings) add:  `"go.formatTool": "goimports"`.
2. In your shell, with the same GOPATH you are using in VS Code, run `go get golang.org/x/tools/cmd/goimports`

**Comment by lukehoban** [comment] 2016-04-08 01:34
This is fixed now in https://github.com/sqs/goreturns/issues/19.

**Closed by lukehoban** 2016-04-08 01:34 UTC

**Comment by joeblew99** [comment] 2016-04-08 06:01
So does that mean the standard way of installing the tools should work now ?

**Comment by joeblew99** [comment] 2016-04-08 06:50
Hey @lukehoban 
It works now when i run the "Analysis Tools Missing" . Thanks.
I tested it by trying a format code.

but i had to do:
go get -u github.com/golang/lint/golint
So maybe that should be added to your script ?

**Comment by joeblew99** [comment] 2016-04-08 07:33
this is my settings:

// Place your settings in this file to overwrite default and user settings.
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.formatTool": "goreturns",

    // "files.autoSave": "onFocusChange", "files.autoSave": "afterDelay",
    "files.autoSave": "onFocusChange",
    
     "telemetry.enableTelemetry": false
}

What should  "go.formatTool" be ?? there are 3 options, and i have no idea whats the default..
