### ISSUE TITLE
Autocompletion not working for external imports when using dep

### ISSUE THREAD

**Issue by fabianem** [Microsoft/vscode-go#2182] opened 2018-12-11 15:42 UTC
I have a project with different packages and imports. Autocompletion works fine for standard libraries like `fmt` but importing my own libraries or external ones - autocompletion doesnt work. The odd thing is, that `peek definition` and `go to definition` works perfectly.

I am using:
OS: windows 10
vs code: 1.29.1
go version: 1.11.1

Steps to Reproduce:

external import:
1. I have a go file in `package main`
2. Importing external library `github.com/hyperledger/fabric/core/chaincode/shim`
3. Autocompletion for `shim.` is not working (`go to definition` etc works fine)

![image](https://user-images.githubusercontent.com/16178078/49810805-3f92ae80-fd62-11e8-82bd-b860f8d3ae82.png)

![image](https://user-images.githubusercontent.com/16178078/49810963-8c768500-fd62-11e8-8c71-0011dac55af5.png)

import custom local package:
1. I have a go file in `package main`
2. Importing my own local package "xxx/CP_BC_Chaincodes/tokenUtils"
3. Autocompletion for `tokenUtils.` is not working (`go to definition` etc works fine)

![image](https://user-images.githubusercontent.com/16178078/49811018-a87a2680-fd62-11e8-96dc-e1743a2ee984.png)

![image](https://user-images.githubusercontent.com/16178078/49811203-060e7300-fd63-11e8-9b80-42fe8579c0e2.png)

autocompletion for `fmt.`:
![image](https://user-images.githubusercontent.com/16178078/49811499-b2e8f000-fd63-11e8-9383-ebce4a1ffc38.png)

I tried already deleting & reinstalling `github.com/mdempsky/gocode`

**Comment by bevanhunt** [comment] 2018-12-11 18:57
Same here on Mac OS 10.13.6, VS Code 1.29.1, and Go 1.11.2.

**Comment by ramya-rao-a** [comment] 2018-12-13 05:05
Please see the section on auto-completion in our [wiki for FAQ](https://github.com/Microsoft/vscode-go/wiki/Go-with-VS-Code-FAQ-and-Troubleshooting)

Are you using Go modules?

**Comment by bevanhunt** [comment] 2018-12-13 05:09
Yes on the Go modules.

**Comment by ramya-rao-a** [comment] 2018-12-13 06:48
@bevanhunt Please try out the steps in the FAQ. 
@fabianem Are you using modules as well?

**Comment by ramya-rao-a** [comment] 2018-12-13 06:49
Also, is this happening the first time you use the package after importing?
Because we have an issue for that: https://github.com/Microsoft/vscode-go/issues/2179

After saving file with the imported package used atleast once, auto-completions should work when using modules

**Comment by bevanhunt** [comment] 2018-12-13 07:08
@ramya-rao-a I followed the FAQ - didn't work. I save all the time - that isn't the issue. I just removed my brew casked version (1.29.1) and brew cask installed the new version (1.3.0) - autocompletions work now - but the onhover documentation still doesn't work.

**Comment by fabianem** [comment] 2018-12-13 10:56
@ramya-rao-a thanks for your replies. At this moment I am not using Go modules - I use dep for managing dependencies.
Also, its not happening for the first time I import a package - I am saving all the time.

**Comment by ramya-rao-a** [comment] 2018-12-13 17:43
@fabianem Did you try running `gocode -s -debug` as per the instructions in the FAQ to see if the issue is with gocode or VS Code?

@bevanhunt On symbols for which the onhover docs dont work, does Go to definition work?

**Comment by bevanhunt** [comment] 2018-12-13 17:55
@ramya-rao-a I tried going to an external package function (goto def) which the onhover doesn't work (it doesn't work for anything though) - it didn't work (goto def).

**Comment by ramya-rao-a** [comment] 2018-12-13 20:56
@bevanhunt Please see 
https://github.com/Microsoft/vscode-go/issues/2165#issuecomment-447116812. Let's continue the discussion on the Go to definition issues there and have this current github issue to track the completion issue.

**Comment by fabianem** [comment] 2018-12-19 12:07
@ramya-rao-a sorry for my delayed response

I am in my package `main `and tried to call a function from package `tokenUtils `(which I am using already several times in `main`)
I tried now running `gocode -s -debug` and received the following output:

```
2018/12/19 12:44:55 -------------------------------------------------------
2018/12/19 12:44:55 Error parsing input file (outer block):
2018/12/19 12:44:55  c:\go-dev\src\mc2innovations.visualstudio.com\CP_BC_Chaincodes\token.go:115:13: expected selector or type assertion, found ';'
2018/12/19 12:44:55  c:\go-dev\src\mc2innovations.visualstudio.com\CP_BC_Chaincodes\token.go:117:2: expected ';', found senderTokenBalance
2018/12/19 12:44:55 gbimporter: no package found for mc2innovations.visualstudio.com/CP_BC_Chaincodes/tokenUtils: can't find import: "mc2innovations.visualstudio.com/CP_BC_Chaincodes/tokenUtils"
2018/12/19 12:44:55 gbimporter: no package found for mc2innovations.visualstudio.com/CP_BC_Chaincodes/eventUtils: can't find import: "mc2innovations.visualstudio.com/CP_BC_Chaincodes/eventUtils"
2018/12/19 12:44:55 gbimporter: no package found for mc2innovations.visualstudio.com/CP_BC_Chaincodes/loggerUtils: can't find import: "mc2innovations.visualstudio.com/CP_BC_Chaincodes/loggerUtils"
2018/12/19 12:44:55 gbimporter: no package found for mc2innovations.visualstudio.com/CP_BC_Chaincodes/validatorUtils: can't find import: "mc2innovations.visualstudio.com/CP_BC_Chaincodes/validatorUtils"
2018/12/19 12:44:55 gbimporter: no package found for github.com/hyperledger/fabric/core/chaincode/shim: can't find import: "mc2innovations.visualstudio.com/CP_BC_Chaincodes/vendor/github.com/hyperledger/fabric/core/chaincode/shim"
2018/12/19 12:44:55 Elapsed duration: 111.0029ms
2018/12/19 12:44:55 Offset: 0
2018/12/19 12:44:55 Number of candidates found: 0
2018/12/19 12:44:55 Candidates are:
2018/12/19 12:44:55 =======================================================
```

I am not quite sure why he cant find any imported packages? My project structure is like the following:
![image](https://user-images.githubusercontent.com/16178078/50219080-52266c80-038e-11e9-9ab7-d18976782039.png)

so the file `token.go` is my `main` package and every folder like `tokenUtils` is his own package.

But autcompletion within the same package works fine:
![image](https://user-images.githubusercontent.com/16178078/50219265-f4465480-038e-11e9-8e51-5e29e713560f.png)

**Comment by Cimsystemsthai** [comment] 2018-12-21 04:36
Same problem here , go back to go extension version 0.7.0 seems to fix the problem

**Comment by DOTA2mm** [comment] 2018-12-21 10:11
Same here on Win10, VS Code 1.30.0, and Go 1.11.2.

**Comment by ramya-rao-a** [comment] 2018-12-31 01:31
@Cimsystemsthai, @DOTA2mm Are you using dep or modules or neither?

@stamblerre TLDR; @fabianem is using dep to manage dependencies and has issues getting completions from external packages that are already imported. See 
https://github.com/Microsoft/vscode-go/issues/2182#issuecomment-448571836. Would you like me to move this issue to https://github.com/mdempsky/gocode?

**Comment by stamblerre** [comment] 2019-01-02 19:11
This is likely a result of https://github.com/mdempsky/gocode/issues/84. The current suggested workaround is running `go install -i ./vendor/...`.

**Comment by ramya-rao-a** [comment] 2019-01-04 06:33
Thanks @stamblerre 
@fabianem Can you try out the workaround that @stamblerre has mentioned above?
@Cimsystemsthai, @DOTA2mm Are you using dep or modules or neither?

**Comment by DOTA2mm** [comment] 2019-01-04 10:07
> Thanks @stamblerre
> @fabianem Can you try out the workaround that @stamblerre has mentioned above?
> @Cimsystemsthai, @DOTA2mm Are you using dep or modules or neither?

Neither used.

**Comment by fabianem** [comment] 2019-01-05 00:17
@ramya-rao-a 
Yesterday I was already trying out the workaround but unfortunately I came across another problem. 
On my ubuntu subsystem it all compiles without problem but I guess gocode (while using vs code) needs the packages build for windows. 
I also need to compile `\github.com\miekg\pkcs11` which is using `cgo`. So I installed gcc on windows (tdm-gcc and now trying with mingw64). But I also needed to install separately libtool for windows. It did almost work but then I got errors (with tdm-gcc + libtool) that its not 64bit compatible. 
Since then I am trying to give mingw64 a shot but I still did not figure out how to get libtool here working for mingw64.

@stamblerre 
Thanks for the advice but do you think this is also a workaround for my packages in subfolders which are not in the vendors folder?

![image](https://user-images.githubusercontent.com/16178078/50717337-f266db80-1086-11e9-918b-288cce7f09b7.png)

`token.go` is my main package and every subfolder like `tokenUtils `is his own package with different go files.
Importing `tokenUtils` in `token.go` I also do not get any autocompletion.

**Comment by ramya-rao-a** [comment] 2019-01-07 05:59
@fabianem 

> but I guess gocode (while using vs code) needs the packages build for windows.

What makes you say that?

**Comment by fabianem** [comment] 2019-01-07 12:01
@ramya-rao-a I assumed so because I thought that vs code (running in windows) is using `GOPATH/bin/gocode.exe` and `gocode.exe` searches for the packages in `GOPATH/pkg/windows_amd64` - or is his assumption wrong?

Nevertheless I installed on ubuntu subsystem all packages from vendor and in my local project. This is how `GOPATH/pkg/linux_amd64` looks like now:

```
fab@fab-surfacePro:/mnt/c/go-dev/pkg/linux_amd64/mc2innovations.visualstudio.com$ find CP_BC_Chaincodes/ -maxdepth 1
CP_BC_Chaincodes/
CP_BC_Chaincodes/errorUtils.a
CP_BC_Chaincodes/eventUtils.a
CP_BC_Chaincodes/loggerUtils.a
CP_BC_Chaincodes/tokenUtils.a
CP_BC_Chaincodes/validatorUtils.a
CP_BC_Chaincodes/vendor
```

and for now I installed manually all local packages in my project on windows:

```
fab@fab-surfacePro:/mnt/c/go-dev/pkg/windows_amd64/mc2innovations.visualstudio.com$ find CP_BC_Chaincodes/ -maxdepth 1
CP_BC_Chaincodes/
CP_BC_Chaincodes/errorUtils.a
CP_BC_Chaincodes/eventUtils.a
CP_BC_Chaincodes/loggerUtils.a
CP_BC_Chaincodes/tokenUtils.a
CP_BC_Chaincodes/validatorUtils.a
CP_BC_Chaincodes/vendor
```

and unfortunately intellisense does still not work in vs code (even for imported local package e.g. `tokenUtils`)

**Comment by Cimsystemsthai** [comment] 2019-01-07 13:49
@ramya-rao-a
I don't use dep and module.

Actually our project is a legacy code using go 1.7.2 and old gotools compiled a year ago ( i.e nsf/gocode not mdempsky/gocode) but before I report this error , I switch to  go 1.11.4 and newest gotool to check whether the problem is come from the old tools that we use or from the vscode-go.
Both old and new gocode show the same problem only switch back to vscode-go 0.7 make the auto complete work again.

**Comment by stamblerre** [comment] 2019-01-07 17:11
@fabianem: Do you mind posting the output of `gocode -s -debug`? If you have those `.a` files, then gocode should work. Also, feel free to file an issue on the gocode repository.

@DOTA2mm and @Cimsystemsthai: Since your issues are not with dep or modules, I would request that you please create new issues, as it seems that you are encountering potentially different problems. Feel free to file them on gocode repository, as it sounds like VSCode-Go is not the problem.

**Comment by ramya-rao-a** [comment] 2019-01-07 18:56
@fabianem 

> I assumed so because I thought that vs code (running in windows) is using GOPATH/bin/gocode.exe and gocode.exe searches for the packages in GOPATH/pkg/windows_amd64 - or is his assumption wrong?

Thats just in Windows. In other OS, VS Code will use just `gocode` for the binary.
Can you create a new issue in https://github.com/mdempsky/gocode with your findings? @stamblerre will be able to help you there. This issue is getting pretty long and also inter-mingled with other concerns from other users.


@DOTA2mm and @Cimsystemsthai: Like @stamblerre mentioned, please log issues in https://github.com/mdempsky/gocode

Closing this issue as we are suggesting to create new issues in the gocode repo.

**Closed by ramya-rao-a** 2019-01-07 18:56 UTC
Labels: needs more info
