### ISSUE TITLE
CPU overuse due to go doc processes

### ISSUE THREAD

**Issue by jpincas** [microsoft/vscode-go#2276] opened 2019-01-27 16:41 UTC
I know this has been logged in multiple issues before, but they are all closed as far as I can see.  Common to those reports, the extension is driving the CPUs in my MacBook Pro through the roof, causing it to overheat and the fans to spin like crazy.

-  I have installed, reinstalled and clean reinstalled both VsCode and the extension 3-4 times.
- I normally get about 15 minutes of normal use before this behaviour starts.
- Only get this when coding Go.
- Have updated Go tools with `Go : Update / Reinstall tools`
- Have added both `"go.docsTool": "gogetdoc"` and `"go.useLanguageServer": true` to my settings and reloaded, as suggested in other threads.

I attach a screenshot of the process viewer mid-spike, that pretty clearly shows that its the `doc` process causing the problem.

<img width="1181" alt="screenshot 2019-01-26 at 23 39 39" src="https://user-images.githubusercontent.com/17711012/51803899-72cdc600-225a-11e9-8c82-e3b3c89aef20.png">

Please help if you can - I code Go all day every day and this is making my life really, really hard right now.  Sometimes the spikes cause the cursor to skip to another pane, and when I look up, I've written code in the middle of another file!

**Comment by tj** [comment] 2019-01-28 18:56
I get this all the time as well, I tried updating all the Go tools using the install/update command but no luck

**Comment by jpincas** [comment] 2019-01-28 20:48
Good to know someone else has experienced it - it's really making work hard.  As you start typing, you can see the linting and suggestions start to slow down to a crawl until they end up not working at all until the CPU has recovered!!

**Comment by jpincas** [comment] 2019-01-29 08:03
Thanks Ramya - have installed the beta version and added those settings.  Will report back after a days work.

**Comment by jpincas** [comment] 2019-01-29 08:12
OK, I can already report the following:

- Im not getting any intelligent autocomplete suggestions - is that expected? is that what the 'doc' feature was?
- It is constantly asking me install the latest version of `gocode`, even though I have done so twice.

**Comment by tj** [comment] 2019-01-29 12:09
Should these processes have some kind of timeout? In my cases it often shows `undefined` as well, as seen in #2248, maybe a bug? I've been working in Go WASM lately, maybe that's part of the problem, I forget now if I had this issue with non-`js,wasm` build tags

**Comment by jpincas** [comment] 2019-01-29 13:12
@tj Did you also add the "--exclude-docs" option to your config as suggested by @ramya-rao-a above? That seems to solve it, but of course it disables the intelligent autocomplete, which makes writing code suck!!

@ramya-rao-a Is there any timeline for a proper fix on this?

**Comment by ramya-rao-a** [comment] 2019-01-29 17:03
@jpincas The flag is `-exclude-docs` not `--exclude-docs`, I have corrected it in my comment above. Once you make that change, you shouldn't see any more prompts for gocode.
Regardless, I'll make that part of the code more resilient

@tj Thats a good idea about the timeout, I'll look into it.

**Comment by tj** [comment] 2019-01-31 11:20
strange, `-exclude-docs` fixed it until I restarted my machine, now it's back to spawning them, the user setting is still set correctly

**Comment by ramya-rao-a** [comment] 2019-01-31 18:18
@tj are you sure your user setting is not getting overriden by workspace settings?

**Comment by ramya-rao-a** [comment] 2019-01-31 18:19
If not then close any running `gocode` process and then try again in VS Code

**Comment by tj** [comment] 2019-02-01 11:41
double checked the workspace settings but mine are empty, I tried `gocode exit` and restarting vscode a few times but somehow it's still doing it

**Comment by tj** [comment] 2019-02-01 15:09
interestingly I'm having similar issues with Atom now 😄 with `gotype`, going to do some digging, pretty suspicious

**Comment by tj** [comment] 2019-02-01 16:05
I ran `find . -name "node_modules" -exec rm -rf '{}' +` (__WARNING__: dont blame me for losing stuff) to remove node modules recursively, since many repos in my GOPATH also have Node-based client code, now unsuccessful `go doc` lookups are quite a bit faster:

```
$ time go doc something

real	2m25.068s
user	0m17.772s
sys	1m45.039s

$ time go doc something

real	0m19.955s
user	0m2.499s
sys	0m9.343s
```

It might be safe to close this issue since `go doc` is at fault for the CPU usage. It would be great to possibly do:

- add a timeout for maybe a few seconds, since showing the docs after a huge delay isn't super useful anyway
- kill previous `go doc` processes when spawning a new one as the old results are no longer going to be displayed

**Comment by ramya-rao-a** [comment] 2019-02-01 19:40
That is a little weird @tj... Why would node_modules have any affect on `go doc`?

We do have a [cancellation token in place](https://github.com/Microsoft/vscode-go/blob/0.8.0/src/goSuggest.ts#L84) for the auto-completion feature. When a previous request is no longer valid (say because you continued typing and now are on a different word), then cancellation token for the previous request is cancelled by VS Code. 

And we do [listen to this cancellation and kill](https://github.com/Microsoft/vscode-go/blob/0.8.0/src/util.ts#L940) the `go doc` process. Looks like this token is not getting cancelled properly, thats the only explanation I can come up with for why these processes are lingering.

**Comment by tj** [comment] 2019-02-01 20:12
I think `go doc` is just traversing too many directories searching for a match. I opened an issue for that here, Brad seemed open to black-listing `node_modules`: https://github.com/golang/go/issues/30058

**Comment by jpincas** [comment] 2019-02-04 09:18
Sorry for the dumb question - but when we talk about 'showing the docs', are we talking about the intelligent completion suggestions, or something else?

**Comment by ramya-rao-a** [comment] 2019-02-04 21:10
Not a dumb question at all @jpincas 

Generally, "showing the docs" could either refer to the docs that accompany the suggestion widget or what you see when you hover over symbols.

But in this case, we are referring to the former.

**Comment by snikch** [comment] 2019-02-11 20:31
I've been battling this same problem for the last 6 months or so.

@ramya-rao-a I can confirm excluding docs has worked for me, although there's the obvious drawbacks.

The node modules things has affected a whole lot of Go tools over the years. I even complained about it in 2016 for `goimports` https://twitter.com/snikchnz/status/749895907777269760

It would be great to have the tools ignoring `node_modules` but in the meantime skipping the doc generation will have to do 👍. Thanks for looking into it.

**Comment by jpincas** [comment] 2019-02-17 09:00
The `-exclude-docs` tag is no longer having any effect for me.  The docs are showing and the CPU is on fire.  I'm on version `0.9.2` - does that version recognise that tag? I thought I read on the Beta download page that auto-updating is disabled once you're on the Beta - so I'm not actually sure how I ended up on 0.9.2.

**Comment by jpincas** [comment] 2019-02-17 09:03
Even whilst doing nothing, `go-langserver` is eating my CPU.
![screenshot 2019-02-17 at 10 01 47](https://user-images.githubusercontent.com/17711012/52910670-31e63180-329b-11e9-909d-b839286f7cce.png)

**Comment by ramya-rao-a** [comment] 2019-02-24 03:02
@jpincas 

Auto-updating doesn't get disabled once you are on beta. That only happens if you opt out using the setting `extension.autoUpdate`

No, there were no changes in 0.9.2 regarding the `-exclude-docs`

From your screenshot it looks like the language server is taking up the CPU and not the `go doc` process anymore. Using the `-exclude-docs` flag only helps with he problem caused by `go doc`

Regarding the problem with the language server, I would suggest to disable that. In a few weeks the team at Google will be ready with a their official language server which should perform better

**Comment by freman** [comment] 2019-10-23 05:49
Similar to the above, I'm on the latest beta (I think) 0.11.8-beta.2 and `-exclude-docs` seems not to be stopping the running of `docs`

![image](https://user-images.githubusercontent.com/506680/67361646-a3098180-f5ac-11e9-91ae-4bd94ec2bf4d.png)

my config looks like this
```
    "go.formatTool": "goimports",
    "go.testFlags": ["-v"],
    "go.gocodeFlags": [
		"-builtin",
		"-ignore-case",
		"-unimported-packages",
		"-exclude-docs"
	]
```

![image](https://user-images.githubusercontent.com/506680/67361370-cb44b080-f5ab-11e9-817d-967baa8641d6.png)

**Comment by stamblerre** [comment] 2020-02-12 18:33
An alternative to this work-around is to use the [`gopls` language server](https://github.com/golang/tools/blob/master/gopls/doc/vscode.md), which handles cancellation.

I have also filed https://github.com/microsoft/vscode-go/issues/3044 to track supporting correct cancellation for all subprocesses, so let's continue the discussion there. The correct fix would really be to limit the number of `go doc` processes that VS Code Go can start. I will close this issue in favor of https://github.com/microsoft/vscode-go/issues/3044.

**Comment by stamblerre** [comment] 2020-02-12 18:33
Duplicate of https://github.com/microsoft/vscode-go/issues/3044

**Closed by stamblerre** 2020-02-12 18:33 UTC
Labels: bug
