### ISSUE TITLE
New test options makes it harder to run tests

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#544] opened 2016-10-18 22:44 UTC
I used to just 
- Ctrl+Shift+p
- Type "test"
- Pick "Go: Test file"

now I have to hit the cursor 3 more times (because of the new items ranked on the top) to reach the same option...

![image](https://cloud.githubusercontent.com/assets/159209/19499151/bd8e5e16-9549-11e6-9e0a-a970174bcc50.png)

**Comment by ramya-rao-a** [comment] 2016-10-31 01:42
Duplicate of #543

**Closed by ramya-rao-a** 2016-10-31 01:42 UTC
