### ISSUE TITLE
cmd/fillstruct: fill struct in disorder

### ISSUE THREAD

**Issue by iiinsomnia** [microsoft/vscode-go#3171] opened 2020-04-13 08:44 UTC
![image](https://user-images.githubusercontent.com/6582246/79106914-fb744b80-7da5-11ea-9366-3d077607e03d.png)

**Comment by stamblerre** [comment] 2020-04-13 15:22
@iiinsomnia: Can you please provide the steps to reproduce this issue?

**Comment by iiinsomnia** [comment] 2020-04-14 10:05
![image](https://user-images.githubusercontent.com/6582246/79212726-90e10f80-7e7a-11ea-8ec0-d1de602db6f1.png)

**Comment by stamblerre** [comment] 2020-04-14 17:51
I am not able to reproduce this issue, and without an example case to reproduce with, there's no way to investigate this issue. I'm going to close this, but please reopen if you can give an example with which to reproduce.

**Closed by stamblerre** 2020-04-14 17:51 UTC
Labels: needs more info
