### ISSUE TITLE
Trying to edit toolsEnvVars via rich interface creates an invalid settings entry

### ISSUE THREAD

**Issue by sandipb** [microsoft/vscode-go#3214] opened 2020-04-30 19:16 UTC
Please direct general questions to:
- [Gitter](https://gitter.im/Microsoft/vscode-go)
- [Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [Wiki](https://github.com/microsoft/vscode-go/wiki) before filing an issue.
Helpful pages include:
- [GOPATH](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)
- [Module Support](https://github.com/microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code)
- [Debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code)
	- Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.13.5 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- ```
           1.44.2
           ff915844119ce9485abfe8aa9076ec76b5300ddd
           x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.1
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- `darwin amd64`

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
```
    "go.goroot": "~/.gradle/language/golang/1.12.5/go",
    "go.toolsGopath": "~/go/go1.12.5",
    "go.useLanguageServer": false,
    "go.languageServerFlags": [
        "-logfile",
        "/Users/snbhatta/langserver.log"
    ],
    "go.docsTool": "godoc",
    "go.testFlags": [
        "-v"
    ],
    "go.testEnvFile": "~/.env.gotest",
    "go.inferGopath": true,
    "go.formatTool": "goimports"
```

### Describe the bug

I wanted to edit the environment settings for Go tools to set a variable in my workspace. I used the rich settings interface to filter out the tools environment settings I wanted, and clicked on the link. It took me to the raw json config of my workspace, with the appropriate empty json dictionary created. However, this entry was created *outside* the settings top level key. Vscode immediately marked this property as unsupported.

I expected this new settings to be created inside the `settings` top level key.

### Steps to reproduce the behavior:
1. Go to workspace setting rich interface.
2. Use the text `tools env` to filter out the toolsEnvVars settings I want to set
3. Click the `Edit in settings.json` link
4. You will find the following created *after* the `settings` key.
     ```
      ,
	"go.toolsEnvVars": {}

### Screenshots or recordings
This is the link I clicked.
![Screen Shot 2020-04-30 at 11 52 37 AM](https://user-images.githubusercontent.com/105359/80749778-d9840400-8adb-11ea-9109-e0e2f9a7fd46.png)

Settings before I clicked:
![Screen Shot 2020-04-30 at 12 13 38 PM](https://user-images.githubusercontent.com/105359/80750021-3bdd0480-8adc-11ea-8610-a675c915d022.png)

Settings after I clicked:
![Screen Shot 2020-04-30 at 12 14 44 PM](https://user-images.githubusercontent.com/105359/80750046-44353f80-8adc-11ea-9ebc-ae81ea410103.png)

**Comment by hyangah** [comment] 2020-04-30 21:38
The rich setting UI is owned by vscode, so github.com/microsoft/vscode is a better place for this question.

Based on https://code.visualstudio.com/docs/getstarted/settings, I thought this was working as intended - they should be on top-level. Seeing `"go.toolsEnvVars"` greyed out in your screen shot, there must be something that I don't know yet. (what is `"settings"` top level key?)

**Comment by hyangah** [comment] 2020-04-30 21:40
Ah, Found it https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings

**Comment by ramya-rao-a** [comment] 2020-05-29 01:15
Looks like this happens only when having a multi root workspace, and yes this is an upstream issue in VS Code. This will be moved appropriately.

Thanks for reporting!

**Comment by ramya-rao-a** [comment] 2020-05-29 01:25
Closing in favor of the upstream issue https://github.com/microsoft/vscode/issues/98774

**Closed by ramya-rao-a** 2020-05-29 01:25 UTC
Labels: upstream
