### ISSUE TITLE
vscode debug issues

### ISSUE THREAD

**Issue by skeleton1231** [Microsoft/vscode-go#717] opened 2017-01-11 03:02 UTC
My GOPATH

➜  test1  echo $PATH
/usr/local/bin:/usr/local/sbin:/Users/huanghaitao/bin:/opt/local/bin:/opt/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/opt/local/lib/mysql55/bin:/Users/huanghaitao/go/bin:/usr/local/go/bin:/opt/local/lib/mysql55/bin:/Users/huanghaitao/Downloads/adt-bundle-mac-x86_64-20140702 2/sdk/tools:/Users/huanghaitao/Downloads/adt-bundle-mac-x86_64-20140702 2/sdk/platform-tools:/Users/huanghaitao/android_project/apache-ant-1.9.4/bin:/Users/huanghaitao/.composer/vendor/bin:/Users/huanghaitao/Downloads/rar:/Users/huanghaitao/go_project/protoc-3.0.0-osx-x86_64/bin/protoc
➜  test1  echo $GOPATH
/Users/huanghaitao/go

![image](https://cloud.githubusercontent.com/assets/2403591/21833513/a1ba6f72-d7ed-11e6-90b0-5b8b5680b48e.png)

sudo dlv debug main.go
could not launch process: error waiting for thread stop -268435459

![image](https://cloud.githubusercontent.com/assets/2403591/21833442/1df69666-d7ed-11e6-8354-68f274a8bdfd.png)

on vscode IDE

![image](https://cloud.githubusercontent.com/assets/2403591/21833460/3a841696-d7ed-11e6-8ab7-8494cb49f4c7.png)

I can find the dlv in Terminal
![image](https://cloud.githubusercontent.com/assets/2403591/21833472/4b3857c2-d7ed-11e6-9fb1-1a076f57777c.png)

What's the problem? Hope someone help me, Thanks a lot!

**Comment by ramya-rao-a** [comment] 2017-01-11 06:21
I can't say much about the error that you see when you run `dlv` from the command line, 

For the error that you see in VS Code, can you set the GOPATH in the env field in the launch.config and try again?
```
"env": {"GOPATH": "/Users/huanghaitao/go"}
```

**Comment by skeleton1231** [comment] 2017-01-11 07:19
@ramya-rao-a 

my lanuch.json

{
    "version": "0.2.0",
    "env": {"GOPATH": "/Users/huanghaitao/go"},
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 6688,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/src/calc/",
            "env": {},
            "args": [],
            "showLog": true
        }
    ]
}

I use homebrew to reinstall go and delve

![image](https://cloud.githubusercontent.com/assets/2403591/21839091/dbfd79ae-d810-11e6-90d4-5fcf5734373f.png)

It works now on Terminal

![image](https://cloud.githubusercontent.com/assets/2403591/21839108/fe0af788-d810-11e6-895d-d02fa8c64f04.png)

But still debug error on Vscode

![image](https://cloud.githubusercontent.com/assets/2403591/21839123/13d896ce-d811-11e6-9256-7a2abe3c6afb.png)

2017/01/11 15:10:57 server.go:73: Using API v1
2017/01/11 15:10:57 debugger.go:66: launching process with args: [/Users/huanghaitao/go/src/calc/debug]
could not launch process: could not fork/exec

**Comment by ramya-rao-a** [comment] 2017-01-11 19:29
Well, atleast the error is different :)
Now VS Code is able to launch delve, delve is giving those errors 

@derekparker Do you know in which scenario will dlv give these errors?
![image](https://cloud.githubusercontent.com/assets/16890566/21863142/1c10ec26-d7f1-11e6-84db-9d3848e97903.png)

**Comment by ramya-rao-a** [comment] 2017-01-11 20:56
After a bit more digging this is what I found.

First off, this issue is a duplicate of #269
And related to https://github.com/derekparker/delve/issues/357

@skeleton1231 Can you go through both these issues and see if the steps there help you at all?

**Comment by skeleton1231** [comment] 2017-01-12 06:55
@ramya-rao-a 

see #717, I solved the problem. thanks!

**Closed** 2017-01-12 06:55 UTC

**Comment by ramya-rao-a** [comment] 2017-01-12 07:10
@skeleton1231 You have linked the same issue :) I am guessing you meant https://github.com/Microsoft/vscode-go/issues/20#issuecomment-272090465 solved it for you
