### ISSUE TITLE
go build fails exclusively in VSC with "cannot import absolute path" error

### ISSUE THREAD

**Issue by TheMidona** [Microsoft/vscode-go#894] opened 2017-03-30 20:07 UTC
VSC Version 1.10.2 (1.10.2)
vscode-go 0.6.57
Go Version 1.8
macOS 10.12.3

gopath is set to "/Users/username/Google Drive/Development workspace/Go"

What did I expect to happen?
When using the VSC plugin it would build to code and correctly identify errors during the build proccess

What is instead happening?
The build fails at the first line presenting the following text in the output
>Finished running tool: /Users/username/Google Drive/Development workspace/bin/golint
>Finished running tool: /usr/local/bin/go build -o /var/folders/41/80twk3lx42b9nkmrq1ybgjz40000gn/T/go-code-check -tags "" /Users/username/Google Drive/Development workspace/Go/src/github.com/TheMidona/project can't load package: package /Users/username/Google Drive/Development/workspace/Go/src/github.com/TheMidona/project: import "/Users/username/Google >Drive/Development workspace/Go/src/github.com/TheMidona/project": cannot import absolute path

The error is exclusive to VSC, go build works perfectly fine everywhere else.
I am very unsure what the issue is or if I am leaving enough information, sorry for bothering but I have been unable to find a solution to this by going through issues or googling, for all I know it might not be related to vscode-go.

**Comment by Urethramancer** [comment] 2017-03-30 21:04
Happening to me too. Have to build via command line to build any of my projects. Every project has one file showing an error line under the package declaration:
![Weird, erroneous error](http://con.structive.net/cannotimport.jpg)

**Comment by hasSalil** [comment] 2017-03-30 21:45
Looks like I've opened this issue in duplicate here: https://github.com/Microsoft/vscode-go/issues/895
For now, I suggest using the workaround in the issue description there

**Comment by ramya-rao-a** [comment] 2017-03-30 23:53
I cannot repro the issue, but I have a pretty good guess at the root cause for which I have committed the fix to master.

Can any of you build from the master and confirm that the fix works?

**Comment by ramya-rao-a** [comment] 2017-03-31 04:08
Since I am not able to repro, can you uninstall the Go extension you have, and install it using the [Go-0.6.58.vsix](https://github.com/Microsoft/vscode-go/blob/master/Go-0.6.58.vsix) to confirm if the fix works for you?

**Comment by TheMidona** [comment] 2017-03-31 05:09
That does indeed fix the issue for me, thank you very much!

**Comment by ramya-rao-a** [comment] 2017-03-31 05:14
@TheMidona Great!

@hasSalil I'll wait for the confirmation that this fixes your issue #895, after that will release an update tomorrow.

@TheMidona 
You should be unblocked now, so closing this issue

**Closed by ramya-rao-a** 2017-03-31 05:14 UTC

**Comment by ramya-rao-a** [comment] 2017-04-05 19:01
I just released an update (0.6.59) yesterday which has the fix
