### ISSUE TITLE
CMD-S Save file --> Chinese characters become garbled

### ISSUE THREAD

**Issue by KISSMonX** [Microsoft/vscode-go#1477] opened 2018-01-22 03:46 UTC
VSCode Version: 1.20.0-insider (d21e6a3e388897a2250cb10ae897b6481e0bd61d)
OS Version: Mac OS 10.13.2
Steps to Reproduce:
1. open/type chinese characters, and cmd-s to save
2. like gif image. 

![](https://user-images.githubusercontent.com/2876745/35203626-13660ad4-ff64-11e7-83a8-670a3bea44db.gif)

Does this issue occur when Go extensions are disabled?: No

[https://github.com/Microsoft/vscode/issues/41942](https://github.com/Microsoft/vscode/issues/41942)

**Comment by ramya-rao-a** [comment] 2018-01-23 01:00
Duplicate of #1469
See https://github.com/Microsoft/vscode-go/issues/1469#issuecomment-359302113 to get the fix before I release an update next week

**Closed by ramya-rao-a** 2018-01-23 01:00 UTC

**Comment by KISSMonX** [comment] 2018-01-23 01:53
OK. Thanks.
