### ISSUE TITLE
Multi-line strings break highlighting

### ISSUE THREAD

**Issue by hoboman313** [Microsoft/vscode-go#707] opened 2017-01-04 23:02 UTC
<img width="662" alt="screen shot 2017-01-04 at 3 01 59 pm" src="https://cloud.githubusercontent.com/assets/595980/21662503/cbb914ea-d28e-11e6-8ad6-a257e18360b9.png">

**Comment by ramya-rao-a** [comment] 2017-01-04 23:59
Closing as duplicate of #666. Its an upstream issue and folks at atom/language-go are looking into it

**Closed by ramya-rao-a** 2017-01-04 23:59 UTC

**Comment by hoboman313** [comment] 2017-01-19 00:34
I don't think it's a duplicate of that particular ticket. 
It's some kind of a bad interaction between the highlighting ( linter error ) and multiline strings. I fixed the reported issue myself by removing 'string' from the variable declaration ( fixes the linter error ).

**Comment by ramya-rao-a** [comment] 2017-01-19 00:37
Oh, so you were referring to linting errors showing up in wrong places?

**Comment by hoboman313** [comment] 2017-01-19 00:52
It appears that linting errors break highlighting for the rest of the file when they're on the same line as multiline strings.
Paste:
```
	var test string = `
		test
	`
```
into vscode to see what I mean

**Comment by ramya-rao-a** [comment] 2017-01-19 06:47
This is a duplicate of #666. Even if you turn linting off, you would still see the issue with the sample code you shared. VS Code uses grammar from atom to render the colors for the text. The problem is with the grammar. 
Here is the related issue in atom https://github.com/atom/language-go/issues/103

**Comment by jpatters** [comment] 2017-04-25 18:43
I've noticed that the fix for this has been merged and released in atom (https://github.com/atom/language-go/pull/111). Any idea when we will see it fixed in vscode?

**Comment by ramya-rao-a** [comment] 2017-04-25 19:32
Nice timing @jpatters :)

I just pulled in the fix yesterday, and the fix will be available in the next Insiders build (probably tomorrow) and in the next stable build of 1.12

**Comment by jpatters** [comment] 2017-04-27 13:53
Hmmm. Just updated to 1.12.0-insider and I'm still seeing this.

**Comment by ramya-rao-a** [comment] 2017-04-27 16:12
Fixed for me. Can you share a screenshot?

<img width="348" alt="screen shot 2017-04-27 at 9 11 30 am" src="https://cloud.githubusercontent.com/assets/16890566/25492983/907c8fb2-2b29-11e7-9f2f-0f1501b12568.png">

**Comment by jpatters** [comment] 2017-04-28 10:55
That's not where the issue was for me. It happens in `var` declarations

<img width="437" alt="screen shot 2017-04-28 at 7 50 39 am" src="https://cloud.githubusercontent.com/assets/195614/25525899/897603e2-2be7-11e7-8f00-6c1b43ef7ebb.png">

Interestingly, it seems as though it is caused by a combination of `var` and `.` because the following two work

<img width="386" alt="screen shot 2017-04-28 at 7 50 53 am" src="https://cloud.githubusercontent.com/assets/195614/25525934/ae6eb27a-2be7-11e7-9943-b6d91c7fbc0a.png">

<img width="336" alt="screen shot 2017-04-28 at 7 55 09 am" src="https://cloud.githubusercontent.com/assets/195614/25526009/0d01fa0e-2be8-11e7-9567-932fd069072e.png">

**Comment by ramya-rao-a** [comment] 2017-04-28 20:03
@jpatters Nice catch.

cc @50Wliu

**Comment by 50Wliu** [comment] 2017-04-28 20:34
Could you create an issue on the language-go repository so I don't forget?

**Comment by ramya-rao-a** [comment] 2017-05-07 01:28
@50Wliu Logged https://github.com/atom/language-go/issues/120

**Comment by 50Wliu** [comment] 2017-05-07 15:52
@jpatters Is `*redis.Script` the type of the variable? (No experience with Go, so I need to make sure I understand what's going on before trying to fix it)

**Comment by ramya-rao-a** [comment] 2017-05-07 17:29
I believe so. `Script` would be the type defined in the `redis` package 
But I'll let @jpatters  confirm

**Comment by jpatters** [comment] 2017-05-08 16:09
@50Wliu That is correct. `*redis.Script` is a pointer to the `Script` type in the `redis` package.

**Comment by 50Wliu** [comment] 2017-05-09 04:58
Cool, thanks.  One more question: can there be multiple period qualifiers, such as `var test a.b.c`?

**Comment by jpatters** [comment] 2017-05-10 02:47
No. Not in that particular location (after the variable name but before the `=`).

**Comment by jpatters** [comment] 2017-06-09 02:10
Just wanted to drop back in and confirm that this is fixed and working for me now.

**Comment by ramya-rao-a** [comment] 2017-06-09 05:09
Thanks for circling back @jpatters
