### ISSUE TITLE
Go to Symbol in File doesn't prefer exact matches

### ISSUE THREAD

**Issue by willfaught** [microsoft/vscode-go#1809] opened 2018-07-25 21:35 UTC
<img width="375" alt="screen shot 2018-07-25 at 2 33 02 pm" src="https://user-images.githubusercontent.com/63830/43228932-df4cf128-9017-11e8-921e-15066bc8e372.png">

Wasn't sure if this is an extension issue or a vscode issue.

**Comment by lggomez** [comment] 2018-07-29 03:43
The extension exposes a symbol provider so it should be [solvable](https://github.com/Microsoft/vscode-go/blob/master/src/goSymbol.ts) on our side

I may give this a try

**Comment by lggomez** [comment] 2018-07-29 05:29
I think that this behavior is intended since method receivers are components of the symbol, consider these two examples:

Regular methods
``` go
package main

func addRecentSearchesComponent(a string, b string, c string, d string) string {
	return a + b
}

func addSearchComponent(a string, b string, c string, d string) []byte {
	return []byte(a + b)
}

func main() {
}
```

Struct methods with value/pointer receiver:
``` go
package main

type Test struct {
	base string
}

func (t *Test) addRecentSearchesComponent(a string, b string, c string, d string) string {
	return t.base + a + b
}

func (t *Test) addSearchComponent(a string, b string, c string, d string) []byte {
	return []byte(t.base + a + b)
}

func main() {
}@(*Test).addsearchcomponent`

```

Searching for `addsearchcomponent` will work as intended on the first example, with the exact match highlighted. For the second example, `(*Test).addsearchcomponent` does the trick

It makes sense that the query with receivers won't get an exact match since the type itself is part of the symbol, but we could still handle the special case of this example, in which only an exact suffix match is found on the workspace symbols, and highlight that one

What's your take on this @ramya-rao-a ?

**Comment by ramya-rao-a** [comment] 2018-07-30 23:42
> It makes sense that the query with receivers won't get an exact match since the type itself is part of the symbol, but we could still handle the special case of this example, in which only an exact suffix match is found on the workspace symbols, and highlight that one

Can you elaborate on this?

Extensions only control the data passed to VS Code, when VS Code asks for symbols. The fitlering, sorting, matching takes place in VS Code. So, I dont follow how we can handle this case

**Comment by lggomez** [comment] 2018-08-02 19:31
I see it [traverses](https://github.com/Microsoft/vscode-go/blob/master/src/goSymbol.ts#L35) the results from the query so I assumed the highlighted result could be changed from our provider but, as you say, it looks like it isn´t

My idea was to follow @willfaught case in which only one exact suiffix (because of the method receiver) matches, and highlight that one over the rest of the fuzzy matches

**Comment by ramya-rao-a** [comment] 2019-07-06 18:58
Combining the examples from @lggomez and using the below sample with the latest version of VS Code and this extension, I see the right option being pre-selected

<img width="514" alt="Screen Shot 2019-07-06 at 11 57 12 AM" src="https://user-images.githubusercontent.com/16890566/60760137-365e7d00-9fe5-11e9-9166-579a7db36163.png">

@willfaught Was your issue the fact that the right option was not pre-selected or that the right option is not the first in the list?

```go
package main

func addRecentSearchesComponent(a string, b string, c string, d string) string {
	return a + b
}

func addSearchComponent(a string, b string, c string, d string) []byte {
	return []byte(a + b)
}

// Test I am
type Test struct {
	base string
}

func (t *Test) addRecentSearchesComponent(a string, b string, c string, d string) string {
	return t.base + a + b
}

func (t *Test) addSearchComponent(a string, b string, c string, d string) []byte {
	return []byte(t.base + a + b)
}

func main() {
}
```

**Comment by willfaught** [comment] 2019-07-08 23:41
@ramya-rao-a I think the issue is more that it wasn't pre-selected. If it was at the top of the list, but it still wasn't pre-selected, I would have had the same issue with it. Basically, if there's an exact match for a full method name, we should be able to press Enter and use it. So if it works now as you showed, that seems like a fix to me!

**Comment by ramya-rao-a** [comment] 2019-07-10 01:46
Great, will close this issue then, Thanks @willfaught!

And thanks to @lggomez for the code samples :)

Happy Coding!

**Closed by ramya-rao-a** 2019-07-10 01:46 UTC
Labels: needs more info
