### ISSUE TITLE
Gopls corrupting files on save

### ISSUE THREAD

**Issue by gittim** [microsoft/vscode-go#3027] opened 2020-02-04 16:40 UTC
Please direct general questions to:
- [Gitter](https://gitter.im/Microsoft/vscode-go)
- [Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [Wiki](https://github.com/microsoft/vscode-go/wiki) before filing an issue.
Helpful pages include:
- [GOPATH](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension)
- [Module Support](https://github.com/microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code)
- [Debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code)
	- Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.7 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- windows amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "files.autoSave": "afterDelay"

### Describe the bug
Following on from a thread by @johneboldt, I seem to have the same problem, which wasn't fixed by updating gopls - see below.

Pressing ctrl-S to save caused Go file corruption, eg. (correct, corrupted):

func (c *Cache) HandlePktImpl(pkt []byte) *StreamData {
//timrSafeStop(&(c.timrGC))
corrupts to:
func (c *Cache) andlePktImpl(pkt []byte) *StreamData {
/timrSafeStop(&(c.timrGC))

Note missing 'H' and forward slash.

This has only started happening in the last few days, following months of no problem. I've just tried uninstalling Go and VS Code, deleting the .vscode directory where the settings are stored, deleting the go/bin directory, then reinstalling everything. Problem only seems to occur when I install gopls.

**Comment by stamblerre** [comment] 2020-02-04 16:54
Can you share your `gopls` logs from a session where it was corrupted? Information on how to capture `gopls` logs can be found here: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs.

**Comment by gittim** [comment] 2020-02-04 17:10
Here they are, good luck :-)

[Trace Information.txt](https://github.com/microsoft/vscode-go/files/4154831/Trace.Information.txt)
[RPC Information.txt](https://github.com/microsoft/vscode-go/files/4154832/RPC.Information.txt)
[metrics.txt](https://github.com/microsoft/vscode-go/files/4154833/metrics.txt)
[GoPls version information.txt](https://github.com/microsoft/vscode-go/files/4154834/GoPls.version.information.txt)
[GoPls memory usage.txt](https://github.com/microsoft/vscode-go/files/4154835/GoPls.memory.usage.txt)

**Comment by stamblerre** [comment] 2020-02-04 17:18
Thank you for these, but I was actually referring to the `gopls` logs that can be found in the VS Code output window. You can find these by navigating to View -> Output (or Ctrl+K Ctrl+H). There will be a drop-down menu titled Tasks in the top-right corner. Select the gopls item, which will contain the gopls logs.

**Comment by gittim** [comment] 2020-02-04 17:52
Ah, I see now. I'm reluctant to post all the output because it includes a lot of source code. I've tried to create a small test program, which seems to be not failing (typical!). I'll get back with an update as soon as I can.

**Comment by stamblerre** [comment] 2020-02-04 18:01
Makes sense - please don't share any logs if they are for a private repository. You may also want to remove the `go.formatTool` setting since it's not necessary with `gopls`, and add the following settings:

```json5
"[go]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true,
    }
}
```

Also, make sure that you don't have any other tools or extensions that might be running something on save.

**Comment by johnmccabe** [comment] 2020-02-04 21:07
@gittim goplus 0.3.1 was release about 3 hours ago - https://github.com/golang/tools/releases/tag/gopls%2Fv0.3.1

I've just updated and that release has fixed the problem for me (also on Windows 10)

**Comment by gittim** [comment] 2020-02-05 13:18
Thanks. Installed, & no further errors so far.

**Comment by stamblerre** [comment] 2020-02-05 18:26
Thanks for following up! Please comment here if you see this again.

**Comment by debojyoti-majumder** [comment] 2020-02-06 05:39
I have seen this issue also. My settings.json is very simple it has 
    "go.formatTool": "goimports",
    "go.useLanguageServer": true

When I am saving a go file, few character in the import section is getting delete
for example if I have 

import (
	"fmt"
	"github.com/debojyoti-majumder/testapp"
)

it becomes this 
import (
	"fmt"
	
         github.com/debojyoti-majumder/testapp"
)

**Comment by stamblerre** [comment] 2020-02-06 19:58
@debojyoti-majumder: What is the output of `gopls version`?

**Comment by debojyoti-majumder** [comment] 2020-02-07 09:48
@stamblerre This is the output I got
gopls version
golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=

**Comment by gittim** [comment] 2020-02-07 11:33
It's started corrupting again. Once it starts, every time i hit ctrl-S, more corruption happens. It was OK until mid morning. Here's the log: everything was fine until the time was sometime after 11:00 in the file. Some of the errors appear to be legit as part of my Go writing (syntax errors, debugger errors etc.).
[corruptlog.txt](https://github.com/microsoft/vscode-go/files/4170530/corruptlog.txt)

**Comment by stamblerre** [comment] 2020-02-07 22:31
@gittim: Thanks for sharing the log. It looks like the "no snapshot for file" errors are coming from `textDocument/didChange`, which implies that somehow `gopls` is not able to process the changes to your file. Are you starting `gopls` from the `d:\code\go\src\proj\` directory?

**Comment by stamblerre** [comment] 2020-02-07 22:33
@debojyoti-majumder: If you could share your logs for an instance when `gopls` corrupts your files that would be helpful in diagnosing this issue. See https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs for details on how to capture those logs.

**Comment by stamblerre** [comment] 2020-02-07 22:56
I've reopened the upstream issue in `gopls`: https://github.com/golang/go/issues/34955. Please comment there with logs, if you are able to provide them.

**Comment by stamblerre** [comment] 2020-02-07 22:59
Also, please add the following settings to your VS Code configuration if you are willing to provide more detailed logs.

```json5
"go.languageServerFlags": [
  "-rpc.trace"
]
```

**Comment by gittim** [comment] 2020-02-08 09:45
I've sent more detailed logs to @stamblerre by email. In summary, I have the latest VS Code & gopls installed as of the morning. I can induce the error immediately, by opening a directory in the project, scrolling down to the first block of code (past the comments), and hitting ctrl-S. Each time I do so, characters are removed; first some whitespace between a const variable name & its value them, characters from the code itself. I can repeat this by reverting the (uncommitted) change in Git, & doing it again.​

I'm running gopls from e:\code\bin

**Comment by stamblerre** [comment] 2020-02-10 19:46
Thanks for sending the logs along, @gittim. I took a look, and there is clear evidence that something is going wrong - `textDocument/codeAction` responses are always being sent for version 1 of your file, even when the version has increased. There are also error messages after `textDocument/didChange` events, while leads me to believe that `gopls` does not think that you file is "part" of your workspace.

**Comment by gittim** [comment] 2020-02-10 20:59
I've got goals.exe in e:\code\bin (I have two machines: one uses d: & the other e:) I may be quoting logs from both. In both cases, the Windows system, Program Files, users etc. are on c: & the code is on d: or e:. I definitely have only one copy of goals - there aren't multiples. The relevant go env parts:
set GOBIN=
set GOCACHE=C:\Users\Tim\AppData\Local\go-build
set GOENV=C:\Users\Tim\AppData\Roaming\go\env
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64

Windows 10/64 is fully up to date with all release-channel updates, & there is no 3rd party anti-virus s/w on either machine. Both have the latest release of VS code, both have various versions of Go 1.13. One also has Visual Studio 2017 Pro, & the other VS 2019 Enterprise.

Regarding the workspace, I have e:\code\src\go\proj with several subdirectories under there for its packages. I'm not opening a VS Code project; I simply open the containing directory: there will be go files open in VS code from that directory, & probably from its peers.

I tried again today in an Ubuntu VM, & didn't see the error. However in the Windows host, I can generate the errors every time I hit ctrl-S. I did wonder if it could be confusion with cr vs crlf line endings, or utf8 or mixed encoding but I don't think so. The corruption seems quite widespread; there's at least one character removed from most lines - sometimes the first character, mostly seemingly at random from the middle of words.

Happy to run further debug tests if it helps.

**Comment by stamblerre** [comment] 2020-02-11 17:33
Thank you for the additional detail. I believe I've figured out the issue and have a fix for it. If you and other affected users could try applying the patch before it is merged to confirm that it fixes the issue, that would be very helpful. Here are the steps to do so:

```shell
$ git clone https://go.googlesource.com/tools
$ cd tools
$ git fetch "https://go.googlesource.com/tools" refs/changes/59/218859/3 && git cherry-pick FETCH_HEAD
$ cd gopls
$ go install
```

**Comment by stamblerre** [comment] 2020-02-11 18:49
The change is now merged, so `gopls` can instead be downloaded by running `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`.

**Comment by gittim** [comment] 2020-02-12 09:29
Thanks! Just tried this & it appears OK now - ctrl-S no longer corrupts the flie outside the main view. I won't have time to test again until later today (UK time), but seems stable so far.

**Comment by stamblerre** [comment] 2020-02-12 17:22
Great, thank you for following up! This fix will be part of the `gopls/v0.3.2` release.

**Comment by johneboldt** [comment] 2020-02-12 17:36
@stamblerre when I reported this bug, I really thought it was an environmental issue on my machine. It looks like it really was a core bug. Thanks for all your help on this!!!

**Comment by stamblerre** [comment] 2020-02-12 19:24
Thank you for the report! `gopls/v0.3.2-pre1` is now available, if you'd like to download it (`GO111MODULE=on go get golang.org/x/tools/gopls@v0.3.2-pre1`).

**Comment by galenwarren** [comment] 2020-02-17 15:43
I'm having the same corruption issues with gopls and VS Code and, unfortunately, they still persist after installing the 0.3.2-pre1 version. The issue is that it scrambles the import strings on save.

**Comment by stamblerre** [comment] 2020-02-18 17:42
@galenwarren: Can you provide the information requested [here](https://github.com/golang/go/issues/34955#issue-508583788)? `gopls` logs would be particularly helpful here.

**Comment by galenwarren** [comment] 2020-02-20 14:41
Sorry for the delay -- I'm working on this project today and will try to capture some information for you. Thanks!

**Comment by galenwarren** [comment] 2020-02-20 15:09
I uploaded the requested information [here](https://github.com/golang/go/issues/34955#issuecomment-589097131). Thanks!

**Comment by stamblerre** [comment] 2020-02-25 23:15
Closing this in favor of the upstream issue. Please comment on https://github.com/golang/go/issues/34955 if you encounter this bug.

**Closed by stamblerre** 2020-02-25 23:15 UTC
Labels: needs more info, upstream-gopls
