### ISSUE TITLE
Updating version from 0.6.57 from 0.6.55 does not support symlinking directories into GOPATH

### ISSUE THREAD

**Issue by hasSalil** [Microsoft/vscode-go#895] opened 2017-03-30 21:41 UTC
VSC Version 1.10.2 (1.10.2)
vscode-go 0.6.57
Go Version go1.7 darwin/amd64
macOS 10.11.5

I have a project that uses relative import paths. My workaround for this has been to symlink the project root directory to $GOPATH/src/{project-root}.

In previous version this worked fine because the assumed 'current go workspace' or the 'current go path' always defaulted to the first path set in the $GOPATH env variable

I suspect that this code is responsible for no longer supporting symlinking into that path:
https://github.com/Microsoft/vscode-go/compare/01e959cba61195d257d4b1567528b5300f97bdb2...master#diff-8cd4968b81985f0efc2053eabc37db6dR260

the second line in that function
`let currentWorkspace = '';` used to be
`let currentWorkspace = path.join(workspaces[0], 'src');` as defined here https://github.com/Microsoft/vscode-go/compare/01e959cba61195d257d4b1567528b5300f97bdb2...master#diff-9695701e3f6cbcdcdaac96d29e6a08e6L49

Currently my work around is to create a new workspace that looks like /path/to/new/workspace/src/{symlinked old workspace root here} and appending
/path/to/new/workspace to the GOPATH

This is somewhat inconvenient, and it would be nice if the new function could go back to using the first path in GOPATH as the default current go workspace

**Comment by ramya-rao-a** [comment] 2017-03-30 23:54
I cannot repro the issue, but I have a pretty good guess at the root cause for which I have committed the fix to master.

Can you build from the master and confirm that the fix works?

**Comment by ramya-rao-a** [comment] 2017-03-31 04:15
Since I am not able to repro, can you uninstall the Go extension you have, and install it using the [Go-0.6.58.vsix](https://github.com/Microsoft/vscode-go/blob/master/Go-0.6.58.vsix) to confirm if the fix works for you?

- Uninstall Go extension
- Download the vsix file [Go-0.6.58.vsix](https://github.com/Microsoft/vscode-go/blob/master/Go-0.6.58.vsix) 
- Run `code --install-extension Go-0.5.58.vsix` from the location where you downloaded the file

**Comment by ramya-rao-a** [comment] 2017-04-04 19:07
This is fixed in the latest update thats been rolled out 0.6.59

**Closed by ramya-rao-a** 2017-04-04 19:07 UTC
