### ISSUE TITLE
Find all references doesn't include function definition

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#562] opened 2016-10-26 20:06 UTC
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

Find all references only displays usages, not function definition
![image](https://cloud.githubusercontent.com/assets/762848/19743114/d6d19e40-9b7c-11e6-8d50-a5c5992471e5.png)

**Comment by ramya-rao-a** [comment] 2016-10-26 21:47
That was by design by @lukehoban. To have parity with other languages we might want to include the function definition

**Comment by ramya-rao-a** [comment] 2016-10-28 21:32
@lukehoban Can you share the reason behind the original design to exclude definitions from references?

**Comment by lukehoban** [comment] 2016-10-28 22:02
I'm actually not sure the original design did exclude definitions.  We did chance from using `go-find-references` (a tool I wrote) to using `guru` (a tools maintained by the Go team) back in May.  It's possible this was a result of that change.  See https://github.com/Microsoft/vscode-go/issues/340 for example.

I think it's fine to reconsider that design - though it may make sense to align with guru, and request changes to the behaviour of guru if needed.

**Comment by ramya-rao-a** [comment] 2016-10-29 00:05
@lukehoban Actually `guru` does return the definition as well.

For example: In https://github.com/golang/example, open the `hello.go` file and Find all references for the `Reverse` function. 
`guru` returns 3 results

![image](https://cloud.githubusercontent.com/assets/16890566/19825639/96fdd4c2-9d30-11e6-8870-2a06bc3b0bee.png)

But the [regex](https://github.com/Microsoft/vscode-go/blob/master/src/goReferences.ts#L50) we use discards the one with the definition

**Comment by lukehoban** [comment] 2016-10-29 01:10
Interesting. I don't recall that being intentional, but it does look like we modified the regex specifically to handle Oracle/Guru. https://github.com/Microsoft/vscode-go/commit/509d6abbe360319596d44eeebfb7917832d89dbb

I think it's fine to update the regex to include the definition if that matches the standard vscode experience for TS and other languages.

**Comment by ramya-rao-a** [comment] 2016-10-31 01:30
@alandonovan Any reason the output of `guru referrers` has different format for the definition vs other references? The definition just has the starting position where as rest of the references have starting AND ending position

Definition   : **filename**:**lineNumber**:**columnNumber**: ...
Others : **filename**:**lineNumberStart**.**columnNumberStart**-:**lineNumberStart**.**columnNumberStart**: ...

An example is shown here: https://github.com/Microsoft/vscode-go/issues/562#issuecomment-257056409

Because of this, the editor needs to add extra logic to be able to highlight the word for which references was queried

**Comment by alandonovan** [comment] 2016-10-31 14:32
Fixed by https://go-review.googlesource.com/c/32440/ (pending).

**Comment by ramya-rao-a** [comment] 2016-10-31 22:32
Its fixed ! Thanks @alandonovan 

Anyone reaching this thread, you can update your `guru` tool to get this fix
`go get -u -v golang.org/x/tools/cmd/guru`

**Closed by ramya-rao-a** 2016-10-31 22:32 UTC
Labels: bug, upstream
