### ISSUE TITLE
"debug this test" option from editor not parsing flags

### ISSUE THREAD

**Issue by lfourky** [microsoft/vscode-go#2894] opened 2019-11-07 19:42 UTC
**Describe the solution you'd like**
I would like to be able to pass flags to the debugger when debugging from the editor.

**Describe alternatives you've considered**
I was able to run `dlv` and pass flags to it from the terminal, so I guess there must be a way to pass flags when using the "debug this test" from the editor, as well.

Example code that I would like to be able to debug from editor:
https://play.golang.org/p/5eZhpWSmhmp

**Comment by BojanKomazec** [comment] 2019-11-14 10:52
@lfourky Are you passing flag via `args` property in `launch.json`? You should have something like:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": ["-f=flag_value_placeholder"]
        }
    ]
}
```
I am able to pass flag value to tests and debug them from VSCode with this in place.

**Comment by lfourkyataxiom** [comment] 2019-11-14 12:36
I have! Since @BojanKomazec and I had a conversation outside of this, we've come to the conclusion that debugging the tests by using the `F5 command` or selecting `Debug -> Start Debugging (F5)` from the menu bar in VSCode works - the flags get parsed!

However, the issue still remains, when pressing the `"debug test"` option just above a specific test, the flags don't get parsed.

**Comment by BojanKomazec** [comment] 2019-11-14 12:43
Seems this issue has already been filed: https://github.com/Microsoft/vscode-go/issues/2115

**Comment by lfourky** [comment] 2019-11-14 17:28
I have tried to add the flag to "args", yes. Since @BojanKomazec and I had a conversation outside of this, we've come to the conclusion that debugging the tests by using the `F5 command` or selecting `Debug -> Start Debugging (F5)` from the menu bar in VSCode works - the flags get parsed!

However, the issue still remains, when pressing the `"debug test"` option just above a specific test, the flags don't get parsed. 

EDIT: Sorry, haven't seen the duplicate issue before. However, it's still ongoing, and I'm happy to provide any feedback if needed.

**Comment by ramya-rao-a** [comment] 2019-11-15 04:57
The flags provided in the debug configuration in the launch.json file do not get used by the `debug test` code lens that appears above individual tests.

But the ones that get passed to `go.testFlags` should definitely get used. Have you tried that?

**Comment by ramya-rao-a** [comment] 2019-11-15 04:57
If you are specifically looking for `args` that should get passed, then #2115 is indeed tracking this case and we can close this issue

**Closed by ramya-rao-a** 2019-11-15 04:57 UTC

**Comment by BojanKomazec** [comment] 2019-11-15 10:24
Thanks @ramya-rao-a for the `go.testFlags` hint. @lfourky I can confirm that particular test is able to pick passed flags if run via code lens if your `settings.json` contains the above mentioned property and looks like:
```
{
   ...
   "go.testFlags": ["-f=flag_value_placeholder"],
   ...
}
```

**Comment by lfourky** [comment] 2019-11-15 23:38
Thanks everyone. @ramya-rao-a I was not looking for `args` specifically, I just need a way to pass flags when debugging specific test functions. Will continue the discussion there, though!
