### ISSUE TITLE
Syntax error :=

### ISSUE THREAD

**Issue by apovetkin** [Microsoft/vscode-go#1487] opened 2018-01-29 19:34 UTC
VSCode Version: 1.19.2
OS Version: 10.0.14393

Steps to Reproduce:

Watch the video with the issue
https://youtu.be/Iew17mpwSCw

In VS Code use i := 1

Does this issue occur when all extensions are disabled?: Yes/No
I disabled the GO extension and no problems after that

**Comment by ramya-rao-a** [comment] 2018-02-01 03:06
In the video I see that on saving the file `i := 1` gets changed to `i: =1` which of course is wrong and results in the error
I believe you have some other extension installed thats doing this change

Can you disable all other extension and see if you are still facing the issue?

**Comment by apovetkin** [comment] 2018-02-01 17:13
In the video all extensions are disabled and only this GO extension enabled.

I thought about this situation from beginning and disabled all extensions.

Any other idea?

Thanks,
Alex
________________________________

**Comment by ramya-rao-a** [comment] 2018-02-01 18:13
Hmm... that is weird

Can you enable just the Go extension and then add the below in your settings and try again?
```
"[go]": {
    "editor.formatOnSave": false
}
```

**Comment by apovetkin** [comment] 2018-02-01 18:36
Please watch the video, change quality to 720

https://youtu.be/C81BAfdKWrI
[https://i.ytimg.com/vi/C81BAfdKWrI/maxresdefault.jpg]<https://youtu.be/C81BAfdKWrI>

GO Extension - Format on save<https://youtu.be/C81BAfdKWrI>
youtu.be


Thanks,
Alex

________________________________

**Comment by ramya-rao-a** [comment] 2018-02-01 19:28
I see that disabling format on save fixed the issue.

We use `goreturns` as a formatter. Can you run it in the terminal on your file and see if it does the same?

**Comment by apovetkin** [comment] 2018-02-01 19:34
I see that disabling format on save fixed the issue. - RIGHT.

We use goreturns as a formatter. Can you run it in the terminal on your file and see if it does the same?

[cid:dab41bc9-f196-42bc-a09c-d46aa15aa3b8]


________________________________

**Comment by n1koo** [comment] 2018-02-09 16:01
I was hitting the same issue and after some head scratching found that https://github.com/TheColorRed/vscode-format collides. Weirdly enough only on some (go) packages, but not all of them. Uninstalling `vscode-format` fixed it for me 🤷‍♂️

**Comment by ramya-rao-a** [comment] 2018-03-16 18:10
@n1koo Thanks for that information!
@apovetkin I am assuming your issue as the same root cause as @n1koo and am closing this issue. Feel free to re-open it if its not the case

**Closed by ramya-rao-a** 2018-03-16 18:10 UTC
Labels: needs more info
