### ISSUE TITLE
"Unexpected end of input" error.

### ISSUE THREAD

**Issue by arashbina** [Microsoft/vscode-go#233] opened 2016-03-08 10:36 UTC
Since updating VS Code to 0.10.10 if during the debugging an error is generated I get the following message: "Unexpected end of input. Stopping the debug adapter."

The debugging stops however the process still is running and would have to be killed from shell.

**Comment by egamma** [comment] 2016-03-08 10:37
FYI @weinand

**Comment by arashbina** [comment] 2016-03-08 15:29
This had disrupted my work so I downloaded 0.10.9 on Mac OS again to test. I can confirm that this does not happen on 0.10.9.

**Comment by liuliuhappy** [comment] 2016-03-09 07:50
FROM 0.10.9 TO 0.10.10, my error message is :"Unexpected token h. Stopping the debug adapter."

**Comment by weinand** [comment] 2016-03-09 07:59
@lukehoban In VS Code 0.10.10 we started to report syntax errors that occur when parsing the json messages received via 'stdout' from the debug adapter. One reason for these errors is a debug adapter that sends arbitrary output to 'stdout' which corrupts the debug protocol messages.

**Comment by lukehoban** [comment] 2016-03-09 16:25
@weinand Got it.  That might explain another issue that's been open for awhile. What is the contract for the messages sent to stdout?

**Comment by weinand** [comment] 2016-03-09 16:30
@lukehoban since VS Code communicates with a debug adapter through stdin/stdout, a debug adapter must not use stdout for anything else. You can freely send output to stderr (which will appear on the VS Code dev tools console).

**Comment by lukehoban** [comment] 2016-03-09 19:42
Okay - I have a fix for this - but I haven't been able to repro the problem myself so I can't verify that I've fixed it.  

Does anyone have a standalone repro?  

@arashbina You mentioned that this happens if "an error is generated" during debugging.  What did you mean by that?

**Comment by lukehoban** [comment] 2016-03-09 20:05
This should be fixed with https://github.com/Microsoft/vscode-go/commit/3583c0f68bc6f8ed01be8986e9db9780bc02a65c and in release `0.6.32` which is available now.

I was able to repro the original issue with `"Unexpected end of input"` - just have a type error in the program so that it won't build.  That is fixed now.

I was not able to repro the `"Unexpected token h. Stopping the debug adapter."` issue from @liuliuhappy.  I expect it is also addressed with this fix, but please confirm if you can.

**Comment by lukehoban** [comment] 2016-03-09 20:23
Unfortunately - it looks like this may not be fixed after all.

@weinand With the exact same bits installed in the extension and available in my local development environment, I'm seeing that setting `"debugServer": 4711` to debug against my development environment doesn't produce this error, but leaving it off and using the installled debugAdapter does produce this error.  

I'm not sure how to test the debugAdapter behaviour for this condition if I can't reproduce it in the debug environment.  I'm also no longer 100% sure of what actual problem VS Code is seeing with the data coming back from the debugAdapter anymore.

Is there anyway to get more insights on what's going wrong here?

**Comment by lukehoban** [comment] 2016-03-09 20:37
Continuing to look into this.

As far as I can tell:
* The original issue in this bug report of having a build error in the code leading to this notification does appear to be fixed in `0.6.32`.
* The issue in #206, which I thought was the same thing, is not fixed in `0.6.32`, but only repros when not debugging the debugAdapter.

So I'll leave this issue closed, and will reactivate 0.6.32.  If anyone is still seeing this error after installing `0.6.32`, please include a repro case on this thread.

**Closed by lukehoban** 2016-03-09 20:37 UTC

**Comment by weinand** [comment] 2016-03-09 21:07
@lukehoban when your debug adapter runs in server mode, VS Code communicates via a socket (which is independent from the stdin/stdout pipe). So sending output to stdout cannot corrupt the debugging protocol. In non-server mode VS Code uses a stdin/stdout pipe which can become corrupted by the unexpected output.

**Comment by lukehoban** [comment] 2016-03-09 21:10
Thanks - that explains why the results are different.

But it sounds like the issue in #206 is still a separate problem which is only present in non-server mode.
