### ISSUE TITLE
Output pane keeps opening to show errors while typing when language server is enabled

### ISSUE THREAD

**Issue by moxuz** [Microsoft/vscode-go#1662] opened 2018-05-06 21:04 UTC
I'm starting a new Go project and I'm constantly getting any errors (even while I'm in the middle of typing) pop open the output terminal.

Here is an example of what happens when starting to assign a new variable. As I type it decides that the code isn't valid (which it is not, but I'd rather the linter just underline the curly brace [which it does] than the terminal open up).

<img src="https://dl.dropboxusercontent.com/s/vwvq19dsuu0vpxz/Screenshot%202018-05-06%2013.58.18.png?dl=0" alt="terminal open" WIDTH="900">

Here are the logs the output terminal is showing me
```
langserver-go: reading on stdin, writing on stdout
Passing an initialize rootPath URI ("file:///Users/christophepouliot/go/src/github.com/moxuz/price-protection-notifier") is deprecated. Use rootUri instead.
[Error - 1:54:56 PM] Request textDocument/documentSymbol failed.
  Message: /Users/christophepouliot/go/src/github.com/moxuz/price-protection-notifier/db/db.go:28:1: expected operand, found '}'
  Code: 0 
[Error - 1:54:57 PM] Request textDocument/documentSymbol failed.
  Message: /Users/christophepouliot/go/src/github.com/moxuz/price-protection-notifier/db/db.go:28:1: expected operand, found '}'
  Code: 0 
[Error - 1:55:00 PM] Request textDocument/documentSymbol failed.
  Message: /Users/christophepouliot/go/src/github.com/moxuz/price-protection-notifier/db/db.go:28:1: expected operand, found '}'
  Code: 0 
[Error - 1:55:28 PM] Request textDocument/hover failed.
  Message: /Users/christophepouliot/go/src/github.com/moxuz/price-protection-notifier/db/db.go:28:1: expected operand, found '}'
  Code: 0 
```

Here are the settings I use for VSCode Go

```json
"go.useLanguageServer": true,
  "go.formatTool": "goimports",
  "go.vetOnSave": "off",
  "go.lintTool":"gometalinter",
  "go.lintFlags": [
    "--disable=gas",
    "--disable=gotype",
    "--disable=gocyclo",
    "--fast",
    "--exclude=.pb.go",
  ],
```

I haven't had this happen to me before while using Go with VSCode so I'm a bit confused about what's happening.

VSCode version: 1.23.0
vscode-go version: 0.6.79

**Comment by qtstc** [comment] 2018-05-06 21:31
Seeing a similar problem in an existing Golang project today. vscode-go version is 0.6.79.

**Comment by moxuz** [comment] 2018-05-06 23:44
I've also noticed that a lot of times after a bunch of errors in the output my cmd+click will no longer work, and I have to close/re-open VSCode for it to start working again.

After these errors I was no longer able to cmd+click to go to the definition of anything in my file (even if the variable was defined a few lines up)
```jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for unknown file "file:///Users/christophepouliot/go/src/github.com/moxuz/price-protection-notifier/check/parse.go"
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for unknown file "file:///Users/christophepouliot/go/src/github.com/moxuz/price-protection-notifier/check/parse.go"
[Error - 4:41:31 PM] Request textDocument/documentSymbol failed.
  Message: /Users/christophepouliot/go/src/github.com/moxuz/price-protection-notifier/check/check.go:34:10: expected ';', found 'IDENT' nil (and 9 more errors)
  Code: 0 
[Error - 4:41:38 PM] Request textDocument/documentSymbol failed.
  Message: /Users/christophepouliot/go/src/github.com/moxuz/price-protection-notifier/check/check.go:34:10: expected ';', found 'IDENT' nil (and 10 more errors)
  Code: 0 ```

After restarting VSCode it works again

**Comment by sudo-suhas** [comment] 2018-05-07 06:49
This also happens when I hover on key name in keyed variable instantiation. For example, consider the following code snippet:
```go
v := MyStruct{
	Message: "value",
}
```

If I hover on `Message`, I get the following error:
```
[Error - 12:14:40] Request textDocument/hover failed.
  Message: no declaration found for Message
  Code: 0
```

This did not bother me much earlier but now the `go-langserver` output keeps opening up repeatedly(if I close it).

My `go` plugin settings:
```json
{
	"go.useLanguageServer": true,
    "go.toolsGopath": "~/installs/go-tools",
	"go.gopath": "~/dev/go",
	"go.autocompleteUnimportedPackages": true,
	"go.useCodeSnippetsOnFunctionSuggest": true,
    "go.testFlags": ["-v"],
    "go.liveErrors": {
        "enabled": true,
        "delay": 500
    }
}
``` 

Is there some editor setting which will prevent opening the output section on error?

**Comment by FryDay** [comment] 2018-05-07 16:14
This just started happening to me too. It's horribly annoying.

```
"go.useLanguageServer": true,
"go.testOnSave": true,
"go.lintOnSave": "package",
"go.coverOnSave": true,
```

**Comment by OneOfOne** [comment] 2018-05-07 20:50
I had to turn off go.useLanguageServer

**Comment by ramya-rao-a** [comment] 2018-05-07 21:06
@FryDay @sudo-suhas @moxuz The errors are coming from the language server which is weird because diagnostics is not a feature that we have enabled in the language server yet.

@slimsag @keegancsmith Errors showing up in the output pane under the language server channel is expected. But here, we see the errors showing up in the "Problems" pane which happens only if the language server has been returning diagnostics. Since when did the language server start returning diagnostics and can we have them disabled by default?

**Comment by ramya-rao-a** [comment] 2018-05-07 21:33
@OneOfOne How is #1667 which is a formatting issue related to the language server or this current issue?

I cannot repro this in the older version of the Go extension either. Also I noticed that the errors are appearing in the "Output" pane not "Problems" pane, so I've deleted my earlier comment. Will look into this more and get back soon

**Comment by ramya-rao-a** [comment] 2018-05-07 22:08
In the latest update to the Go extension, we updated the version of [vscode-languageclient](https://github.com/Microsoft/vscode-languageserver-node/tree/master/client) we use from 2.5.0 to 4.1.3 which somehow causes this issue. This is why, this issue is not repro-able in the older version of the Go extension

@dbaeumer Between versions 3.0.1-alpha.14 and 3.0.2-beta.1, some change was introduced in the language client that for every error coming from the language server, the output panel comes into view even after repeated hiding. Do you recall any feature request or bug fix that might have caused this? Can this be fixed from the language client's side or is there something that we need to do from the language server's side to fix this?

Others,
Until we figure out a fix for this, you can disable the language server by setting `go.useLanguageServer` to `false`

**Comment by dbaeumer** [comment] 2018-05-08 09:49
This got changed to make errors more visible to the user. However it can be control by the language client using the `revealOutputChannelOn` property on the `LanguageClientOptions`

**Comment by ramya-rao-a** [comment] 2018-05-08 18:20
Thanks @dbaeumer, I've added the `revealOutputChannelOn` option.

Others, To get this fix before I release an update sometime later this week, you can

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by OneOfOne** [comment] 2018-05-08 18:29
I can confirm that fixes the issue, thanks!

**Comment by ramya-rao-a** [comment] 2018-05-14 17:36
This bug is now fixed in the latest update to the Go extension (0.6.80)

**Closed by ramya-rao-a** 2018-05-14 17:36 UTC
Labels: bug
