### ISSUE TITLE
cann't change import infomation

### ISSUE THREAD

**Issue by kybom** [Microsoft/vscode-go#719] opened 2017-01-12 10:34 UTC
Once save the change import infomation ,it recovers.
Go 0.6.52
![qq 20170112183206](https://cloud.githubusercontent.com/assets/24692485/21886221/baf2e358-d8f5-11e6-8086-f43e1f853aa4.png)

**Comment by ramya-rao-a** [comment] 2017-01-12 18:56
Are you saying that when you add a new import statement and save, it disappears?

If yes, then this is due to the formatting tool. By default, the extension uses `goreturns` as the formatting tool. By default, formatting is run on save. `goreturns` removes any unused imports.
So if you add an import, but don't use it, then it will be removed.

Workaround:
Use the new import before saving
OR
Change the formatting tool to be used to `gofmt` in the settings
OR
Turn `go.formatOnSave` off in the settings

**Comment by kybom** [comment] 2017-01-13 01:40
Yes,and i cann't even delete the blank line too.
![qq 20170113093825](https://cloud.githubusercontent.com/assets/24692485/21915351/5361671c-d974-11e6-8be7-aef925db2b17.png)

**Comment by ramya-rao-a** [comment] 2017-01-13 02:37
>  i cann't even delete the blank line too.

That is also done by the formatting tool.
As a guideline, there is always a blank line between the standard packages and any third party packages

Closing this issue as by design.

**Closed by ramya-rao-a** 2017-01-13 02:37 UTC
