### ISSUE TITLE
Extension is unable to find go binary

### ISSUE THREAD

**Issue by Kannaj** [microsoft/vscode-go#2595] opened 2019-06-23 16:50 UTC
Hi guys , i've been having trouble running this extension over the past few days - I dont recall changing anything. But hover, autocomplete all seem to be failing

i get this output in particular for the linter
```
level=warning msg="Failed to discover go env: failed to run 'go env': exec: \"go\": executable file not found in $PATH"
level=error msg="Running error: context loading failed: failed to load program with go/packages: 'go list' driver requires 'go', but executable file not found in $PATH"
```

but i have specified the go path
if i switch to the vscode terminal and run `echo $PATH`

`...:/usr/local/go/bin` the go binary does seem to be present

**Comment by ramya-rao-a** [comment] 2019-06-26 04:29
Thanks for reporting @Kannaj 

Since you mentioned that this was a recent change, can you try out the previous version of the extension and let us know if things work better there?
- First, run the command `Extensions: Disable Auto Updating Extensions` to disable the auto-update of extensions feature so that you dont get automatically updated to the latest version when you install the older one 
- Download the Go-0.10.2.vsix file from https://github.com/microsoft/vscode-go/releases/tag/0.10.2
- Use the command `Extensions: Install from vsix` to install the downloaded extension
- Reload VS Code window

**Comment by Kannaj** [comment] 2019-06-26 05:48
@ramya-rao-a  - I've fallen back to 0.10.2 and everything seems to be working fine now. Please let me know if you need anymore information to fix 0.11.0

**Comment by ramya-rao-a** [comment] 2019-06-29 02:14
Thanks for the confirmation @Kannaj!

This is a regression indeed, I have pushed a fix. Can you try the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension and confirm if the fix works for you?

**Comment by ramya-rao-a** [comment] 2019-07-03 03:14
This issues is fixed in the latest update to the Go extension (0.11.1)

**Closed by ramya-rao-a** 2019-07-03 03:14 UTC
Labels: bug

**Comment by jaredallard** [comment] 2019-07-20 04:34
I seem to be encountering this ins 0.11.4.

```
Failed to run "go env" to find GOPATH as the "go" binary cannot be found in either GOROOT(undefined) or PATH(/usr/bin:/bin:/usr/sbin:/sbin)
```

Same thing, runs fine in my shell. I've set PATH multiple places. Usin Mac OS X, running out of ideas.

**Comment by andrewpurdin** [comment] 2019-07-21 03:41
I am having this issue in 0.11.4 as well.

**Comment by ramya-rao-a** [comment] 2019-07-21 04:05
@jaredallard, @andrewpurdin Is the value for PATH that is getting printed in the error message what you expect? 

If your shell is showing you the right PATH, then try running VS Code from the shell. When run this way, VS Code inherits all the env variables from the shell

**Comment by jaredallard** [comment] 2019-07-21 05:38
@ramya-rao-a It's not, I've mitigated this for now by running it out of my shell. Go is just in the default location that homebrew installs it in though, is there a better way of modifying how PATH is exposed to vscode by default?

**Comment by andrewpurdin** [comment] 2019-07-22 15:18
> @jaredallard, @andrewpurdin Is the value for PATH that is getting printed in the error message what you expect?
> 
> If your shell is showing you the right PATH, then try running VS Code from the shell. When run this way, VS Code inherits all the env variables from the shell

This was my problem, I wasn't aware that opening VS Code outside of the shell would fail to inherit environment variables from ZSH. 

Thank you!

**Comment by harpenden** [comment] 2019-07-31 17:29
Is there an update with this issue? I'm using v0.11.4 and I receive following error if I run vscode outside of the shell,

> Failed to run "go env" to find GOPATH as the "go" binary cannot be found in either GOROOT(undefined) or PATH

Do we have to run vscode from the shell every time?

**Comment by ramya-rao-a** [comment] 2019-08-01 00:55
Is everybody on this issue using zsh? We do have some troubles reading env variables in case of zsh, see https://github.com/microsoft/vscode-go/issues/1133

> Do we have to run vscode from the shell every time?

Workaround for running vscode from shell every time:
You can set the `go.goroot` setting to point to your GOPATH. The Go extension will read from this setting to determine the goroot

Another workaround is to set the PATH in the .bashrc file

**Comment by AndreiD** [comment] 2019-08-11 19:21
still doesn't work. why did you break VSCode with Go Microsoft....whyyyyyyyyyyyyyyyy ??? hy did you break VSCode with Go Microsoft....whyyyyyyyyyyyyyyyy ???hy did you break VSCode with Go Microsoft....whyyyyyyyyyyyyyyyy ???hy did you break VSCode with Go Microsoft....whyyyyyyyyyyyyyyyy ???

**Comment by AndreiD** [comment] 2019-08-12 17:19
actually you set the go.goroot setting pointing to your GOROOT dir (example: /home/USERNAME/.go)
