### ISSUE TITLE
Print values from go.testEnvVars when running tests

### ISSUE THREAD

**Issue by henrahmagix** [microsoft/vscode-go#3100] opened 2020-03-13 15:18 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes I forget that I've set some `go.testEnvVars` and I get odd results from running my tests. When looking at the `Go Tests` output, there's no difference when `go.testEnvVars` are set vs when there are none.

**Describe the solution you'd like**
Print the values of `go.testEnvVars` in the output, like
```
Running tool: MY_ENV=value SOME_DEBUG=1 /usr/local/bin/go test -timeout 30s -coverprofile=/var/folders/kn/rkk3dw9s7w130cg__d6sdp5m0000gn/T/vscode-goMGftBF/go-code-cover github.com/org/repo/pkg
```
where currently it outputs
```
Running tool: /usr/local/bin/go test -timeout 30s -coverprofile=/var/folders/kn/rkk3dw9s7w130cg__d6sdp5m0000gn/T/vscode-goMGftBF/go-code-cover github.com/org/repo/pkg
```

**Describe alternatives you've considered**
Printing the JSON of `go.testEnvVars` before the `Running tool` bit instead of combined into it. Anywhere really, just so long as it's visible =)

**Additional context**
`go.testEnvVars` setting is fantastic and it's saving me so much time! I just wish it would operate more transparently =)

To be clear, this isn't a blocking problem, because it is, at the end of the day, _my_ fault for using `go.testEnvVars` for occasional, short-lived test vars and forgetting to remove them after I'm done =D But it would be nice to see everything that's being used in the tests running =)

**Comment by wtask** [comment] 2020-03-13 17:10
I think you should print your environment inside your tests or app if you depend on it. This is your responsibility.

**Comment by stamblerre** [comment] 2020-03-27 05:10
I'm not sure - it may be helpful to users to see the environment variables they set, especially since they may have forgotten they changed the settings and can't understand a test failure. @ramya-rao-a, @hyangah - what do you think?

**Comment by hyangah** [comment] 2020-03-27 13:40
I understand the desire - I also want to have an easy way to inspect what command VS code is invoking underneath :-) - but agree with @wtask about the test commands. If a test depends on some of the environment variables and the results can be confusing, the tests should print them. 

My reasoning is:

testEnvVars are not the only environment variables passed to a test. Current implementation
(https://github.com/microsoft/vscode-go/blob/134a1a04177c85efbee4956e61420b108afdf965/src/testUtils.ts#L82-L95) passes all the env vars set when launching the vscode, set through toolsEnvVars, and set with go.testEnvFile. So, the environment variables can be set in many different ways. Printing all the environment variables by default is not ideal either because there can be easily tens of environment variables.

**Comment by stamblerre** [comment] 2020-03-27 15:27
Ok - makes sense to me! I hadn't checked the implementation, so thanks for looking into it. I guess I'll close this issue as working as intended then.

**Closed by stamblerre** 2020-03-27 15:27 UTC
Labels: needs-decision
