### ISSUE TITLE
"Go: run test at cursor" doesn't…

### ISSUE THREAD

**Issue by garthk** [Microsoft/vscode-go#182] opened 2016-01-27 23:27 UTC
… and "Go: run tests in file" doesn't, either.

* Open `whatever_test.go`
* ⌘⇧P`gotestpack` (Go: run tests in current package)
* Observe Output window opens with your test results
* ⌘⇧P`gotestfile` (Go: run tests in current file)
* Observe nothing happens
* Place the cursor in a test function name, its `func` keyword, or its body
* ⌘⇧P`gotestcurs` (Go: run test at cursor)
* Observe nothing happens

Environment details:

* Mac OS X 10.11.3 (`15D21`)
* Code 0.10.6 (`a80232bbcfe8a5cdad1ebc98638673d9dcb02458`)
* Code `ext update` reports no outdated extensions found
* `go version` →  `go1.5.3 darwin/amd64`

**Comment by lukehoban** [comment] 2016-01-28 05:52
I think this is a dupe of https://github.com/Microsoft/vscode-go/issues/176, which is fixed in master.  I'll push an update to the extension soon with this fix.

**Closed by lukehoban** 2016-01-28 05:52 UTC
