### ISSUE TITLE
Code coverage in gutter covers breakpoints

### ISSUE THREAD

**Issue by FryDay** [microsoft/vscode-go#1715] opened 2018-06-06 13:13 UTC
Using these settings:
```
    "go.coverageDecorator": {
        "type": "gutter",
        "coveredHighlightColor": "rgba(64,128,128,0.5)",
        "uncoveredHighlightColor": "rgba(128,64,64,0.25)",
        "coveredGutterStyle": "blockgreen",
        "uncoveredGutterStyle": "slashred"
    },
```

I have a break-point at both line 269 and 270, but the one at 270 is behind the coverage.
![image](https://user-images.githubusercontent.com/754086/41040154-399c4580-6961-11e8-9c27-da80ef80e6a1.png)

**Comment by ramya-rao-a** [comment] 2018-06-06 17:35
This was always the case with the gutter style ever since we introduced it last year.
I don't have any bright ideas how to solve this at the moment.
But ideas and PRs are most welcome.

**Comment by kentquirk** [comment] 2018-06-07 13:14
For what it's worth, I tried setting the opacity of the gutter svg to semitransparent, but it looks like it's not overlaid. I'm guessing there can be only one gutter decoration per line?

**Comment by ramya-rao-a** [comment] 2018-06-11 01:51
The ability to add a z-index on decorations was introduced recently. If that works then we can give a lower z-index for the coverage decorator which should fix this issue.

When I get a link to the docs on that, I'll add it here.

**Comment by rhullah** [comment] 2018-09-26 19:41
This appears to be an [ongoing issue](https://github.com/Microsoft/vscode/issues/5923) with VSCode in general.  And it doesn't look like z-index would help as the images are applied as classes so the latest one replaces the existing (breakpoint) one.  It could be possible to have two images (for each color, total of four), one without the breakpoint and one with (CSS targeting both classes).  But the presence of the coverage SVG seems to also disable the ability to add breakpoints via the mouse (hover and click).  I haven't found the cause of why yet.

**Comment by ramya-rao-a** [comment] 2020-05-28 20:49
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Closing this issue in favor of the upstream issue in VS Code https://github.com/Microsoft/vscode/issues/5923. If anyone has a solution to this at the extension level, please create a PR in https://github.com/golang/vscode-go/

Thanks for all the support & Happy Coding!

**Closed by ramya-rao-a** 2020-05-28 20:49 UTC
Labels: help wanted, needs-investigation
