### ISSUE TITLE
Path to modules is cached at startup and never updated

### ISSUE THREAD

**Issue by alloro** [microsoft/vscode-go#2388] opened 2019-03-19 17:51 UTC
In a project that uses go modules, vscode caches the paths to each library that is specified in the `go.mod` file on startup. When altering the go.mod file by e.g. `go get` the cache is not updated. Meaning that on lookup (e.g. go to definition) you'll be directed to the old path/library. 
Only after a restart of the editor it'll be reloaded -- because it's always doing it on startup only as mentioned.

Steps to Reproduce:

1. Create a go project that relies on modules and is outside of your GOPATH
2. Lookup the implementation for one specific library (if you have breadcrumbs enabled you can see the path to the version)
3. Downgrade the library via `go get <lib path>@<version>`
4. Do a lookup again
5. You should see the previous implementation (if you have breadcrumbs enabled you can see the path to the version)

Possible Section in the [Code](https://github.com/Microsoft/vscode-go/blob/master/src/goModules.ts#L63)

To mention:
- tried it with and without LSP (language server), to make sure that it is not a language server issue

**Comment by ramya-rao-a** [comment] 2019-07-06 18:29
Thanks for reporting @alloro and apologies for the delay in responding.

The extension caches 2 maps related to modules. 
- Folder of the file opened in VS Code -> Path to the go.mod file for the package in this folder
- Folder of the file opened in VS Code -> Import path to the package in this folder

We do not cache the paths to each library in the go.mod file

Therefore, it looks like the problem is with the tool used for doing the lookup. 
If you are not using the language server, then the tool that gets used is `godef`

Can you run the `Go: Install/Update Tools` , select `godef` and `gopls` , press Ok to update them and try again both with and without the language server? If you still see the issue then we need to redirect the issue to godef/gopls
The key is the folder path of the file that was opened in VS Code. The value is the path to the go.mod file

**Comment by ramya-rao-a** [comment] 2019-07-06 18:29
cc @stamblerre

**Comment by stamblerre** [comment] 2019-07-08 19:29
`gopls` does not yet actually handle the contents of `go.mod` files, so when your `go.mod` file changes, we do not update our caches. This is tracked upstream here: https://github.com/golang/go/issues/31999.

**Comment by ramya-rao-a** [comment] 2019-07-10 02:15
Thanks @stamblerre 
Closing this issue in favor of the upstream issue

**Closed by ramya-rao-a** 2019-07-10 02:15 UTC
Labels: needs more info
