### ISSUE TITLE
Go to definition doesn't work in some cases

### ISSUE THREAD

**Issue by lpintes** [Microsoft/vscode-go#1622] opened 2018-04-12 10:41 UTC
Tested with VSCode 1.22.1 on Windows 10 64-bit, Go version go1.10.1 windows/amd64.

Steps to Reproduce:

1. Install the package github.com/lxn/walk
2. Open the file walk/examples/databinding/databinding.go
3. Locate the Bind function by finding the string "Bind(" for example
4. Press F12 while the cursor is somewhere on the Bind identifier
5. You will see that "No definition found".
6. I tried to locate another symbols in the same file like fmt.Sprintf without problems.

**Comment by ramya-rao-a** [comment] 2018-04-30 21:41
The case you have mentioned is for symbols for a package that has been dot imported.

Duplicate of #496
 The `godef` tool does not support dot imports. See https://github.com/rogpeppe/godef/issues/19
Please follow the instructions in https://github.com/Microsoft/vscode-go/issues/496#issuecomment-261838636 to get the solution for this issue.

**Closed by ramya-rao-a** 2018-04-30 21:41 UTC
