### ISSUE TITLE
Errors no longer clearing

### ISSUE THREAD

**Issue by FryDay** [Microsoft/vscode-go#1036] opened 2017-06-15 17:56 UTC
On Arch Linux, just updated to 1.13.1 and now my errors no longer clear. I have to restart VSCode for them to go away.

**Comment by ramya-rao-a** [comment] 2017-06-19 18:15
Do you have to restart every single time for the errors to disappear?

**Comment by boljen** [comment] 2017-06-23 23:55
I assume that I'm experiencing the same issue.

It occurs with both gometalinter and golint and for both errors and warnings. A restart is required to clear the problems in visual code.

If "go.liveErrors" is enabled, all linter problems are cleared and replaced with the live errors.

Ubuntu 16.04
Go 1.8.3
Latest tools installed (afaik)

**Comment by ramya-rao-a** [comment] 2017-06-25 18:47
@FryDay @boljen The errors clear up when there is a save on the current file. Can you please check that the errors do not go away even after fixing the issues and saving the file?

Can you share a gif/video of the same? I cannot repro

**Comment by ramya-rao-a** [comment] 2017-06-25 18:47
Also, what is the value of `go.lintOnSave` in your settings?

**Comment by FryDay** [comment] 2017-06-26 14:51
I have lintOnSave set to package. I'll try and get a gif to show you.

**Comment by boljen** [comment] 2017-06-26 15:46
I got it all working again but I don't know why.

Coverage didn't work even though it was enabled in the user settings.json file  and wasn't set in the workspace settings.json file. Setting it explicitly in the workspace settings.json file for some reason fixed both the error clearing issue as well as no coverage showing up in the editor.

The best explanation I can come up with is a corrupted cache of some sorts which got fixed by one of the following operations, or several of them in this order;

- Changed lintOnSave to "workspace" and back to "package" in the workspace settings.json (it was explicitly set to "package".) I also purposely introduced a typo here to see the effect but there wasn't a detectable effect.
- Created a test file in a package I was working on.
- Enabled "coverOnSave" in workspace settings because coverage wasn't showing up. That's when everything worked again.

I then tried to reintroduce the issue by:

- Restarting visual code
- Disabling coverOnSave
- Deleting the test file (here coverage still shows up in the editor)
- ps aux | grep go -- and then killing the processes

but I'm unable to replicate the issue.

I should add that I sometimes had issues saving the file in visual code. I modify the file and save it using the accelerator (CTRL+S), but visual code still shows a save file dialog and I can only close the file after saving it through that dialog. Can't recall whether it are just "Go" files or other languages as well. "editor.formatOnSave" is enabled inside the user settings.json.

Perhaps both issues are related?

I had the issue even if only the vscode-go extension was enabled, and when the issue was fixed, the only other enabled extension is vscode-protobuf.

**Comment by FryDay** [comment] 2017-06-26 16:58
Yeah, it's mysteriously working for me again too. No idea what happened that caused it to start working as intended again, though.

**Comment by ramya-rao-a** [comment] 2017-06-27 00:19
On every save, the diagnostics are cleared and calculated again, so I am stumped as to how this is happening.

If you can get a consistent repro, please do share.

Closing this issue until then

**Comment by posito** [comment] 2017-07-01 22:15
@ramya-rao-a , I have the same issue. If I run the 

```json
go.coverOnSave": true,
```

The error is not clearing. 
Here is my config 

```json
{
	"editor.minimap.enabled": false,
	"window.reopenFolders": "none",
	"editor.formatOnSave": true,
	"go.docsTool": "gogetdoc",
	"go.buildOnSave": true,
	"go.lintOnSave": "package",
	"go.coverOnSave": false,
	"go.formatTool": "goimports",
	"go.vetOnSave": true,
	"go.useDiffForFormatting": false,
	// "go.useCodeSnippetsOnFunctionSuggest": true,
	"go.gopath": "/Users/barack/gopath",
	//  "beautify.onSave": ["js", "html", "css"],
	"go.lintTool": "golint",
	"cSpell.userWords": [
		"gitlab",
		"robfig",
		"structs"	],
	"workbench.sideBar.location": "left",
	"window.zoomLevel": 0,
	"workbench.colorTheme": "Visual Studio Light"
}
```

**Comment by ramya-rao-a** [comment] 2017-07-04 02:18
@posito can u share a screenshot or GIF or video of the issue?

**Comment by FryDay** [comment] 2017-07-14 13:22
@ramya-rao-a After updating VS Code, it's happening again. Here is a screenshot showing the issue. You can see I am clearly returning, but the error won't go away unless I close and reload VS Code.

![image](https://user-images.githubusercontent.com/754086/28213876-925a9a32-686d-11e7-952f-d1d596c4ec93.png)

**Comment by FryDay** [comment] 2017-07-14 13:57
Quick update, it does appear that turning off coverOnSave fixes the issue, but I'd like to be able to keep it on.

**Comment by ramya-rao-a** [comment] 2017-07-15 03:34
I still can't repro this.

@FryDay Can you go to the output pane, select "Go" from drop down, try to repro this and share the output? The build, lint and vet processes are run on save and the output is dumped here.

**Comment by FryDay** [comment] 2017-07-17 17:50
`Finished running tool: /home/jordan/go/bin/golint

Finished running tool: /usr/bin/go build -i -o /tmp/go-code-check -tags ""

Finished running tool: /usr/bin/go vet`

**Comment by ramya-rao-a** [comment] 2017-07-17 19:31
That output shows no errors/warnings. This is the same output that gets used by the Problems view.

So am not sure where the problem is.

If you can repro this consistently, can you share a video/gif of the issue and the affect of turning `coverOnSave` off has on it?

**Comment by boljen** [comment] 2017-07-19 09:01
The issue appears to be fixed by deleting the ~/.config/Code directory entirely.

First I deleted the Cache, CachedData and Local Storage directories separately but that didn't fix the issue.

**Comment by ramya-rao-a** [comment] 2017-08-22 00:14
@FryDay @posito 

There is one reason why the cover on save feature can affect the problems view.

The build/lint/vet/cover on save operations are triggered at the same time. And only after all are complete, the results get updated. In your cases I believe, the running of the coverage might be taking a long time, thus delaying the update of the build/lint/vet results.

I have decoupled the coverage part from build/lint/vet process. Can you re-try after installing the extension from https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix and setting `go.coverOnSave` back to `true`?

**Comment by posito** [comment] 2017-08-24 05:03
@ramya-rao-a i get  a end of central directory record signature not found

**Comment by ramya-rao-a** [comment] 2017-08-24 05:41
@posito Can you share more details? Screenshot of the error? Error message? When do you see the error? Are you using the `Go-latest.vsix`?

**Comment by ramya-rao-a** [comment] 2017-09-06 23:11
I believe the latest version of the Go extension (0.6.64) has the fix for this issue

Since I havent heard back from anyone here in a while, I am assuming that the fix works.
If it doesnt, please re-open this issue

**Closed by ramya-rao-a** 2017-09-06 23:11 UTC
Labels: needs more info
