### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by h-wei** [Microsoft/vscode-go#2464] opened 2019-04-24 03:51 UTC
[ms-vscode.Go-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-go/files/3110501/ms-vscode.Go-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `Go`
- Extension Version: `0.10.0`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ramya-rao-a** [comment] 2019-04-24 07:17
- Are you using Go modules?
- Can you share any Go related settings you may have?

If using Go modules and the language server, then can you try the steps at https://github.com/Microsoft/vscode-go/issues/2461#issuecomment-486097632 and see if that helps?

**Comment by ramya-rao-a** [comment] 2019-04-25 05:14
We have figured out the root cause for the high cpu usage and a fix has been made.
A new release (0.10.1) has just been published and it will have the fix to the issue.

Thanks a lot for reporting and your patience!

**Closed by ramya-rao-a** 2019-04-25 05:14 UTC
