### ISSUE TITLE
`Go: test at cursor` doesn't work

### ISSUE THREAD

**Issue by ccirello** [Microsoft/vscode-go#734] opened 2017-01-19 16:50 UTC
Steps to reproduce:
1 - correctly configured Go environment outside the vscode.
2 - settings.json configured both with GOPATH and GOROOT (double checked with process `process.env['GOPATH']` and `process.env['GOROOT']`).
3 - open a test file, and move cursor to a test with a known failure.
4 - Call command prompt and choose `Go: Test at Cursor`

Result:
```
Success: Tests passed.
``` 
(one liner)

Expected: some output showing the failure.

VSCode 1.8.1
vscode-go: 0.6.52
Platform: macOS 10.12.2
Go: 1.7.4

**Comment by ccirello** [comment] 2017-01-19 18:17
Important additional information: The workspace root is my GOPATH.

**Comment by ramya-rao-a** [comment] 2017-01-20 01:10
It works for me...

Does this happen only a single project or all projects?

What about other commands ?
`Go: Test File` `Go: Test Package`

**Comment by ccirello** [comment] 2017-01-20 01:11
> Does this happen only a single project or all projects?
All projects in this workspace.

> What about other commands ?
All of them fail.

**Comment by ramya-rao-a** [comment] 2017-01-20 01:14
That's interesting..

What is the message you get when you run the other 2 commands?

Can you run `go test` in the command line work for the package in question?

**Comment by ccirello** [comment] 2017-01-20 01:17
> What is the message you get when you run the other 2 commands?

```
Success: Tests passed.
```

> Can you run go test in the command line work for the package in question?

Yes, and all my tests go fine when I call them on the shell.

**Comment by ramya-rao-a** [comment] 2017-01-20 01:44
When you run `Go: Test Package`, the extension runs the below with the package as `cwd` assuming you havent changed any of the `go.testTimeout` , `go.buildTags` and `go.buildFlags` settings.

` go test -v -timeout 30s -tags`

So if can run ` go test -v -timeout 30s -tags` in the directory where your test file exists, then I don't see why the extension is not able to run the tests as well.

@ironcladlou Thoughts?

**Comment by ccirello** [comment] 2017-01-20 01:46
```ShellSession
➜  mysql git:(master) go test -v -timeout 30s -tags
go test: missing argument for flag tags
run "go help test" or "go help testflag" for more information
```

That's what I get. Without `-tags` it goes just fine.

**Comment by ramya-rao-a** [comment] 2017-01-20 02:22
Do you see anything logged in the console? Run `Developer: Toggle Developer Tools` to see the console

**Comment by ironcladlou** [comment] 2017-01-20 13:54
@ccirello

Try:
```
go test -v -timeout 30s
```

The `-tags` flag requires an argument.

@ramya-rao-a 

Interestingly, we're [passing the tags flag](https://github.com/Microsoft/vscode-go/blob/master/src/goTest.ts#L156) even when no `go.buildTags` is set, which is wrong, but surprisingly, works. In the debugger, I can see the args array we build:

```
0:"test"
1:"-v"
2:"-timeout"
3:"30s"
4:"-tags"
5:""
```

I wonder if `cp.spawn()` is quoting the empty argument value? For example, `-tags ''` works.

P.S., what's the correct way to log to the developer console from within the plugin?

**Comment by ccirello** [comment] 2017-01-20 17:06
@ironcladlou as I mentioned in https://github.com/Microsoft/vscode-go/issues/734#issuecomment-273954169 it goes just fine without the `-tags` flag.

**Comment by ramya-rao-a** [comment] 2017-01-23 00:32
@ironcladlou `console.log()` will log things to the dev console.

**Comment by ramya-rao-a** [comment] 2017-02-07 06:41
Circling back here...

So @ccirello, so what you have is a case of a failing test. And All 3 commands to test package/file/cursor are giving you a single line output "Success: Tests passed".
Is that correct?

Do you have any build flags or build tags or test flags set in your settings?

@ironcladlou Any other thoughts?

**Comment by ironcladlou** [comment] 2017-02-07 15:02
An isolated example would be helpful, as I can't reproduce any of the reported behavior.

**Comment by ccirello** [comment] 2017-02-13 19:42
I cannot reproduce in a self-contained example. :(

**Comment by ramya-rao-a** [comment] 2017-02-13 20:58
Thanks @ccirello, do share the example when you find it. Closing till then.

**Closed by ramya-rao-a** 2017-02-13 20:58 UTC
