### ISSUE TITLE
Cursor jumps to end of file with `"editor.formatOnSave": true` in vscode 1.33

### ISSUE THREAD

**Issue by ViktorQvarfordt** [microsoft/vscode-go#2426] opened 2019-04-08 21:02 UTC
After updating vscode to version 1.33 and having the setting `"editor.formatOnSave": true`, the cursor jumps to the end of the file after saving (which triggers reformat).

Seems like this can be an issue with vscode and not this plugin itself, because I also found this issue https://github.com/Microsoft/vscode/issues/71707. But I cannot verify this.

**Comment by TomasB** [comment] 2019-04-08 21:05
Happens to me as well. Happens only when a file is >= 10000 bytes

**Comment by AlexThurston** [comment] 2019-04-09 20:21
This might be a regression as it was mentioned back in 2017:
https://github.com/Microsoft/vscode-go/issues/1378

**Comment by mkraft** [comment] 2019-04-10 23:48
Having the same issue on:

Extension: 0.9.2
VSCode: Version 1.33.0 (1.33.0) 0dd516dd412d42323fc3464531b1c715d51c4c1a
OS: macOS 10.14.4 (18E226)

**Comment by ramya-rao-a** [comment] 2019-04-11 00:40
As per https://github.com/Microsoft/vscode/issues/71707#issuecomment-481245152, this should be fixed in the latest [insiders](https://code.visualstudio.com/insiders) or you wait for the 1.33.1 release.

Can someone in this mail thread try out the insiders and confirm that the problem is indeed fixed?

**Comment by Racle** [comment] 2019-04-11 06:16
Extension: 0.9.2
Version: 1.34.0-insider
Commit: 07d9e44f910223e7ab6d3e8bc02439f39213cd90
Date: 2019-04-10T05:13:47.193Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic (Ubuntu 18.04)

After ctrl+s, cursor doesn't jump to bottom of file anymore 
BUT
If I add space after row and press ctrl+s, cursor moves to start of next line.
If I add space inside row and press ctrl+s, cursor stays in static place, so losing "correct" place in code after automatic reformat.

Screen record: https://i.imgur.com/nV7urMG.gif
First is old behaviour, then switching to 1.34.0

**Comment by ramya-rao-a** [comment] 2019-04-11 06:56
Thanks @Racle.
This is still an issue with VS Code and not this extension.
Can you please add a comment in https://github.com/Microsoft/vscode/issues/71707 or log a new issue there?

**Comment by pharrisee** [comment] 2019-04-12 10:03
strangely I'm seeing the cursor jumping to the start of the file on save with or without formatonsave enabled, not sure if it's related:

Extension: 0.9.3-beta.7
Version: 1.34.0-insider (user setup)
Commit: c763eea5c175acbc004aeb8c38fbdcd2e8ed6712
Date: 2019-04-12T07:21:14.182Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by chiniara** [comment] 2019-05-31 18:19
I dont know if its related but the same behaviour is happening with me with the Go extensions.
When formatting the cursor jumps to the top or bottom.

**Comment by ramya-rao-a** [comment] 2019-06-01 23:39
@chiniara   Are you using the language server? Can you share your Go related settings that you might have added/changed

**Comment by chiniara** [comment] 2019-06-01 23:47
Yes i am using the language server with these configurations :
`"go.lintOnSave": "file",
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "diagnostics": true // for diagnostics as you type
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "gopls": {
        "usePlaceholders": true,
        "enhancedHover": true,
    },
    "go.vetOnSave": "off",
    "go.buildOnSave": "off",`

Just followed the language server github instructions.

**Comment by ramya-rao-a** [comment] 2019-06-01 23:52
- Please ensure you are on the latest version of VS Code (1.34) which has the upstream fix
- Please ensure you have the latest version of the language server. Run the command `Go: Install/Update Tools`, select `gopls`, press Ok and try again
- If you still see the issue, try disabling the language server (set `go.useLanguageServer` to `false`), reload VS Code, and try to replicate the issue. If you don't see the issue at this point, it means that the problem is with the language server

**Comment by stamblerre** [comment] 2019-06-03 18:28
There is a known issue with this in `gopls`: https://github.com/golang/go/issues/31937.

**Comment by ramya-rao-a** [comment] 2019-06-04 03:22
Thanks @stamblerre 

Closing this issue as the original issue with VS Code was fixed with https://github.com/microsoft/vscode/issues/71707 and the issue with gopls and line endings is being tracked upstream

**Closed by ramya-rao-a** 2019-06-04 03:22 UTC
Labels: bug, upstream

**Comment by markvincze** [comment] 2019-07-01 15:00
Hey @ramya-rao-a,

Is it possible we have a regression with this?
I'm on the Go extension 0.11.0, and on VSCode 1.35.1, and if I save my source file, the cursor jumps to the very top of the file. If I disable the "use language server" option, then it stops happening.

**Comment by ramya-rao-a** [comment] 2019-07-03 02:56
@markvincze As concluded in https://github.com/microsoft/vscode-go/issues/2426#issuecomment-498504800, the issue with `gopls` still exists and was not solved. Please see https://github.com/golang/go/issues/31937

There was another issue with VS Code itself (regardless of the language server), that has been fixed a few releases ago

**Comment by markvincze** [comment] 2019-07-03 09:21
@ramya-rao-a, sorry, I missed the second part of your comment apparently 😅
Thanks for the info!
