### ISSUE TITLE
debug  Lost print

### ISSUE THREAD

**Issue by springzero** [microsoft/vscode-go#2898] opened 2019-11-12 06:17 UTC
```
package main

import "fmt"

func main() {
	fmt.Print("start")

LABEL1:
	for i := 0; i <= 5; i++ {
		for j := 0; j <= 5; j++ {
			if j == 4 {
				break LABEL1
			}
			fmt.Printf("i is: %d, and j is: %d\n", i, j)
		}
	}
	fmt.Print("end1")

	fmt.Print("end2")
	fmt.Print("end3")
}

```
If you debug this code, you will find that sometimes "end2" and "end3" will not print to the terminal when step by step debugging

```
go version go1.11.4 darwin/amd64
VSCode Version: 1.40.0
ms-vscode.go Version: 0.11.9
OS Version: macOS 10.14.6
```

**Comment by lggomez** [comment] 2019-11-12 19:16
I can reproduce it on linux also. This looks like something on the debug output console... maybe VS has trouble appending results in some cases when they're not newline entries?

The debug adapter obtains the values successfully always, as shown from the verbose output (which works becase each result is shown on its own line): 
```
NextRequest
NextResponse
end1
next state {"Running":false,"currentThread":{"id":398,"pc":4868516,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":19,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false},"goroutineID":1,"ReturnValues":null},"currentGoroutine":{"id":1,"currentLoc":{"pc":4868516,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":19,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"userCurrentLoc":{"pc":4868516,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":19,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"goStatementLoc":{"pc":4547065,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/asm_amd64.s","line":201,"function":{"name":"runtime.rt0_go","value":4546768,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4381744,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":110,"function":{"name":"runtime.main","value":4381744,"type":0,"goType":0,"optimized":true}},"threadID":398,"unreadable":""},"Threads":[{"id":398,"pc":4868516,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":19,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false},"goroutineID":1,"ReturnValues":null},{"id":405,"pc":4561677,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/sys_linux_amd64.s","line":131,"function":{"name":"runtime.usleep","value":4561616,"type":0,"goType":0,"optimized":true},"goroutineID":0,"ReturnValues":null},{[...]
StoppedEvent("step")
ThreadsRequest
goroutines [{"id":1,"currentLoc":{"pc":4868516,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":19,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"userCurrentLoc":{"pc":4868516,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":19,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"goStatementLoc":{"pc":4547065,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/asm_amd64.s","line":201,"function":{"name":"runtime.rt0_go","value":4546768,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4381744,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":110,"function":{"name":"runtime.main","value":4381744,"type":0,"goType":0,"optimized":true}},"threadID":398,"unreadable":""},{"id":2,"currentLoc":{"pc":4383156,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":302,"function":{"name":"runtime.gopark","value":4382944,"type":0,"goType":0,"optimized":true}},"userCurrentLoc":{"pc":4383156,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":302,"function":{"name":"runtime.gopark","value":4382944,"type":0,"goType":0,"optimized":true}},"goStatementLoc":{"pc":4382581,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":239,"function":{"name":"runtime.init.5","value":4382528,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4382608,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":242,"function":{"name":"runtime.for[...]
ThreadsResponse [{"id":1,"name":"main.main"},{"id":2,"name":"runtime.gopark"},{"id":3,"name":"runtime.gopark"},{"id":17,"name":"runtime.gopark"}]
StackTraceRequest
locations [{"pc":4868516,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":19,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false},"Locals":[],"Arguments":[],"FrameOffset":-104,"FramePointerOffset":-120,"Defers":[],"Err":""},{"pc":4382191,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":200,"function":{"name":"runtime.main","value":4381744,"type":0,"goType":0,"optimized":true},"Locals":[{"name":"g","addr":824634306504,"onlyAddr":false,"type":"*runtime.g","realType":"*runtime.g","flags":0,"kind":22,"value":"","len":1,"cap":0,"children":[{"name":"","addr":824633721216,"onlyAddr":false,"type":"runtime.g","realType":"runtime.g","flags":0,"kind":25,"value":"","len":44,"cap":0,"children":[{"name":"stack","addr":824633721216,"onlyAddr":false,"type":"runtime.stack","realType":"runtime.stack","flags":0,"kind":25,"value":"","len":2,"cap":0,"children":[{"name":"lo","addr":824633721216,"onlyAddr":false,"type":"uintptr","realType":"uintptr","flags":0,"kind":7,"value":"824634302464","len":0,"cap":0,"children":[],"base":0,"unreadable":"","LocationExpr":"","DeclLine":0},{"name":"hi","addr":824633721224,"onlyAddr":false,"type":"uintptr","realType":"uintptr","flags":0,"kind":7,"value":"824634306560","len":0,"cap":0,"children":[],"base":0,"unreadable":"","LocationExpr":"","DeclLine":0}],"base":0,"unreadable":"","LocationExpr":"","DeclLine":0},{"name":"stackguard0","addr":824633721232,"onlyAddr":false,"type":"uintptr","realType":"uintpt[...]
StackTraceResponse
NextRequest
NextResponse
end2
next state {"Running":false,"currentThread":{"id":398,"pc":4868638,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":20,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false},"goroutineID":1,"ReturnValues":null},"currentGoroutine":{"id":1,"currentLoc":{"pc":4868638,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":20,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"userCurrentLoc":{"pc":4868638,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":20,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"goStatementLoc":{"pc":4547065,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/asm_amd64.s","line":201,"function":{"name":"runtime.rt0_go","value":4546768,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4381744,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":110,"function":{"name":"runtime.main","value":4381744,"type":0,"goType":0,"optimized":true}},"threadID":398,"unreadable":""},"Threads":[{"id":407,"pc":4563107,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/sys_linux_amd64.s","line":536,"function":{"name":"runtime.futex","value":4563072,"type":0,"goType":0,"optimized":true},"goroutineID":0,"ReturnValues":null},{"id":408,"pc":4563107,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/sys_linux_amd64.s","line":536,"function":{"name":"runtime.futex","value":4563072,"type":0,"goType":0,"optimized":true},"goroutineID":0,"[...]
StoppedEvent("step")
ThreadsRequest
goroutines [{"id":1,"currentLoc":{"pc":4868638,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":20,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"userCurrentLoc":{"pc":4868638,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":20,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"goStatementLoc":{"pc":4547065,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/asm_amd64.s","line":201,"function":{"name":"runtime.rt0_go","value":4546768,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4381744,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":110,"function":{"name":"runtime.main","value":4381744,"type":0,"goType":0,"optimized":true}},"threadID":398,"unreadable":""},{"id":2,"currentLoc":{"pc":4383156,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":302,"function":{"name":"runtime.gopark","value":4382944,"type":0,"goType":0,"optimized":true}},"userCurrentLoc":{"pc":4383156,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":302,"function":{"name":"runtime.gopark","value":4382944,"type":0,"goType":0,"optimized":true}},"goStatementLoc":{"pc":4382581,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":239,"function":{"name":"runtime.init.5","value":4382528,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4382608,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":242,"function":{"name":"runtime.for[...]
ThreadsResponse [{"id":1,"name":"main.main"},{"id":2,"name":"runtime.gopark"},{"id":3,"name":"runtime.gopark"},{"id":17,"name":"runtime.gopark"}]
StackTraceRequest
locations [{"pc":4868638,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":20,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false},"Locals":[],"Arguments":[],"FrameOffset":-104,"FramePointerOffset":-120,"Defers":[],"Err":""},{"pc":4382191,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":200,"function":{"name":"runtime.main","value":4381744,"type":0,"goType":0,"optimized":true},"Locals":[{"name":"g","addr":824634306504,"onlyAddr":false,"type":"*runtime.g","realType":"*runtime.g","flags":0,"kind":22,"value":"","len":1,"cap":0,"children":[{"name":"","addr":824633721216,"onlyAddr":false,"type":"runtime.g","realType":"runtime.g","flags":0,"kind":25,"value":"","len":44,"cap":0,"children":[{"name":"stack","addr":824633721216,"onlyAddr":false,"type":"runtime.stack","realType":"runtime.stack","flags":0,"kind":25,"value":"","len":2,"cap":0,"children":[{"name":"lo","addr":824633721216,"onlyAddr":false,"type":"uintptr","realType":"uintptr","flags":0,"kind":7,"value":"824634302464","len":0,"cap":0,"children":[],"base":0,"unreadable":"","LocationExpr":"","DeclLine":0},{"name":"hi","addr":824633721224,"onlyAddr":false,"type":"uintptr","realType":"uintptr","flags":0,"kind":7,"value":"824634306560","len":0,"cap":0,"children":[],"base":0,"unreadable":"","LocationExpr":"","DeclLine":0}],"base":0,"unreadable":"","LocationExpr":"","DeclLine":0},{"name":"stackguard0","addr":824633721232,"onlyAddr":false,"type":"uintptr","realType":"uintpt[...]
StackTraceResponse
ScopesRequest
locals []
functionArgs []
NextRequest
NextResponse
global vars [{"name":"keepalive_modinfo","addr":5734832,"onlyAddr":false,"type":"string","realType":"string","flags":0,"kind":24,"value":"0w�\f�","len":124,"cap":0,"children":[],"base":5111011,"unreadable":"","LocationExpr":"[block] DW_OP_addr 0x5781b0 ","DeclLine":0}]
ScopesResponse
VariablesRequest
VariablesResponse []
end3
next state {"Running":false,"currentThread":{"id":398,"pc":4868757,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":22,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false},"goroutineID":1,"ReturnValues":null},"currentGoroutine":{"id":1,"currentLoc":{"pc":4868757,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":22,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"userCurrentLoc":{"pc":4868757,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":22,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"goStatementLoc":{"pc":4547065,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/asm_amd64.s","line":201,"function":{"name":"runtime.rt0_go","value":4546768,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4381744,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":110,"function":{"name":"runtime.main","value":4381744,"type":0,"goType":0,"optimized":true}},"threadID":398,"unreadable":""},"Threads":[{"id":398,"pc":4868757,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":22,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false},"goroutineID":1,"ReturnValues":null},{"id":405,"pc":4561677,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/sys_linux_amd64.s","line":131,"function":{"name":"runtime.usleep","value":4561616,"type":0,"goType":0,"optimized":true},"goroutineID":0,"ReturnValues":null},{[...]
StoppedEvent("step")
ThreadsRequest
goroutines [{"id":1,"currentLoc":{"pc":4868757,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":22,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"userCurrentLoc":{"pc":4868757,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":22,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false}},"goStatementLoc":{"pc":4547065,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/asm_amd64.s","line":201,"function":{"name":"runtime.rt0_go","value":4546768,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4381744,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":110,"function":{"name":"runtime.main","value":4381744,"type":0,"goType":0,"optimized":true}},"threadID":398,"unreadable":""},{"id":2,"currentLoc":{"pc":4383156,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":302,"function":{"name":"runtime.gopark","value":4382944,"type":0,"goType":0,"optimized":true}},"userCurrentLoc":{"pc":4383156,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":302,"function":{"name":"runtime.gopark","value":4382944,"type":0,"goType":0,"optimized":true}},"goStatementLoc":{"pc":4382581,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":239,"function":{"name":"runtime.init.5","value":4382528,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4382608,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":242,"function":{"name":"runtime.for[...]
ThreadsResponse [{"id":1,"name":"main.main"},{"id":2,"name":"runtime.gopark"},{"id":3,"name":"runtime.gopark"},{"id":17,"name":"runtime.gopark"}]
StackTraceRequest
locations [{"pc":4868757,"file":"/home/razael/DEV/go/test_2898/main/main.go","line":22,"function":{"name":"main.main","value":4868160,"type":0,"goType":0,"optimized":false},"Locals":[],"Arguments":[],"FrameOffset":-104,"FramePointerOffset":-120,"Defers":[],"Err":""},{"pc":4382191,"file":"/home/razael/.gvm/gos/go1.12.4/src/runtime/proc.go","line":200,"function":{"name":"runtime.main","value":4381744,"type":0,"goType":0,"optimized":true},"Locals":[{"name":"g","addr":824634306504,"onlyAddr":false,"type":"*runtime.g","realType":"*runtime.g","flags":0,"kind":22,"value":"","len":1,"cap":0,"children":[{"name":"","addr":824633721216,"onlyAddr":false,"type":"runtime.g","realType":"runtime.g","flags":0,"kind":25,"value":"","len":44,"cap":0,"children":[{"name":"stack","addr":824633721216,"onlyAddr":false,"type":"runtime.stack","realType":"runtime.stack","flags":0,"kind":25,"value":"","len":2,"cap":0,"children":[{"name":"lo","addr":824633721216,"onlyAddr":false,"type":"uintptr","realType":"uintptr","flags":0,"kind":7,"value":"824634302464","len":0,"cap":0,"children":[],"base":0,"unreadable":"","LocationExpr":"","DeclLine":0},{"name":"hi","addr":824633721224,"onlyAddr":false,"type":"uintptr","realType":"uintptr","flags":0,"kind":7,"value":"824634306560","len":0,"cap":0,"children":[],"base":0,"unreadable":"","LocationExpr":"","DeclLine":0}],"base":0,"unreadable":"","LocationExpr":"","DeclLine":0},{"name":"stackguard0","addr":824633721232,"onlyAddr":false,"type":"uintptr","realType":"uintpt[...]
StackTraceResponse
ScopesRequest
locals []
functionArgs []
global vars [{"name":"keepalive_modinfo","addr":5734832,"onlyAddr":false,"type":"string","realType":"string","flags":0,"kind":24,"value":"0w�\f�","len":124,"cap":0,"children":[],"base":5111011,"unreadable":"","LocationExpr":"[block] DW_OP_addr 0x5781b0 ","DeclLine":0}]
ScopesResponse
VariablesRequest
VariablesResponse []
```

**Comment by springzero** [comment] 2019-11-15 07:15
Yes, there is no problem with a new line;
This looks like a small trap, if someone uses print to debug. The same code is no problem on Goland, but unfortunately I don't have enough ability to provide more help.
Thank you for your sincere reply!

**Comment by lggomez** [comment] 2019-11-15 09:59
@roblourens do you know of some way to help track down this?

At this point the only thing we do is the call to sendResponse for every successful step out action: https://github.com/microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L1465-L1478. Should this be empty for the repro case like we see on the output consule, we'd have seen it with the verbose logs on too but that's not what is happening here

...so if we fail to flush properly to console under some cases like this one any additional info will be welcome

**Comment by ramya-rao-a** [comment] 2020-01-20 02:42
@quoctruong Can you take a look at this?

**Comment by hyangah** [comment] 2020-06-04 02:21
@lggomez @springzero Is this issue still reproducible? How frequently this issue occurs?
I tried on my mac several times, but could reproduce the problem.
As we are moving to a new repo, we would appreciate it if you could check if this is still an issue. 
(even though I have no idea how to track down this issue if logging interferes)

Thanks!

**Comment by stamblerre** [comment] 2020-06-06 00:19
I just tried to reproduce this a few times on Linux with no success. I wonder if this is because @springzero was using `go1.11`. @lggomez, what version of Go were you using to reproduce?

Since [we are moving](https://github.com/microsoft/vscode-go/issues/3247), I am going to go ahead and close this issue. @springzero or @lggomez, if you can still reproduce this, please file a new issue in https://github.com/golang/vscode-go with an exact set of steps to reproduce.

**Closed by stamblerre** 2020-06-06 00:19 UTC
Labels: debug, needs more info, needs-investigation
