### ISSUE TITLE
"could not import syscall/js" error message even though it builds and runs successfully

### ISSUE THREAD

**Issue by coreyog** [Microsoft/vscode-go#1874] opened 2018-08-26 03:54 UTC
```
package main

import (
	"syscall/js"
)

func main() {
	js.Global().Call("alert", "Hello World")
}
```

When built with `GOOS=js GOARCH=wasm go build main.go` using Go 1.11 this produces a WASM binary without error. However VSCode shows that there's an error:

> could not import syscall/js (can't find import: "syscall/js")

I think this has to do with that namespace being experimental while wasm support stabilizes over the coming versions. I'm given very little details about the error.

As a result of the namespace not being found, intellisense also doesn't work.

I'm running VSCode 1.26.1 on Linux Mint 19 x64 with Go 1.11

**Comment by coreyog** [comment] 2018-08-26 04:56
I reopened the project to investigate further and when I moused over the import with it's red squiggly line, I got this error:

> build constraints exclude all Go files in /usr/local/go/src/syscall/js

I think the plugin doesn't use an altered GOOS and GOARCH when checking the code for errors.

**Comment by coreyog** [comment] 2018-08-26 05:13
In Output I see:

>/home/corey/src/goprojects/src/wasm-hw>Finished running tool: /home/corey/src/goprojects/bin/golint
>
>/home/corey/src/goprojects/src/wasm-hw>Finished running tool: /usr/local/go/bin/go build -i -o /tmp/go-code-check.198072839 wasm-hw
>go build runtime/internal/atomic: mkdir /usr/local/go/pkg/js_wasm: permission denied
>go build runtime/internal/sys: open /usr/local/go/pkg/js_wasm/runtime/internal/sys.a: no such file or directory
>go build internal/race: mkdir /usr/local/go/pkg/js_wasm: permission denied
>go build sync/atomic: mkdir /usr/local/go/pkg/js_wasm: permission denied
>go build internal/cpu: open /usr/local/go/pkg/js_wasm/internal/cpu.a: no such file or directory
>
>
>/home/corey/src/goprojects/src/wasm-hw>Finished running tool: /usr/local/go/bin/go vet ./...

I've set my go.toolsEnvVars as follows:

```
{
  "go.toolsEnvVars": {
    "GOOS": "js",
    "GOARCH": "wasm",
    "GOROOT": "/usr/local/go",
    "GOPATH": "/home/corey/src/goprojects"
  }
}
```

GoRoot and GoPath reflect what the normal env variables are. I'm still getting the `could not import` error.

**Comment by ramya-rao-a** [comment] 2018-09-10 02:56
Can you try adding the setting `"go.installDependenciesWhenBuilding": false`. See #1464 for another case where the build process had permission issues

**Comment by eternal-flame-AD** [comment] 2018-09-10 03:10
@ramya-rao-a Thanks, I followed your steps and the error is not coming out. However, there is still no IntelliSense for `syscall/js` package.

**Comment by ramya-rao-a** [comment] 2018-09-11 00:41
- If there are any running process for `gocode`, close them
- Run gocode -s -debug in a terminal and try for intellisense in VS Code. Results from gocode will show up in the terminal. 

If the results from `gocode` show zero candidates, then the issue is with gocode

**Comment by eternal-flame-AD** [comment] 2018-09-11 02:58
It indeed said zero candidates. I guess that's an upstream issue then.

**Comment by ramya-rao-a** [comment] 2018-09-12 01:16
Are you using modules?
Also, can you try again by setting GOOS=js GOARCH=wasm in your terminal before running `gocode -s -debug`. Remember to kill existing processes for gocode

And why is the GOPATH being set to `/home/corey/src/goprojects`? Shouldnt it be just `/home/corey` ?

**Comment by coreyog** [comment] 2018-09-12 01:32
It should be `/home/corey/src/goprojects`. /home/corey/src also has other non-Go project folders that I don't want mixed in with go projects.

I'll try setting env variables like you suggest when I get a chance.

**Comment by ramya-rao-a** [comment] 2018-09-12 01:41
- What do you get when you run `Go: Current GOPATH` ?
- Are you using the new modules feature in Go 1.11?

**Comment by eternal-flame-AD** [comment] 2018-09-12 09:19
I tried setting env before starting gocode but it is still not spawning candidates :(

**Comment by ramya-rao-a** [comment] 2018-09-13 04:28
@eternal-flame-AD @coreyog If you don't have `syscall/js` under `$GOROOT/pkg/js_wasm`, then can you run `go install syscall/js` after setting the GOOS and GOARCH as env vars and try again?

**Comment by eternal-flame-AD** [comment] 2018-09-13 04:35
I ran the command and `$GOPATH/pkg/js_wasm` dir appeared. However, the IntelliSense wasn't fixed.

**Comment by ramya-rao-a** [comment] 2018-09-13 04:36
@eternal-flame-AD Ensure GOOS and GOARCH are js, wasm and retry 
https://github.com/Microsoft/vscode-go/issues/1874#issuecomment-420107114

**Comment by eternal-flame-AD** [comment] 2018-09-13 04:40
Yep I think the problem was still there:(
```
 ~/code/go/src/github.com/eternal-flame-AD/hellowasm  ls /usr/lib/go/pkg
include  js_wasm  linux_amd64  linux_amd64_dynlink  linux_amd64_race  linux_amd64_shared  linux_amd64_testcshared_shared  obj  tool
 ~/code/go/src/github.com/eternal-flame-AD/hellowasm  kill 1521
 ~/code/go/src/github.com/eternal-flame-AD/hellowasm  kill 32471
 ~/code/go/src/github.com/eternal-flame-AD/hellowasm  rm /tmp/gocode-daemon.ef
 ~/code/go/src/github.com/eternal-flame-AD/hellowasm  env GOOS=js GOARCH=wasm gocode -s --debug
2018/09/13 12:38:22 Got autocompletion request for '/home/ef/code/go/src/github.com/eternal-flame-AD/hellowasm/main.go'
2018/09/13 12:38:22 Cursor at: 99
2018/09/13 12:38:22 -------------------------------------------------------
package main

import (
        "fmt"
        "syscall/js"
)

func main() {
        fmt.Println("loaded")
        js.Global()
        j#s.
}
2018/09/13 12:38:22 -------------------------------------------------------
2018/09/13 12:38:22 Error parsing input file (outer block):
2018/09/13 12:38:22  /home/ef/code/go/src/github.com/eternal-flame-AD/hellowasm/main.go:12:1: expected selector or type assertion, found '}'
2018/09/13 12:38:22  /home/ef/code/go/src/github.com/eternal-flame-AD/hellowasm/main.go:12:3: expected ';', found 'EOF'
2018/09/13 12:38:22  /home/ef/code/go/src/github.com/eternal-flame-AD/hellowasm/main.go:12:3: expected '}', found 'EOF'
2018/09/13 12:38:22 Elapsed duration: 2.52415ms
2018/09/13 12:38:22 Offset: 0
2018/09/13 12:38:22 Number of candidates found: 1
2018/09/13 12:38:22 Candidates are:
2018/09/13 12:38:22   package js
2018/09/13 12:38:22 =======================================================
2018/09/13 12:38:22 Got autocompletion request for '/home/ef/code/go/src/github.com/eternal-flame-AD/hellowasm/main.go'
2018/09/13 12:38:22 Cursor at: 101
2018/09/13 12:38:22 -------------------------------------------------------
package main

import (
        "fmt"
        "syscall/js"
)

func main() {
        fmt.Println("loaded")
        js.Global()
        js.#
}
2018/09/13 12:38:22 -------------------------------------------------------
2018/09/13 12:38:22 Error parsing input file (outer block):
2018/09/13 12:38:22  /home/ef/code/go/src/github.com/eternal-flame-AD/hellowasm/main.go:11:5: expected selector or type assertion, found ';'
2018/09/13 12:38:22 Elapsed duration: 2.981524ms
2018/09/13 12:38:22 Offset: 0
2018/09/13 12:38:22 Number of candidates found: 0
2018/09/13 12:38:22 Candidates are:
2018/09/13 12:38:22 =======================================================
2018/09/13 12:38:22 Got autocompletion request for '/home/ef/code/go/src/github.com/eternal-flame-AD/hellowasm/main.go'
2018/09/13 12:38:22 Cursor at: 121
2018/09/13 12:38:22 -------------------------------------------------------
package main
import "syscall/js"

import (
        "fmt"
        "syscall/js"
)

func main() {
        fmt.Println("loaded")
        js.Global()
        js.#
}
2018/09/13 12:38:22 -------------------------------------------------------
2018/09/13 12:38:22 Error parsing input file (outer block):
2018/09/13 12:38:22  /home/ef/code/go/src/github.com/eternal-flame-AD/hellowasm/main.go:12:5: expected selector or type assertion, found ';'
2018/09/13 12:38:22 Elapsed duration: 2.52288ms
2018/09/13 12:38:22 Offset: 0
2018/09/13 12:38:22 Number of candidates found: 0
2018/09/13 12:38:22 Candidates are:
2018/09/13 12:38:22 =======================================================
```

**Comment by ramya-rao-a** [comment] 2018-09-13 04:51
@eternal-flame-AD Last question. You have set GOOS and GOARCH to js and wasm in the toolsEnvVars setting right?

```
"go.toolsEnvVars": {
    "GOOS": "js",
    "GOARCH": "wasm"
  }
```

**Comment by eternal-flame-AD** [comment] 2018-09-13 04:53
```
 ~  cat code/go/src/github.com/eternal-flame-AD/hellowasm/.vscode/settings.json 
{
    "go.toolsEnvVars": {
        "GOARCH":"wasm",
        "GOOS":"js",
    },
    "go.testEnvVars": {
        "GOARCH":"wasm",
        "GOOS":"js",
    },
    "go.installDependenciesWhenBuilding": false,
}
```

**Comment by ramya-rao-a** [comment] 2018-09-13 05:01
Ok, I am running out of ideas, lets take this up in https://github.com/mdempsky/gocode/issues/56

Was this working before you upgraded to go 1.11?

**Comment by eternal-flame-AD** [comment] 2018-09-13 05:04
Sorry I didn't get what `this` means :question: 
I think go don't have `wasm` support before 1.11

**Comment by ramya-rao-a** [comment] 2018-09-13 05:06
Thats right, sorry my mistake

**Comment by eternal-flame-AD** [comment] 2018-10-14 02:31
I think this issue should be reopened. I dug a little through the vscode-go code and found this line which masked all `GOARCH` and `GOOS` env.

https://github.com/Microsoft/vscode-go/blob/d1a9f9a8cd7428c552517d72af148b7b116b9ed0/src/goSuggest.ts#L185
After I got rid of this in a dev environment, the suggestions worked perfectly.

**Comment by eternal-flame-AD** [comment] 2018-10-14 02:33
I am not sure how to reproduce the issue mentioned on the code comments before this line. However I think we should definitely at least add an exception for `wasm/js`

**Comment by stamblerre** [comment] 2018-10-15 18:35
@ramya-rao-a: gocode tracks the build.Context of requests, so if you explicitly set `GOOS` and `GOARCH` in a client request, it should work correctly.

**Comment by ramya-rao-a** [comment] 2018-10-15 19:04
Thanks @stamblerre!

@eternal-flame-AD Would you be interested in submitting a PR to fix this?

**Comment by eternal-flame-AD** [comment] 2018-10-16 02:36
Yep.

I found that when `GOOS` and `GOARCH` are set, `gocode` barely tracks import correctly:( I have to run like `sudo env GOOS=js GOARCH=wasm go install math/rand` in order to get `math/rand` suggestions working on `wasm/js`

I found a solution to the problem that is enabling source import when spawning gocode daemon. Should we include this change in the PR?
```diff
diff --git a/src/goSuggest.ts b/src/goSuggest.ts
index a5d9e66..40a63d1 100644
--- a/src/goSuggest.ts
+++ b/src/goSuggest.ts
@@ -187,14 +187,11 @@ export class GoCompletionItemProvider implements vscode.CompletionItemProvider {
 				return reject();
 			}
 
-			// Unset GOOS and GOARCH for the `gocode` process to ensure that GOHOSTOS and GOHOSTARCH
-			// are used as the target operating system and architecture. `gocode` is unable to provide
-			// autocompletion when the Go environment is configured for cross compilation.
-			let env = Object.assign({}, getToolsEnvVars(), { GOOS: '', GOARCH: '' });
+			let env = Object.assign({}, getToolsEnvVars());
 			let stdout = '';
 			let stderr = '';
 
-			let goCodeFlags = ['-f=json'];
+			let goCodeFlags = ['-f=json','-source=true'];
 			if (!this.setGocodeOptions) {
 				goCodeFlags.push('-builtin');
 			}

```

**Comment by ramya-rao-a** [comment] 2018-10-16 02:44
Including the `-source` flag slows things down a lot.

Are you saying that if you add the `source` flag, you dont have to run `go install` on the packages for which you want completions?

**Comment by eternal-flame-AD** [comment] 2018-10-16 02:45
Yeah. Or maybe only enabling this when cross compiling?

**Comment by eternal-flame-AD** [comment] 2018-10-16 10:09
I think we could move this discussion to #2015 as the corrent topic is more related to detailed implementation of the fix.

**Comment by ramya-rao-a** [comment] 2018-10-17 21:15
The fix for this issue is now out in the latest update to the Go extension (0.6.92). Thanks @eternal-flame-AD!

**Note**: Part of the fix here is in `gocode`. Therefore, run the command `Go: Install/Update Tools`, select `gocode` and press `Ok` to update it

**Closed by ramya-rao-a** 2018-10-17 21:15 UTC
Labels: needs more info
