### ISSUE TITLE
Debugger doesn't work

### ISSUE THREAD

**Issue by tapir** [Microsoft/vscode-go#323] opened 2016-05-10 20:13 UTC
After installing Delve with `go get github.com/derekparker/delve/cmd/dlv` as recommended [here](https://github.com/derekparker/delve/blob/master/Documentation/installation/linux/install.md) debugging a go application gives this error:
```
2016/05/10 23:11:03 server.go:41: Using API v1
2016/05/10 23:11:03 debugger.go:61: launching process with args: [./debug]
could not launch process: fork/exec ./debug: permission denied
```
launch.json is as seen below:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}",
            "env": {},
            "args": []
        }
    ]
}
```

**Comment by lukehoban** [comment] 2016-05-10 20:21
Are you on Linux?  This error is expected on OSX since different installation steps for Delve are required there.

Does `dlv` work at all?  From the error I expect it does not, and that you'll need to report this in the delve repo if indeed it is a problem.

**Comment by tapir** [comment] 2016-05-10 20:23
I'm on arch linux. I can successfully debug go code with `dlv debug some-go-code.go`
I tried this on Windows 7 as well and I get the same error there also. dlv.exe works on its own but not in the editor.

**Comment by OneOfOne** [comment] 2016-05-11 03:36
On linux, are you trying trying to run the project on a filesystem mounted with noexec?

**Comment by tapir** [comment] 2016-05-11 05:01
Nope it's mounted rw thats all.

**Comment by lukehoban** [comment] 2016-05-11 05:49
Are you perhaps running into https://github.com/derekparker/delve/issues/27#issuecomment-188795465?  

I doubt it's really possible for this to be something caused by `vscode-go` based on the error you are seeing.  The options you have specified will result in executing `dlv debug --headless=true --listen=127.0.0.1:2345 --log --` with the working directory set to your `${workspaceRoot}`.

Note that `dlv debug` accepts a package argument, not a file argument - so it's not clear what `dlv debug some-go-code.go` in your example would be doing.

**Comment by tapir** [comment] 2016-05-11 05:56
Ok we made some progress :)
First of all, I don't know if it's a new feature or not but `dlv debug some-go-code.go` definitely works.
Now I tried `dlv debug --headless=true --listen=127.0.0.1:2345 --log some-go-code.org` and it gives the same error above. Until I do this: `dlv debug --listen=127.0.0.1:2345 --log some-go-code.org` and then it works OK.

**Comment by tapir** [comment] 2016-05-11 15:14
I've solved the problem. The code that I was trying to debug was outside of the GOPATH/src. Now that I moved it back to there, debugger seems to work ok.
Using delve manually doesn't cause such behaviour so this still might be vscode-go related.

**Comment by lukehoban** [comment] 2016-05-15 19:48
> Now I tried dlv debug --headless=true --listen=127.0.0.1:2345 --log some-go-code.go and it gives the same error above. Until I do this: dlv debug --listen=127.0.0.1:2345 --log some-go-code.go and then it works OK.

Sounds like that's a bug in Delve that it should support consistent behaviour of arguments across headless and interactive.  Feel free to report that to Delve.

> Using delve manually doesn't cause such behaviour so this still might be vscode-go related.

From `vscode-go` you can pass the file path is you want by setting `"program"` to point at a file instead of package directory.  The only thing `vscode-go` could do to "fix" this apparently would be to not pass `--headless`, but that is requried to be able to interact with the debug server.

Closing for now since I don't see any change `vscode-go` could make to help here.

**Closed by lukehoban** 2016-05-15 19:48 UTC
