### ISSUE TITLE
Directories/files left in /tmp/

### ISSUE THREAD

**Issue by mwat56** [microsoft/vscode-go#2442] opened 2019-04-14 11:30 UTC
In one week (from April 7, 12:26 until April 14, 12:56) there were created 6,221 (!) directories in /tmp/ with names like "go-buildxxxxxxxxx", for example:

    ./go-build992210238/b118:
    total 24
    drwxrwxr-x 2 matthias matthias  4096 Apr 11 12:07 .
    drwx------ 3 matthias matthias  4096 Apr 11 12:07 ..
    -rw-rw-r-- 1 matthias matthias   423 Apr 11 12:07 importcfg
    -rw-rw-r-- 1 matthias matthias 11076 Apr 11 12:07 _pkg_.a

I'm using VSCode
    Version: 1.33.1
    Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
    Date: 2019-04-11T08:20:22.771Z
    Electron: 3.1.6
    Chrome: 66.0.3359.181
    Node.js: 10.2.0
    V8: 6.6.346.32
    OS: Linux x64 4.15.0-47-generic

with the Go plugin 0.9.2

A similar situation with directories in /tmp/ named "vscode-goXXXXXX":

    /tmp# ls -la vscode-*/*
    -rwxrwxr-x 1 matthias matthias  4508159 Apr  9 11:57 vscode-go0ppQjK/go-code-check
    -rw-rw-r-- 1 matthias matthias   167608 Apr 14 12:57 vscode-go3G9WmY/go-code-check
    -rwxrwxr-x 1 matthias matthias 10277195 Apr  8 20:51 vscode-go4ZDB4B/go-code-check
    -rw-rw-r-- 1 matthias matthias   167608 Apr 14 13:09 vscode-goA7UvWB/go-code-check
    -rw-rw-r-- 1 matthias matthias   141206 Apr 11 14:31 vscode-goaDphWk/go-code-check
    -rw-rw-r-- 1 matthias matthias   108340 Apr  8 20:11 vscode-gobDQErc/go-code-check
    -rw-rw-r-- 1 matthias matthias   150162 Apr 12 11:21 vscode-goeBRlRL/go-code-check
    -rwxrwxr-x 1 matthias matthias  3305920 Apr  8 14:58 vscode-goFmoNRL/go-code-check
    -rw-rw-r-- 1 matthias matthias     5772 Apr  8 14:55 vscode-goFmoNRL/go-code-cover
    -rw-rw-r-- 1 matthias matthias   149530 Apr 11 18:23 vscode-goGNlW4y/go-code-check
    -rw-rw-r-- 1 matthias matthias   158366 Apr 12 18:09 vscode-goGUzCRq/go-code-check
    -rw-rw-r-- 1 matthias matthias     4073 Apr 12 17:41 vscode-goGUzCRq/go-code-cover
    -rw-rw-r-- 1 matthias matthias    57494 Apr  8 13:38 vscode-gokWCgAn/go-code-check
    -rw-rw-r-- 1 matthias matthias   165804 Apr 13 21:15 vscode-goO82rUE/go-code-check
    -rw-rw-r-- 1 matthias matthias    96804 Apr  9 20:39 vscode-goSdc4rH/go-code-check
    -rw-rw-r-- 1 matthias matthias   108340 Apr  9 14:16 vscode-goT0F7fT/go-code-check
    -rw-rw-r-- 1 matthias matthias   108024 Apr 13 15:07 vscode-gowJ9MSe/go-code-check
    -rw-rw-r-- 1 matthias matthias   150336 Apr 12 12:46 vscode-goXtnzWt/go-code-check
    -rw-rw-r-- 1 matthias matthias   149214 Apr 12 10:10 vscode-gozoLNsS/go-code-check
    [...]

I'm not sure who's responsible for creating those all files/directories; but I'd rather have them removed by the entity which is creating them when I quit VSCode for the day.

Thank you!

**Comment by mwat56** [comment] 2019-04-24 13:15
For the time being I have a nightly cron-job to remove ~1K directories/day:

    rm -fr /tmp/go-build* /tmp/vscode-go*

But I still think there should be a solution removing those dirs/files by those who created them in the first place.

**Comment by ramya-rao-a** [comment] 2019-04-25 05:17
Thanks for reporting @mwat56 

We did ship a fix for this in our last update (0.10.0)
Can you update to the latest version of the extension, stop the nightly cron-job you have and see if the problem still persists?

**Comment by mwat56** [comment] 2019-04-25 08:20
> [...]
> We did ship a fix for this in our last update (0.10.0)
> Can you update to the latest version of the extension, stop the nightly cron-job you have and see if the problem still persists?

I updated the plugin to 0.10.1 and just did a quick run: Started VSCode, edited some Go files and left (after about 20 minutes). There were 22 directories like `/tmp/go-build*` left, but all of them empty now. However, no `vscode-go*` directories remained.

So __something__ changed, but there are still directories left.

Thanks for your efforts!

**Comment by ramya-rao-a** [comment] 2019-04-26 04:33
`/tmp/vscode-go*` are directories created by the Go extension for each VS Code session to store temporary files. The fix we put in place in 0.10.1 was to clean them up when you close a VS Code session.

I believe `/tmp/go-build*` is created by Go itself when the extension runs `go build`.
See https://dave.cheney.net/2013/10/15/how-does-the-go-build-command-work

@stamblerre Would you know the right person to answer the question of who is responsible for clean up for such files created by `go build`?

**Comment by mwat56** [comment] 2019-04-26 11:55
> [...]
> I believe `/tmp/go-build*` is created by Go itself when the extension runs `go build`.

A quick test showed that `go build some/file.go` does _not_ leave anything in `/tmp`.

When looking up `go help build` it shows (besides other things):

    -work
            print the name of the temporary work directory and
            do not delete it when exiting.

So my suspicion is that the Go-plugin uses that flag when invoking `go build ...` and everything _should_ be fine without that flag. But maybe I'm missing something. What was the rationale for using that flag (if indeed it is the culprit)?

**Comment by ramya-rao-a** [comment] 2019-05-06 05:04
Apologies for the late reply.

We definitely do not use the `-work` flag when building. If you open the Output pane for Go, then you will see the exact command we run when building the Go files. 

Select `View` from the menu -> `Output`. This will open the output panel. Select `Go` from the dropdown on the top right corner of the panel.

Make some changes to your Go file and save it.
The build command we use will be logged

**Comment by mwat56** [comment] 2019-05-11 19:48
Just an **update**:
Since I changed `GO111MODULE` from `auto` to `on` (while still working in `GOPATH` sub-directories) the creation of the temp files in questions seems to have stopped.

**Comment by ramya-rao-a** [comment] 2019-05-12 01:09
Oh wow, didn't see that coming.
It must be a behavior of the go tool itself.

The only flag we use when building is the `-o` to give path for the build output.
Can you change `GO111MODULE` back to `auto`, try `go build -o path-to-a-temp-file` and see if the `/tmp/go-build*` folders get created?

**Comment by mwat56** [comment] 2019-05-12 18:08
> Oh wow, didn't see that coming.

Me neither ;-)

> [...]
> Can you change `GO111MODULE` back to `auto`, try `go build -o path-to-a-temp-file` and see if the `/tmp/go-build*` folders get created?

I switched to `auto`, created a new Go project, worked for a couple of hours (incl. auto-save, testing etc.) and found _no_ leftovers …

Hmm …

Thinking of it, the only thing changed was that I was ordered to install a new language server after enabling the use of modules.
At the same time editing became rather bothersome: whenever I mark a piece of code with the mouse and then insert them (with the middle mouse button or wheel) a strange thing happens: The text gets inserted _and_ then contents of the whole source file I'm editing gets replaced by the inserted text. So each time after inserting some text fragment I _have_ to use Ctrl-Z to restore the file's contents (including the inserted text).

The only connection between that strange – and annoying – behaviour and the new language server is that it happened at the same time. But I have no idea who's responsible for the described vanishing act. – And BTW: it only happens if I insert something into the actual code, while inserting something into a comment everything works as intended i.e. without vanishing …

Anyway. The initial problem of thousands of leftover directories seems to have gone (for no apparent reason). Insofar I'm quite happy, at least.

**Comment by ramya-rao-a** [comment] 2019-05-12 22:17
>  The text gets inserted and then contents of the whole source file I'm editing gets replaced by the inserted text. So each time after inserting some text fragment I have to use Ctrl-Z to restore the file's contents (including the inserted text)

To narrow down whether the language server is the culprit here, can you disable the language server by setting `go.useLanguageServer` to `false` and see if it still happens? And then you can enable it back. You will be prompted to reload VS Code when you change the setting, please do so.

If we do narrow it down to the language server, then I am sure the folks behind it would like to fix it :)

**Comment by mwat56** [comment] 2019-05-13 08:28
> To narrow down whether the language server is the culprit here, can you disable the language server by setting `go.useLanguageServer` to `false` and see if it still happens?

No, it doesn't.  :-))

On the other hand: In about one and a half hours there were ~150 directories created in `/tmp/`. So the initial problem is back.  :-((

> And then you can enable it back.

No, I won't (at least for the time being). I can live with the tmp files, the described vanishing act, however, is really quite bothersome, annyoing.

> You will be prompted to reload VS Code when you change the setting, please do so.

FYI: I wasn't prompted, but I did it anyway.

> If we do narrow it down to the language server, then I am sure the folks behind it would like to fix it :)

Well, to conclude: Without the new language server there a hundreds of temp files left in `/tmp` but editing source files and comments works well (i.e. as expected). _With_ the new language server the temp files are either not created at all or deleted automatically; on the other hand, marking and inserting text with the mouse (_not_ Ctrl-C/Ctrl-V which I never use) replaces the current edit file with the inserted text fragment.

I have no idea, how a language server can be responsible for either of the problems.

**Comment by stamblerre** [comment] 2019-05-13 15:32
@mwat56: I am not seeing this behavior with the language server right now - however, there was some issue with formatting on paste a few days ago. I expect that if you update to the latest version of the language server (`go get -u golang.org/x/tools/cmd/gopls`), you will no longer see this issue. If you do still see the issue, please open a new issue in the Go issue tracker: https://github.com/golang/go/issues.

**Comment by ramya-rao-a** [comment] 2019-05-13 15:37
@stamblerre  is right. The issue was with the format on paste feature when using the language server. 
@mwat56 Do you have that feature enabled? Check your `editor.formatOnPaste` setting.

@stamblerre Can you help in figuring out what exactly is creating these `/tmp/go-build*` files? Or help directing this issue to the right person in the Go team?

Below is the summary of when this is happpening for @mwat56 
- Working on a project under GOPATH, using modules, and `GO111MODULE` set to `auto`, not using the language server
- In this situation, the go plugin runs `go build -o` to build the packages and this seems to be resulting in the `/tmp/go-build*` directories
- Setting `GO111MODULE` to `on` fixes the issue.

**Comment by mwat56** [comment] 2019-05-13 16:02
> @mwat56 Do you have that feature enabled? Check your `editor.formatOnPaste` setting.

It is enabled.

**Comment by ramya-rao-a** [comment] 2019-05-13 16:13
Alright then! Update the language server (`Go: Install/Update Tools` -> select `gopls` -> press ok), reload vs code, and the pasting/formatting issue should go away

**Comment by mwat56** [comment] 2019-05-13 16:32
> Alright then! Update the language server (`Go: Install/Update Tools` -> select `gopls` -> press ok), reload vs code, and the pasting/formatting issue should go away

@ramya-rao-a: Well, I did it from the command-line as @stamblerre  suggested. And I switched `go.useLanguageServer` to `on` again. So far no problems. I'll let you know if something noteworthy happens ;-)

**Comment by jayconrod** [comment] 2019-05-13 20:59
I can confirm these directories are created by the Go command. They should not be left behind unless the `-work` flag is passed (sounds like it's not).

There is a known issue (golang/go#25808) where these directories aren't cleaned up when the Go command exits because of an internal error. 

If you're able to reproduce this, and it's not covered by golang/go#25808, please file an issue on golang/go and tag me.

**Comment by ramya-rao-a** [comment] 2019-05-17 05:09
Thanks @jayconrod 

Closing this issue as all relevant concerns have been addressed

**Closed by ramya-rao-a** 2019-05-17 05:09 UTC
Labels: under-discussion
