### ISSUE TITLE
goimports and gofmt no longer working

### ISSUE THREAD

**Issue by theGeekPirate** [Microsoft/vscode-go#1344] opened 2017-11-15 22:27 UTC
OS: Win 10
Go: 1.9.2
VS: 1.18.0
vscode-go: 0.6.67

*Notes*:
They both stopped working some time last night while in the middle of working on a project.
I can run ```goimports``` and ```gofmt``` manually without any issues, and ```go vet``` as well as ```golint``` are still being run on each save.
All other extensions seem to be working correctly (including those with "on save" functionality).

*Paths*:
Current PATH: ```C:\Users\user\go\bin``` and ```C:\Users\user\go\src\Go\bin``` are contained within it
Current GOPATH (as per the VSC extension command): ```C:\Users\user\go```
gofmt Location: ```C:\tools\go\bin\gofmt.exe``` as well as ```C:\Users\user\go\src\Go\bin\gofmt.exe```
goimports Location: ```C:\Users\user\go\bin\goimports.exe```
goreturns Location: ```C:\Users\user\go\bin\goreturns.exe```

*Output*:
```
Finished running tool: C:\Users\user\go\bin\golint.exe
Finished running tool: C:\tools\go\bin\go.exe tool vet .
Finished running tool: C:\tools\go\bin\go.exe build -i -o C:\Users\user\AppData\Local\Temp\go-code-check project\project_sub-folder
```

*What I've Tried*:
- Adding ```"go.buildOnSave": "package",``` to my preferences (note: I have no other variables set for this extension, and had none set for it previously)
- Updating all tools used via the CLI (using ```go get```)
- Updating all tools using this extension's built-in installer/updater
- Right-click -> ```Format Document```
- Rebooting

What else should I be trying to correct this issue, or information can I provide for you?

Thanks!

**Comment by theGeekPirate** [comment] 2017-11-15 22:56
Specifying ```"go.formatTool": "gofmt",``` does seem to work, while setting it to ```"goimports"``` or ```"goreturns"``` does not.

**Comment by ramya-rao-a** [comment] 2017-11-17 01:24
The fact that `gofmt` works but the other 2 dont are puzzling to me.
Choosing all the 3 tools use the same code path.

Can you try setting `go.useDiffForFormatting` to `false`? We noticed that goreturns sometimes returns diff data in an incompatible format.

We did have an issue with formatting (#1333), but that was for folks on 1.19 Insiders but you are on 1.18

**Comment by theGeekPirate** [comment] 2017-11-17 01:26
@ramya-rao-a That seems to have fixed it!

**Comment by ramya-rao-a** [comment] 2017-11-17 01:41
Great, I am not sure of the root cause here though as to why goreturns and goimports do not return anything when run with `-d`

Here is the upstream issue if you are interested: https://github.com/sqs/goreturns/issues/28

Closing this issue as the workaround works for you.

Happy Coding!

**Closed by ramya-rao-a** 2017-11-17 01:41 UTC
