### ISSUE TITLE
GoToDef Only Works When Reloading A Window

### ISSUE THREAD

**Issue by marwan-at-work** [Microsoft/vscode-go#1802] opened 2018-07-23 03:18 UTC
To reproduce: import a third party package from GOPATH and notice that you won't be able to command click symbols to GoToDef unless you :Reload Window

**Comment by ramya-rao-a** [comment] 2018-07-23 17:43
What is the value for `go.docsTool` and `go.useLanguageServer` in your settings?
If you arent using the language server, then are you able to get to the definition using `godef` or `gogetdoc`?

**Comment by marwan-at-work** [comment] 2018-07-26 16:08
@ramya-rao-a i'm using `guru` for tools and `true` for lang server

**Comment by ramya-rao-a** [comment] 2018-07-26 18:57
Then the issue is with the language server. Can you log an issue at https://github.com/sourcegraph/go-langserver?

**Comment by ramya-rao-a** [comment] 2018-12-30 07:45
Closing this issue as there is an upstream issue tracking the same

**Closed by ramya-rao-a** 2018-12-30 07:45 UTC
