### ISSUE TITLE
Use WSL go environment for tools

### ISSUE THREAD

**Issue by srfrog** [microsoft/vscode-go#926] opened 2017-04-14 17:02 UTC
I would like to have my environment set in WSL (bash.exe) and not in Windows, can vscode-go exec bash.exe before running the tools (golint, goreturns, etc) ?

I have the following settings but doesn't appear to work:
```
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\bash.exe",
    "terminal.external.windowsExec": "C:\\WINDOWS\\sysnative\\bash.exe",
    "go.goroot": "/usr/local/go"
```
vscode alerts with:
```
Cannot find \usr\local\go\bin\go.exe
```

**Comment by ramya-rao-a** [comment] 2017-04-14 23:29
Can you try pointing your PATH to `/usr/local/go/bin/`  and restart VS Code?

**Comment by srfrog** [comment] 2017-04-15 09:37
Can you be more specific? Set PATH where, WSL or Windows? I have `/usr/local/go/bin` in `~/.bashrc` and `~/.profile`, no luck.

From **cmd.exe** when I run `bash -c 'echo $PATH'`, I don't see my `/usr/local/go/bin` in PATH. So perhaps **bash.exe** ignores `.bashrc` and `.profile` initially. Any ideas?

**Comment by ramya-rao-a** [comment] 2017-04-15 18:06
Taking a step back, you are on Windows and you have set the `go.goroot` to be `/usr/local/go` which doesn't look like a valid path in Windows.

`go.goroot` should be point to the path where you have the Go executable.

Next, about your ask 

>  I would like to have my environment set in WSL (bash.exe) and not in Windows

Sorry, but I don't understand what exactly you are trying to do here.
Are you saying that you want to use bash in the integrated terminal?

cc @tylerb for terminal related queries

**Comment by tylerb** [comment] 2017-04-15 18:15
`.bashrc` should be executed for non interactive shells, which would mean your path should be set correctly. If not, then you need to debug if/why `.bashrc` is not being executed. I don't know anything about bash in windows, so I'd recommend googling around a bit.

**Comment by srfrog** [comment] 2017-04-15 20:29
@ramya-rao-a I thought that by changing `terminal.integrated.shell.windows` and `terminal.external.windowsExec` to use **bash.exe** (Windows Subsystem for Linux) it would allow vscode-go to use the go tools in the lxss environment. This feature would be ideal for people that are leaving macOS for Windows+WSL.

Perhaps this is a setting in electron/nodejs. I'll do some more digging.

**Comment by ramya-rao-a** [comment] 2017-04-15 22:17
Oh sorry @tylerb, I meant to cc @Tyriar (our resident terminal expert), did a premature auto-complete and your name got entered :)

@srfrog ah! I think I am following what you are trying to do a little better. You are referring to the usage of go tools (like formatting using `gofmt`/`goimports/`goreturns`, renaming using `gorename` etc) and want them to run in WSL instead of Windows.

Currently, we use simple [child_process](https://nodejs.org/api/child_process.html) in the Go extension to run the Go tools. How WSL plays into this, I don't know.

@Tyriar thoughts?

**Comment by srfrog** [comment] 2017-04-16 02:18
@ramya-rao-a vscode-go is using `child_process.execFile()` which is why the shell settings aren't used. Additionally, `path.getGoRuntimePath()` is hard-coded to  **C:\\Go\\bin\\go.exe** on windows, so it will never detect Go in WSL. I will play around with these, most likely a new setting for WSL would be needed that makes use of `child_process.exec()` and checks for the setting value in `getGoRuntimePath()`.

e.g., `go.useWSL = true || false`

The actual command string might look like:

`cmd.exe /d /s /c bash.exe -ic '{command}'`

Unfortunately, NodeJS is hard-coded to use `cmd.exe /d /s /c {command}` on windows :disappointed:

**Comment by ramya-rao-a** [comment] 2017-04-16 05:00
@srfrog 

_Regarding the go runtime path_

`path.getGoRuntimePath()` first tries to find the go binary/executable as per the path in `go.goroot` first and then the PATH. If not found, then it tries `C:\Go\bin\go.exe` on windows and `/usr/local/go/bin/go` on other platforms.

In your case, looks like it says "\usr\local\go\bin\go.exe" which is weird to me because it is looking for an "exe" in a non Windows like path. I'd suggest to get a local environment of the Go extension set up and debug to see how exactly are you ending up with this scenario. Instructions" https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code

_Regarding shell usage_

So are you saying that if we use `child_process.exec` and pass the `shell` option, you should be able to get the expected behavior?

**Comment by Tyriar** [comment] 2017-04-17 17:56
This was brought up for the git support recently, not sure what the result of that conversation was yet.

> The actual command string might look like:
>
> `cmd.exe /d /s /c bash.exe -ic '{command}'`

Does adding `bash.exe -ic` work? Seems like a pretty good solution to me, if this is the direction the Go extension goes, @ramya-rao-a will probably need to make sure all paths are mapped to and from the `/mnt/c/...` and `C:\...` formats correctly.

> In your case, looks like it says "\usr\local\go\bin\go.exe" which is weird to me because it is looking for an "exe" in a non Windows like path.

What's probably happening here is it's assuming `go.goroot` is a standard Windows style path and transforming it so:

```
/usr/local/go
\usr\local\go
\usr\local\go\bin\go.exe (look in the bin\ for go.exe)
```

**Comment by ioblank** [comment] 2017-04-26 12:37
> Does adding `bash.exe -ic` work? Seems like a pretty good solution to me, if this is the direction the Go extension goes, @ramya-rao-a will probably need to make sure all paths are mapped to and from the `/mnt/c/...` and `C:\...` formats correctly.

I've done just that in my (somewhat messy) [fork](https://github.com/ioblank/vscode-go/commit/cb140c441d73cbf1208f12a5b8c47f9d55cac98f) and, bare a few remaining bugs, it works! But it's considerably slower than native tools. :( Any ideas for speeding it up?

In case you're interested in trying it out, here's an example of what you need to add to the vscode settings.json:
```
"go.useWsl": true,
"go.goroot": "/mnt/c/local/go",
"go.gopath": "/mnt/c/go",
```

**Comment by tiagommferreira** [comment] 2017-05-01 18:26
Any updates on this? WSL integration would be really useful.

**Comment by postgrep** [comment] 2017-05-25 21:06
I think this is related.
https://github.com/Microsoft/vscode/issues/22663

**Comment by gdrte** [comment] 2017-06-16 16:14
Integration with WSL is highly preferable for users like me, who just moved from Mac OS X to Windows X :).

**Comment by radu-matei** [comment] 2017-09-17 15:02
[I think the C++ tools for VS Code on Windows make use of WSL (I haven't used them, this is only based on their docs).](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/Windows%20Subsystem%20for%20Linux.md)

It would be great to have the same for Go.

**Comment by ramya-rao-a** [comment] 2017-09-21 23:15
Hello all,

There is no update as of yet. There is some talks to better support WSL in general in VS Code. When these talks solidify a bit, I'll see how we can bring over such support to the Go extension.

**Comment by lambrospetrou** [comment] 2017-10-16 19:23
I would really love for this to go forward too. The only way now to work with WSL is to run the editor locally in WSL and display it in Windows using X-Server. But this does not work with VSCode though and I fall back to Sublime.

An option to use WSL entirely in the editor would be amazing.

**Comment by radu-matei** [comment] 2017-10-17 09:32
@lambrospetrou you could use VS Code on Windows and use Bash as the integrated terminal, executing the `go` commands against Linux.

Not the best experience, but gets the job done.

**Comment by lambrospetrou** [comment] 2017-10-17 09:36
@radu-matei I know about that but the whole benefit of having a plugin for a language is to provide editor assistance (autocomplete, suggestions, auto formatting on save, highlighting errors, etc.). If I was just using it as a notepad and then run commands through terminal, I could just use the normal terminal, not VSCode's.

**Comment by radu-matei** [comment] 2018-03-29 09:29
Any news on this?
Thanks!

**Comment by Benjiiim** [comment] 2018-05-01 23:01
It seems that VS Code has a debugging option "useWSL" which aims to acheive that. Cf https://blogs.msdn.microsoft.com/commandline/2017/10/27/running-node-js-on-wsl-from-visual-studio-code/
Wouldn't it make sense to use this setting for Go as well?

**Comment by eug48** [comment] 2018-06-07 10:14
WSL could enable use of Sourcegraph's Language Server on Windows, potentially improving editor latency?

**Comment by xcdr** [comment] 2018-06-14 11:45
Support for WSL is important to me, any complete solution is desirable.

**Comment by mhamrah** [comment] 2018-08-03 00:08
+1

**Comment by mrpoundsign** [comment] 2018-08-03 00:45
+1

**Comment by RobHumphris** [comment] 2018-08-07 12:02
Another please please please vote from me. I am writing go code on my Windows machine that runs a number Linux executable binaries, so the debugger needs to run in the context of the WSL for me to inspect the command and ProcessState values.

**Comment by tscott-au** [comment] 2018-08-15 03:52
+1

**Comment by raphaelvalerio** [comment] 2018-08-25 19:47
+1

**Comment by benc-uk** [comment] 2018-09-10 07:17
Sorry to be another +1'er but this is a problem that plagues VSCode. Using Git, Node, Python and Golang requires me to have the them all installed twice, once in WSL and once in Windows. 
It's very messy, very confusing & requires multiple configurations that can get out of sync

**Comment by dsci** [comment] 2018-09-13 09:40
+1

**Comment by lsh246** [comment] 2018-10-17 15:50
Another +1. Moving from MacOS to Win10 building Linux binaries and wish I could debug seamlessly in VSCode.

**Comment by xcdr** [comment] 2018-10-29 09:33
This is also important for me, I cannot switch from MacOS to WIndows 10 without this feature.

**Comment by nkhine** [comment] 2018-10-29 15:59
+1, I have the same, I am developing functions for serverless in golang on windows10

**Comment by shayne** [comment] 2018-10-29 17:13
While having this issue resolved within VSCode would be nice, I've found that using VSCode installed under WSL, using X410 (Windows Store) as the X11 server, is incredibly seamless and solved my immediate needs.

Installing VSCode in WSL Ubuntu is as easy as downloading the .deb package from the VSCode website. Running `sudo apt install <deb-file>`, then creating a shortcut that launches VSCode from within WSL utilizing the X410 (which enables GUI Linux apps on Windows, i.e. WSL GUI apps).

https://token2shell.com/howto/x410/creating-shortcut-for-wsl-gui-desktop/

From there you setup Ubuntu under WSL as you would a Linux dev environment. Fonts can be copied over from Windows to `~/.local/share/fonts` and are made available to the Linux apps.

For better looking UI take a look at the X410 howto below:
https://token2shell.com/howto/x410/setting-the-theme-for-linux-gui-apps-windowed-apps-mode/

And halfway down in this how-to they show how to install Adapta theme, which I thought looked good.
https://token2shell.com/howto/x410/customizing-xfce-desktop-for-ubuntu-wsl/

**Comment by napalm684** [comment] 2018-10-31 17:06
@shayne I pursued this today looks ok but I'm curious how stable given guis aren't officially supported by WSL.  What has your stability experience been like?

**Comment by napalm684** [comment] 2018-11-01 16:08
Also (sorry for double post) delve for debugging doesn't seem to work this way.  Any special config needed?

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": [],
            "showLog": true
        }
    ]
}
```

**Comment by redblue9771** [comment] 2018-11-16 01:32
Have you solved this problem? I can't get any relevant news.

**Comment by nicowernli** [comment] 2018-12-01 15:02
I've made a test to see if it was possible to run tests from WSL and everything worked fine.

```bash
bash.exe -c 'source /etc/environment && source ~/.bashrc && cd PATH_TO_GO_MODULE && GOOS=linux GO111MODULE=on /usr/local/go/bin/go test -run ^TestWSL$'
```

Running the `bash.exe` won't load the environment variables configured in your wsl linux, so you need to set every thing again or run the `source` command.

**Comment by nicowernli** [comment] 2018-12-19 11:54
After installing the wsl-alias I'm able to run linux `go` commands from powershell. The proble is that the extension will add the `.exe` to the executable if detectes that you are running it on windows. 

Would be nice to have a `go.executable` config to override that behaviour.

**Comment by ramya-rao-a** [comment] 2019-05-03 00:56
Hello everyone, we finally have an update here!

Checkout the below tweets from the official VS Code twitter handle: https://twitter.com/code/status/1124057230624665620
https://twitter.com/code/status/1124016109076799488

And the official blog post on [Remote Development with VS Code](https://code.visualstudio.com/blogs/2019/05/02/remote-development)

Please try out the above extensions and log new issues if any of the features of the Go extension doesn't work as expected.

**Comment by shayne** [comment] 2019-05-03 01:08
@ramya-rao-a incredible! Can't wait to try it out. Thank everyone for me, will ya

**Comment by redblue9771** [comment] 2019-05-03 10:30
I am so happy to hear that VS Code officially supports the remote development mode, which includes ssh mode, docker mode and wsl mode. Although not perfect, the official saw our needs.
From Chinese developers

**Comment by yanivpaz1973** [comment] 2019-05-22 06:43
I tried the links above but still cant add breakpoints for my go code

**Comment by ramya-rao-a** [comment] 2019-07-07 00:33
Closing this issue as we now have [Remote Development with VS Code](https://code.visualstudio.com/blogs/2019/05/02/remote-development)

If you see any problems working with the above, please log new issues

**Closed by ramya-rao-a** 2019-07-07 00:33 UTC
