### ISSUE TITLE
Type hints on hover are incorrect when omitting the value while ranging over a slice

### ISSUE THREAD

**Issue by m90** [Microsoft/vscode-go#1242] opened 2017-09-23 11:27 UTC
Considering the following program:

```go
package main

import (
	"fmt"
)

func main() {
	s := []string{"a", "b", "c"}
	for index, char := range s {
		fmt.Println(index, char)
	}
	for index := range s {
		fmt.Println(index)
	}
}
```
with the rather obvious output of

```
0 a
1 b
2 c
0
1
2
```

I found a bug in the type hints that will be displayed when hovering over an expression in the editor.

Using 0.6.65, running Go 1.9 I will see the correct hint (`int`) when hovering over `index` in the first loop of the example:

![bildschirmfoto vom 2017-09-23 13-20-18](https://user-images.githubusercontent.com/1662740/30772762-c39d6c50-a062-11e7-8ed0-0530aee1eec3.png)

when hovering over the second `index`, I will incorrectly be told that this is a `bool` (when it is still an `int`):

![bildschirmfoto vom 2017-09-23 13-20-24](https://user-images.githubusercontent.com/1662740/30772777-f7097f66-a062-11e7-9376-cf9f8b0ad6ff.png)

**Comment by ramya-rao-a** [comment] 2017-09-24 08:30
@zmb3 Thoughts? I see the same when using `gogetdoc` as well.

**Comment by zmb3** [comment] 2017-09-25 00:31
Interesting. I will look into it!

**Comment by zmb3** [comment] 2017-09-25 17:08
@ramya-rao-a can we confirm vs-code is invoking `gogetdoc` with the correct offset?  I'm not able to reproduce at the command line:
```
~/src/github.com/zmb3/doctest
❯ cat main.go
package main

import (
	"fmt"
)

func main() {
	s := []string{"a", "b", "c"}
	for index, char := range s {
		fmt.Println(index, char)
	}
	for index := range s {
		fmt.Println(index)
	}
}

~/src/github.com/zmb3/doctest
❯ gogetdoc -pos "main.go:#84"
import "github.com/zmb3/doctest"

var index int

Undocumented.


~/src/github.com/zmb3/doctest
❯ gogetdoc -pos "main.go:#144"
import "github.com/zmb3/doctest"

var index int

Undocumented.
```

**Comment by m90** [comment] 2017-09-25 17:58
@zmb3 I just looked into this and it seems that the bug stems from the fact that the extension is falling back to `godef` as it is set to `go.docsTool: godoc`. If I use `gogetdoc` it will show me the correct type (which is great).

@ramya-rao-a  this probably means it is still an upstream bug, but in `godef`. What's the reason for `godoc` as a default?

**Comment by m90** [comment] 2017-09-25 18:05
Yes, I can confirm that `godef` prints incorrect information in this case:

```
frederik@fr-xps:~/projects/go/src/github.com/m90/test$ cat main.go 
package main

import (
	"fmt"
)

func main() {
	s := []string{"a", "b", "c"}
	for index, char := range s {
		fmt.Println(index, char)
	}
	for index := range s {
		fmt.Println(index)
	}
}

frederik@fr-xps:~/projects/go/src/github.com/m90/test$ godef -o 144 -f main.go -t
main.go:12:6
index bool
```

**Comment by ramya-rao-a** [comment] 2017-09-25 19:50
Sorry about that @zmb3, I was so sure I had changed the setting to use `gogetdoc` when testing.

@m90 `godef` gives the location and signature of the definition. We pass this to godoc to get further doc info. 

Please open an issue in the `godef` repo so that @rogpeppe can take a look there

#1025 is tracking the feature request to make gogetdoc the default option as there are quite a few cases where the godef+godoc combo doesnt give the right results

Closing this issue for now as using gogetdoc gives you the right results

**Closed by ramya-rao-a** 2017-09-25 19:50 UTC
Labels: upstream
