### ISSUE TITLE
Can't debug a single file in debug mode

### ISSUE THREAD

**Issue by erifan** [microsoft/vscode-go#3053] opened 2020-02-17 05:07 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
         go1.13.8 amd64 windows platform
         vscode version: 1.42.0

### Describe the bug
There are two files under $GOPATH/src, both of them contain main function, I want to debug one file of them, the the launch.json file is as follow:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch file",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${file}"
        }
    ]
}

```

**Comment by hyangah** [comment] 2020-02-21 21:19
Looks like a duplicate of #1229

**Comment by stamblerre** [comment] 2020-02-21 21:27
Duplicate of #1229

**Comment by stamblerre** [comment] 2020-02-21 21:28
Thanks for looking into this - I'll close in favor of that issue then.

**Closed by stamblerre** 2020-02-21 21:28 UTC
Labels: debug
