### ISSUE TITLE
[feature request] add go.lintOnOpen option

### ISSUE THREAD

**Issue by bruceauyeung** [microsoft/vscode-go#654] opened 2016-11-28 06:45 UTC
when i open a golang workspace, i'd like `vscode-go` to lint this workspace immediately, but currently there is only an option `go.lintOnSave`, so the only way to lint immediately is that modify some go source file(s) manually ( add a blank space in the end of line for example ).
i request adding an option `go.lintOnOpen`, so when we open a go source file or a golang workspace, `go lint` will be started.

**Comment by ramya-rao-a** [comment] 2016-11-29 04:42
If you have `go.lintOnSave` enabled, then on opening a workspace, linting does run. You don't have to specifically save to trigger it.

Can you open your output window, change the chanel to Go and reload VS Code?
You should see linting output there.

**Comment by bruceauyeung** [comment] 2016-12-01 03:25
strange things are happening! it does lint when open a workspace , accurate to say that it's triggered by opening a go source file in the workspace. but i am quite sure that i have to modify and save something to trigger lint because i waited for a long long time on purpose.

**Comment by ramya-rao-a** [comment] 2016-12-01 04:10
When the Go extension first gets activated (when you open a workspace and open a Go file), it lints the package to which the currently opened Go file belongs to. On subsequent file opening, linting does not get triggered until you save.

Does that match what you are seeing?

**Comment by bruceauyeung** [comment] 2016-12-01 07:03
1，i open a totally fresh vscode without opening any workspace, then i open a workspace through `File` -> `Open Folder`, and then i open a Go file in this workspace, now i can see this file is detected as a Go file because the right-bottom corner says so. then i open output window (View -> Output), i don't see any outputs.in the dropdown list there neither is no Go option
2, i keep the opened Go file opened and restart vscode, the Go file is opened by default, and lint is triggered as you said. i open another Go file in a different package, lint is not triggered until i save.

**Comment by ramya-rao-a** [comment] 2016-12-16 01:56
I can confirm you second point, but not the first.

Regardless, lint on file open seems like a good feature.

PRs are welcome

**Comment by jackie-qiu** [comment] 2017-06-01 07:19
@ramya-rao-a Like the sublimelinter, could vscode-go supports trigger the lint with serval modes?
Like background, load/save, save only and manually?

**Comment by ramya-rao-a** [comment] 2017-06-01 14:31
@jackie-qiu That is not currently possible, but it would be a good feature to add. We were just discussing something similar in #1015. Please add your thoughts there.

**Comment by ramya-rao-a** [comment] 2020-01-22 23:14
There hasnt been much progress in this area in the 2 years since the help-wanted tag was added to this issue.

While I do see the merits of this feature, I am afraid the work to make this happen is not trivial.
Since been lint on demand and lint on file save features do provide good enough linting, am closing this feature request.

In the future, the language server `gopls` can be the right place for lint on open feature.

Thanks for your patience and Happy Coding!

**Closed by ramya-rao-a** 2020-01-22 23:14 UTC
Labels: enhancement, help wanted
