### ISSUE TITLE
try to install gocode-gomod and godef-gomod but output panel stacking there

### ISSUE THREAD

**Issue by wotmshuaisi** [Microsoft/vscode-go#2024] opened 2018-10-18 04:35 UTC
```
Installing 2 tools at /home/xxxx/go/bin
  gocode-gomod
  godef-gomod
```

**Comment by 2011fuzhou** [comment] 2018-10-18 07:01
> ```
> Installing 2 tools at /home/xxxx/go/bin
>   gocode-gomod
>   godef-gomod
> ```

same problem, but i'm using go in windows:
Installing 2 tools at D:\coding\go\bin
  gocode-gomod
  godef-gomod

**Comment by demothorg** [comment] 2018-10-18 07:04
I have such issue with gocode-gomod.
VSCode: 1.28.2,
VSCode-go: 0.6.92,
golang: 1.11.1, 

Console output on every install/update tools run:
```
log.ts:171   ERR ENOENT: no such file or directory, open 'C:\Program Files\Microsoft VS Code\extension-output-#2': Error: ENOENT: no such file or directory, open 'C:\Program Files\Microsoft VS Code\extension-output-#2'
	at Object.fs.openSync (fs.js:646:18)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
	at Object.fs.readFileSync (fs.js:551:33)
	at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
	at TrailingSpaces.freezeLastVersion (C:\Users\Admin\.vscode\extensions\shardulm94.trailing-spaces-0.2.11\out\src\trailing-spaces\trailing-spaces.js:266:51)
	at C:\Users\Admin\.vscode\extensions\shardulm94.trailing-spaces-0.2.11\out\src\trailing-spaces\trailing-spaces.js:56:19
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:588:237
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:488:823)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:126)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

And also I have godoc installation error:
```
Installing 1 tool at C:\Users\Admin\Documents\Source\Go\bin
  godoc

Installing undefined FAILED

1 tools failed to install.

godoc:
Error: Command failed: C:\Go\bin\go.exe get -u -v 
package undefined: unrecognized import path "undefined" (import path does not begin with hostname)
package undefined: unrecognized import path "undefined" (import path does not begin with hostname)
```

**Comment by pr10n** [comment] 2018-10-18 10:36
Same here.
> Installing 13 tools at /mnt/xxxx/go/bin
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  dlv
  gocode-gomod
  godef
  godef-gomod
  goreturns
  golint
  golangci-lint

**Comment by karthikraobr** [comment] 2018-10-18 13:46
Maybe related to [this](https://github.com/Microsoft/vscode-go/issues/1979).

**Comment by apmckinlay** [comment] 2018-10-18 17:10
But 2025 says it is just a "partial" fix?

**Comment by Dexus** [comment] 2018-10-18 17:38
The fix does not help.....

The problem is that #2025 does not fix this in any way.

The following has helped me:
```
go get -u -v github.com/ianthehat/godef
go get -u -v github.com/stamblerre/gocode

# and in $GOPATH/bin use the first folder of the gopath, if there are several.....
cp godef godef-gomod
cp gocode gocode-gomod
```

Have fun!

**Comment by ramya-rao-a** [comment] 2018-10-18 17:45
The issue with `godoc` is resolved in #2025. 

I have pushed a separate fix for the issue with `gocode-gomod`

Can someone here try the [beta-version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension to confirm the fix?

**Comment by sonofachamp** [comment] 2018-10-18 17:50
@ramya-rao-a The fix is working for me. 👍

**Comment by Dexus** [comment] 2018-10-18 17:50
It looks like something went wrong in PR #1932...
I never get the second if comparison. https://github.com/Microsoft/vscode-go/pull/1932/files#diff-3f57b095642b0ee445d6cdbc4f60d751R371

**Comment by Dexus** [comment] 2018-10-18 17:53
> The issue with `godoc` is resolved in #2025.
> 
> I have pushed a separate fix for the issue with `gocode-gomod`
> 
> Can someone here try the [beta-version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension to confirm the fix?

Maybe you also fix this with godef-gomod

**Comment by ramya-rao-a** [comment] 2018-10-18 17:56
@Dexus I believe the problem was only with `gocode-gomod` and not `godef-gomod`, and since that was stuck, we never go to the point of declaring all updates as successful.

**Comment by Dexus** [comment] 2018-10-18 18:01
@ramya-rao-a Okay, but even `gocode-gomod` didn't help me. I didn't explicitly test the latest beta, but I think it would make sense to intercept it as well for `godef-gomod`

**Comment by ramya-rao-a** [comment] 2018-10-18 18:03
@Dexus Can you elaborate a little more?

**Comment by Dexus** [comment] 2018-10-18 18:07
@ramya-rao-a Sorry `godef-gomod` is correct, I'm a bit confused the day is already more than 20 hours old :eyes:. It does indeed only concern `gocode-gomod` to making everything work.

**Comment by ramya-rao-a** [comment] 2018-10-18 18:14
@Dexus Great!

@sonofachamp Thanks for confirming the fix!

If I can have one more person vet the fix, then I will release an update soon.

**Closed** 2018-10-18 18:42 UTC
