### ISSUE TITLE
No function signature on hover after godef update

### ISSUE THREAD

**Issue by arthurwhite** [Microsoft/vscode-go#366] opened 2016-06-19 15:56 UTC
The function signature does not display (as a tooltip) anymore when hovering a function of the [github.com/andlabs/ui](https://github.com/andlabs/ui) package.

Bug only appeared after updating [godef](https://github.com/rogpeppe/godef), and only with the [github.com/andlabs/ui](https://github.com/andlabs/ui) package, as far as I can see.

But I am not sure if the problem is in [godef](https://github.com/rogpeppe/godef) or in this VS Code extension (maybe because of an API breaking change).

**Comment by lukehoban** [comment] 2016-06-25 17:54
I can't reproduce this.  Can you provide more specific details - like which function call in particular you aren't seeing hover tips for?

Note that there is a lot of CGOcode in `github.com/andlabs/ui`, and godef has never supported hover tips on CGO function calls (not even clear it could support this since the information is only available at link time).  Are the places you aren't seeing function signatures in hover tips just on CGO calls?

**Comment by arthurwhite** [comment] 2016-06-26 18:28
You're right. It has something to do with CGO.

I also tried hovering `Version()` in 

```Go
package main

import "github.com/mattn/go-sqlite3"

func main() {
	sqlite3.Version()
}
```

and the tooltip doesn't show up either.

This started after a recent `go get -u github.com/rogpeppe/godef`.
Maybe something broke with [godef commits on May 27, 2016](https://github.com/rogpeppe/godef/commits/master) because if I roll back to the previous build, the function signature tooltips also work with CGO packages.

So it's more like a godef problem.
Thank you.

NB: For the record, it has been verified on 2 different Macs on OS X 10.11.5.

**Comment by lukehoban** [comment] 2016-07-23 22:56
Got it.  Sounds like this should definitely be reported in the `godef` repo, as it does appear there was some sort of regression there.  Closing issue here since there's nothing we can do in `vscode-go` to help with this.

**Closed by lukehoban** 2016-07-23 22:56 UTC
