### ISSUE TITLE
Extension won't activate with error: failed: Cannot find module 'vscode-extension-telemetry' 

### ISSUE THREAD

**Issue by dawidp** [Microsoft/vscode-go#1612] opened 2018-04-07 11:49 UTC
**Go Version:** `go version go1.10.1 windows/amd64`
**VS Code Version:** 

    Version 1.22.1
    Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
    Date 2018-04-06T02:26:57.615Z
    Shell 1.7.12
    Renderer 58.0.3029.110
    Node 7.9.0
    Architecture x64

**Windows:** `8.1 Pro x64`
**Go Extension Version:** `0.6.78`

I have Go and GOPATH in my env path set, but when I open folder containing go files either from console with (inside folder containing go files): `code .` or with `File -> Open folder...` the extension is not activated and I cannot use `Go: Install/Update Tools` as it says the command doen't exists. Yes, I have disabled the telemetry in VC Code but this error also appears with telemetry enabled.

Here is error from VS Code Developer Console:

    13:25:35.445 extensionService.ts:848 Activating extension 'lukehoban.Go' failed: Cannot find module 'vscode-extension-telemetry'.
    w._logMessageInConsole @ extensionService.ts:848
    w._logOrShowMessage @ extensionService.ts:862
    e.$localShowMessage @ mainThreadExtensionService.ts:32
    e._doInvokeHandler @ rpcProtocol.ts:174
    e._invokeHandler @ rpcProtocol.ts:159
    e._receiveRequest @ rpcProtocol.ts:108
    e._receiveOneMessage @ rpcProtocol.ts:90
    (anonymous) @ rpcProtocol.ts:33
    (anonymous) @ rpcProtocol.ts:213
    e.fire @ event.ts:140
    (anonymous) @ ipc.net.ts:81
    emitOne @ events.js:96
    emit @ events.js:191
    readableAddChunk @ _stream_readable.js:178
    Readable.push @ _stream_readable.js:136
    onread @ net.js:560
    
    13:25:35.445 console.ts:136 [Extension Host] Activating extension `lukehoban.Go` failed:  Cannot find module 'vscode-extension-telemetry'
    t.log @ console.ts:136
    t._logExtensionHostMessage @ extensionHost.ts:395
    (anonymous) @ extensionHost.ts:210
    emitTwo @ events.js:106
    emit @ events.js:194
    process.nextTick @ internal/child_process.js:766
    _combinedTickCallback @ internal/process/next_tick.js:73
    _tickCallback @ internal/process/next_tick.js:104
    
    13:25:35.446 console.ts:136 [Extension Host] Here is the error stack:  Error: Cannot find module 'vscode-extension-telemetry'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Dawid\.vscode\extensions\lukehoban.go-0.6.78\out\src\util.js:11:38)
    at Object.<anonymous> (C:\Users\Dawid\.vscode\extensions\lukehoban.go-0.6.78\out\src\util.js:724:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Dawid\.vscode\extensions\lukehoban.go-0.6.78\out\src\goSuggest.js:9:16)
    at Object.<anonymous> (C:\Users\Dawid\.vscode\extensions\lukehoban.go-0.6.78\out\src\goSuggest.js:287:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Dawid\.vscode\extensions\lukehoban.go-0.6.78\out\src\goMain.js:8:21)
    at Object.<anonymous> (C:\Users\Dawid\.vscode\extensions\lukehoban.go-0.6.78\out\src\goMain.js:392:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:30:770)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:676:131
    at t._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:676:243)
    at t._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:675:161)
    at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:673:282)
    at e._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:417:920)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:417:539
    at Array.map (native)
    at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:417:514)
    at e.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:416:14)
    at t.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:673:646)
    at t.$activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:822)
    at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:395)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:113)
    at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:559:237)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:559:6)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:558:75
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:929
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:30
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:344)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:143:1008)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

**Comment by ramya-rao-a** [comment] 2018-04-08 21:30
Duplicate of #1595 

@dawidp Please try the following
- Delete the folder C:\Users\Dawid\.vscode\extensions\lukehoban.go-0.6.78
- Reload VS Code, install the Go extension

**Closed** 2018-04-08 23:59 UTC

**Comment by dawidp** [comment] 2018-04-09 15:12
missed that bug... but removing folder worked. Thanks :+1:
