### ISSUE TITLE
Blinking screen after auto-import and attempt to save Go files

### ISSUE THREAD

**Issue by fnouama** [Microsoft/vscode-go#420] opened 2016-08-09 20:32 UTC
I'm running vscode 1.4 on Mac OS Yosemite, but I have noticed this issue a while ago. I'm using atom as an alternative, but I prefer vscode. 

![aug-09-2016 16-19-01](https://cloud.githubusercontent.com/assets/586511/17532299/eec7ad8a-5e4d-11e6-9fc6-65d0e506f589.gif)

Meanwhile, I don't see any error through the developer console

<img width="841" alt="vscode_error_snapshot" src="https://cloud.githubusercontent.com/assets/586511/17532496/d97d2814-5e4e-11e6-9eb5-1214a8d81c56.png">

**Comment by kletkeman** [comment] 2016-11-07 01:58
Also occurs on Sierra. I just got an "Illegal value for line" message if that helps. The work around is to touch another tab and then come back. Stops it every time and you can continue. But it's hugely annoying.

**Comment by ramya-rao-a** [comment] 2017-01-03 01:50
@fnouama @kletkeman Do you see the "Illegal value for line" while performing any particular operation or only while saving?

To exclude the sceanrio that this might be caused by other extensions interfering with the save operation, can you disable all other extensions (other than Go) and see if you can still repro this?

**Comment by kletkeman** [comment] 2017-01-03 05:52
I have not seen this in a long time. If I recall correctly, I did just as you suggest, paring down my extensions to a much smaller list and getting rid of anything that seemed experimental or immature. Sure enough, things have stabilised.

**Comment by ramya-rao-a** [comment] 2017-01-03 18:55
Thanks @kletkeman 
@fnouama How about you?

**Comment by fnouama** [comment] 2017-01-03 19:22
@ramya-rao-a I'm not reproducing this issue anymore. One fix that I applied at the time was to run the go command `gocode close`. it seems to fix it.

**Comment by ramya-rao-a** [comment] 2017-01-03 19:33
Thanks @fnouama 
Will close this issue then.

**Closed by ramya-rao-a** 2017-01-03 19:33 UTC
