### ISSUE TITLE
"Go: Build Workspace" fails when editing _test files in a pkg directly under GOPATH

### ISSUE THREAD

**Issue by eraserix** [microsoft/vscode-go#1789] opened 2018-07-16 09:00 UTC
1. Create a simple package pkg with a pkg.go and pkg_test.go file.
2. Edit pgk_test.go and try to build the workspace from there: Ctrl+Shift+P-> Go: Build Workspace.
3. I always get the following error: "can't load package: package .: no Go files in ~/go/src

The same thing works perfectly fine when I'm editing pkg.go, it only fails in pkg_test.go.

```
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
```

**Comment by ramya-rao-a** [comment] 2018-07-16 18:29
Can you share what you see in the output channel for Go at this point? View -> Output -> Go

**Comment by ramya-rao-a** [comment] 2018-07-17 20:51
This seems to happen only when the package is directly under the GOPATH and you have opened GOPATH/src in VS Code
Try building workspace when editing the test file after opening the `pkg` folder in VS Code. It should work.

**Comment by eraserix** [comment] 2018-07-23 05:38
Yep, this works. So I should not add ~/go/src to the workspace but the individual "projects"?

Thanks!

**Comment by ramya-rao-a** [comment] 2018-07-23 17:57
Ideally, we wouldnt want you to open the entire gopath in VS Code. There are performance considerations especially when your GOPATH grows bigger and bigger due to all the imported packages.

You are still free to open the GOPATH directly in VS Code. I'll keep this issue open until we provide a fix though.

**Comment by ramya-rao-a** [comment] 2018-07-23 17:59
PRs are welcome to fix this issue.

Code pointers:
- [Building and Debugging the extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension) 
- The code responsible for running build when current file is a test file is at https://github.com/Microsoft/vscode-go/blob/0.6.84/src/goBuild.ts#L51

**Comment by qzyse2017** [comment] 2018-08-15 15:02
@ramya-rao-a Hi! I would like to issue a PR to fix this issue, but I am very confused about what the correct behaviour should be for "Run `building workspace` command when editing a *_test.go file". And I found that the output talked above `can't load package: package .: no Go files in /home/user/go/src`  can also appear when use `build workspace` command in a directory opened in vscode which has no direct go files in it(the go files are in its subdirectories).
IMHO，what about let the behaviour for running `build workspace` with test files open be run `go build ...` directly for the workspace and I issued a PR to do that(see [PR 1849](https://github.com/Microsoft/vscode-go/pull/1849) , I closed it myself for I am still not convinced I had done the right thing)

**Comment by ramya-rao-a** [comment] 2018-08-15 17:39
@qzyse2017 The problem with the approach in your PR is that if the user is editing a test file, has set `"go.buildOnSave": "workspace"`, then the errors form the test file will not show up. This is because `go build` ignores test files. We need to run ` go test -c` to get build errors from test files.

> And I found that the output talked above can't load package: package .: no Go files in /home/user/go/src can also appear when use build workspace command in a directory opened in vscode which has no direct go files in it(the go files are in its subdirectories).

Are you sure? Because there is code in place to get all the packages from the subdirectories and run build on them.

**Comment by qzyse2017** [comment] 2018-08-16 00:16
So it is, it needs `go test` to check there is no build error in "*_test.go  files", 
Sorry I had not read the code more carefully but I found if remove the `!isTestFile` (just like I did in the cloded PR), the command run will still be `go test -c -i -o <output-here>`, but it run the command for every package in the space, however, when adding `!isTestFile`, it will run `go test -c -i -o <output-here>` directly in the workspace, so it will performed like the condition talked above.
For the parts
>And I found that the output talked above can't load package: package .: no Go files in /home/user/go/src can also appear when use build workspace command in a directory opened in vscode which has no direct go files in it(the go files are in its subdirectories).  

It can be confirmed by testing [golang example](https://github.com/golang/example) directly in ~/go/src , download the zip and unzip it into ~/go/src/example and test it with `build Workspace` command with a `*_test.go` file open and it will go to execute `go test -c -i -o <output-here>` directly in the workspace, because it will not do this in per package, it will present `no go files ` in the output.

**Comment by ramya-rao-a** [comment] 2018-08-17 00:34
Yes, you are right. Now I recall the reason I had added the `!isTestFile` there.

At any given point, we can either run `go build` or `go test -c` which means either we can build all the go files or all the test files.

When editing and saving single files, I would expect `go build` to run if the file is a go file and `go test -c` to run if it is a test file.

When running the commands `Go: Build Workspace` or `Go: Current Package`, ideally we should run both `go build` and `go test -c`, because the expectation is that all files in the workspace/package should be checked for errors.

When I implemented this feature ( `Go: Build Workspace` & `Go: Current Package`), I felt it was an overhead to run both `go build` and `go test -c`, so I took the shortcut which is what you see in the code today.

Hope that explains the history behind this code.

Currently, the issue that @eraserix has is that `currentGoWorkspace` is the same as `cwd` at  https://github.com/Microsoft/vscode-go/blob/0.6.88/src/goBuild.ts#L123. In such cases, I think we can safely call `go test -c ./...` instead. What do you think?

**Comment by qzyse2017** [comment] 2018-08-17 01:51
Thanks a lot for your detailed explanation about the code's history!~
Yes, you 're right `importPath` is "" for `eraserix`'s case.
It is a good solution to use `go test -c ./...`, it can also work for the condition I mentioned above~
can you give me more advice on how to issue a correct PR to let it cover these various conditions?

**Comment by qzyse2017** [comment] 2018-08-17 07:19
What about using the first  `return` clause for both conditions about `test` and `build`, in fact, remove the `isTestFile` check can do that.

It may be a better choice to use `getNonVendorPackages` and run test compile for each package instead of just use `go test -c ./...` 

Because `go test ./...` seems to search all packages in file system and will not filter packages in vendor under version1.9, see [golang's changelog 1.9 ](https://github.com/golang/go/blob/master/doc/go1.9.html#L147)

**Comment by ramya-rao-a** [comment] 2020-05-28 22:22
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Closing this issue in favor of https://github.com/golang/vscode-go/issues/125. Please subscribe to it for further updates and upvote it as well

Thanks for all the support & Happy Coding!

**Closed by ramya-rao-a** 2020-05-28 22:22 UTC
Labels: help wanted, needs-investigation
