### ISSUE TITLE
Insiders can't start Go debug session: "Cannot find Delve debugger.

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-go#358] opened 2016-06-09 07:59 UTC
Moved from Microsoft/vscode#7374
From @lirao

---
- VSCode Version: Version 1.3.0-insider 2016-06-07T14:59:54.411Z
- OS Version: OSX El Capitian

Steps to Reproduce:
1. Set up a Go project for debugging.
2. Try to start debugging.
3. Error pops up at the top of the screen:  

```
Failed to continue: Cannot find Delve debugger. Ensure it is in your `GOPATH/bin` or `PATH`.
```

With a prompt to edit my launch.json.

This happened in my Go projects after today's update. Did launch.json change? I can't find the Insiders nightlies release notes...

**Comment by lirao** [comment] 2016-06-22 00:01
Any updates? this only happens in the insiders build, but @alexandrudima moved it here so....
I tried adding GOPATH into launch.json in addition to settings.json, but this isn't helping. The same project settings works perfect in stable VS code.

**Comment by alexandrudima** [comment] 2016-06-25 08:41
fyi @egamma @weinand

**Comment by lukehoban** [comment] 2016-06-25 18:07
I just tried a couple projects on the Insiders build, and I can't reproduce this.

How is your GOPATH env var set up?  Have you configured it in settings.json?  Or also globally in a `.bash_profile` or similar?

Are you seeing the different results between release and insiders builds on the same machine with same configuration and same workflow?

There could potentially have been a chance in how vscode env vars are inherited by the debug process.

**Comment by lirao** [comment] 2016-07-06 22:37
Well, I just updated to the latest Insiders, and debugging works again! Guess they fixed it :)

**Comment by weinand** [comment] 2016-07-06 22:41
Most likely the issue was a customised prompt for zsh (or any other shell): https://github.com/Microsoft/vscode/issues/7343

**Comment by lirao** [comment] 2016-07-07 23:50
My GOPATH and GOROOT was defined in settings.json with "go.gopath" and "go.goroot". I use zsh as my shell, and GOPATH is defined in my ~/.zshrc.

**Comment by beinrhythm** [comment] 2016-07-15 18:18
I am also having same issue with the Version 1.3.1. Same issue happening when trying to debug using delve.

`
pandey:~$ dlv version
Delve Debugger
Version: 0.11.0-alpha
Build:
`
 
But its not working on VScode. In vs code when I try to do the debug.. I get this
`
Failed to continue: "Cannot find Delve debugger. Ensure it is in your `GOPATH/bin` or `PATH`."
`

`
pandey:~$ echo $PATH
/Users/pandey/.nvm/v0.10.32/bin:/Users/pandey/bin:/usr/local/sbin:/usr/local/bin:/Users/pandey/bin:/usr/local/sbin:/usr/local/bin:/Users/pandey/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/munki:/Users/pandey/gocode/bin:/Users/pandey/gocode/bin
`
`
pandey:~$ echo $GOPATH
/Users/pandey/gocode
`
`
pandey:~$ ls /Users/pandey/gocode/bin/
dlv*        go-outline* go-symbols* gocode*     godef*      goimports*  golint*     gopkgs*     gorename*   goreturns*  guru*
`

**Comment by weinand** [comment] 2016-07-15 20:38
The fix for Microsoft/vscode#7343 in the June release (1.3.1) was not sufficient to cover all cases.
The July release will have a better fix; you can try it already in the current insider release.
If you cannot use the insider release, just run VS Code from the command line and all will be good.

**Comment by CannibalVox** [comment] 2016-08-24 16:51
Still receiving this error.  Can confirm that `dlv` is on my PATH and not in my gopath/bin.  Running it manually from the command line works fine.  Have restarted vscode-go, can't figure out what's gone wrong.

**Comment by ramya-rao-a** [comment] 2016-10-11 19:01
@CannibalVox Do you still have issues? Which version of VS Code are you using? Can you share your OS details?

As per https://github.com/Microsoft/vscode/issues/7343#issuecomment-227740322, can you try the following:
- open a terminal and print your environment (e.g. by using `env`)
- in VS Code open the Development Tools (<kbd>F1</kbd>, `Developer: Toggle Developer Tools`) and type `process.env` in the console and expand the Object.

Now compare both environments (especially the PATH).
In theory they should be (almost) the same because VS Code tries to import the environment that you get in a terminal into the VS Code environment.

**Comment by anirudh-chhangani** [comment] 2016-10-31 06:23
I could not find GOPATH set inside when I did process.env, though I have setup the same inside user configs, shouldn't it take from there?

**Comment by ramya-rao-a** [comment] 2016-10-31 21:30
The `process` in the console has the same env vars as the process runinng vscode. The Go extension runs in a separate process which should have the same env vars as the former + whatever GOPATH and GOROOT you set in user/workspace config.

To people still having this issue, can you confirm that `dlv` is in your $GOPATH/bin or PATH?

**Comment by nuclearsandwich** [comment] 2016-11-15 05:42
> To people still having this issue, can you confirm that dlv is in your $GOPATH/bin or PATH?

@ramya-rao-a thanks for looking into this! Reporting this on behalf of someone I'm mentoring: we're running into this on a Windows 10 running Code 1.7.1 with Go extension 0.6.49

- `go.gopath` is set in workspace settings.json
- dlv.exe is in `%GOPATH%\bin` and I can run it from a command prompt by specifying the path to it (that is, it isn't in `%PATH%` but is in the GOPATH bin folder).
- We attempted to add the gopath environment variable to `env: {}` in launch.json but it didn't change the error message and I removed it, preferring not to have the same info specified in multiple places.

**Comment by unboxedsolutions** [comment] 2016-12-31 17:22
On Windows 10 I had this same problem. The solution was to set GOPATH (no $ in front) as an environment variable pointing to a folder (which can NOT be your Go directory).  

For example, at a command prompt type:  SET GOPATH=D:\GoPath  
Better yet, set a System Variable in the Advanced tab of your System properties.

Next, follow the instructions for installing dlv, which is at https://github.com/derekparker/delve/blob/master/Documentation/installation/windows/install.md

> go get github.com/derekparker/delve/cmd/dlv

After that everything works for me in Visual Studio Code.

**Comment by ramya-rao-a** [comment] 2017-01-12 21:43
@nuclearsandwich Can you try again with the latest VS Code and latest Go extension?

The debugger cannot read GOPATH from the settings. Therefore, if it is not set outside of VS Code as an env variable, then setting it via the `env` property in the launch.json is the way to go

**Comment by ramya-rao-a** [comment] 2017-02-01 18:55
Summarizing here:

- The debugger tries to find `dlv` binary in GOPATH/bin where GOPATH is the one you have set outside of VS Code as an env variable. If not found there, then it looks at PATH
- The debugger is not aware of any of the settings in your User/Workspace settings. Therefore, if you have set `go.gopath` and expect that value to be used by the debugger to find `dlv`, that will not work. Workaround is to either
     - Specify the GOPATH as an env variable outside VS Code and reload VS Code window
     OR
     - Specify the GOPATH as an env variable using the `env:{}` property in `launch.json`. This will be used as GOPATH by `dlv` itself. And as of the latest Go extension update (0.6.53), this will also be used by the debugger to find `dlv` binary in the first place as well
     OR
     - Update your PATH env variable to point to the location of the `dlv` binary and reload VS Code window

This should help resolve the issue of "Cannot find Delve debugger".
I am closing this issue for now. If the steps above do not help, please drop a comment.

I have added a wiki for troublseshooting debugging issues as well with the same notes: https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#troubleshooting

**Closed by ramya-rao-a** 2017-02-01 18:55 UTC

**Comment by nuclearsandwich** [comment] 2017-02-02 17:24
> The debugger cannot read GOPATH from the settings. Therefore, if it is not set outside of VS Code as an env variable, then setting it via the env property in the launch.json is the way to go

Apologies for the delay, took me a while to try this again on the computer we encountered it on. Updating VSCode and the Go extension, then specifying the GOPATH in both settings and launch.json worked was finally sufficient. Thanks for the help!

**Comment by ramya-rao-a** [comment] 2017-02-02 18:17
@nuclearsandwich glad to hear, Happy Coding!

**Comment by didenko** [comment] 2017-08-19 15:05
Thank you @ramya-rao-a for all the clarifications and the troubleshooting wikipage.

From what I observed when _vscode-go_ fails to find an executable, it often has to do with where the `PATH` and `GOPATH` variables were defined. One should be aware that setting environment variables in different startup files has different, and possibly confusing, effects. In that case on _Manjaro_ Linux distribution, one can set `PATH` and `GOPATH` variables in `.bashrc` (via it's accompanied `.extend.bashrc`). Confusingly, the effect is that both variables will show the correct values from a standalone terminal _*and*_ from the VS Code build-in terminal - so it seems that _vscode-go_ should be aware of the settings. But it is not, and instead it shows the "Cannot find Delve debugger..." error.

The key is to check, like @ramya-rao-a suggested in one of the posts, the Javascript `process.env` property. To do that, go to the menu _*Help*_ &rarr; _*Toggle Developer Tools*_, click on the _*Console*_ tab, and issue the commands `process.env.GOPATH` and `process.env.PATH` at the prompt. If you do not see the desired values displayed, while your terminals seem to show them with the `env | grep PATH` command, then it is likely that `.bashrc` is the wrong location to set these values in your operating system.

Going back to the _Manjaro_ case, one should set the variables via the `.profile` file (in it's `.extend.profile` companion). Although there are some generic guidelines, specifics do differ between Linux distributions. Further documentation about which _Bash_ initialization scripts feed interactive/non-interactive shells with values for _Arch_-based distributions can be found here:

https://wiki.archlinux.org/index.php/Bash#Configuration_files

**Comment by ramya-rao-a** [comment] 2017-08-19 22:59
Thanks for the analysis @didenko
