### ISSUE TITLE
"Find All References" taking forever

### ISSUE THREAD

**Issue by gedw99** [Microsoft/vscode-go#443] opened 2016-08-19 11:25 UTC
This used to be pretty fast. Maybe 1 to 10 seconds depending on the size of the project.

Now its taking over 5 to 10 minutes ! I have to Escape it and break out of it.

I am wondering whats wrong ??
- Is it because i have so many go projects in my $GOPATH/src/... ?
- Is there a setting i have wrong ?
- Is there a bug in the extension ?

````
go env
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

````

User Settings:
````
// Place your settings in this file to overwrite the default settings
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.formatTool": "goreturns"

    , // "files.autoSave": "onFocusChange",
    "files.autoSave": "onFocusChange"
    
}
````

workspace settings:
````
// Place your settings in this file to overwrite default and user settings.
{
}

`````

**Comment by gedw99** [comment] 2016-08-19 13:36
Could someone let me know  if this is a bug, or a user usability error at least.

Its really slow

**Comment by lukehoban** [comment] 2016-08-21 00:24
A couple months back we switched to use `oracle` as a more official implementation of Find References.  https://github.com/Microsoft/vscode-go/commit/509d6abbe360319596d44eeebfb7917832d89dbb

I suspect this is a dupe of https://github.com/Microsoft/vscode-go/issues/340.  Would be good to continue discussion/feedback there.

I dod suspect that cost of Find References is proportional to size of your GOPATH, so if you work in a smaller scoped environment it may be faster.

**Closed by lukehoban** 2016-08-21 00:24 UTC
