### ISSUE TITLE
Remove incorrect slice declaration suggestion and fix the debugger display

### ISSUE THREAD

**Issue by didenko** [Microsoft/vscode-go#1099] opened 2017-07-20 15:35 UTC
The extension's problem report to replace an initializing "make" call for a slice is wrong and dangerous - may create a hard to trace bug. Here is how the problematic suggestion looks like [in the code](https://github.com/didenko/slops/blob/8f53b2f/exclude.go#L7):
 
![1707201002](https://user-images.githubusercontent.com/99670/28424906-759730b0-6d34-11e7-8d9b-14f4a24e372d.jpg)
![1707191448](https://user-images.githubusercontent.com/99670/28424911-78d88422-6d34-11e7-9098-bb21db99ef9e.png)

It is wrong because it suggests to replace an actual empty slice with a nil pointer. Yes, in many cases it would be OK - and `fmt.Println` even prints them both as `[]`. However, there are some very important cases when the difference creates a hard to find bug - exactly because most logging solutions show these values in the same way. And even though the suggestion uses the word "probably", it is dangerous because it's effects may not be immediately obvious.

Specifically, tests fail if the suggestion is followed in the `slops` package - and it is not immediately obvious why.

Here is the playground example of the issue: https://play.golang.org/p/Hwoy7nAuV8

There also was a related meaningful discussion in [comments to the answer at StackOverflow](https://stackoverflow.com/questions/15311969/checking-the-equality-of-two-slices/15312097#comment48159183_15312097). As I mentioned there: it is common for a slice-return value of nil to have meaning, like used by the `regexp` package's `Find*` functions: https://golang.org/pkg/regexp/#Regexp.FindAll

Given how hard this issue is to troubleshoot because of the lack of visibility I also suggest that in the debugger watch panels should display uninitialized slices as what they are - `nil` values.

**Comment by ramya-rao-a** [comment] 2017-08-21 03:01
@didenko 

Thanks for the detailed report.

About the reported problem, looks like it is coming from either the linter or by running `go vet`. The Go extension displays the results from these tools and is not aware of the nature of the errors/warnings themselves. I can help in narrowing down which tool is giving the said warning, but beyond that you'd have to log the issue in the repo for the tool in question.

About the debugger watch panel, can you provide a code sample and repro steps with details on the current and expected behavior?

**Comment by didenko** [comment] 2017-08-30 16:24
@ramya-rao-a, sorry it took me a while to get back to this. Here is the screenshot of what I mean:

![2017-08-30 11 14 44](https://user-images.githubusercontent.com/99670/29883029-8880eb02-8d74-11e7-8b3b-8d8ad2a10c40.jpg)

As you can see, the slice of strings `ss` has been declared, at which point it is initialized as `nil`. It does test equal to nil.  Note how it is shown as 0-length slice of strings in the _VARIABLES_ window. This is where I would like to see some indication of it being `nil`.

As we step through the example, `ss` gets a 0-length slice value. It does not test equal to `nil` anymore - so the value stored in the variable has clearly changed. Yet the debugger's _VARIABLES_ window shows it exactly the same as before:

![2017-08-30 11 15 13](https://user-images.githubusercontent.com/99670/29883236-44dec13e-8d75-11e7-83e8-7da4f722ab09.jpg)

So my perception of the bug is that the debugger does not show a change in the variable value.

To save you typing, here is the snippet used in the example:

```go
package main

import "log"

func main() {
	var ss []string
	log.Println(ss == nil)
	log.Println(ss)
	ss = make([]string, 0)
	log.Println(ss == nil)
	log.Println(ss)
}
```

P.S. As you can see from the print statements, Go libraries also print different `ss` values identically, so I suspect the debugger problem is upstream as well - but I thought it would be worth to check with you.

**Comment by didenko** [comment] 2017-09-01 01:50
By the way, updated `golint` no longer gives the wrong suggestion.

**Comment by ramya-rao-a** [comment] 2017-09-01 02:34
The issue with the display of slices is upstream as well

The Go extension uses delve for debugging and displays what it gets from delve.
As you can see below delve returns the exact same thing both the times, and we display the same

![debug](https://user-images.githubusercontent.com/16890566/29953231-22ac0ee6-8e83-11e7-8438-4fb93aacff1f.gif)

Can you log an issue for delve at https://github.com/derekparker/delve? 

Closing this issue as there is nothing we can do from the extension's side unfortunately.

**Closed by ramya-rao-a** 2017-09-01 02:34 UTC

**Comment by didenko** [comment] 2017-09-01 02:58
Makes sense. Thank you for looking into this and for the pointers!

**Comment by ramya-rao-a** [comment] 2017-09-01 05:27
No problem and Happy Coding!
