### ISSUE TITLE
Use goimports fork for modules support

### ISSUE THREAD

**Issue by heschik** [Microsoft/vscode-go#2098] opened 2018-11-05 18:25 UTC
I've pushed a [beta version of goimports](https://github.com/heschik/goimports) that uses go/packages for module support. As usual, it's slower than we'd like it to be but should be functional. I think it's ready for use in the same circumstances as the godef and gocode forks.

It does have one slight difference in behavior vs. standard goimports, described in https://github.com/golang/go/issues/28428, but that change should be merged soon.

**Comment by heschik** [comment] 2018-11-08 19:37
@ramya-rao-a: need anything else from me?

**Comment by ramya-rao-a** [comment] 2018-11-08 23:38
@heschik I have pushed the necessary changes, and this will be part of the next update

**Closed** 2018-11-09 02:18 UTC

**Comment by coder543** [comment] 2018-11-17 21:13
I'm not 100% sure, but this could be breaking things right now. `goimports` was seemingly never being run, and switching back to `gofmt` definitely worked in VS Code settings, so I started digging in the code here and found that it might be trying to call `goimports-gomod` which isn't in my path. So, I `go get` installed the fork, then copied it to `goimports-gomod`, and things started working.

However, I'm not sure this code change has actually been deployed to the extension store yet, so another possibility is that `goimports` (non-fork) simply doesn't work on module-enabled projects at this point, and that by installing the fork on top of `goimports` and `goimports-gomod` that I fixed things that way.

**Comment by ramya-rao-a** [comment] 2018-11-21 03:41
> I'm not sure this code change has actually been deployed to the extension store yet,

Yes, this code change has not been released yet. You can use our [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) which does have the changes

> So, I go get installed the fork, then copied it to goimports-gomod, and things started working.

Am not sure how this would work as the changes to use `goimports-gomod` is not yet out. Were you using the extension by running it from source?

> goimports (non-fork) simply doesn't work on module-enabled projects at this point, 

That is true

> but if I set goreturns as the on save formatter, nothing ever happens when I save.

How about when you manually run the formatter? Right click -> Format Document?

**Comment by heschik** [comment] 2018-11-27 20:55
@ramya-rao-a if this still hasn't been released it might make sense to roll it back. The fork is affected by golang/go#28645, and after some internal discussions it looks like we're going to try to get tip working with modules. (Similar to godef.)

If it has been released, no problem.

**Comment by ramya-rao-a** [comment] 2018-11-28 00:57
This has not been released @heschik 

> after some internal discussions it looks like we're going to try to get tip working with modules. (Similar to godef.)

That's great news. In that case, I'll just revert the changes done as part of this issue.

**Comment by atombender** [comment] 2018-12-05 16:51
@ramya-rao-a Until this is fixed, how do I make the `github.com/heschik/goimports` fork work with Go 1.11 and modules?

I installed the fork, and via `ps` I can see that it's being executed (`goimports -srcdir <file>`). If I run it manually on the command line, it works, and correctly adds missing imports. But inside VSCode, while the code is formatted correctly, imports are never automatically added.

I don't understand why the tool would behave differently in the shell, vs. inside VSCode. My environment should be identical.

**Comment by atombender** [comment] 2018-12-05 16:57
...Looks like it's because VScode runs `goimports` from a different directory. `goimports` only works if invoked with the current working directory set to the root of the module. I bet this also applies to the official `goimports` tool, once fixed. (`go get` also works differently if invoked inside a module, vs. outside. I don't like that.)

**Comment by atombender** [comment] 2018-12-05 17:32
Yes, the parent directory of the file is the most appropriate. I've confirmed that it works correctly for subdirectories under a module.

[This comment](https://github.com/golang/go/issues/27287#issuecomment-430525898) is relevant to the above. Not sure if `goimports` will be fixed, or if it will require the right working directory.

**Comment by ramya-rao-a** [comment] 2018-12-05 17:54
@atombender Can you remove the wrapper and try the latest [beta version](
https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension? I have updated it to use the parent directory of the file as cwd.

**Comment by atombender** [comment] 2018-12-05 18:01
Fix confirmed. 🎉 Thank you!

**Comment by ramya-rao-a** [comment] 2018-12-05 18:08
Thanks! Since you already have the beta version now, you can also check out the upcoming features in the next update. Take a look at 
https://github.com/Microsoft/vscode-go/issues/2164

**Comment by atombender** [comment] 2018-12-05 23:41
I understand the problem, but is that relevant to `goimports` and formatting? If we only consider Go modules (not pre-modules `GOPATH` or `vendor`), I see two use cases:

1. You run `goimports` on a module within your own tree. In this case, `go env GOMOD` is always the next parent in the file system that has a `go.mod`, as I understand it.

2. You do a "jump to definition" and end up in a file outside your project, presumably inside the module cache. But you're not going to be running `goimports` on that code anyway. But if you _did_, it would resolve imports relative to _that_ module, by finding the parent module, which would be correct. You wouldn't want that to resolve imports relative to the module in which you jumped from.

Are there other use cases?

**Comment by ianthehat** [comment] 2018-12-06 00:49
It is less of a problem for goimports than almost any other tool, but we want one clear rule that works for all tools in all editors, and most other tools will care.
If a tool would be happy with using the parent dir of the file, the tool could do that itself, so why get all the editors to do it. If it wants to know the workspace and you have changed the directory to the file, it has no way to recover that information. Setting the CWD to the workspace allows the tool to make that decision for itself.

Extra cases to consider:
  * multi-module repositories
  * a module with a replace directive

Also, if you ran it in the module cache it might not do it relative to that module, because on disk it might not be a valid module, `go env GOMOD` may return the empty string, and it's certainly not on your GOPATH.
Also it may be reasonable to run it on all files, even in the module cache. For instance, goimports does not have to write the file, you might be running it to see if it would change and suggesting fixes before the file is saved, and not want to have to special case the module cache to turn that behavior off.

**Comment by ramya-rao-a** [comment] 2018-12-06 03:18
So, in this case, are we saying that the editor should use the workspace as cwd or that goimports should figure out the right directory based on the file being imported?

**Comment by atombender** [comment] 2018-12-06 03:21
The workspace will be the wrong directory if the file being formatted is in a sub-module. E.g. you have `/go.mod` and `/src/sub/go.mod`, and the file being formatted is `/src/sub/main.go`. In this case, `/src/sub` is the right directory.

In my opinion, from what I understood of @ianthehat's explanation, the directory of the current file will always work for us when formatting with `goimports`. This won't work if you open something in the module cache, or something outside of a module. But then `goimports` will still work, it will just not be able to automatically add new imports.
