### ISSUE TITLE
 You are neither in a module nor in your GOPATH in latest VSCode  

### ISSUE THREAD

**Issue by ramprasadp** [microsoft/vscode-go#3136] opened 2020-03-28 09:18 UTC
Creating a duplicate bug of  Closed issue 
You are neither in a module nor in your GOPATH in latest VSCode
#3086 

I get an irritating message everytime I try to edit a go file 
How can I disable this alert. 
I guess I have to disable gopls  , how can I do that

**Comment by hyangah** [comment] 2020-03-28 12:07
The following will disable the use of Go language server.

```
"go.useLanguageServer" : false
```

But first, check whether your workspace is configured in a way for the gopls can process. Here are the workspace setups currently supported by gopls 0.3.x 
 https://github.com/golang/go/issues/33030#issuecomment-510151934 

We plan to expand the scope of the setup gopls can handle. It would be helpful if you describe your workflow e.g.,
 - Are you running in GOPATH mode or modules mode?
 - go env
 - The current project directory structure (full path)
 - where is go.mod?
 - From which directory you opened the project?

**Comment by hyangah** [comment] 2020-03-28 12:10
@ramya-rao-a and @stamblerre - can we add this to the FAQ?
(Seems like wiki edit permission is restricted)

**Comment by pre** [comment] 2020-03-29 11:15
Had to disable the gopls extension, as it does not work out of the box for exploring projects which do not have modules defines or GOPATH set, as described in
https://github.com/microsoft/vscode-go/issues/3086#issuecomment-597423488

Steps to reproduce the problem: 
- Create a simple "hello world" main.go in an empty folder A
- Do not have GOPATH or Go modules defined
- Open this newly created empty folder A in VSCode 

=> Syntax checking and formatting **do not** work and  Visual Code will display "You are neither in a module nor in your GOPATH. Please see https://github.com/golang/go/wiki/Modules for information on how to set up your Go project."

With gopls disabled, this same "hello world" main.go **does** have syntax checking, formatting and there's no error message even though GOPATH is unset and there are no Go modules defined.

**Comment by Migaelh** [comment] 2020-03-30 08:29
Yeah I also have this issue, however, I am using [govendor](https://godoc.org/github.com/grobie/govendor) as this separates my modules across different projects/folders. 

I previously did not have this issue until I pulled an old project (that did not make use of govendor) and i had to switch to my GOPATH in settings  (and uncheck "Infer Gopath") after i continued onto my current project (that has govendor) this warning keeps on popping up but everything still works fine.

**Comment by stamblerre** [comment] 2020-03-30 17:06
> @ramya-rao-a and @stamblerre - can we add this to the FAQ?
> (Seems like wiki edit permission is restricted)

@hyangah: I don't have edit permissions for the wiki, but it would be good to add some additional info. I can add it to the Troubleshooting guide, which I believe is linked from the wiki.

> Had to disable the gopls extension, as it does not work out of the box for exploring projects which do not have modules defines or GOPATH set, as described in
> [#3086 (comment)](https://github.com/microsoft/vscode-go/issues/3086#issuecomment-597423488)

@pre: `gopls` doesn't work in a monorepo that contains multiple modules, but it should work fine for packages outside of GOPATH/a module, as long as they don't have any unresolved dependencies. I'm happy to investigate the issue, if you can share the output of `gopls -rpc.trace -v check path/to/file.go`. You can also disable `gopls` by setting `"go.useLanguageServer": false`, as @hyangah said above.

> Yeah I also have this issue, however, I am using [govendor](https://godoc.org/github.com/grobie/govendor) as this separates my modules across different projects/folders.
> 
> I previously did not have this issue until I pulled an old project (that did not make use of govendor) and i had to switch to my GOPATH in settings (and uncheck "Infer Gopath") after i continued onto my current project (that has govendor) this warning keeps on popping up but everything still works fine.

@Migaelh: The warning only pops up when `gopls` can't resolve your dependencies. Can you share your `gopls` logs? (Info on how to do this [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).)

**Comment by alekseyt** [comment] 2020-04-19 14:44
I have the same issue. I'm not using modules or GOPATH, in fact, i'm using CMake scripts to build go code and this warning pops when i press any button. Before extension update it was working fine because i also don't have any dependencies, so there is nothing to resolve besides standard library. I'm using `go version go1.14 linux/amd64`.

**Comment by stamblerre** [comment] 2020-04-19 17:25
@alekseyt: `gopls` relies on on https://pkg.go.dev/golang.org/x/tools/go/packages?tab=doc, which requires a go/packages driver for a given build system (see docs [here](https://github.com/golang/tools/blob/7093a17b0467e77fb41804b2754a44f54a8c9ca2/go/packages/external.go#L20)). In the case that you've describe, `gopls` will be trying to load your workspace using the `go` command and failing, which is why it pops up the warning. If your build system does not have a `gopackagesdriver`, then it will not work well with `gopls`.

**Comment by alekseyt** [comment] 2020-04-19 20:20
Umm. I'm not sure if i understand everything correctly, so `gopackagesdriver` is a binary that speaks JSON - i don't think i have it. I also don't think i have a Go workspace either, the project is in C, but there are some tools needed for projects that compiled from Go source code, then used during build, everything is integrated into CMake scripts as custom targets etc (doesn't matter). There is no GOPATH or modules, nothing is exported, essentially it's just `go build -o tool tool.go lib.go` invoked by `make`, and i need to edit source code of those tools.

I'm just saying. I think i figured out what was wrong with this. Somehow i've got 

```json
"go.useLanguageServer": true
```

in my `settings.json` in vscode, i'm not sure how and when. But default value for this setting appears to be `false`, so if i simply delete this line then message stops popping up. I still have autocompletion, autoformatting and all the goodies that i need.

Maybe i'm missing something, but it works. Thank you for looking into this.

**Comment by cat-turner** [comment] 2020-04-27 14:15
I have this issue today. I would like this to work out of the box. I installed non-insiders version and said no to new gopls related things, and I no longer have this issue.

**Comment by stamblerre** [comment] 2020-05-10 05:57
This issue has now been resolved by https://github.com/golang/go/issues/37279.

**Closed by stamblerre** 2020-05-10 05:57 UTC
Labels: needs more info, upstream-gopls
