### ISSUE TITLE
vscode-go delays keyboard input

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode-go#869] opened 2017-03-16 21:02 UTC
Enabling the go language extension causes noticeable lag on keyboard input. See the attached video where I first type rapidly with the extension disabled and then type rapidly with the extension enabled. Notice that input halts at certain points.

https://cl.ly/063o091N441u

**Comment by nicksnyder** [comment] 2017-03-16 21:06
enabling "go.useLanguageServer" did not improve the behavior

**Comment by ramya-rao-a** [comment] 2017-03-16 23:48
@nicksnyder Has this always been the case or a recent behavior after an update to VS Code or the Go extension?

**Comment by nicksnyder** [comment] 2017-03-17 00:02
I am not always writing Go, so it is hard for me to say how recent this is, but I don't remember it being as bad as I observed today so I do feel like something has changed recently. I am using VS Code 1.10.2 and vscode-go 0.6.55.

**Comment by ramya-rao-a** [comment] 2017-03-17 04:17
Do you have auto save enabled as well as `go.formatOnSave` enabled?

**Comment by nicksnyder** [comment] 2017-03-17 14:36
```
"files.autoSave": "off",
"go.formatOnSave": true
```

**Comment by ramya-rao-a** [comment] 2017-03-17 17:16
Can you try with turning the formatOnSave off? Just to see if its the formatting that's introducing the delay

**Comment by nicksnyder** [comment] 2017-03-17 23:08
Hmm, I can't seem to reproduce today. Maybe my machine got into a bad state yesterday somehow.

**Comment by nicksnyder** [comment] 2017-03-18 14:21
Hmm, wasn't able to reproduce yesterday. Maybe my machine got into a bad state somehow. Will close unless I can reproduce again and have more info.

**Comment by ramya-rao-a** [comment] 2017-03-18 18:47
Thanks @nicksnyder

**Comment by nicksnyder** [comment] 2017-04-05 22:14
I am able to reproduce this again now.

https://cl.ly/3i372x2H3F3t

```
"go.lintTool": "golint",
    "go.formatTool": "goimports",
    "go.gocodeAutoBuild": false,
    "go.formatOnSave": false,
    "go.vetOnSave": false,
    "go.lintOnSave": false,
    "go.buildOnSave": false
```

What else would be helpful for me to do to narrow this down?

**Comment by ramya-rao-a** [comment] 2017-04-06 00:05
I can't think of anything else to help narrow down the cause here. 
And you are sure this happens only in Go files and only when the extension is enabled ?

The only way out I can think of is to reverse engineer this by looking at the code.

Below is the list of what takes place for each change in the current document
- `gocode` is run for autocompletions. This is run for every new word or `.` not every letter
- test coverage is cleared if any
- the test status bar item is cleared
- live errors are reported if `go.liveErrors` is enabled which you dont

![image](https://cloud.githubusercontent.com/assets/16890566/24731703/9bf102d4-1a20-11e7-982f-eb94f4721880.png)

Of these the clearing of test status bar item was introduced in 0.6.54 as part of the test on save feature implementation.
0.6.55 was released the very next day, and you first saw this issue in 0.6.55

https://github.com/Microsoft/vscode-go/blob/master/src/goCheck.ts#L27 gets run EVERY time there is a change to the file which is definitely an overkill. This runs whether you have `testOnSave` turned on or not.

Let's run an experiment. Can you find `<Your user directory>/.vscode/extensions/lukehoban.go-0.6.59/out/src/goCheck.js` and comment the lines that hides the statusbaritem and sets its text?

Note: if you are using insiders replace `.vscode` with `.vscode-insiders` 

And then see if you still see a lag?

OR if you can clone this repo make the above change and side load the extension. See https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code

**Comment by nicksnyder** [comment] 2017-04-06 00:24
Commenting out these lines doesn't change any perf

```
//statusBarItem.hide();
//statusBarItem.text = '';
```

Let me know if you can think of anything else I can/should try to disable.

**Comment by ramya-rao-a** [comment] 2017-04-06 00:35
Another thing you can try is to sideload an old version of the extension say 0.6.53 and see if you still see issues. That way we can narrow down which version caused this.

I still find it hard to believe that the extension is causing this though

**Comment by nicksnyder** [comment] 2017-06-06 03:52
I have since gotten a new laptop. I suspect that the issue here is that on my old machine only had two cores (no hyperthreading), and at times the work being done by the vscode-go extension was hogging enough system resources to negatively impact the perf of the main thread.

I assume the extension model protects against slow running synchronous code (i.e. if you just did a bunch of sleeps in the extension, it shouldn't be able to impact typing in the main thread, right?).

Given that assumption, maybe vscode-go is just kicking off too many jobs in parallel by default (built, fmt, vet, etc.) some of which are potentially long running and resource intensive.

**Comment by ramya-rao-a** [comment] 2017-06-06 05:45
Yes, a slow extension should not be able to impact simple editor behavior like typing in the VS Code extension model.

If you are not seeing this anymore, then I'll close this issue.

Eventually, we plan to move to a language server model where a single server can cater to most of the extension's features and we won't have to kick off multiple processes everytime.

Thanks for circling back to this thread and Happy Coding :)

**Closed by ramya-rao-a** 2017-06-06 05:45 UTC
