### ISSUE TITLE
launch only one gopls

### ISSUE THREAD

**Issue by primalmotion** [Microsoft/vscode-go#2450] opened 2019-04-20 01:49 UTC
I'm not sure if this is possible, but I think it would be good that vscode-go only uses one single instance of gopls. for me it uses ~1.5GB or memory *per* vscode window (and I usually work with 3 or 4 or them). Only using one make my laptop a happy camper.

**Comment by stamblerre** [comment] 2019-04-20 18:54
This is something that we were actually planning on working on, and it would probably be fairly doable because we support 1 "view" per workspace root URI. The issue is that the cache is not shared between views, so if we did that now, the 1 gopls instance per *n* VSCode windows would probably just use *n* times the amount of memory.

**Comment by stamblerre** [comment] 2019-04-20 18:56
Filed https://github.com/golang/go/issues/31589 to track this.

**Comment by ramya-rao-a** [comment] 2019-04-23 06:10
Thanks for reporting @primalmotion 
Since we now have an upstream issue to track this, I'll close this issue

**Closed by ramya-rao-a** 2019-04-23 06:10 UTC
