### ISSUE TITLE
Extension host terminated unexpectedly with SIGPIPE

### ISSUE THREAD

**Issue by gpomykala** [Microsoft/vscode-go#1845] opened 2018-08-14 10:54 UTC
Issue occurs on 2 different Linux systems: Debian 9 / Ubuntu 18. Default plugin / go env settings. GOPATH defined, go tools available in PATH
Steps to Reproduce:

1. open Go project ie. influxDB
2. open any .go file 

Result:
Extension host terminated unexpectedly. Code:  null  Signal:  SIGPIPE

Last entries from extension host log:

[2018-08-14 06:43:59.022] [exthost1] [info] ExtensionService#_doActivateExtension ms-vscode.Go {"startup":false,"activationEvent":"onLanguage:go"}
[2018-08-14 06:43:59.022] [exthost1] [info] ExtensionService#loadCommonJSModule /home/plgrpom/.vscode/extensions/ms-vscode.go-0.6.86/out/src/goMain
[2018-08-14 06:43:59.437] [exthost1] [info] eager extensions activated

**Comment by ramya-rao-a** [comment] 2018-08-14 16:05
Can you try the below just to ensure the state of the extension is not corrupted?
- Uninstall the Go extension
- Close all instances of VS Code and open a new instance 
- The previous step should have cleared up the extension. If not, then go to `~/.vscode/extensions` and delete the folder corresponding to the Go extension
- Install the Go extension

**Comment by ramya-rao-a** [comment] 2018-08-14 17:03
Are you on the latest version (1.26.0) of VS Code? There was both a VS Code (1.26.0) and the Go extension (0.6.86) update yesterday.
Let's try to narrow down which of the 2 might have caused the issue. 
- Uninstall the Go extension
- Add the setting `"extensions.autoUpdate": false` so that when you install the older version in the next step, VS Code doesnt automatically update it.
- Install the older version from https://github.com/Microsoft/vscode-go/releases/tag/0.6.84. (Download the vsix file -> run `code --install-extension Go-0.6.84.vsix` -> restart VS Code)

If you still see the same issue, then its the new update to VS Code, else its the new update to Go extension.

**Comment by ramya-rao-a** [comment] 2018-08-14 17:33
I am assuming you are on the latest version of VS Code (1.26.0). If so, an upstream issue https://github.com/Microsoft/vscode/issues/56301 is being tracked for this in the VS Code repo. 

This is most likely related to an issue with electron throwing SIGPIPE error when passing stdin to a badly spawned process. Stay tuned here for further updates.

**Comment by juliofarah** [comment] 2018-08-14 18:15
I'm having exactly the same issue with `ms-vscode.go`. Is there a quick fix I can make locally before the next updates?

**Comment by ramya-rao-a** [comment] 2018-08-14 18:17
So the upstream electron issue occurs when we try to spawn a process using a command that is not found and then pipe stdin.
Previously this would have resulted in a ENOENT which we catch and show an appropriate msg.
I have pushed a fix to try and catch such a case earlier.

Please try the below and let me know if it fixes the issue

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code
- Try and debug your code now

**Comment by juliofarah** [comment] 2018-08-14 20:10
Thank you so much for the quick reply and for acting so fast on it!

I'm sorry but I don't believe it worked :(
I tried installing it both from the command line and from visual code "Install from VSIX".
This is the output I have from the terminal:
```
➜  service git:(staging) ✗ code --install-extension ~/Downloads/Go-latest.vsix
Extension 'Go-latest.vsix' was successfully installed!
```
Maybe I'm doing something wrong?


![image](https://user-images.githubusercontent.com/484013/44115580-256e85c6-9fc3-11e8-97d7-ab7417e19cce.png)

**Comment by ramya-rao-a** [comment] 2018-08-14 21:36
@juliofarah Can you run `Go: Install/Update Tools` and install all the tools and retry?

**Comment by mgitkin-vz** [comment] 2018-08-14 22:27
Installing the latest version you linked above worked for me 🎉

Thanks @ramya-rao-a !

**Comment by juliofarah** [comment] 2018-08-14 22:30
It worked!

Thanks @ramya-rao-a !

**Comment by mgitkin-vz** [comment] 2018-08-14 22:38
@ramya-rao-a  I seem to be getting the issue again when I save a file and go-format gets triggered. I'll keep testing...

**Comment by mgitkin-vz** [comment] 2018-08-14 22:58
@ramya-rao-a This issue is still occurring sporadically when I save a file. Not sure if its related to gofmt

**Comment by ramya-rao-a** [comment] 2018-08-14 23:08
@mgitkin-vz Can you try to run `Go: Install/Update Tools` to ensure you have all the tools in the right place and see if you still see the issue?

**Comment by calvn** [comment] 2018-08-14 23:27
@ramya-rao-a Also encountering this issue. I've installed the workaround and ensured that all the tools are up-to-date. The extension host still crashes on save.

**Comment by mgitkin-vz** [comment] 2018-08-14 23:29
@ramya-rao-a Yes, I ran `Go: Install/Update Tools` after installing the new extension version

**Comment by ramya-rao-a** [comment] 2018-08-14 23:42
@calvn @mgitkin-vz 
- Can you consistently repro on file save?
- The upstream electron issue may effect other extensions as well. Can you disable other extensions you might have installed other than Go and try?
- Do the logs (Help -> Toggle Developer Tools -> Console) have any other helpful information?

**Comment by calvn** [comment] 2018-08-14 23:46
<img width="1214" alt="screen shot 2018-08-14 at 4 44 08 pm" src="https://user-images.githubusercontent.com/1883212/44124306-6392c970-9fe1-11e8-9563-a33670ac39fb.png">

These are the latest logs from the Console.

**Comment by ramya-rao-a** [comment] 2018-08-15 00:07
@calvn The first error about 'map' of undefined would have shown up when updating the tools right? Then how did you ensure all tools were updated?
Can you turn off the build, test, vet on save feature but not the lint,format on save feature and see if you still get the issue?

I am trying to narrow down which feature is actually causing this. If `Go: Install/Update Tools` was successful, then this issue should not be appearing at all as all required tools will be where they are expected to be

**Comment by ramya-rao-a** [comment] 2018-08-15 00:27
@calvn To disable the features, go to your settings (Ctrl+,), look for `go.buildOnSave`, `go.vetOnSave` and `go.testOnSave` and turn them off.

@mgitkin-vz Please keep an eye out if you see it now after fully quitting VS Code

**Comment by mgitkin-vz** [comment] 2018-08-15 00:42
@ramya-rao-a I just got another crash, this one looks much more informative.

```
log.ts:159  INFO no standard startup: not just one text editor
console.ts:136 [Extension Host] /Users/itkinma/go/src/nms/nms_rest/data_utils.go:484:3: expected operand, found '}'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:488:3: expected '{', found 'return'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:495:6: expected '(', found 'IDENT' generateAppHealthSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:519:6: expected '(', found 'IDENT' getVrrHealth
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:587:6: expected '(', found 'IDENT' getInstanceHealth
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:781:6: expected '(', found 'IDENT' refreshBpToken
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:800:6: expected '(', found 'IDENT' ControllerPeerSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:858:1: expected expression
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:858:6: expected '(', found 'IDENT' BgpPeerSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:861:2: expected 'IDENT', found 'go'

log.ts:171   ERR An unknown error occurred. Please consult the log for more details.
console.ts:136 [Extension Host] /Users/itkinma/go/src/nms/nms_rest/data_utils.go:484:3: expected operand, found '}'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:488:3: expected '{', found 'return'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:495:6: expected '(', found 'IDENT' generateAppHealthSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:519:6: expected '(', found 'IDENT' getVrrHealth
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:587:6: expected '(', found 'IDENT' getInstanceHealth
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:781:6: expected '(', found 'IDENT' refreshBpToken
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:800:6: expected '(', found 'IDENT' ControllerPeerSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:858:1: expected expression
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:858:6: expected '(', found 'IDENT' BgpPeerSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:861:2: expected 'IDENT', found 'go'

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398   ERR An unknown error occurred. Please consult the log for more details.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] /Users/itkinma/go/src/nms/nms_rest/data_utils.go:484:3: expected operand, found '}'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:488:3: expected '{', found 'return'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:495:6: expected '(', found 'IDENT' generateAppHealthSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:519:6: expected '(', found 'IDENT' getVrrHealth
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:587:6: expected '(', found 'IDENT' getInstanceHealth
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:781:6: expected '(', found 'IDENT' refreshBpToken
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:800:6: expected '(', found 'IDENT' ControllerPeerSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:858:1: expected expression
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:858:6: expected '(', found 'IDENT' BgpPeerSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:861:2: expected 'IDENT', found 'go'

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398   ERR An unknown error occurred. Please consult the log for more details.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] /Users/itkinma/go/src/nms/nms_rest/data_utils.go:479:24: expected expression

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398   ERR An unknown error occurred. Please consult the log for more details.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] /Users/itkinma/go/src/nms/nms_rest/data_utils.go:479:24: expected expression

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398   ERR An unknown error occurred. Please consult the log for more details.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] /Users/itkinma/go/src/nms/nms_rest/data_utils.go:492:8: expected operand, found ')'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:495:3: expected ')', found 'for'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:508:6: expected '(', found 'IDENT' generateAppHealthSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:532:6: expected '(', found 'IDENT' getVrrHealth
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:600:6: expected '(', found 'IDENT' getInstanceHealth
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:794:6: expected '(', found 'IDENT' refreshBpToken
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:813:6: expected '(', found 'IDENT' ControllerPeerSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:871:1: expected expression
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:871:6: expected '(', found 'IDENT' BgpPeerSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:874:2: expected 'IDENT', found 'go'

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398   ERR An unknown error occurred. Please consult the log for more details.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] /Users/itkinma/go/src/nms/nms_rest/data_utils.go:492:8: expected operand, found ')'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:495:3: expected ')', found 'for'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:508:6: expected '(', found 'IDENT' generateAppHealthSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:532:6: expected '(', found 'IDENT' getVrrHealth
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:600:6: expected '(', found 'IDENT' getInstanceHealth
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:794:6: expected '(', found 'IDENT' refreshBpToken
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:813:6: expected '(', found 'IDENT' ControllerPeerSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:871:1: expected expression
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:871:6: expected '(', found 'IDENT' BgpPeerSummary
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:874:2: expected 'IDENT', found 'go'

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398   ERR An unknown error occurred. Please consult the log for more details.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] /Users/itkinma/go/src/nms/nms_rest/data_utils.go:496:3: expected operand, found 'for'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:502:3: expected ';', found 'return'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:509:6: expected '(', found 'IDENT' generateAppHealthSummary

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398   ERR An unknown error occurred. Please consult the log for more details.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] /Users/itkinma/go/src/nms/nms_rest/data_utils.go:496:3: expected operand, found 'for'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:502:3: expected ';', found 'return'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:509:6: expected '(', found 'IDENT' generateAppHealthSummary

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398   ERR An unknown error occurred. Please consult the log for more details.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] /Users/itkinma/go/src/nms/nms_rest/data_utils.go:498:3: expected operand, found 'for'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:504:3: expected ';', found 'return'
/Users/itkinma/go/src/nms/nms_rest/data_utils.go:511:6: expected '(', found 'IDENT' generateAppHealthSummary

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1398   ERR An unknown error occurred. Please consult the log for more details.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3213 Extension host terminated unexpectedly. Code:  null  Signal:  SIGPIPE
w._onExtensionHostCrashed @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3213
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2386 Extension host terminated unexpectedly.
t.onDidNotificationChange @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2386
```

**Comment by calvn** [comment] 2018-08-15 00:53
I disabled the three features, did a hard restart of vscode, and after some time the crash occurred. I've attached the a screen capture of the console once again.
<img width="1209" alt="screen shot 2018-08-14 at 5 51 51 pm" src="https://user-images.githubusercontent.com/1883212/44126081-f02f0200-9fea-11e8-8acd-6387d2df93a4.png">

**Comment by ramya-rao-a** [comment] 2018-08-15 00:55
@mgitkin-vz I believe all the errors in that log related to "expected this, got that" is from formatting.

@mgitkin-vz @calvn Can you disable the format on save feature and try again? Add the below setting
```
"[go]": {
    "editor.formatOnSave": false
}
```

**Comment by calvn** [comment] 2018-08-15 01:01
@ramya-rao-a No dice.

<img width="1207" alt="screen shot 2018-08-14 at 6 00 57 pm" src="https://user-images.githubusercontent.com/1883212/44126264-174576a2-9fec-11e8-9cb8-a2f4ca7c5fd1.png">

**Comment by ramya-rao-a** [comment] 2018-08-15 01:03
@calvn I see that you are on gophers slack, can you log in there and we can continue the investigation there? it would be much faster.

**Comment by gpomykala** [comment] 2018-08-15 06:49
In my case reinstall of go sdk  via apt helped. It seems like apt package contains much more than .tgz artifact hosted on golang. It seems like some tool used by an extension was missing in the system

**Comment by iotdog** [comment] 2018-08-15 09:55
I encoutered the same issue, and I just return to VS Code 1.25.1 which works well

**Comment by lizebang** [comment] 2018-08-16 07:34
Not work for me. Emmm...

**Comment by xuefeng-huang** [comment] 2018-08-16 09:47
It appears that this issue happens whenever I enable vscodevim extension and vscodego together. It works fine if I enable vscodego only

**Comment by ramya-rao-a** [comment] 2018-08-16 17:34
@lizebang @xuefeng-huang Did you run `Go: Install/Update Tools` and updated all the Go tools?

**Comment by lizebang** [comment] 2018-08-16 17:53
@ramya-rao-a Thanks a lot. I have update go tools and it works well at least 8 hours. I think there is no problem for me. Thanks.

**Comment by mgitkin-vz** [comment] 2018-08-16 21:17
@ramya-rao-a Using version 0.6.87 I'm not able to reproduce this issue any more (even when using editor.formatOnSave)

Thanks!

**Comment by xuefeng-huang** [comment] 2018-08-17 03:42
@ramya-rao-a I tried to download the new extension Go-latest.vsix you provided but it can't be downloaded. I guess it is a issue with github. Is the fix will be installed automatically within VSCode?

**Comment by ramya-rao-a** [comment] 2018-08-17 11:58
Alright then I'll close this issue.
Thanks everyone for verifying the fix.

**Closed by ramya-rao-a** 2018-08-17 11:58 UTC

**Comment by jhartman86** [comment] 2018-08-17 16:04
Seeing this as well. Tried the fix and still occurring regularly.

**Comment by xuefeng-huang** [comment] 2018-08-18 07:42
@jhartman86 did you upgrade VSCode to 1.26.1? it should fix this issue
