### ISSUE TITLE
Highlighted occurrences do not show in scroll bar when gopls is enabled

### ISSUE THREAD

**Issue by blocknonip** [microsoft/vscode-go#2664] opened 2019-07-19 20:28 UTC
Latest stable vscode-go on macOS Mojave.

```
$ gopls version
version v0.1.3-cmd.gopls, built in $GOPATH mode
```

When `gopls` is enabled, highlighted words no longer show in the scroll bar. This happens regardless of `editor.occurrencesHighlight` setting (which I prefer false, but tested in both configurations).

This does not affect other non-Go file formats, like `settings.json`.

No language server:
![No language server](https://user-images.githubusercontent.com/630723/61563401-72f49480-aa39-11e9-9dbb-138af55fb608.png)

Gopls:
![gopls](https://user-images.githubusercontent.com/630723/61563426-8a338200-aa39-11e9-8e04-66611a96f62d.png)

Thanks.

**Comment by ramya-rao-a** [comment] 2019-07-26 19:18
This is interesting... I see this too, but as far as I know this feature is language agnostic and VS Code shouldn't be caring about whether a language server is being used or not to provide this feature...

@rebornix Any idea why this might be happening or how a language server can possibly interfere with this feature?

**Comment by rebornix** [comment] 2019-07-26 19:56
I'm wondering whether it's because of `DocumentHighlightProvider.provideDocumentHighlights` which might change the behavior of word highlight features.

**Comment by ramya-rao-a** [comment] 2019-07-27 16:01
@rebornix Thanks! I can confirm that the language server does register a document highlight provider.

So it looks like VS Code highlights all occurrences of the word by default unless a document highlight provider is registered. As per https://microsoft.github.io/language-server-protocol/specification#textDocument_documentHighlight, a document highlight provider is very similar to reference provider, which explains why the results from the language server is a much smaller subset than the textual occurrences.

@rebornix So am guessing this is an expected behavior?

**Comment by rebornix** [comment] 2019-07-29 17:46
@ramya-rao-a yup, it's as expected.

**Comment by ramya-rao-a** [comment] 2019-08-01 01:00
Thanks @rebornix 

Closing this issue as this is the expected behavior

**Comment by blocknonip** [comment] 2019-08-01 02:33
@ramya-rao-a Can this be kept open until there is feature parity in this regard with and without the language server? Not being able to skim highlighted occurrences in the scroll bar is a big usability regression for me. I can't imagine I'm the only one.

**Comment by stamblerre** [comment] 2019-08-02 14:51
@blocknonip: What is your preferred outcome for the resolution of this issue? Is it helpful to you for `gopls` to highlight all instances of the `func` keyword? I'd like to understand the expected use cases before `gopls` adds support for this behavior.

**Comment by blocknonip** [comment] 2019-08-02 14:59
I would like it to work in the same fashion that it does without `gopls` in use. In my particular case (`"editor.occurrencesHighlight":false`), that would highlight all occurrences in a semantic-insensitive way. For most people, presumably, who don't change that option from the default, it would highlight semantic symbol occurrences.

Basically, I am accustomed to it working in the current way without `gopls` in use, and I would expect/request that it continue working that way.

**Comment by stamblerre** [comment] 2019-08-02 15:20
In this case, I think perhaps VSCode-Go could consider adding a configuration to disable highlighting via `gopls`, as I don't think it would make sense for `gopls` to support semantic-insensitive highlighting.  @ramya-rao-a: What do you think?

**Comment by ramya-rao-a** [comment] 2019-09-25 03:10
@stamblerre Yes that is a sensible solution.

PRs are welcome to update `go.languageServerExperimentalFeatures` to include `highlight` as a property that the user can enable/disable

Code Pointers:
- [Set up local dev environment](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- package.json is the file to edit to update the `go.languageServerExperimentalFeatures` setting
- `registerLanguageFeatures` function in  `goLanguageServer.ts` should be updated to respect the new setting and disable the feature from the language server appropriately

**Closed** 2019-10-20 21:14 UTC
Labels: good-first-issue, help wanted

**Comment by ramya-rao-a** [comment] 2019-11-04 05:54
Please try the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension has the fix for this

You can use the `go.languageServerExperimentalFeatures` setting to disable the "highlight" feature when using the language server
