### ISSUE TITLE
Go: Autocomplete Unimported Packages works on variable or package symbols

### ISSUE THREAD

**Issue by szyhf** [Microsoft/vscode-go#2469] opened 2019-04-25 01:15 UTC
My go extension suddenly doesn't works well on "Go: Autocomplete Unimported Packages".

If I set the setting of "Go: Autocomplete Unimported Packages" to true, it works well if I first type package name on blank line as I wish, for example:

![error2](https://user-images.githubusercontent.com/14870120/56700956-69f07180-672f-11e9-9fa2-4b372cf31809.png)

But if I already import the package or using an existing variable, it also show the suggest of package, mixed with the 'Member variables' for example:

![err](https://user-images.githubusercontent.com/14870120/56700984-92786b80-672f-11e9-84ea-cb87ac628fdb.png)

And what I used to and expect to see is:

![11](https://user-images.githubusercontent.com/14870120/56701005-c3f13700-672f-11e9-996e-8169096a3c00.png)

I don't know why and I didn't change any setting before.

Really thanks for help.

---
go env
```
go version go1.12.4 darwin/amd64
macOS Mojave 10.14.4
```

**Comment by szyhf** [comment] 2019-04-25 01:16
I‘ve already tried reinstall all go tools and kill old gocode process.

**Comment by huynhnangit** [comment] 2019-04-25 08:16
I have the same issues, vs code not auto import.

**Comment by szyhf** [comment] 2019-04-25 08:18
> I have the same issues, vs code not auto import.

No, my problem is auto import package while I type '.' after a variable, in this case I just want to see the member of the variable Orz

**Comment by huynhnangit** [comment] 2019-04-25 09:38
i just fixed:
1. stop VS code
2. delete file: %UserProfile%\AppData\Roaming\Code\User\settings.json
3. start again

**Comment by rokf** [comment] 2019-04-25 12:08
Deleting `"goUseLanguageServer": true` from the settings should work.

**Comment by Hawken94** [comment] 2019-04-25 13:04
> > I have the same issues, vs code not auto import.
> 
> No, my problem is auto import package while I type '.' after a variable, in this case I just want to see the member of the variable Orz

I also meet the issues, vs code will show all the packages from gopath rather than the member of the variable. This happens suddenly. I remember it worked well a few days ago.

go version go1.12.4 darwin/amd64
macOS Mojave 10.13.6
vscode: 1.33.1
vscode-go:0.10.1

![image](https://user-images.githubusercontent.com/12959892/56737608-61cf1b00-679d-11e9-890c-ca9bf77cde0c.png)

vs code setting:
``` javascript
 {
    "go.autocompleteUnimportedPackages": true,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.lintTool": "golint",
    "go.lintOnSave": "workspace"
}
```

**Comment by szyhf** [comment] 2019-04-25 13:28
> Deleting `"go.useLanguageServer": true` from the settings should work.

I didn't use "go.useLanguageServer"

**Comment by jellevandenhooff** [comment] 2019-04-25 18:05
This happens to me both go.useLanguageServer and without. It started happening recently. It make autocompleteUnimportedPackages impossible to use.

**Comment by szyhf** [comment] 2019-04-26 09:29
> This happens to me both go.useLanguageServer and without. It started happening recently. It make autocompleteUnimportedPackages impossible to use. Reverting to 0.9.2 makes the problem disappear.

Thanks, I revert it

**Comment by malexdev** [comment] 2019-04-26 18:22
I'm having this same issue. Something in v0.10 broke.

Autocompletion seems to suggest the correct symbols, but it also suggests a bunch of other unimported packages, and the cursor for some reason suggests the package I'm trying to complete members for.

Example:
![example](https://user-images.githubusercontent.com/1665116/56827689-24ae6b80-6825-11e9-82e2-44bbfb40e9fe.png)

That same snippet, with the autocomplete box scrolled up:
![example-scrolled-up](https://user-images.githubusercontent.com/1665116/56827701-2e37d380-6825-11e9-8742-d2a2d1a0908f.png)

I have tried completely uninstalling Go, VS Code, the VS Code Go extension, and removing every single customization setting from VS Code. Nothing seems to help. 

This is using the latest versions of the tools VS Code auto installs as of today (2019-04-26), since I completely removed and reinstalled everything. I'm also not using modules yet.

As mentioned earlier this thread, reverting to 0.9.2 fixes the issue. I'm just adding this for additional information if it is helpful.

Sample code:

```go
package password

import (
	"crypto/rand"
)

func randomInt() (int, error) {
	var b []byte
	rand. // autocompleting here fails to sort properly and suggests a lot of unimported packages
}
```

Go settings:

```json
{
    "go.autocompleteUnimportedPackages": false,
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": false,
}
```

Steps to Reproduce:

1. Create a new package.
2. Import anything.
3. Attempt to use autocomplete on the imported package.

**Comment by jellevandenhooff** [comment] 2019-04-27 00:46
FYI @ramya-rao-a -- do you have any idea which 0.10 changes might be related?

**Comment by kyeett** [comment] 2019-04-28 15:41
I have the same problem:

- VSCode Version: 1.33.1, 51b0b28134d51361cf996d2f0a1c698247aeabd8, x64
- OS Version: macOS Sierra, 10.12.6

I backed to 0.9.2, and it solved. Thanks for the suggestion! Coding is impossible with 0.10.

**Comment by ramya-rao-a** [comment] 2019-04-30 00:27
Hello all,

Thanks for reporting the issue. This is definitely a regression i.e. this wasnt a problem in the previous version of this extension (0.9.2). 
  
I have pushed a fix for this. Please try the [latest beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension which has the fix for this and let me know how it goes.

If a couple of you can confirm the fix, I will release an update soon

**Comment by szyhf** [comment] 2019-04-30 01:02
@ramya-rao-a Thanks a lot !!

**Comment by malexdev** [comment] 2019-04-30 15:04
@ramya-rao-a The beta version fixes the issue for me.

It also broke my tab size settings - I went from 2 space sized tabs to 8 space sized tabs (ignoring my VSCode settings, which were still set to 2 spaces). But I imagine that's just something to do with the fact that it's a beta version.

**Comment by ramya-rao-a** [comment] 2019-04-30 16:09
Apologies on the tab size change
It should be back to normal in the [beta update](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)(0.10.2-beta.2) that I just released

**Comment by malexdev** [comment] 2019-04-30 16:18
@ramya-rao-a No worries here. That fixed everything perfectly. Thanks so much!

**Comment by ramya-rao-a** [comment] 2019-04-30 17:10
The fix to this has been released in the latest update (0.10.2)

**Closed by ramya-rao-a** 2019-04-30 17:10 UTC
Labels: bug

**Comment by fintanchen** [comment] 2019-05-01 10:45
So the `GO: Autocomplete Unimported Packages` option isn't work now? When I try to use this feature and this option is checked, it seem nothing happened and no autocompletion . It's a problem since I using `gopls` and seem like no one mentioned before.
![image](https://user-images.githubusercontent.com/28680236/57014025-bf9db000-6c40-11e9-9b3a-fc1ae28cb1a1.png)

**Comment by ramya-rao-a** [comment] 2019-05-01 15:59
@fintanchen Is your project under your GOPATH or are you using Go modules?

If you are using Go modules, then yes this feature doesnt work in such cases and I have logged #2484 to track next steps.

**Comment by fintanchen** [comment] 2019-05-02 01:08
@ramya-rao-a Thans for your work. I am using Go modules. I will check #2484.
