### ISSUE TITLE
Shows that error is in current document, but is actually in another

### ISSUE THREAD

**Issue by deathly809** [Microsoft/vscode-go#105] opened 2015-11-26 08:44 UTC
Sometimes, not sure why, it says there is an error in a comment or random line.  But the error is actually in another document.  Trying to get it to happen again and will take screen shot next time it occurs.

**Comment by lukehoban** [comment] 2015-11-26 16:30
have you updated to the latest version of `vscode-go`?  There was a fix for an issue like this a few days ago.

**Comment by deathly809** [comment] 2015-11-26 17:50
This actually started happening after I updated.

**Comment by lukehoban** [comment] 2015-11-26 18:59
I can't see any obvious way this could happen with the current implementation.  If you can get this to happen again, a screenshot, the error message in question, and any file contents you can share would help track it down.

Closing for now until there is more details to help track this down.

**Closed by lukehoban** 2015-11-26 18:59 UTC

**Comment by deathly809** [comment] 2015-11-26 19:10
I was lucky and it happened again and I got a  screenshot.  I also notice that sometimes errors which do exist don't appear at all until I try to compile.  Could that be related in some way?

![image](https://cloud.githubusercontent.com/assets/1381210/11429528/f69bab12-943e-11e5-9002-6a11ea4caf67.png)

**Comment by lukehoban** [comment] 2015-11-27 19:17
@deathly809 I spent some more time trying to identify the root cause here but I can't find anything and haven't been able to repro in your codebase.  

Two questions:

1. I see you have build/test tasks set up in Code.  Is it possible these errors are coming from those tasks somehow?  I don't think they should, but that would at least provide an explanation.

2. You are working in test files as well as non-test files.  Do you know if when these issues happen, there is any correlation with hitting save inside a `_test.go` file?  The logic for doing type-checking is slightly different in that case, so that may provide a hint at where the problem is.

And of course, if you come up with any steps that can repro this consistently from a fresh Code session, that would be really helpful.

**Comment by deathly809** [comment] 2015-11-27 19:28
Not sure if it is the tasks file as I copied an example I saw online and tweaked it some.  Here is my tasks.json file:  
[tasks.json.txt](https://github.com/Microsoft/vscode-go/files/46020/tasks.json.txt)

At the time I was not modifying the test file, but just noticed that the "error" appeared there as well.  

Will try to reproduce on two machines from scratch.  Both with testing files and without.
