### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by abg1964** [Microsoft/vscode-go#2453] opened 2019-04-22 02:53 UTC
- Issue Type: `Performance`
- Extension Name: `Go`
- Extension Version: `0.9.2`
- OS Version: `Linux x64 4.18.0-17-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/bag/ms-vscode.Go-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ramya-rao-a** [comment] 2019-04-23 06:04
- Are you using Go modules?
- Please use the `Developer: Open Process Explorer` to see which process is causing the high cpu usage and share a screen shot if possible
- Also share any Go related settings you have changed

**Comment by ramya-rao-a** [comment] 2019-04-25 05:15
We have figured out the root cause for the high cpu usage and a fix has been made.
A new release (0.10.1) has just been published and it will have the fix to the issue.

Thanks a lot for reporting and your patience!

**Closed by ramya-rao-a** 2019-04-25 05:15 UTC
Labels: needs more info
