### ISSUE TITLE
Autocomplete for unimported packages Not Working

### ISSUE THREAD

**Issue by ragurney** [Microsoft/vscode-go#1881] opened 2018-08-27 17:16 UTC
I just recently upgraded to Go v1.11, and autocompletion of go packages to import has stopped working. Other intellisense functionality for code completion seems to be working. I have `autocompleteUnimportedPackages` enabled, and have so far tried to reinstalling all tools via `Go: Install/Update Tools`.

**Comment by imkos** [comment] 2018-08-28 01:34
I am the same, for what reason do self-writing objects have only one "PANIC"

**Comment by ragurney** [comment] 2018-08-29 15:08
Thanks for the fast response @ramya-rao-a! No, I don't believe I am using `go.mod`.

**Comment by ramya-rao-a** [comment] 2018-08-29 17:32
@ragurney Are there any errors in the console? Help -> Toggle Developer Tools -> Console

Can you try running `gopkgs -format {{.Name}};{{.ImportPath}}` from the terminal and see if it gives any results?

**Comment by juicemia** [comment] 2018-08-29 22:32
I don't know if there's a process to avoid "me too" comments on issues here so I'm just gonna do it to give y'all some confirmation that it's not necessarily an isolated issue. Sorry in advance.

I'm running into the same thing after installing Go 1.11.

It probably just means that gocode hasn't been updated to account for packages using modules yet.

**Comment by ramya-rao-a** [comment] 2018-08-30 17:51
@ragurney Yes, the javascript related thing is unrelated

Can you grep for the package you were hoping to import from the results of that call to `gopkg`?
Also, have you by any chance set the `go.toolsgopath` setting?

@juicemia 
- Are you using go modules? go.mod?
- Did you recompile all the  Go tools after moving to Go 1.11? Run `Go: Install/Update Tools` and select atleast the top 11 tools and then press enter or the ok button to have them updated
- Issues with completions of symbols from imported packages would be a `gocode` problem. But completions of unimported packages themselves (after setting `go. autocompleteUnimportedPackages` is `gopkgs` problem

**Comment by ragurney** [comment] 2018-08-31 03:11
@ramya-rao-a yes, a particular package is there, e.g.: 
```
$ /Users/rygurney/go/bin/gopkgs -format "{{.Name}};{{.ImportPath}}" | grep service/codepipeline

codepipelineiface;github.com/aws/aws-sdk-go/service/codepipeline/codepipelineiface
codepipeline;github.com/aws/aws-sdk-go/service/codepipeline
```
however, prior to the upgrade the autocomplete would list package suggestions even with just `git` typed.

I have not set the `go.toolsGopath` setting. The only `go` settings I have specified are:
```
"go.formatTool": "gofmt",
"go.autocompleteUnimportedPackages": true
```
I also just tried switching back to Go v1.10.1 and reinstalling all tools and autocomplete did not start working again -- and previously I did not have `autocompleteUnimportedPackages` set and it was still working 🤔

**Comment by ramya-rao-a** [comment] 2018-08-31 19:26
At this point, I would suggest you try debugging the extension itself. Its pretty straightforward if you have node installed. Please checkout the instructions at [Building & Debugging the Extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)

The `goSuggest.ts` file is the one that powers the autocompletions.

Note: For completions of unimported packages there are 2 separate features
1. Type the partial package name, choose from completion list, add the package gets added to the import block. This is not enabled by default. You have to set the `go.autocompleteUnimportedPackages` setting
2. Type the entire package name (name not path), add a `.` in the end, The completion list will have symbols from the package. This feature is enabled by default

**Comment by ragurney** [comment] 2018-08-31 19:49
@ramya-rao-a will do. I'll try to dig into it this weekend when I have some more time. Thanks a lot for your suggestions so far!

**Comment by ramya-rao-a** [comment] 2018-08-31 20:13
@ragurney  lol... I just made the connection that you are the same person who sent the PR for the `_` identifiers. I feel like a fool giving you links on how to build and debug the extension in https://github.com/Microsoft/vscode-go/issues/1881#issuecomment-417766683 :)

**Comment by ragurney** [comment] 2018-08-31 20:33
@ramya-rao-a no worries, never hurts to have more places I can find the instructions :D

**Comment by ShoshinNikita** [comment] 2018-09-01 12:00
*Go version:* `go1.11 windows/amd64`
*OS:* `Windows 10`

I had the same problem, but I solved it with some magic)

Steps:
1. Delete `%GOPATH%/bin/gocode.exe` and `%GOPATH%/src/github.com/mdempsky/gocode`
1. Install `github.com/nsf/gocode` (run `go get -u github.com/nsf/gocode`)
1. Open VSCode. It should suggest to install `github.com/mdempsky/gocode`. Accept.
1. After installing autocompletion works, except import, but it is better, than nothing)

I'm not sure it can help, but decided to share my solution.

**Comment by Ilyes512** [comment] 2018-09-01 13:18
Steps I took on MacOS that made it work again using 1.11:

1. Make sure vscode is not running and open "Activity Monitor" and select the "Memory" tab. Search for "gocode", if one is running, select it and stop it.
2. Remove old bin: `$ rm $GOPATH/bin/gocode` and source `rm -rf $GOPATH/src/github.com/mdempsky/gocode`
3. Run `go get -u github.com/mdempsky/gocode`.
4. Open vscode and try and trigger an autocomplete. A popup should show and ask you if you want to install gocode (Accept).

I think step 3 might not be needed, but it was I did and not going to try it again to find out :)

**Comment by ramya-rao-a** [comment] 2018-09-01 17:07
@ShoshinNikita @Ilyes512 Thanks for sharing those steps. Are you also able to get completions for unimported packages?

@Ilyes512 Yes, step 3 is not required as it gets done in Step 4

**Comment by Ilyes512** [comment] 2018-09-01 18:06
@ramya-rao-a Yes, for core non-imported package like fmt. Not sure if you also mean non-core package (for those I don't get autocompletions until I import them).

**Comment by ramya-rao-a** [comment] 2018-09-01 18:09
@Ilyes512 Yes, I meant non-core packages. See the second half of https://github.com/Microsoft/vscode-go/issues/1881#issuecomment-417766683

**Comment by ShoshinNikita** [comment] 2018-09-01 18:40
@ramya-rao-a Yes, I am able to get autocompletion for unimported packages. For instance,
`net/http`:

![image](https://user-images.githubusercontent.com/30220965/44948916-843baf00-ae2f-11e8-8e88-5d120b46fccd.png)

And `github.com/gorilla/mux`:

![image](https://user-images.githubusercontent.com/30220965/44948897-1d1dfa80-ae2f-11e8-822d-80d95c0ed773.png)

Nevertheless, I can't get suggestions for import even standart packages (like `fmt`, `log` and etc.)

**Comment by Ilyes512** [comment] 2018-09-01 19:03
Without importing any of the packages in a new file:

I do get autocompletions for Mux, but I don't seem to get autocompletion for log nor (net/)http, but I do get autocompletion for fmt? Okey strange...

**Comment by ramya-rao-a** [comment] 2018-09-02 09:26
@ShoshinNikita @Ilyes512 To get completions for the packages themselves, you need to set `go.autocompleteUnimportedPackages` to `true`.

**Comment by ShoshinNikita** [comment] 2018-09-03 11:51
@ramya-rao-a I am afraid `go.autocompleteUnimportedPackages: true` didn't help.

**Comment by ragurney** [comment] 2018-09-04 16:27
Digging into the code a little bit: 

https://github.com/Microsoft/vscode-go/blob/c8ed6b122714e9bba6800602258bbe7ded3545c0/src/goSuggest.ts#L103

always returns false, because `!inString` is always true when typing `"github.com/..."` in an import statement. I'm pretty confused, because from what I remember the the package autocomplete functionality worked before by typing the package prefix (e.g. `"github.com..."`) or a part of the package path and it would list packages that matched, kind of like a fuzzy search. That's how I was testing this, which is why I wasn't getting any results. Now, however, it seems to be working when I type the _name_ of the package _not_ in double quotes:

<img width="599" alt="screen shot 2018-09-04 at 9 01 14 am" src="https://user-images.githubusercontent.com/15261525/45043101-22429b80-b021-11e8-9a66-2b6570e2bcd0.png"> 

which I'm guessing is the expected behavior of this extension <img width="30" alt="palm to face" src="https://emojis.slackmojis.com/emojis/images/1450319441/51/facepalm.png?1450319441">

Maybe I was unknowingly using some other package autocomplete functionality provided by another extension? Regardless, I think this issue can now be closed if @ramya-rao-a can confirm this is how it's supposed to work.

**Comment by randallmlough** [comment] 2018-09-06 00:15
+1 for this issue. All I've changed is upgrading to Go 1.11 and VS no longer auto imports or shows suggestions. I followed [@Ilyes512](https://github.com/Microsoft/vscode-go/issues/1881#issuecomment-417859156) suggestion, however that did work for me. Also @ramya-rao-a I confirmed that I have autocomplete set to true.

**Comment by ragurney** [comment] 2018-09-06 04:09
@randallmlough can you try that command with quotes around the argument? e.g. `"{{.Name}};{{.ImportPath}}"`?

**Comment by randallmlough** [comment] 2018-09-06 18:02
@ragurney - doing the above in the VS and terminal shell (using zsh) I got "gopkgs command not found" which I thought was interesting since everything before worked. So I looked up the package and did the std `go get https://github.com/uudashr/gopkgs`, restarted everything and still nothing worked. I then verified that VS has access to the right go env variables and can run standard GO commands (I typically dont work out of the VS shell) – it can. So I then manually executed the package (`$ sudo $GOPATH/bin/gopkgs -format "{{.Name}};{{.ImportPath}}"` from VS. Once I did this it finally listed all my packages, but still nothing would auto import or autocomplete. I restarted VS and was again prompted with the message "Ensure gopkgs -format..." I'm at a loss.

**Comment by ramya-rao-a** [comment] 2018-09-10 01:33
🤦‍♀️ 

@ragurney All this time I assumed that you were referring to the auto-completion of unimported packages while writing actual code and not in the import block.

Sorry for that

Yes, auto-completion of unimported packages in the import block was a feature that worked when we were using `nsf/gocode`

But, we have since moved on to use `mdempsky/gocode` which is a fork of `nsf/gocode` as the latter doesnt work well in go 1.10 and and doesnt work at all in go 1.11

I have logged an upstream issue for this back in July. See https://github.com/mdempsky/gocode/issues/38

Please subscribe to the upstream issue

**Closed by ramya-rao-a** 2018-09-10 01:33 UTC
Labels: needs more info

**Comment by ramya-rao-a** [comment] 2018-09-10 02:58
Also see #1870

**Comment by ragurney** [comment] 2018-09-10 03:46
@ramya-rao-a no worries it was completely my fault. I should have been more clear. Thanks for the information, and sorry for wasting your time on this issue 😅
