### ISSUE TITLE
goimports is not used as the default format tool in Go module-enabled environment

### ISSUE THREAD

**Issue by nezorflame** [microsoft/vscode-go#2416] opened 2019-04-05 09:24 UTC
This issue is created due to the discussion at https://github.com/Microsoft/vscode-go/issues/2410#issuecomment-479895673

It seems like the `goreturns` is still being preferred instead of `goimports` for me in spite of change from #2309.
Removing `"go.formatTool": "goimports"` instantly makes the editor ask to install `goreturns`. This doesn't go away after the IDE restart or after I open a new project.

My setup:
- macOS `10.14.4`
- Go `1.12.1`
- VSCode `1.33.0` (same happens in `1.32.3`)
- vscode-go `0.9.3-beta.7`
- `GO111MODULE=on` is globally set in my ENV in `.zprofile`, so modules are enabled

Warning:

![warning](https://user-images.githubusercontent.com/3906766/55617861-ba625800-579d-11e9-84c6-ce1efe664662.png)

**Comment by nezorflame** [comment] 2019-04-06 16:29
Also, when you open a Go file, the editor asks for the default formatter, but the options are non-descriptive:
![1](https://user-images.githubusercontent.com/3906766/55672310-48c00200-58a2-11e9-8449-299f46ee9f36.png)
![2](https://user-images.githubusercontent.com/3906766/55672315-51b0d380-58a2-11e9-995d-6e9f65effac3.png)

**Comment by nezorflame** [comment] 2019-04-10 12:46
@ramya-rao-a any info I'm missing which could help?

**Comment by ramya-rao-a** [comment] 2019-04-12 00:07
@nezorflame Apologies for the delay

> Removing "go.formatTool": "goimports" instantly makes the editor ask to install goreturns. This doesn't go away after the IDE restart or after I open a new project.

When you remove the `"go.formatTool": "goimports"`, you are telling the extension that you don't want to use `goimports` for formatting. Since the default is `goreturns` which the extension can't find on your machine, you get the prompt. This is the expected behaviour.

From this point, if I reload the VS Code window, then I get the prompt on using the `gopls` language server for better performance. If I don't agree to update, the extension adds the setting "go.formatTool": "goimports" back.

Below are the cases where this may not happen and instead one would get prompted about goreturns not being available
- Not using Go modules
- Using language server, but not the formatting feature from the language feature
- Said "No" to the update to use gopls for modules

Did you land in any of the above cases?

**Comment by ramya-rao-a** [comment] 2019-04-12 00:33
Regarding the prompt on multiple formatters, can you share what your Go related settings were when you got that prompt?

Based on your screenshots it looks like 2 formatting providers were registered by the Go extension. I'd like to know the settings that lead to that

**Comment by nezorflame** [comment] 2019-04-12 15:40
Thanks for clearing this out.

> Did you land in any of the above cases?

Indeed, case 2 as in

> Using language server, but not the formatting feature from the language feature

As for the prompt:

```json
"go.autocompleteUnimportedPackages": true,
"go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
"go.docsTool": "godoc",
"go.formatTool": "goimports",
"go.formatFlags": [
    "--local=github.com/nezorflame"
],
"go.lintTool": "golangci-lint",
"go.lintFlags": [
    "--config=/home/nezorflame/.config/.golangci.yml"
],
"go.buildOnSave": "off",
"go.vetOnSave": "off",
"go.lintOnSave": "off",
"go.coverageDecorator": {
    "type": "gutter",
},
"go.coverageOptions": "showUncoveredCodeOnly",
"go.coverOnTestPackage": true,
"go.coverOnSingleTest": false,
"go.testFlags": [
    "-v",
    "-cover"
],
"go.addTags": {
    "tags": "json",
    "promptForTags": false,
    "transform": "snakecase"
},
"go.enableCodeLens": {
    "references": false,
    "runtest": true
},
"go.useLanguageServer": true,
"go.languageServerExperimentalFeatures": {
    "autoComplete": true,
    "diagnostics": true,
    "documentSymbols": true,
    "findReferences": true,
    "format": false,
    "goToDefinition": true,
    "goToTypeDefinition": true,
    "hover": true,
    "rename": true,
    "signatureHelp": true,
    "workspaceSymbols": true,
},
"[go]": {
    "editor.snippetSuggestions": "top",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
}
```

Setting the `"format"` to `true` doesn't show me any messages (I assume since `gopls` is automatically used as the default formatter)

**Comment by ramya-rao-a** [comment] 2019-04-15 06:00
I've pushed a fix so that `goimports` is again chosen as the tool to use in the below cases
- Using language server, but not the formatting feature from the language feature
- Said "No" to the update to use gopls for modules

Setting "format" to `false` in `go.languageServerExperimentalFeatures` tells the extension to register the old formatting provider. But this doesn't tell the language server **not** to register its formatting provider. I believe this is the case where we end up with 2 formatters being registered and thus the prompt.

**Comment by ramya-rao-a** [comment] 2019-04-15 06:12
Logged https://github.com/Microsoft/vscode/issues/72315 to track the second issue

**Comment by ramya-rao-a** [comment] 2019-06-29 03:52
#2446 is tracking the issue of multiple formatters being registered.
Closing this issue as `goimports` is getting chosen as the formatting tool when using Modules

**Closed by ramya-rao-a** 2019-06-29 03:52 UTC
