### ISSUE TITLE
Saving 'main.go': Getting code actions from ''Go', 'Go'' (configure).

### ISSUE THREAD

**Issue by iiinsomnia** [microsoft/vscode-go#3170] opened 2020-04-12 16:03 UTC
![image](https://user-images.githubusercontent.com/6582246/79073582-05506d00-7d1a-11ea-9f5b-dc4161da321c.png)

![image](https://user-images.githubusercontent.com/6582246/79073617-27e28600-7d1a-11ea-8c17-9e1b59fbd1b9.png)

**Comment by iiinsomnia** [comment] 2020-04-12 16:05
![image](https://user-images.githubusercontent.com/6582246/79073670-7001a880-7d1a-11ea-832b-6e20ef4c4aba.png)

**Comment by iiinsomnia** [comment] 2020-04-12 16:14
![image](https://user-images.githubusercontent.com/6582246/79073899-b99ec300-7d1b-11ea-9e3c-39d68d5c95b4.png)

**Comment by iiinsomnia** [comment] 2020-04-13 06:41
![image](https://user-images.githubusercontent.com/6582246/79098546-d2978a80-7d94-11ea-815c-0be814459fb1.png)

**Comment by stamblerre** [comment] 2020-04-13 15:20
@iiinsomnia: What other extensions do you have enabled? Spell Right and Go Group Imports have both been known to cause this issue, so please try disabling them if you have them installed.

Otherwise, can you please share your `gopls` logs? They can be found by following the steps [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).

**Comment by stamblerre** [comment] 2020-04-15 16:32
I'm trying to consolidate discussion about this issue into one bug, so I'm going to close this in favor of https://github.com/microsoft/vscode-go/issues/3179.

**Comment by stamblerre** [comment] 2020-04-15 16:32
Duplicate of https://github.com/microsoft/vscode-go/issues/3179

**Closed by stamblerre** 2020-04-15 16:32 UTC
Labels: needs more info, upstream-gopls
