### ISSUE TITLE
Adding imports from vendor/

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#376] opened 2016-07-07 21:18 UTC
If I have a dependency not in `$GOPATH/src/[import-path]` but under my `$GOPATH/src/myapp/vendor/[import-path]` and if I use this `Go: Add Import` command, it adds it to my code as:

    import "mycode/vendor/[importpath]"

whereas `import "[importpath"]` is just sufficient.

**Comment by ramya-rao-a** [comment] 2016-09-12 21:06
Duplicate of #316

**Closed by ramya-rao-a** 2016-09-12 21:06 UTC
