### ISSUE TITLE
gopls panic parse url

### ISSUE THREAD

**Issue by nicebug** [microsoft/vscode-go#2570] opened 2019-06-11 09:48 UTC
my vscode-go use gopls, but when show autocomplete gopls panic. my vscode-go version:0.10.2

my setting.json:
```   
 "go.autocompleteUnimportedPackages": true,
    // "go.docsTool": "gogetdoc",
    "go.testFlags": [
        "-v"
    ],
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "diagnostics": true, // for build and vet errors as you type
        "findReferences": true   // for finding in-package references
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
        "editor.codeActionsOnSaveTimeout": 3000
    },
    "gopls": {
        "usePlaceholders": true // add parameter placeholders when completing a function
    },
    "files.eol": "\n", // formatting only supports LF line endings```

and the gopls output show:
```
Go info
-------
go version go1.12.4 windows/amd64

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\damonhu\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\gopath
set GOPROXY=
set GORACE=
set GOROOT=D:\go
set GOTMPDIR=
set GOTOOLDIR=D:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\damonhu\AppData\Local\Temp\go-build711939154=/tmp/go-build -gno-record-gcc-switches

panic: parse : empty url

goroutine 21 [running]:
golang.org/x/tools/internal/span.URI.Filename(0x0, 0x0, 0xc001675700, 0x1f)
	D:/gopath/src/golang.org/x/tools/internal/span/uri.go:27 +0xd1
golang.org/x/tools/internal/span.CompareURI(0xc000361ef0, 0x27, 0x0, 0x0, 0x0)
	D:/gopath/src/golang.org/x/tools/internal/span/uri.go:64 +0x89
golang.org/x/tools/internal/lsp/protocol.(*ColumnMapper).Range(0xc0022fd800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1e00f0, ...)
	D:/gopath/src/golang.org/x/tools/internal/lsp/protocol/span.go:49 +0xb1
golang.org/x/tools/internal/lsp.toProtocolDocumentSymbols(0xc0022fd800, 0xc001964180, 0x1, 0x1, 0xc001964180, 0x1, 0x1)
	D:/gopath/src/golang.org/x/tools/internal/lsp/symbols.go:35 +0x267
golang.org/x/tools/internal/lsp.(*Server).documentSymbol(0xc000182980, 0xb550c0, 0xc0022fd7a0, 0xc00067d510, 0xc00067d510, 0x0, 0x0, 0x0, 0xc002260460)
	D:/gopath/src/golang.org/x/tools/internal/lsp/symbols.go:23 +0x16b
golang.org/x/tools/internal/lsp.(*Server).DocumentSymbol(0xc000182980, 0xb550c0, 0xc0022fd7a0, 0xc00067d510, 0xc00067d510, 0x0, 0x0, 0x0, 0x0)
	D:/gopath/src/golang.org/x/tools/internal/lsp/server.go:199 +0x54
golang.org/x/tools/internal/lsp/protocol.serverHandler.func1(0xb550c0, 0xc0022fd7a0, 0xc000200000, 0xc000330b00)
	D:/gopath/src/golang.org/x/tools/internal/lsp/protocol/tsserver.go:335 +0x53c3
golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1(0xc000173620, 0xc000200000)
	D:/gopath/src/golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:288 +0x190
created by golang.org/x/tools/internal/jsonrpc2.(*Conn).Run
	D:/gopath/src/golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:278 +0xc1
```

Steps to Reproduce:

1.useLanguageServer, then type some code,eg: fmt.  then,gopls panic. vscode show error: The gopls server crashed 5 times in the last 3 minutes. The server will not be restarted. 
2. easy to reproduce on my pc and mac

**Comment by linguohua** [comment] 2019-06-13 13:42
@nicebug upgrade to the latest gopls, use the command: go get -u -v golang.org/x/golang.org/x/tools/cmd/gopls, it has fixed this panic:https://github.com/golang/tools/commit/25a4f137592ff7de30eb0758889d917a1c6979bf

**Comment by ramya-rao-a** [comment] 2019-06-14 04:32
Thanks @linguohua 
@nicebug Can you please update your version of `gopls` by either using the command `Go: Install/Update Tools` or by running the command `go get -u -v golang.org/x/golang.org/x/tools/cmd/gopls` and then try again?

cc @stamblerre

**Comment by nicebug** [comment] 2019-06-17 03:20
@linguohua @ramya-rao-a 
i update gopls to v0.1.0, vscode in mac  works, but vscode on win pc still has a panic:
```
goroutine 39 [running]:
go/token.(*File).Pos(...)
	D:/go/src/go/token/position.go:267
golang.org/x/tools/internal/span.Span.Range(0xc00037c0f0, 0x27, 0x30, 0x6, 0x428, 0x30, 0x6, 0x428, 0xc000f79260, 0x0, ...)
	D:/gopath/src/golang.org/x/tools/internal/span/token.go:104 +0x373
golang.org/x/tools/internal/lsp.organizeImports(0xb5d4e0, 0xc0010b4090, 0xb66620, 0xc0001c0d00, 0xc00037c0f0, 0x27, 0x30, 0x6, 0x428, 0x30, ...)
	D:/gopath/src/golang.org/x/tools/internal/lsp/code_action.go:70 +0x141
golang.org/x/tools/internal/lsp.(*Server).codeAction(0xc0001a0e00, 0xb5d4e0, 0xc0010b4090, 0xc0004bd7a0, 0xc0004bd7a0, 0x0, 0x0, 0x0, 0xc00183a000)
	D:/gopath/src/golang.org/x/tools/internal/lsp/code_action.go:32 +0x1f8
golang.org/x/tools/internal/lsp.(*Server).CodeAction(0xc0001a0e00, 0xb5d4e0, 0xc0010b4090, 0xc0004bd7a0, 0xc0004bd7a0, 0x0, 0x0, 0x0, 0x0)
	D:/gopath/src/golang.org/x/tools/internal/lsp/server.go:203 +0x54
golang.org/x/tools/internal/lsp/protocol.serverHandler.func1(0xb5d4e0, 0xc0010b4090, 0xc000206000, 0xc00031f4c0)
	D:/gopath/src/golang.org/x/tools/internal/lsp/protocol/tsserver.go:355 +0x2e7e
golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1(0xc000199c80, 0xc000206000)
	D:/gopath/src/golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:288 +0x190
created by golang.org/x/tools/internal/jsonrpc2.(*Conn).Run
	D:/gopath/src/golang.org/x/tools/internal/jsonrpc2/jsonrpc2.go:278 +0xc1
```

**Comment by ramya-rao-a** [comment] 2019-06-17 16:51
Thanks for the follow up @nicebug 

@stamblerre, @ianthehat The [fix](https://github.com/golang/tools/commit/25a4f137592ff7de30eb0758889d917a1c6979bf) seemed to be around paths and most likely needs Windows specific treatment

**Comment by stamblerre** [comment] 2019-06-17 17:03
Looks like we have an upstream issue filed here: https://github.com/golang/go/issues/32639. @nicebug: Does this issue reproduce on all files?

**Comment by nicebug** [comment] 2019-06-24 10:45
@stamblerre  yes, reproduce on windows

**Comment by stamblerre** [comment] 2019-06-27 16:41
@nicebug: You can follow along on https://github.com/golang/go/issues/32639.

**Comment by ramya-rao-a** [comment] 2019-06-29 01:41
Closing this issue in favor of the upstream issue https://github.com/golang/go/issues/32639

**Closed by ramya-rao-a** 2019-06-29 01:41 UTC
Labels: needs more info, upstream-gopls
