### ISSUE TITLE
Debug not stopping at breakpoints

### ISSUE THREAD

**Issue by IzakMarais** [Microsoft/vscode-go#125] opened 2015-11-30 11:37 UTC
Using 0.6.15 with a small test program I cannot get the debugger to stop at breakpoints. When using dlv from the console it works.

![vs-code-debug](https://cloud.githubusercontent.com/assets/8266640/11470541/8343524e-9756-11e5-8d94-f80e4180972e.png)

**Comment by lukehoban** [comment] 2015-12-01 14:54
I've tried reproducing this on several machines (including a Linux box since it seems that's what you are working on), but can't get this to happen.

Note that you should be seeing an additional diagnostic line in the debug console `debugger.go:174: created breakpoint...`.  

Could you share:
1. Your launch.json
2. Your folder layout for this code
3. Whether you have the latest `dlv`
4. Anything else you think might be notable about your environment?

And in case you want to diagnose the issue yourself - could you follow the instructions [here](https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/Readme.md) to debug the debugger.  It's a bit of work to set up, but once you do you can step through the code in https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts to see where things are failing.  In particular the code around line 257 is where breakpoints should be set up.

**Comment by lukehoban** [comment] 2015-12-02 00:45
I looked into this a bit more, and I think there is indeed a race condition here, and that for some reason on Linux it is much more common for that race to cause the `Continue` to happen before the `SetBreakpoints` meaning that the process runs to completion before the debugger asks to set the breakpoints.  

We should be able to fix this.

**Comment by IzakMarais** [comment] 2015-12-02 05:34
I have never seen the `created breakpoint` diagnostic line.

Launch.json:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch main.go",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"program": ".",
			"env": {},
			"args": []
		}
	]
}
```

Folder layout is `mainDebug.go` in the GOPATH root.

I built `dlv` from source 2 days ago from a fresh git clone, so I assume it is the latest. Output of `dlv version` is `Delve version: 0.10.0-alpha`.

This is running on Fedora 20 with xfce in a virtual box VM on a Windows host. (Looking forward to Windows support for the debugger).

**Comment by ulrichSchreiner** [comment] 2015-12-07 08:53
hi,
i have this race condition too. When debugging i have to hit F5 multiple times and one of them then hits the breakpoints.

I'm using the latest version of `vscode` and `vscode-go` in a dockerized environment.

</usc>

**Comment by lukehoban** [comment] 2015-12-10 22:55
With https://github.com/Microsoft/vscode-go/commit/b4dbda4a6b3893c4e3d4d45012570e66534e385e, I believe this should be fixed.  

Version `0.6.19` has this change, so you can update and verify whether it is fixed for you.

**Comment by IzakMarais** [comment] 2015-12-11 07:14
Sorry, still not fixed. 

(I destroyed the VM this was in, so recreated everything with the latest versions, including vscode-go `0.6.19`)

Console output very similar to before, e.g. `coninuing`, still no `creating breakpoint`. I can still break when using `dlv` from the command line. 

`Gorename` is also not working; maybe this is in some way related? Maybe some GOPATH related issue? GOPATH is set in the terminal I used to lauch vscode from. The other tools (e.g. _Peek definition_) *do* work. 
<img width="815" alt="screenshot" src="https://cloud.githubusercontent.com/assets/8266640/11737966/216183ae-9fe7-11e5-88a8-4414b40b6b6f.png">

**Comment by ulrichSchreiner** [comment] 2015-12-11 08:26
hi,
on my side: it is better no, but now it only starts when there is **any** breakpoint set :-). my launch-config looks like:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch main.go",
			"type": "go",
			"request": "launch",
			"mode": "exec",
			"program": "bin/test",
			"env": {},
			"args": []
		}
	]
}
```
and if i run this, nothing happens until i set a breakpoint anywhere in the code. then the program starts to run and stops at the breakpoint. version of gocode is
```
$ git rev-parse HEAD
598b92cb9543afb37a38c81dd9cf2068aca0c5f7
```

**Comment by lukehoban** [comment] 2015-12-11 23:55
Sorry about that.

I pushed up a change to fix the regression that @ulrichSchreiner mentions.  

I also looked deeper into what's going on with Delve on Linux, and I'm pretty sure there is some subtle bug in Delve on Linux that is the root cause of this.  

Sometimes, and possibly more often if it's soon after launching the debugger, an RPC call to Delve's `CreateBreakpoint` API is returning an array with `null`s in it.  I haven't been able to pin down a concrete repro case outside of vscode yet - I need to investigate this more on the Delve side.

Reopening for now, as this is definitely not fixed.

**Comment by lukehoban** [comment] 2015-12-18 22:12
I believe this should be fixed (or at least largely mitigated) by https://github.com/Microsoft/vscode-go/commit/69f781534b766f871a6246eaa61c879176696b56.  On my Linux machine I am no longer seeing the failure to hit breakpoints anymore with that change.

I've also added support for `stopOnEntry` with https://github.com/Microsoft/vscode-go/commit/16a4f4f306f201e5dbb809c655e44b8a77af7de1, so if all else fails you can turn that on to ensure that the debugger will pause and give you a chance to set breakpoints before running any code.

**Closed by lukehoban** 2015-12-18 22:12 UTC

**Comment by zanven42** [comment] 2016-01-18 13:52
@lukehoban i am running into this same issue on windows. i am running delve using your delve fork under branch 'windows'. i am able to hit breakpoints in delve but not in vscode. 

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch main.go",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"program": "${workspaceRoot}/main.go",
			"env": {},
			"args": [],
            "stopOnEntry": true
		}
	]
}
```

console output ( i have tried to place breakpoints before hitting continue and already having breakpoints available )
```
2016/01/19 00:46:47 debugger.go:55: launching process with args: [./debug]
2016/01/19 00:46:47 server.go:301: method Run has wrong number of ins: 1
2016/01/19 00:46:47 server.go:301: method Stop has wrong number of ins: 2
2016/01/19 00:49:44 debugger.go:239: continuing
```
