### ISSUE TITLE
Could not import "..." with go modules

### ISSUE THREAD

**Issue by affanshahid** [Microsoft/vscode-go#1953] opened 2018-10-01 08:38 UTC
I created a go module and installed some deps with:

```sh
go mod init github.com/affanshahid/hello-world
go get "github.com/fatih/color"
```

Wrote the following in `main.go`:
```go
package main

import "github.com/fatih/color"

func main() {
	color.Cyan("Hello world")
}

```

When I run `go build && ./hello-world`, it runs fine. However when I go into vscode, I get the following:
<img width="669" alt="screen shot 2018-10-01 at 1 37 42 pm" src="https://user-images.githubusercontent.com/17955210/46278306-370e4280-c57f-11e8-8030-1645b2ec0e1a.png">

I'm not sure what I'm doing wrong

**Comment by tamasf97** [comment] 2018-10-01 23:41
Go modules are still pretty new and aren't supported by a lot of tools. Make sure you use the latest beta of this extension(https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension), and disable live errors, as they aren't supported yet.(related: https://github.com/Microsoft/vscode-go/issues/1950).

**Comment by ramya-rao-a** [comment] 2018-10-02 17:21
@tamasf97 is right.

@affanshahid That definitely looks like the error from the live errors feature. Like @tamasf97 said, can you disable the live errors feature and try again?

Also, keep an eye on our wiki [Go modules in VS Code](https://github.com/Microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code) for current status on Go modules support.

**Comment by ramya-rao-a** [comment] 2018-10-09 15:52
Closing as duplicate of #1950

**Closed by ramya-rao-a** 2018-10-09 15:52 UTC
Labels: go-modules
