### ISSUE TITLE
With delve remote-debugging on vscode unable to print maps/structures

### ISSUE THREAD

**Issue by venkatsvpr** [microsoft/vscode-go#3035] opened 2020-02-09 22:10 UTC
What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
        - go version go1.11.4 linux/amd64
        - delve debugger version - 1.3.2

- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.38.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- linux/amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` prefixes.

settings.json
`{
    "go.delveConfig": {
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 100,
            "maxStringLen": 100000,
            "maxArrayValues": 100000,
            "maxStructFields": -1
        },
        "apiVersion": 2,
        "showGlobalVariables": true
    }
}
`

launch.json
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Connect to remote server",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "remotePath": "/hello",
            "port": 2345,
            "host": "localhost",
            "dlvLoadConfig": {
                "maxStringLen": 23232323
            }
        }
    ]
}
`

### Describe the bug
Could not access the contents of a map, structures. Only the type is getting printed when trying to remote debug on vscode with deleve.

![image](https://user-images.githubusercontent.com/4478054/74110698-9866fe00-4b43-11ea-8798-549daf9e9618.png)

In the above example, I was expecting contents of key, value and the testMap to be printed.
 Able to access the values when deleve is run directly. Please refer to the next screenshot.

![image](https://user-images.githubusercontent.com/4478054/74110823-80dc4500-4b44-11ea-8878-378395b58665.png)

### Steps to reproduce the behavior:
1.  Run the below hello.go in deleve using the command
dlv debug --api-version=2 --headless --listen=:2345 ./hello

`package main

import (
	"fmt"
)

type keyStruct struct {
	key1 string
	key2 string
}

type valueStruct struct {
	value1 string
	value2 string
}

func main() {
	testMap := make(map[keyStruct]valueStruct)
	key := keyStruct{key1: "k1", key2: "k2"}
	value := valueStruct{value1: "v1", value2: "v2"}
	testMap[key] = value
	fmt.Println(testMap)
}
`
2. Add a breakpoint on main and StepOver and try printing the values on vscode.
3. All we could print are the types and not the value.

### Screenshots or recordings

![image](https://user-images.githubusercontent.com/4478054/74110955-9c941b00-4b45-11ea-89cc-353979cf486c.png)

**Comment by stamblerre** [comment] 2020-03-27 05:20
Duplicate of https://github.com/microsoft/vscode-go/issues/3032

**Closed by stamblerre** 2020-03-27 05:20 UTC
Labels: debug
