### ISSUE TITLE
gorename: vscode-go incorrectly reports identifier offsets based on CRLF line endings even when the source file is using LF line endings

### ISSUE THREAD

**Issue by rotemdan** [Microsoft/vscode-go#165] opened 2015-12-18 08:25 UTC
I haven't really managed to create a reproducible test case [edit: instructions to reproduce in a later comment] but this has happened several times so far. It seems that gorename would sometimes permanently lose sync with the identifier positioning that is reported by vs-code and attempting to rename any identifier would either return a  "no identifier at this position" error or apply the rename operation to the wrong identifier (usually one that is positioned several characters away).

Restarting vs-code or re-opening the file(s) or directories would usually correct the problem. Explicitly saving the file does not seem to help (I also have auto-save turned on).

I have several speculations on why this could be happening:
* Something to do with having multiple files referring to the same identifier? (when the problem appears, the error would usually happen with any identifier, including local ones, though)
* CR/LF line endings may somehow confuse gorename. I will try to make sure all my files have LF line endings and see if it repeats..? (however the problem seems to get resolved after vs-code is restarted, without actually modifying any of the files so this doesn't seem probable)
* One or some of the files in the project directory aren't correctly saved? (I will try to explicitly save all the files when this happens again?)
* A bug in gorename?

Anyone else experiencing this? is this a known problem?

**Comment by rotemdan** [comment] 2015-12-18 09:07
This simple test case seems to reproduce the problem using a single file (a.go):
```go
package main

import (
)

func main(){
	a := 34
	a++
}

```
(Note the formatting and line breaks at the end of the file)

Trying to rename 'a' to 'b' returned a 'no identifier at this position' error. Repeating this several times sometimes fixes the problem. After trying to re-paste the code again rename sometimes works and sometimes doesn't. There doesn't seem to a pattern here but I will continue experimenting. In any case, this shows that multiple files are not needed to reproduce the problem. Line endings are set to LF as well so this doesn't seem to be the issue.

**Comment by rotemdan** [comment] 2015-12-18 11:20
I opened the same file in Notepad++ and enabled `View -> Show Symbol -> Line Endings`. I converted the file from LF to CRLF back and forth several times. It turns out the problem was that even when the file had LF (unix type) line endings, vscode-go still reported the offset for the target identifier based on CRLF line endings to go-rename, this explains the error given by gorename.

With the previous example, having line endings of CRLF the `a` identifier would have an offset of 45 in the file, and the rename would work correctly. With LF, or having at least one line having an ending of LF, the offset of the identifier would still be incorrectly reported as 45, thus the error:
```
Cannot rename due to errors: Error: Command failed: C:\Rotem\Go\bin\gorename.exe -offset C:\Rotem\Go\src\GoRenameTest\a.go:#45 -to b
```

**Comment by lukehoban** [comment] 2015-12-18 20:49
Hmm - yeah - it looks like the VS Code APIs are not reporting back the correct line ending information in all cases.  

Let me see if I can get a concrete example of this to open an issue against https://github.com/Microsoft/vscode.

Thanks for tracking this down so far.

**Comment by rotemdan** [comment] 2015-12-22 13:29
@lukehoban 

This series of steps seems to reliably reproduce the issue:

1. Open an empty folder, add a new file 'a.go' with the content:
```go
package main

func main() {
	a := 1
	a++
}
```
2. Try to rename 'a' several times, it should work.
3. Change the line endings through the UI to a different setting than the one that it is currently set.
4. Try to rename 'a' several times, it should fail (with a 'no identifier at this position' error).
5. Change the line endings back to the original setting.
6. Try to rename 'a' several times, it should work.
7. Change the line endings to a different setting and verify renaming fails.
8. Reopen the file and renaming should work again.

(Interestingly the problem occurs in a similar way even if the line endings are changed through an external program like Notepad++)

----

I tried to 'dig' through the code a bit. If this is actually a problem with vscode itself it may be that the result of the call to `document.offsetAt` at [this line](https://github.com/Microsoft/vscode-go/blob/c14dfb2a906dd1f245dde80808d1c0ba9ccc1f2d/src/util.ts#L5) is the one providing the incorrect result? (I'm assuming that `byteOffsetAt` function is not related to the problem).

If that is really the case, and [this](https://github.com/Microsoft/vscode/blob/70ee90dcc1c9a3094ae2ba94f8d0c210a72e499e/src/vs/workbench/api/common/extHostDocuments.ts#L309) is the implementation, then I speculate that perhaps when the user changes the line endings through the editor (which seems to start [here](https://github.com/Microsoft/vscode/blob/9f6b37fbcf18bc924bfb406ef8114705a8db8778/src/vs/workbench/browser/parts/editor/editorStatus.ts#L537) and then [here](https://github.com/Microsoft/vscode/blob/e573984ee25a22764209ab574c230811ab2d4f4d/src/vs/editor/common/model/textModel.ts#L587)) the `_lineStarts` structure may not reset correctly and the line start offsets are not rebuilt when [`_ensureLineStarts()`](https://github.com/Microsoft/vscode/blob/70ee90dcc1c9a3094ae2ba94f8d0c210a72e499e/src/vs/workbench/api/common/extHostDocuments.ts#L330) is called..

I understand this is probably more appropriate to `vscode` itself, but I still can't be 100% sure this isn't a problem with the extension. I tried to clone the vscode repository and debug/modify this to see if this is really the case but at some point gave up as the build/debugging/run from dev build process seemed a bit too complex.. Maybe I'll try again in some other time..

**Comment by rotemdan** [comment] 2015-12-22 14:41
@lukehoban 

I managed to build and run vscode from the master build. I tried to force the `_lineStarts` structure to be rebuilt in every call to `offsetAt` (by commenting out line [330](https://github.com/Microsoft/vscode/blob/70ee90dcc1c9a3094ae2ba94f8d0c210a72e499e/src/vs/workbench/api/common/extHostDocuments.ts#L330) and [337](https://github.com/Microsoft/vscode/blob/70ee90dcc1c9a3094ae2ba94f8d0c210a72e499e/src/vs/workbench/api/common/extHostDocuments.ts#L337)) based on my previous speculations, but it didn't seem to have any effect. I wasn't even able to hit the 'offsetAt' method at all with the debugger in any case.

Anyway, I discovered another component to the problem. It seems like the rename utility itself keeps changing the line endings back to LF when the rename succeeds and the endings are initially set to CRLF (including when the file is initially loaded this ). So the problem may occur more frequently, I mean, even when the line endings are not modified manually.

**Comment by rotemdan** [comment] 2015-12-22 15:56
@lukehoban 

I haven't managed to get full debugging working yet, for some reason, but using `console.log` printouts for the plugin host and can verify with high certainty that the host api returns invalid offsets and the [`_eol` property](https://github.com/Microsoft/vscode/blob/70ee90dcc1c9a3094ae2ba94f8d0c210a72e499e/src/vs/workbench/api/common/extHostDocuments.ts#L185) in `BaseTextDocument` (within `extHostDocuments.ts`) is not updated _at all_ when the line endings are changed in the UI (and I guess from outside of it as well). This probably explains why forcing a refresh of line start offsets in [`_ensureLineStarts`](https://github.com/Microsoft/vscode/blob/70ee90dcc1c9a3094ae2ba94f8d0c210a72e499e/src/vs/workbench/api/common/extHostDocuments.ts#L329) had no effect.

It seems like this is a general problem and I'm quite surprised it hasn't come up yet since it may effect all extensions that use this API. I believe fixing this would require multiple code changes, a bit beyond what I can do myself and definitely seems like something important that should be forwarded to `vscode` developers. I'll open an issue there.

**Comment by lukehoban** [comment] 2015-12-24 04:02
@rotemdan Thanks so much for the investigation!  What you describe matches what I thought I was seeing when I looked at this initially.  Specifically - after changing the line endings in VS Code UI, the offsets reported back from `document.offsetAt` appeared to be incorrect.  

As far as I can tell, the issue is purely on the VS Code side, and I'm not sure there's anything we can do to work around it reliably.  So I'll close this for now and leave https://github.com/Microsoft/vscode/issues/1580 active to track the issue.  If you think there's something we could do to work around this though - feel free to reactivate with the suggestion.

**Closed by lukehoban** 2015-12-24 04:02 UTC

**Comment by brunomvsouza** [comment] 2016-03-08 01:17
Hi there!
I'm giving the Go plugin (latest) for VS Code (latest) a try but I'm not being able to rename code occurrences.

"Cannot rename due to errors: Error: Command failed /foo/go/bin/gorename -offset /Users/foo/go/src/github.com/foo/hello/hello.go:#79 -to helloNurse"
"rename: -offset \"/Users/foo/go/src/github.com/foo/hello/hello.go:#79\": no identifier at this position"

Do I have to do anything specific for it to work or it should just work?
Found a this issue which led me to (https://github.com/Microsoft/vscode/issues/1580) which is already merged, but I'm still not able to rename symbols.

Code: (tried to rename helloWorld to helloNurse)
```go 
package main

import (
    "fmt"
)

func main() {
    helloWorld()
}

func helloWorld() {
    fmt.Printf("hello, world\n")
}
```

**Comment by lukehoban** [comment] 2016-03-08 01:39
Interesting - I do see that failure when I have my cursor on the character immediately following the identifier.  But not when I have the cursor anywhere else before or in the identifier.  

Is that what you are seeing as well?

If that is the issue, we may want to work around the `gorename` limitation and adjust the point at which we invoke rename to the beginning of the preceding token.

**Comment by brunomvsouza** [comment] 2016-03-08 01:43
Hmm nice. That's exactly what I'm seeing! 
Thanks for looking into it. :bow:

**Comment by tnine** [comment] 2016-03-15 15:21
Hey guys.  I know this issue is closed, but I'm also experiencing this.  I'm running Vscode on OS X 10.11.3.  Is there a workaround I could document and submit?
