### ISSUE TITLE
GOPATH using symlink under linux prevents correct gorename

### ISSUE THREAD

**Issue by dbenque** [Microsoft/vscode-go#298] opened 2016-04-17 15:25 UTC
gorename does not work with the following settings:

GOPATH=/home/david/code/go

with /home/david/code is a symlink to /mnt/code

the gorename command will complain that the package is not found under /mnt/code/go/src/foo/main.go for example.

setting GOPATH to /mnt/code/go will make this work; but would it be possible to support correctly symlink used in GOPATH ?

Not sure how this affect other tools, but gorename may not be the only one impacted.

**Comment by ironcladlou** [comment] 2016-04-26 19:37
Haven't looked into this specific instance yet, but in general symlinks with GOPATH can be really problematic for tools.

If the problem is specific to `gorename`, an issue will need filed upstream.

**Comment by dbenque** [comment] 2016-05-20 20:51
@ironcladlou, it is not `gorename` only. For example the debugger `dlv` also completely mess up with symlink.
With the values of my previous example if I set a breakpoint in `main.go` at the root of my project, the breakpoint is associated to `/home/david/code/go/src/myproject/main.go` and the debugger just don't stop... but if I manage to place the breakpoint to `/mnt/code/go/src/myproject/amin.go` then it works.

**Comment by ironcladlou** [comment] 2016-05-21 15:48
That's too bad. My usual recommendation for these cases is to abandon symlinks and use something more transparent like bind mounts. More work to set up and maintain, but has none of the problems you'll encounter with symlinks.

**Comment by mattetti** [comment] 2017-01-16 03:28
While this is indeed a problem, I'm afraid this isn't a VSCode specific issue and therefore I'd suggest we close this issue @ramya-rao-a

**Comment by ramya-rao-a** [comment] 2017-01-16 20:19
@mattetti Agreed.

**Closed by ramya-rao-a** 2017-01-16 20:19 UTC
