### ISSUE TITLE
unfinished cc1 processes are not terminated on new build

### ISSUE THREAD

**Issue by andaag** [microsoft/vscode-go#2421] opened 2019-04-06 11:52 UTC
When I save a reasonably big application and auto run golint/go build it spawns up cc1 processes to do the work. If I save again it spawns up *new* processes, without terminating the old ones.

1. Load big project
2. Quickly save a few times after eachother
3. Observe N*N cc1 processes running in the background.

Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-16-generic
Go extension 0.9.2

Log will contain:
```
/home/neuron/src/gogui/examples/basic/qml>Finished running tool: /home/neuron/src/go/bin/golint

/home/neuron/src/gogui/examples/basic/qml>Finished running tool: /snap/bin/go vet ./...

/home/neuron/src/gogui/examples/basic/qml>Finished running tool: /snap/bin/go build -i -o /tmp/vscode-goxtldFS/go-code-check .
```
After finishing, if saving multiple times while go vet ./... command is running it'll keep spawning new processes.

**Comment by tapir** [comment] 2019-04-08 14:05
This is a Go bug I've been struggling a lot lately. Here is the bug report and my comment:
https://github.com/golang/go/issues/29452#issuecomment-480077537

Is there a way to temporarily disable the use of `go list` via vscode settings?

**Comment by lggomezml** [comment] 2019-04-15 13:01
@tapir there's not a way to disable go list that I'm aware of but I've been working on a feature to add timeouts to child processes which should alleviate this issue: https://github.com/Microsoft/vscode-go/pull/2372

If this happens constantly and makes vs code unusable for both of you maybe you can try using a build based on that branch. If you need any help ping me

**Comment by stamblerre** [comment] 2020-02-12 15:59
[`gopls`](https://github.com/golang/tools/blob/master/gopls/README.md), the Go language server, handles request cancellation and tries to minimize the number of calls to `go list`. You may want to try that out as an alternative.

Otherwise, I will defer to @ramya-rao-a on the correct response here. I imagine that disabling `go list` is not really a possibility because the extension needs the output of that command to operate.

**Comment by stamblerre** [comment] 2020-02-12 18:50
Since this issue has not had any activity for quite some time, I will close it in favor of a new umbrella issue for improving VS Code Go's handling of subprocesses: https://github.com/microsoft/vscode-go/issues/3044. It will be easier to track improvements with one issue, instead of many hard-to-find ones.

As an alternative, you can use the [language server](https://github.com/golang/tools/blob/master/gopls/doc/vscode.md), which handles cancellation.

**Comment by stamblerre** [comment] 2020-02-12 18:50
Duplicate of  #3044

**Closed by stamblerre** 2020-02-12 18:50 UTC
Labels: needs-decision
