### ISSUE TITLE
"text/template" & "html/template" support

### ISSUE THREAD

**Issue by gobijan** [microsoft/vscode-go#228] opened 2016-03-06 23:37 UTC
Vscode-go is a really nice IDE for working with Go. Great job!

I would be super happy if vscode would support "text/template" & "html/template" as an edit mode for template editing.
Is this feature planned?

Kind regards Bijan

**Comment by lukehoban** [comment] 2016-03-07 04:45
Good idea - not planned yet - but should be something we can add.

**Comment by GoBijan** [comment] 2016-07-08 09:58
Any status update on this? 
Here someone tried to implement it but failed: https://marketplace.visualstudio.com/items?itemName=casualjim.gotemplate

GoSublime for Sublime Text has this kind of template support:
https://github.com/DisposaBoy/GoSublime

Maybe you could get some inspiration from these on how to do it in your extension?

**Comment by nullbio** [comment] 2016-08-29 02:36
I'd love to see this feature.

**Comment by Depado** [comment] 2017-01-05 11:07
I'd love to see this feature too.

**Comment by ramya-rao-a** [comment] 2017-01-11 06:28
This feature request has gotten quite a few up votes. Can someone provide a gif or a video of what is the expected behavior? I can then look into what is needed to get this implemented.

**Comment by gertcuykens** [comment] 2017-01-12 17:29
![image](https://cloud.githubusercontent.com/assets/863731/21900197/4592b658-d8f3-11e6-9546-6b3f34dd7f04.png)

renamed to `.html`
![image](https://cloud.githubusercontent.com/assets/863731/21900219/57a99672-d8f3-11e6-8d47-68a79c283e78.png)

So in short use the vscode html engine and just add parameters like, hey html engine all that non html stuff like `{{...}}` don't worry about that, here are the syntax and autocomplete rules for it. 

You have to think the other way around. Extend your html api so the go plugin can just push in a chunk of html code and return the same output as shown in the screenshots + some extra syntax highlighting provided by the plugin as extra html parameter so the html engine can learn what all that non html stuff means.

**Comment by Depado** [comment] 2017-01-13 15:59
That's quite the same as the [Jinja support](https://marketplace.visualstudio.com/items?itemName=wholroyd.jinja) actually. That would be so cool 👍

**Comment by andreis** [comment] 2017-11-14 01:08
Working with [`xo`](https://github.com/xo/xo) and editing a lot of `.tpl.go` files, I'd absolutely love this feature!

**Comment by kmanley** [comment] 2018-01-21 15:00
Would be handy for [ego](https://github.com/benbjohnson/ego) templates too

**Comment by oneslash** [comment] 2018-11-28 11:41
I am taking this

**Comment by oneslash** [comment] 2018-12-05 06:30
Hey guys, I am not sure how to implement it correctly.

### Problem

I need to implement support of go templates inside ``. It is possible to do, however the upstream for vscode golang syntax support is in https://github.com/atom/language-go. I would need to make a change request first to the upstream repo and then pull it downstream into vscode (not to this project).

The atoms languge-go has three modes for golang:
 
- `Go (file: go.cson)` - basic golang syntax
- `Go Template (file: gotemplate.cson)` - support for go synxtax inside `{{ }}` but no HTML (please refer to the screenshot 1)
- `HTML (Go) (file: gohtml.cson)` - support for go synxtax inside `{{ }}` and HTML (please refer to the screenshot 2)

The reason I am stuck is, what should I do, there are several options which comes first to my head:

- Add support for HTML and Go Templates inside `` into the main file
- Crearte a separate mode `Go (Template + HTML)`

I would be happy to hear your suggestions.

### Screenshots

**Screenshot 1**
<img width="333" alt="screenshot 2018-12-05 at 07 24 53" src="https://user-images.githubusercontent.com/15870134/49494167-f7095b80-f85e-11e8-907f-a8de073bbc3d.png">

**Screenshot 2**
<img width="296" alt="screenshot 2018-12-05 at 07 27 38" src="https://user-images.githubusercontent.com/15870134/49494247-48194f80-f85f-11e8-972d-ad0ec0b94c52.png">

**Comment by oneslash** [comment] 2018-12-05 07:47
@ramya-rao-a, what do you think would be better?

**Comment by gertcuykens** [comment] 2018-12-05 20:33
How do other languages do it? For example does vscode-php use https://github.com/atom/language-php? Is current vscode core template design consistent with other languages?  Or does each language plugin has there own way of template support? For me it makes sense to make sure a template system is done the way all other language plugins are doing it. If my go file contains html php or c code I can recycle other plugins work to highlight that part. Now we are fixing just go templates but then there is cgo where you have a mix of c code https://golang.org/cmd/cgo/ in the end if we don't look how other languages are doing it then vscode-go will be more lines of code then vscode itself :)

**Comment by gertcuykens** [comment] 2018-12-06 02:33
@oneslash not sure if this can be done i am just trying to come up with idea's. What if you made 2 separate plugins also completely separate from vscode-go. One for `*.html.go` files and one for`*.txt.go` files? 
I make the assumption that multiple plugins can be activated for the same file. If not then we definitely need to create a ticket for vscode to just do that. Can you imagine where every plugin needs to reinvent let say a spell checker, that just unacceptable. Let me know if it makes sense

**Comment by oneslash** [comment] 2018-12-06 08:30
@ramya-rao-a, yes you got it correct.

@gertcuykens, the thing is, from what I understood, for PHP there are two modes, `text.html.php` and `source.php`. `text.html.php` - includes `source.php` inside, and it detects if it can use php syntax by `<?php` or `<?`. Go is a bit different, `` inside can be anything, not just HTML or Go templates.

**Comment by gertcuykens** [comment] 2018-12-06 09:05
And can we make a distinction based on file extention that dictates what to expect inside \`...\` like if file extention is `*.html.go` use html mode + template mode ?

**Comment by oneslash** [comment] 2018-12-06 09:19
@gertcuykens yes we can, and I can do it then if it is a common practice to name files. I usually develop services which are not exposed to a user so I am cannot decide.

**Comment by ramya-rao-a** [comment] 2018-12-10 05:17
> Or does each language plugin has there own way of template support?

Thats how it is today. 

> I make the assumption that multiple plugins can be activated for the same file.

Yes that is true

> And can we make a distinction based on file extention that dictates what to expect inside `...` like if file extention is *.html.go use html mode + template mode

Yes

**Comment by gertcuykens** [comment] 2018-12-10 05:40
Ok then I suggest to do each language template syntax in a separate plugin: *.hml.go, *.txt.go, … other people can then easily add more template plugins like c etc without submitting a vscode-go pull request. Now wat all does plugins do have in common is the go template autocomplete part `{{ if else .something }}` Now that going to be the hart part and needs to be in vscode-go for example when I push `.` I would like to see a list of available variables in the template

**Comment by ramya-rao-a** [comment] 2020-01-30 05:53
Hello all,

As mentioned in https://github.com/microsoft/vscode-go/issues/464#issuecomment-580093228, the syntax highlighting request for html template code in Go files is out of scope for this extension.

@stamblerre, 
Would `gopls` consider adding some kind of embedded language feature support for the Go code in the template?

**Comment by stamblerre** [comment] 2020-01-30 22:43
Yes absolutely, though it won't be for quite some time, as it's fairly low priority.
Filed golang/go#36911 to track it.

**Comment by ramya-rao-a** [comment] 2020-01-31 06:21
Thanks @stamblerre!

Everyone else,
Closing this issue in favor of the upstream issue logged for gopls in  https://github.com/golang/go/issues/36911

Once this feature is implemented upstream, language server users in VS Code will be able to use the Go language features inside html template code.

**Closed by ramya-rao-a** 2020-01-31 06:21 UTC
Labels: enhancement, help wanted

**Comment by inliquid** [comment] 2020-03-03 15:18
What does it mean? `gopls` will implement syntax highlighting? Or will make Vs Code support autocompletion in `*.html` go templates along with html language features?
 
/cc @ramya-rao-a 
/cc @stamblerre

**Comment by stamblerre** [comment] 2020-03-03 15:56
> What does it mean? `gopls` will implement syntax highlighting?

Syntax highlighting is not in the LSP, and is usually implemented in a grammar used by VS Code directly. I am not sure where exactly this would fit, but it may be worth filing a feature request with https://github.com/microsoft/vscode.

> Or will make Vs Code support autocompletion in `*.html` go templates along with html language features?

This is what golang/go#36911 is tracking. I don't expect it to be implemented for a while, but we may prioritize it after `gopls` reaches `v1.0.0`.

**Comment by inliquid** [comment] 2020-03-03 16:12
> I am not sure where exactly this would fit, but it may be worth filing a feature request with https://github.com/microsoft/vscode.
I think it is a responsibility of `vscode-go` extension, particularly this exact issue has already got all requirements and inputs. And was closed. I can't understand why it's been all thrown to `gopls` side.

**Comment by stamblerre** [comment] 2020-03-03 16:32
To be clear, syntax highlighting is typically not the job of a VS Code extension (for example, [here](https://github.com/microsoft/vscode/blob/master/extensions/go/syntaxes/go.tmLanguage.json) is the syntax for Go). I agree with Ramya that it doesn't make sense to have the syntaxes live in different repositories. The only language that this extension has added support for is `go.mod` files, which are significantly simpler.

With respect to language features, it is much easier to support autocompletion, definition, etc. through `gopls` than it is to add it to this extension. This extension relies mostly on command-line tools to provide features, and it seems like a tool does not exist to satisfy this use case.

**Comment by inliquid** [comment] 2020-03-03 16:46
Ok, let me ask again, will we have syntax highlighting with language features on `*.html` template files after it's implemented on `gopls` side, no? I expect both html/css and go templates to be working, otherwise it will all have close to zero sense.

**Comment by stamblerre** [comment] 2020-03-03 16:47
No, `gopls` will not implement syntax highlighting, as that is not part of the language server protocol.

**Comment by hyangah** [comment] 2020-03-03 16:50
I think for syntax highlighting, it's better to start discussion in https://github.com/jeff-hykin/better-go-syntax (upstream of Go syntax highlighting VS Code uses) and check if changes to use https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages make sense.

**Comment by inliquid** [comment] 2020-03-03 17:01
Will I need to switch `*.html` file language to `go` or smth like `gotemplate` for `gopls` to work on it?

**Comment by stamblerre** [comment] 2020-03-03 17:04
When features are implemented in `gopls`, we will make the necessary changes in the extension so that `gopls` works automatically, as one would expect. As of right now, this feature is not prioritized for `gopls/v1.0.0`, so I would not expect any progress on it for the near future.

**Comment by inliquid** [comment] 2020-03-04 12:44
I see. Thank you for clarification.
