### ISSUE TITLE
Go to definition not working when using build tags with gopls

### ISSUE THREAD

**Issue by dapiedra** [microsoft/vscode-go#2808] opened 2019-10-03 03:26 UTC
Hi.

Seems that VS go extension, go to definition function is not working when using build tags.

I have created an example here https://github.com/dapiedra/vs-go-example.git

VS-code version: 1.38.1

Go extension version: 0.11.7

Go env: vscode@d17eeba12b2e:/workspaces/go-example$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vscode/.cache/go-build"
GOENV="/home/vscode/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspaces/go-example/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build991075050=/tmp/go-build -gno-record-gcc-switches"

It works for the function PrintHelloFooBar() but it does not work for the function PrintHello() which declared twice but with a conditional compilation flag. It does not matter if you use the Language Server or not. It does not work in both modes.

Is it a known issue? Is there any workaround? Am I doing something wrong? Is someone else experiencing the same?

Thanks in advance.

**Comment by stamblerre** [comment] 2019-10-03 22:21
This is a known issue for the language server (https://github.com/golang/go/issues/29202), though there is a work-around, which is to configure the [`buildFlags`](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#buildflags-array-of-strings) configuration of the language server.

**Comment by ramya-rao-a** [comment] 2019-10-04 06:07
@dapiedra Can you share the Go related settings you might have added/edited so that we can determine if you are using the language server or not? You can get them by running the command `Preferences: Open Settings(JSON)`

**Comment by dapiedra** [comment] 2019-10-06 13:45
Looks like if I use this, it works: 
{
    "go.buildFlags": [
        "foo"
    ],
    "go.useLanguageServer": true,
    "go.toolsEnvVars": {
        "GOFLAGS": "-tags=foo"
    },
}

It also works this way:
{
    "go.buildFlags": [
        "foo"
    ],
    //"go.useLanguageServer": true,
    "go.toolsEnvVars": {
        "GOFLAGS": "-tags=foo"
    },
}

Thanks!

**Comment by ramya-rao-a** [comment] 2019-10-21 02:12
@stamblerre Should the Go extension pass the value of the `go.buildFlags` to `gopls` using `-tags`?

**Comment by stamblerre** [comment] 2019-10-21 16:40
Currently, `gopls` users can configure build flags with the following setting:

```json5
"gopls": {
    "buildFlags": ["-tags=foo"]
}
```
The extension could pass `go.buildFlags` through this setting, but we should be careful to handle the case where the value of `go.buildFlags` differs from that of `gopls.buildFlags`.

**Comment by alkaliphile** [comment] 2019-12-28 23:12
This happens for me, too.

Versions:

VS Code: 1.41.1
Go: 0.11.9

No errors in the developer tools when I ctrl-click in a file with the build flags. Also, adding the gopls setting mentioned above doesn't do anything; the setting is greyed out in settings.json, with a message that says "Unknown Configuration Setting." (Could this have something to do with the message I see about gopls being out of date, despite several attempts to update it by following the prompts?) The other settings that dapiedra mentioned don't work, either.

Something strange is that if I just remove the "// +build integration" line from the top of each file, then add it back, Go to Definition works. At least, until I have to reload VS Code. Also, it's a slight hassle needing to do this for each file I'm working with.

**Comment by ramya-rao-a** [comment] 2019-12-29 22:33
@stamblerre What is the official story for passing such configuration to `gopls`? Am guessing you would want to have it in a way that it is editor agnostic.

**Comment by stamblerre** [comment] 2019-12-30 18:57
This way actually is editor agnostic - the client just has a `gopls` section for settings and can pass in anything through the middleware. In the next few weeks, I am planning on writing a generator for the VS Code `package.json` file based on the [current `gopls` options](https://github.com/golang/tools/blob/master/internal/lsp/source/options.go) so that we can have settings that are recognized by VS Code Go.

**Comment by stamblerre** [comment] 2020-02-11 21:26
Closing this as a duplicate of https://github.com/microsoft/vscode-go/issues/2965, which will track the unification of settings between `gopls` and VS Code Go. For now, please use the workaround suggested above.

**Comment by stamblerre** [comment] 2020-02-11 21:27
Duplicate of https://github.com/microsoft/vscode-go/issues/2965

**Closed by stamblerre** 2020-02-11 21:26 UTC
Labels: under-discussion
