### ISSUE TITLE
Formatting a Go document mangles and breaks code.

### ISSUE THREAD

**Issue by Borkason** [microsoft/vscode-go#2969] opened 2020-01-06 00:47 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.5 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- Go 0.12.0
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- windows amd64

### Share the Go related settings you have added/edited

```
{
    "python.pythonPath": "/usr/bin/python3",
    "go.useLanguageServer": true
}
```

### Describe the bug
When formatting the document, code gets mangled and broken.
Happens also when saving.

### Steps to reproduce the behavior:
Happens when formatting the document (ALT-SHIFT-F).
Sometimes also when saving the document.
I can't always reproduce this.

### Screenshots or recordings

![CEoqaCxUcw](https://user-images.githubusercontent.com/2971735/71788789-e8731200-3025-11ea-84dd-90298c51d954.gif)

It also breaks the import statement

```
```

**Comment by stamblerre** [comment] 2020-01-06 21:28
What is the output of `gopls version`? Can you share your `gopls` logs for when this happens? The instructions for capturing `gopls` logs are here: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs.

**Comment by ramya-rao-a** [comment] 2020-01-15 07:23
@Borkason Can you please provide the details @stamblerre is asking above?

**Comment by darjun** [comment] 2020-01-15 15:08
I encountered the same problem. gopls version:
```
$ gopls version
golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
```

but by `"View: Debug Console" -> "Output" -> "Tasks" -> "gopls"`, I cann't find the gopls log.

It's just a black windows there at Debug Console.

this is my user settings.json:
```
{
    "git.ignoreMissingGitWarning": true,
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "explorer.confirmDragAndDrop": false,
    "go.autocompleteUnimportedPackages": true,
    "editor.insertSpaces": false,
	"editor.detectIndentation": false,
	"go.formatTool": "gofmt",
	"explorer.confirmDelete": false,
	"go.gotoSymbol.includeGoroot": true,
	"go.gotoSymbol.includeImports": true,
	"go.useLanguageServer": true
}
```

**Comment by stamblerre** [comment] 2020-01-15 18:15
@darjun: You can also try Ctrl + Shift + P -> "View: Toggle Output", and then there should be a drop-down menu that says "Tasks" in the right-hand top corner. When you click on it, "gopls" should be in this list. Click on that, and then the log should be there. You will also need to add the following to your settings to get more detailed logging:

```json5
"go.languageServerFlags": [
    "-rpc.trace"
]
```

**Comment by stamblerre** [comment] 2020-01-15 18:17
There is also more information on the Go issue tracker (https://github.com/golang/go/issues/34955), so please follow-up there, if possible.

**Comment by darjun** [comment] 2020-01-15 23:36
I put gopls log at gist, this is the link [https://gist.github.com/darjun/447159f76166f2d45684da406e646f1c](https://gist.github.com/darjun/447159f76166f2d45684da406e646f1c)

**Comment by stamblerre** [comment] 2020-01-17 17:45
@darjun: Would you be able to provide a smaller log with a repro and the other details requested on  golang/go#34955 (feel free to just add a comment to that issue)? The log you've provided seems to be truncated and for a larger project, so it's difficult to parse. Thanks!

**Comment by LordNeznay** [comment] 2020-01-21 22:36
I have the same problem.
I put example of problim into repository: https://github.com/LordNeznay/vscode_go_issue_2969_example
gopls log: https://github.com/LordNeznay/vscode_go_issue_2969_example/blob/master/gopls.log

For reproduce clone repo, open folder in visual studio code, open main.go and save it

**Comment by stamblerre** [comment] 2020-01-21 22:42
@LordNeznay: Do you have the same issue with `gopls` at master (you can download it by running `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`)?

**Comment by LordNeznay** [comment] 2020-01-21 22:51
@stamblerre, after `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master` the problem has stopped reproducing. So much thank!

**Comment by stamblerre** [comment] 2020-01-21 22:56
Glad to hear it! Thanks for following up.

**Comment by stamblerre** [comment] 2020-01-26 22:00
@Borkason, @darjun: If you get a chance, please try out `gopls` at master and let me know if the problem persists. Thank you!

**Comment by ramya-rao-a** [comment] 2020-01-27 04:19
@stamblerre We can close this issue once the next version is `gopls` is out.

**Comment by ramya-rao-a** [comment] 2020-01-27 04:26
Thanks @stamblerre 

Since the next version `gopls/v0.3.0` will have the fix, closing this issue.
For folks who want to try the fix before the next version is out, please try out `gopls` from the master branch. You can download it by running 
```
GO111MODULE=on 
go get golang.org/x/tools/gopls@master golang.org/x/tools@master
```

**Closed by ramya-rao-a** 2020-01-27 04:26 UTC
Labels: under-discussion, upstream-gopls
