### ISSUE TITLE
Add option to reduce the scope in which guru runs for Find All References feature

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-go#2347] opened 2019-02-24 02:26 UTC
_From 
https://github.com/Microsoft/vscode-go/issues/2084#issuecomment-464706343 by @MelleKoning_

I've got the same sympthon; very high CPU usage that does not come back down.

In task manager it is visible that guru.exe is being called and eats up the CPU% and memory.
Same can be seen in developer processes:

![image](https://user-images.githubusercontent.com/506830/52949586-020f5a80-337d-11e9-8210-c4e279125a53.png)

So, 75% CPU usage and keeps on going. 

The action was Find-All-References (Shift-Alt-F12) or Peek-References (Shift-F12)

Is there any reason guru.exe does not come back with results or is it continuously restarted by the vscode-go module?

-edit- Might this be related to a very large vendor folder, that it simply takes a very long time for guru to process all the *.go files in the project? If yes, might Find-all-references be limited to certain packages as per the command line of guru.exe option "scope packages"? See guru command line params below.

```
Flags:
  -cpuprofile file
        write CPU profile to file
  -json
        emit output in JSON format
  -modified
        read archive of modified files from standard input
  -ptalog file
        write points-to analysis log to file
  -reflect
        analyze reflection soundly (slow)
  -scope packages
        comma-separated list of packages the analysis should be limited to
  -tags build tags
        a list of build tags to consider satisfied during the build. For more information about build tags, see the description of build constraints in the documentation for the go/build package
```

**Comment by ramya-rao-a** [comment] 2019-02-24 02:40
We could use the scope argument and restrict `guru` to just the folder that is opened in VS Code. But making this as a default might not be a good idea as one would expect `Find all references` to well... find **all** references.

Instead we can introduce a setting, say `go.guruScope` and allow users to provide the scope value here. Or this can be a boolean that would either set the scope to current project or the entire GOPATH.
Thoughts?

cc @jhendrixMSFT, @vladbarosan

**Comment by zgramana** [comment] 2019-02-26 20:01
@ramya-rao-a I would expand that to a list of packages contained in all my workspace folders. Another way to think of it is "just my code."

**Comment by vladbarosan** [comment] 2019-02-26 20:33
@ramya-rao-a , to make sure i understand, the issue is here when we do find all references in something coming from a dependency that is also used in other dependencies ? If that is the case I think a "just my code" option is strongly desired I would say, since most times I wont care where that something is used in any of the dependencies.  I think usually the case is to find where in my code is being used.

**Comment by ramya-rao-a** [comment] 2019-02-26 20:42
@zgramana What do you refer to when you say "all my workspace folders"? Is that folders under the workspace that was opened in VS Code? Or my entire GOPATH?

@vladbarosan How would we define "just my code"?

**Comment by vladbarosan** [comment] 2019-02-26 20:47
@ramya-rao-a  welllllll i think there are a couple of options. I think it makes sense current folder - vendor folder makes most sense ?  We can also enable just in this package, just in the GoPath - vendor, or just this folder + vendor.

and tbf with Go modules this wont really be an issue any more (unless you still vendor)

**Comment by zgramana** [comment] 2019-02-26 21:21
@ramya-rao-a good question. In this case, I mean vscode workspace folders.

**Comment by ramya-rao-a** [comment] 2019-02-27 02:31
AFAIK, the `scope` argument takes in package import paths and not absolute folder paths. Therefore, we need to map the folder opened in VS Code to a package. This will not always work as there might not be a package at the root level.
Which then leaves us with running `go list ./...` in the root folder and using all the resulting packages.

**Comment by stamblerre** [comment] 2020-02-18 22:39
Since `gopls` will be replacing `guru` (and already does the work of running `go list ./...`), I think it probably makes sense to close this issue and have `gopls` take care of finding references with a limited scope.

**Closed by stamblerre** 2020-02-18 22:39 UTC
Labels: enhancement, help wanted
