### ISSUE TITLE
debugger not showing variables and callstack

### ISSUE THREAD

**Issue by rhinoid** [Microsoft/vscode-go#51] opened 2015-11-21 08:19 UTC
Attached is a screenshot of a simple program.
When the breakpoint is hit I don't see variables (no local 'text' or global 'a'), and no call stack (main -> hello)

<img width="1277" alt="helloworld_test" src="https://cloud.githubusercontent.com/assets/2438289/11317478/87b99eaa-9030-11e5-805c-547a61ff3d50.png">

**Comment by lukehoban** [comment] 2015-11-21 10:36
Could you share your `launch.json` file as well?

**Comment by rhinoid** [comment] 2015-11-21 14:59
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch main.go",
			"type": "go",
			"request": "launch",
			"program": "/Users/reinier/Projects/go/src/bitbucket.org/rhinoid/helloworld/main.go",
			"stopOnEntry": false,
			"env": {},
			"args": [],
			"cwd": "."
		}
	]
}

**Comment by lukehoban** [comment] 2015-11-22 02:49
Interesting.  When I try those steps (on OS X) I see this:

![screen shot 2015-11-21 at 6 44 53 pm](https://cloud.githubusercontent.com/assets/223467/11321757/016a637a-9080-11e5-9032-c6d36babc5fc.png)

Note that when the breakpoint is hit you should see the line drown in yellow, the callstack and the locals.

Couple questions:

1. What OS?
2. Do you have a recent version of Delve installed?  Ideally built from current master.
3. If you try on the command line with the following, does it work?

```
lukeh@Lukes-MacBook-Pro:~/dd/go/src/github.com/lukehoban/helloworld$ $GOPATH/bin/dlv debug
Type 'help' for list of commands.
(dlv) b main.go:13
Breakpoint 1 set at 0x20af for main.hello ./main.go:13
(dlv) c
> main.hello() ./main.go:13 (hits goroutine(1):1 total:1)

     8:		a = a + 1
     9:		hello("world")
    10:	}
    11:
    12:	func hello(text string) {
=>  13:		fmt.Printf("%s - %d", text, a)
    14:	}
(dlv) p text
"world"
(dlv)
```

**Comment by rhinoid** [comment] 2015-11-22 10:17
Just after your announcement I installed everything fresh (I did not have Vis Studio (or Delve) yet)

OS: 10.11.1 (el capitan)

Delve version: 0.9.0-alpha

commandline:

reiniers-MacBook-Pro:helloworld reinier$ dlv debug
Type 'help' for list of commands.
(dlv) b main.go:13
Breakpoint 1 set at 0x20af for main.hello ./main.go:13
(dlv) c
> main.hello() ./main.go:13
	
    8:		a = a + 1
    9:		hello("world")
   10:	}
   11:	
   12:	func hello(text string) {
=> 13:		fmt.Printf("%s - %d", text, a)
   14:	}

**Comment by rhinoid** [comment] 2015-11-22 10:17
oh sorry about the previous odd markdown styling

**Comment by lukehoban** [comment] 2015-11-23 05:13
@rhinoid Strange.  That is the same configuration I have, and I have seen this working on several machines with the same setup.  It's hard to tell what exactly might be wrong here.

1. Do you see the exact same results consistently?
2. Can you get the debugger to correctly hit a breakpoint (as in my screenshot) for any codebase?  Or does it always do what you describe here?
3. Much more work - but if you are willing to help invetigate, you can follow the instructions for [debugging the debugger](https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/Readme.md), then watch the debug console from within debugging the debugger for any errors/warnings, and also possibly inside the response from `this.delve.call<DebuggerState>('Command', [{ name: 'continue' }], (err, state) => {`.

I'm going to close for now since there is nothing more I can think to try without more info - but feel free to reopen if there is anything more you can gather.  And if anyone else is having the same issue let me know.

**Comment by joeblew99** [comment] 2015-11-23 13:46
today i did a clean install
osx
delve

the local variables worked for the first session and then stopped working.
now i have no variables.
no idea why.

**Comment by lukehoban** [comment] 2015-11-23 17:05
Thanks @joeblew99.  Could you attach a screenshot of exactly what you see?  Is there a spinner in the "Variables" window?  Is there a yellow highlighted row in the source code where the breakpoint was hit?  Is there anything in the debug console?

**Comment by joeblew99** [comment] 2015-11-23 17:59
Hey Luke, 
I am the buy that cried wolf it seems.
I started working on another project and the local variables window started working.

Yes the yellow is always highlighting always.

Yes the debug console always works.

If you need me to do a ything else please let me know.

**Comment by lukehoban** [comment] 2015-11-23 21:38
@joeblew99 Good to hear.  I have seen it happen before that the Variables window stop working for some reason and will not work again until VS Code is shutdown.  I have not yet been able to reproduce this reliably though.

**Comment by rhinoid** [comment] 2015-11-24 06:35
I tried restarting visual studio but it didn't have any effect.

Things which might have to do with it:
 - I'm Dutch, but my machine is set to English. Perhaps other localization weirdness like my regional settings causing havoc on number/date parsing routines?

<img width="277" alt="localization" src="https://cloud.githubusercontent.com/assets/2438289/11359593/c5e7db84-927d-11e5-92aa-0244fe504e81.png">

- I was still on go 1.3.something and upgraded just before installing visual studio to 1.5.1

**Comment by rhinoid** [comment] 2015-11-24 06:37
Ok I tried switching to Region 'United states (computer)', and restart Visual studio, but same effect.

**Comment by lukehoban** [comment] 2015-11-25 00:15
@rhinoid Really hard to tell whats wrong here.  Any chance you can try the somewhat involved steps described here to debug the debugger: https://github.com/Microsoft/vscode-go/issues/78#issuecomment-159363629.

You should be able to step through the debugger and see where there is a failure + some additional diagnostics output.

**Comment by lukehoban** [comment] 2015-11-25 17:23
Going to close this for now - please reopen or add comments here if you have additional data or if anyone else is able to repro.

**Closed by lukehoban** 2015-11-25 17:23 UTC

**Comment by grimmer0125** [comment] 2016-07-11 17:38
Hi lukehoban, I am new to use Go and I notice the global variables will not be shown in the variables inspector, just the same as the screenshot you posted (var a = 4). Is this by design ?

**Comment by fstapleford** [comment] 2017-05-26 17:48
As soon as I added a 'Watch', my variables went away. Can't get them back

**Comment by achandlerwhite** [comment] 2017-05-30 23:19
I am not seeing any local variables. I'm debugging aspnetcore 2.0-preview1-final projects.

**Comment by hielfx** [comment] 2017-08-25 08:53
For me only shows the local variables, the global are not displayed.
- Latest Delve version
- Ubuntu 16.04
- VS Code 1.15.1
- Auto generated lauch.json config

**Comment by ramya-rao-a** [comment] 2017-09-01 21:16
@grimmer0125 @hielfx  We use the `locals` command in delve to get the local variables. I am not aware of a way to get the global variables in delve. @derekparker Is there a way to get the global variables?
