### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by WLBF** [Microsoft/vscode-go#2470] opened 2019-04-25 01:49 UTC
- Issue Type: `Performance`
- Extension Name: `Go`
- Extension Version: `0.10.0`
- OS Version: `Linux x64 4.15.0-48-generic`
- VSCode version: `1.33.1`

[ms-vscode.Go-unresponsive.cpuprofile.txt](https://gist.github.com/WLBF/c2d5ac9c940bd388ff28986e9d385ed6)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ramya-rao-a** [comment] 2019-04-25 04:02
@WLBF Can you share any setting changes you did after upgrading to 0.10.0?
- Are you using Go modules?
- Did you get prompted to use `gopls`?
- Did you go through with installing `gopls`?

If using Go modules and the language server, then can you try the steps at #2461 (comment) and see if that helps?

**Comment by ramya-rao-a** [comment] 2019-04-25 05:14
We have figured out the root cause for the high cpu usage and a fix has been made.
A new release (0.10.1) has just been published and it will have the fix to the issue.

Thanks a lot for reporting and your patience!

**Closed by ramya-rao-a** 2019-04-25 05:14 UTC
