### ISSUE TITLE
unpredictable codelens in go test files

### ISSUE THREAD

**Issue by cyc115** [Microsoft/vscode-go#999] opened 2017-05-15 15:45 UTC
The new version of vscode introduced codeLens for `*_test.go` files that allows user to quickly `run` and `debug` a test method. Thank you for this feature, it is extremely handy. But it seems that those two buttons in codeLens would swap place from time to time (an example below). 
![client_test_go_-_notary](https://cloud.githubusercontent.com/assets/2107333/26066130/90aec08c-395b-11e7-9d24-fd19066c1178.png)
![client_test_go_-_notary](https://cloud.githubusercontent.com/assets/2107333/26066147/9bd49db0-395b-11e7-952c-a3e58b71493e.png)

**Comment by ramya-rao-a** [comment] 2017-05-16 00:09
Interesting..

@jrieken Do you know the reason for this? The code that provides the codelens for run/debug tests is https://github.com/Microsoft/vscode-go/blob/master/src/goRunTestCodelens.ts#L79-L80

I don't see why the order should change.

**Comment by cyc115** [comment] 2017-05-16 00:24
Update : This behavior seems to affect all codeLens. The groups would also
be inverted from time to time when there are multiple logical groups of
codeLens on one line.

**Comment by jrieken** [comment] 2017-05-16 08:02
Interesting indeed. There is some [sorting](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/codelens/common/codelens.ts#L35), namely by line number, provider, and column. 

@ramya-rao-a Do both code lenses come from the same provider?

**Comment by ramya-rao-a** [comment] 2017-05-16 14:19
@jrieken Yes, they come from the same provider, same function. See https://github.com/Microsoft/vscode-go/blob/master/src/goRunTestCodelens.ts#L79-L80

**Comment by jrieken** [comment] 2017-05-16 15:12
Thank, the problem is that our sort isn't stable so equal items (which you code lenses are) might not keep their initial sort order... Feel free to forward this bug to me

**Comment by jrieken** [comment] 2017-05-16 15:47
Should be fixed with https://github.com/Microsoft/vscode/commit/8ac7e555d1790267bf58e1922fc2f737a4d1c1ab

**Comment by ramya-rao-a** [comment] 2017-05-16 16:28
thanks @jrieken!

@cyc115 The fix will be out in tomorrow's insiders build

**Closed** 2017-05-16 16:29 UTC
