### ISSUE TITLE
Enable Easier Debugging of Code Requiring Root

### ISSUE THREAD

**Issue by sethRait** [microsoft/vscode-go#2610] opened 2019-06-27 17:50 UTC
Currently, if one needs to run code with superuser privileges, but edits it as a standard user, the debugging process is very convoluted.  Since there is no way to specify "run delve as root" in the launch.json, here is what must be done currently:
Steps to Reproduce:

1. In launch.json, set request to "attach" and mode to "remote" and change the remotePath, host, port settings as required.  Add a preLaunch task.
2. In tasks.json, create a new task which runs the command `sudo /path/to/dlv debug --headless --log --listen=:<port> -- <args to program you want to debug>`
3. Set "isBackground" to true
4. Create a problem matcher with a "background" property including a  "beginsPattern" and an "endsPattern" so VSCode knows when it's okay to begin the debug session.

launch.json:
~~~"version": "0.2.0",
    "configurations": [
        {
            "name": "launch",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "showLog": true,
            "preLaunchTask": "startDelve"
        }]
~~~
tasks.json:
~~~{
	"version": "2.0.0",
	"tasks": [{
		"label": "startDelve",
		"command": "cd /path/to/go/code/dir; sudo /path/to/dlv debug --api-version=2 --headless --listen=:2345 --log -- <args to go program>",
		"type": "shell",
		"isBackground": true,
		"problemMatcher": {
			"pattern": {
				"regexp": "Error: ([^(]+)\\((\\d+|\\d+,\\d+|\\d+,\\d+,\\d+,\\d+)\\): (.*)$",
				"file": 1,
				"location": 2,
				"message": 3
			},
			"background": {
				"beginsPattern": "API server listening",
				"endsPattern": "20"
			}
		}
	}]
}
~~~
Suggested workflow:
1. In  launch.json, under the configuration you would like to run as root, add `"runas": "root"` or `"root": true`

**Comment by ramya-rao-a** [comment] 2019-07-07 00:53
Can you try another workaround that involves setting the `go.alternateTools` setting?

- Write a script that internal calls delve with `sudo` and pass all the arguments as is
- Add the below to your settings
```
"go.alternateTools": {
    "dlv": "absolute path to your script"
}
```

This will make the extension call your script instead of dlv. And internally you can call dlv with `sudo`

**Comment by sethRait** [comment] 2019-07-10 15:32
@ramya-rao-a this works perfectly! Thank you :D Is there a way this could be made more discoverable though?

**Comment by ramya-rao-a** [comment] 2019-07-17 18:18
Not sure...
Maybe a section in the README or FAQs?

**Comment by jadarsie** [comment] 2019-11-06 18:05
@ramya-rao-a do you expect [this](https://github.com/microsoft/vscode-go/issues/2610#issuecomment-508963280) approach to work with the [remote development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) extensions?

My use case is similar, I also need to run dlv as root. I can debug a project sitting on the server just fine, but my `alternateTool` is not being picked-up (I do not think so).  Is there a log file I can inspect to confirm that?

This is my remote settings file.

```
me@remote:~$ cat ~/.vscode-server/data/Machine/settings.json 
{
    "go.alternateTools": {
        "dlv": "dlvsu.sh" // this script calls: sudo -E dlv $@
    }
}
```
Remote host is an UbuntuServer 18.04
Am I missing anything?

**Comment by sethRait** [comment] 2019-11-18 21:55
I am also now having trouble with this approach using the remote development extension.  After [enabling debug logs](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code) I can verify that my script specified using go.alternateTools is not even being called.  i have verified that the setting is set on the remote machine and an absolute path to the script is given.

**Comment by stamblerre** [comment] 2020-02-11 21:16
This sounds like a duplicate of https://github.com/microsoft/vscode-go/issues/2889 - please follow along with the discussion on that issue.

**Comment by stamblerre** [comment] 2020-02-11 21:16
Duplicate of #2889

**Closed by stamblerre** 2020-02-11 21:16 UTC
Labels: debug, under-discussion
