### ISSUE TITLE
Show struct member comment in autocompletion

### ISSUE THREAD

**Issue by AndreKR** [microsoft/vscode-go#2228] opened 2019-01-07 01:12 UTC
Issue Type: <b>Feature Request</b>

It would be very helpful if struct member comments (and tags) would show up in auto completion:

![2019-01-07-01-52-48-code](https://user-images.githubusercontent.com/1188538/50744072-8e2b4f80-121f-11e9-8c4f-4f9dfbd22f4e.png)

Extension version: 0.8.0
VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 6.1.7601

**Comment by ramya-rao-a** [comment] 2019-01-09 17:09
We use `go doc` to get the documentation to show in such cases. 

Can you look into and share how would we use the `go doc` command for this case?

**Comment by AndreKR** [comment] 2019-01-09 17:47
I checked how VS Code runs `go doc` and I found this command line:

    go doc -c -cmd -u github.com/AndreKR/test Foo

When I run this, the output is:

```
type Foo struct {
        a string // Foo
        b string // Bar
}
```

So apparently the information is already there, VS Code is just not consuming/displaying it.

**Comment by ramya-rao-a** [comment] 2019-01-09 18:04
That would be for `Foo`, but we are talking about `f.a` here. So my question was if you were to use `go doc`, how would you use it such that you get the `Foo` and `Bar` comments for the struct members

**Comment by AndreKR** [comment] 2019-01-09 18:53
Well, you can actually call `go doc -c -cmd -u github.com/AndreKR/test Foo.a` which will give you the information for just that one field:

```
type Foo struct {
    a string  // foo

    // ... other fields elided ...
}
```
(`// ... other fields elided ...` is actually part of the output.)

But since it's very inefficient to make so many calls and the format to parse is the same and you can get all the information from the one call mentioned above, this is probably not the way you want to do it.

**Comment by ramya-rao-a** [comment] 2019-01-15 04:08
The problem is that we only know about the text next to the cursor, which in this case would be `f.a`. The editor has no idea of either `Foo` or `Foo.a` at this point.

**Comment by AndreKR** [comment] 2019-01-15 13:14
It already offers "a" and "b" in the autocompletion box (see screenshot). For this it calls `go doc -c -cmd -u github.com/AndreKR/test Foo` so it does in fact know that `f` is of type `Foo`.

**Comment by ramya-rao-a** [comment] 2019-01-15 17:50
> It already offers "a" and "b" in the autocompletion box

Here "it" is [gocode](https://github.com/mdempsky/gocode).
We pass in the file and cursor position and it returns us the completion candidates along with the package the candidates belong to.

We then use this information and try to call `go doc`.

> For this it calls go doc -c -cmd -u github.com/AndreKR/test Foo so it does in fact know that f is of type Foo.

We dont call `go doc` for the actual completion items. We call `go doc` only to get the documentation for the completion items already provided by `gocode`. At this point, the code (the VS Code extension) is not aware of `Foo`

**Comment by AndreKR** [comment] 2019-01-15 18:05
Hm, I see. In the screenshot it shows that Foo.a ist `string`... where does that information come from - from gocode or from the `go doc -c -cmd -u github.com/AndreKR/test Foo` call?

**Comment by ramya-rao-a** [comment] 2019-08-26 03:28
@AndreKR Apologies for not replying sooner.

The information on `string` is coming from the `gocode` tool. This information is provided for each completion item. Then, `go doc` is called only for the selected item.

By now, it is clear that it is not trivial to implement this feature, but the good news is that there is active 
active development on an official language server for Go via [gopls](https://github.com/golang/go/wiki/gopls) which will provide the auto-completion feature as well, and it should be able to provide this feature

This issue is being closed in favor of having the auto-completion feature from the language server which will not have the same problem.

For more on language server integration with this extension, please see [Go language server](https://github.com/microsoft/vscode-go#go-language-server)

To go a feature request for gopls, use the [Go issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E)

**Closed by ramya-rao-a** 2019-08-26 03:28 UTC
Labels: enhancement, help wanted
